; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=ysx64 | FileCheck %s --check-prefixes=CHECK

define i1 @test1(i64 %x) {
;
; CHECK-LABEL: test1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srai a0, a0, 30
; CHECK-NEXT:    addi a0, a0, 2
; CHECK-NEXT:    seqz a0, a0
; CHECK-NEXT:    ret
  %a = and i64 %x, -1073741824
  %b = icmp eq i64 %a, -2147483648
  ret i1 %b
}

define i1 @test2(i32 signext %x) {
; CHECK-LABEL: test2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a1, 786432
; CHECK-NEXT:    and a0, a0, a1
; CHECK-NEXT:    seqz a0, a0
; CHECK-NEXT:    ret
  %a = and i32 %x, -1073741824
  %b = icmp eq i32 %a, 0
  ret i1 %b
}

define i1 @test3(i32 signext %x) {
; CHECK-LABEL: test3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a1, 917504
; CHECK-NEXT:    and a0, a0, a1
; CHECK-NEXT:    snez a0, a0
; CHECK-NEXT:    ret
  %a = and i32 %x, -536870912
  %b = icmp ne i32 %a, 0
  ret i1 %b
}

define i1 @test4(i64 %x) {
;
; CHECK-LABEL: test4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srli a0, a0, 46
; CHECK-NEXT:    slli a0, a0, 46
; CHECK-NEXT:    seqz a0, a0
; CHECK-NEXT:    ret
  %a = and i64 %x, -70368744177664
  %b = icmp eq i64 %a, 0
  ret i1 %b
}

define i1 @test5(i64 %x) {
;
; CHECK-LABEL: test5:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srliw a0, a0, 29
; CHECK-NEXT:    slli a0, a0, 29
; CHECK-NEXT:    seqz a0, a0
; CHECK-NEXT:    ret
  %a = and i64 %x, u0xE0000000
  %b = icmp eq i64 %a, 0
  ret i1 %b
}

define i1 @test6(i64 %x) {
;
; CHECK-LABEL: test6:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srliw a0, a0, 29
; CHECK-NEXT:    slli a0, a0, 29
; CHECK-NEXT:    snez a0, a0
; CHECK-NEXT:    ret
  %a = and i64 %x, u0xE0000000
  %b = icmp ne i64 %a, 0
  ret i1 %b
}

define i1 @test7(i64 %x) {
;
; CHECK-LABEL: test7:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srliw a0, a0, 29
; CHECK-NEXT:    li a1, 3
; CHECK-NEXT:    slli a0, a0, 29
; CHECK-NEXT:    slli a1, a1, 30
; CHECK-NEXT:    xor a0, a0, a1
; CHECK-NEXT:    seqz a0, a0
; CHECK-NEXT:    ret
  %a = and i64 %x, u0xE0000000
  %b = icmp eq i64 %a, u0xC0000000
  ret i1 %b
}

define i1 @test8(i64 %x) {
;
; CHECK-LABEL: test8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srliw a0, a0, 20
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:    slli a0, a0, 20
; CHECK-NEXT:    slli a1, a1, 31
; CHECK-NEXT:    xor a0, a0, a1
; CHECK-NEXT:    snez a0, a0
; CHECK-NEXT:    ret
  %a = and i64 %x, u0xFFF00000
  %b = icmp ne i64 %a, u0x80000000
  ret i1 %b
}

define i1 @test9(i64 %x) {
;
; CHECK-LABEL: test9:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srliw a0, a0, 16
; CHECK-NEXT:    slli a0, a0, 16
; CHECK-NEXT:    lui a1, 32768
; CHECK-NEXT:    xor a0, a0, a1
; CHECK-NEXT:    seqz a0, a0
; CHECK-NEXT:    ret
  %a = and i64 %x, u0xFFFF0000
  %b = icmp eq i64 %a, u0x08000000
  ret i1 %b
}

; Make sure the and constant doesn't get converted to an opaque constant by
; ConstantHoisting. If it's an opaque constant, we'll have addi -16 and addi 15.
define i64 @test10(i64 %0) #0 {
;
; CHECK-LABEL: test10:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addiw a0, a0, -1
; CHECK-NEXT:    srliw a0, a0, 4
; CHECK-NEXT:    slli a0, a0, 4
; CHECK-NEXT:    snez a0, a0
; CHECK-NEXT:    ret
entry:
  %1 = add nuw nsw i64 %0, u0xffffffff
  %2 = and i64 %1, u0xfffffff0
  %3 = icmp ne i64 %2, 0
  %4 = zext i1 %3 to i64
  ret i64 %4
}

; Make sure the and constant doesn't get converted to an opaque constant by
; ConstantHoisting. If it's an opaque constant, we'll have addi -16 and addi 15.
define i64 @test11(i64 %0) #0 {
;
; CHECK-LABEL: test11:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addiw a0, a0, -1
; CHECK-NEXT:    lui a1, 524285
; CHECK-NEXT:    srliw a0, a0, 4
; CHECK-NEXT:    slli a1, a1, 1
; CHECK-NEXT:    slli a0, a0, 4
; CHECK-NEXT:    addi a1, a1, -1360
; CHECK-NEXT:    xor a0, a0, a1
; CHECK-NEXT:    seqz a0, a0
; CHECK-NEXT:    ret
entry:
  %1 = add nuw nsw i64 %0, u0xffffffff
  %2 = and i64 %1, u0xfffffff0
  %3 = icmp eq i64 %2, u0xffff9ab0
  %4 = zext i1 %3 to i64
  ret i64 %4
}

; Make sure the and constant doesn't get converted to an opaque constant by
; ConstantHoisting. If it's an opaque constant we'll end up with constant
; materialization sequences on RV64.
define i64 @test12(i64 %0) #0 {
;
; CHECK-LABEL: test12:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addiw a0, a0, -16
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:    slli a0, a0, 32
; CHECK-NEXT:    slli a1, a1, 32
; CHECK-NEXT:    srli a0, a0, 32
; CHECK-NEXT:    addi a1, a1, -13
; CHECK-NEXT:    xor a0, a0, a1
; CHECK-NEXT:    seqz a0, a0
; CHECK-NEXT:    ret
entry:
  %1 = add nuw nsw i64 %0, u0xfffffff0
  %2 = and i64 %1, u0xffffffff
  %3 = icmp eq i64 %2, u0xfffffff3
  %4 = zext i1 %3 to i64
  ret i64 %4
}

; Make sure the and constant doesn't get converted to an opaque constant by
; ConstantHoisting.
define i64 @test13(i64 %0) #0 {
;
; CHECK-LABEL: test13:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lui a1, 524288
; CHECK-NEXT:    addi a1, a1, -15
; CHECK-NEXT:    sub a0, a0, a1
; CHECK-NEXT:    srliw a0, a0, 31
; CHECK-NEXT:    slli a0, a0, 31
; CHECK-NEXT:    seqz a0, a0
; CHECK-NEXT:    ret
entry:
  %1 = add nuw nsw i64 %0, u0x8000000f
  %2 = and i64 %1, u0x80000000
  %3 = icmp eq i64 %2, 0
  %4 = zext i1 %3 to i64
  ret i64 %4
}
