; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=ysx64 -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV64I %s
; RUN: llc -mtriple=ysx64 -mattr=+a -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefixes=RV64IA %s
; RUN: llc -mtriple=ysx64 -mattr=+zalrsc -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefixes=RV64I-ZALRSC %s

define i32 @atomicrmw_sub_i32_constant(ptr %a) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_sub_i32_constant:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a1, -1
; RV64I-NEXT:    amoadd.w.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_sub_i32_constant:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    li a1, -1
; RV64IA-NEXT:    amoadd.w.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_sub_i32_constant:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    li a1, -1
; RV64I-ZALRSC-NEXT:    amoadd.w.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw sub ptr %a, i32 1 seq_cst
  ret i32 %1
}

define i64 @atomicrmw_sub_i64_constant(ptr %a) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_sub_i64_constant:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a1, -1
; RV64I-NEXT:    amoadd.d.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_sub_i64_constant:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    li a1, -1
; RV64IA-NEXT:    amoadd.d.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_sub_i64_constant:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    li a1, -1
; RV64I-ZALRSC-NEXT:    amoadd.d.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw sub ptr %a, i64 1 seq_cst
  ret i64 %1
}

define i32 @atomicrmw_sub_i32_neg(ptr %a, i32 %x, i32 %y) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_sub_i32_neg:
; RV64I:       # %bb.0:
; RV64I-NEXT:    sub a1, a2, a1
; RV64I-NEXT:    amoadd.w.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_sub_i32_neg:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    sub a1, a2, a1
; RV64IA-NEXT:    amoadd.w.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_sub_i32_neg:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    sub a1, a2, a1
; RV64I-ZALRSC-NEXT:    amoadd.w.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
  %b = sub i32 %x, %y
  %1 = atomicrmw sub ptr %a, i32 %b seq_cst
  ret i32 %1
}

define i64 @atomicrmw_sub_i64_neg(ptr %a, i64 %x, i64 %y) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_sub_i64_neg:
; RV64I:       # %bb.0:
; RV64I-NEXT:    sub a1, a2, a1
; RV64I-NEXT:    amoadd.d.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_sub_i64_neg:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    sub a1, a2, a1
; RV64IA-NEXT:    amoadd.d.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_sub_i64_neg:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    sub a1, a2, a1
; RV64I-ZALRSC-NEXT:    amoadd.d.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
  %b = sub i64 %x, %y
  %1 = atomicrmw sub ptr %a, i64 %b seq_cst
  ret i64 %1
}
