; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ysx64 -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV64I %s
; RUN: llc -mtriple=ysx64 -mattr=+a -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV64IA %s


define i8 @atomicrmw_uinc_wrap_i8(ptr %ptr, i8 %val) {
;
;
; RV64I-LABEL: atomicrmw_uinc_wrap_i8:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a3, a0, 3
; RV64I-NEXT:    li a4, 255
; RV64I-NEXT:    andi a0, a3, 24
; RV64I-NEXT:    sllw a4, a4, a3
; RV64I-NEXT:    lw a3, 0(a2)
; RV64I-NEXT:    not a4, a4
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    li a5, 1
; RV64I-NEXT:  .LBB0_1: # %atomicrmw.start
; RV64I-NEXT:    # =>This Loop Header: Depth=1
; RV64I-NEXT:    # Child Loop BB0_3 Depth 2
; RV64I-NEXT:    srlw a6, a3, a0
; RV64I-NEXT:    sext.w a7, a3
; RV64I-NEXT:    zext.b t0, a6
; RV64I-NEXT:    addiw a6, a6, 1
; RV64I-NEXT:    sltu t0, t0, a1
; RV64I-NEXT:    xori t0, t0, 1
; RV64I-NEXT:    addiw t0, t0, -1
; RV64I-NEXT:    and a6, t0, a6
; RV64I-NEXT:    zext.b a6, a6
; RV64I-NEXT:    sllw a6, a6, a0
; RV64I-NEXT:    and a3, a3, a4
; RV64I-NEXT:    or a6, a3, a6
; RV64I-NEXT:  .LBB0_3: # %atomicrmw.start
; RV64I-NEXT:    # Parent Loop BB0_1 Depth=1
; RV64I-NEXT:    # => This Inner Loop Header: Depth=2
; RV64I-NEXT:    lr.w.aqrl a3, (a2)
; RV64I-NEXT:    bne a3, a7, .LBB0_5
; RV64I-NEXT:  # %bb.4: # %atomicrmw.start
; RV64I-NEXT:    # in Loop: Header=BB0_3 Depth=2
; RV64I-NEXT:    sc.w.rl t0, a6, (a2)
; RV64I-NEXT:    bnez t0, .LBB0_3
; RV64I-NEXT:  .LBB0_5: # %atomicrmw.start
; RV64I-NEXT:    # in Loop: Header=BB0_1 Depth=1
; RV64I-NEXT:    xor a6, a3, a7
; RV64I-NEXT:    seqz a6, a6
; RV64I-NEXT:    bne a6, a5, .LBB0_1
; RV64I-NEXT:  # %bb.2: # %atomicrmw.end
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_uinc_wrap_i8:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a3, a0, 3
; RV64IA-NEXT:    li a4, 255
; RV64IA-NEXT:    andi a0, a3, 24
; RV64IA-NEXT:    sllw a4, a4, a3
; RV64IA-NEXT:    lw a3, 0(a2)
; RV64IA-NEXT:    not a4, a4
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    li a5, 1
; RV64IA-NEXT:  .LBB0_1: # %atomicrmw.start
; RV64IA-NEXT:    # =>This Loop Header: Depth=1
; RV64IA-NEXT:    # Child Loop BB0_3 Depth 2
; RV64IA-NEXT:    srlw a6, a3, a0
; RV64IA-NEXT:    sext.w a7, a3
; RV64IA-NEXT:    zext.b t0, a6
; RV64IA-NEXT:    addiw a6, a6, 1
; RV64IA-NEXT:    sltu t0, t0, a1
; RV64IA-NEXT:    xori t0, t0, 1
; RV64IA-NEXT:    addiw t0, t0, -1
; RV64IA-NEXT:    and a6, t0, a6
; RV64IA-NEXT:    zext.b a6, a6
; RV64IA-NEXT:    sllw a6, a6, a0
; RV64IA-NEXT:    and a3, a3, a4
; RV64IA-NEXT:    or a6, a3, a6
; RV64IA-NEXT:  .LBB0_3: # %atomicrmw.start
; RV64IA-NEXT:    # Parent Loop BB0_1 Depth=1
; RV64IA-NEXT:    # => This Inner Loop Header: Depth=2
; RV64IA-NEXT:    lr.w.aqrl a3, (a2)
; RV64IA-NEXT:    bne a3, a7, .LBB0_5
; RV64IA-NEXT:  # %bb.4: # %atomicrmw.start
; RV64IA-NEXT:    # in Loop: Header=BB0_3 Depth=2
; RV64IA-NEXT:    sc.w.rl t0, a6, (a2)
; RV64IA-NEXT:    bnez t0, .LBB0_3
; RV64IA-NEXT:  .LBB0_5: # %atomicrmw.start
; RV64IA-NEXT:    # in Loop: Header=BB0_1 Depth=1
; RV64IA-NEXT:    xor a6, a3, a7
; RV64IA-NEXT:    seqz a6, a6
; RV64IA-NEXT:    bne a6, a5, .LBB0_1
; RV64IA-NEXT:  # %bb.2: # %atomicrmw.end
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %result = atomicrmw uinc_wrap ptr %ptr, i8 %val seq_cst
  ret i8 %result
}

define i16 @atomicrmw_uinc_wrap_i16(ptr %ptr, i16 %val) {
;
;
; RV64I-LABEL: atomicrmw_uinc_wrap_i16:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a5, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    andi a0, a5, 24
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    lw a4, 0(a2)
; RV64I-NEXT:    sllw a5, a3, a5
; RV64I-NEXT:    not a5, a5
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    li a6, 1
; RV64I-NEXT:  .LBB1_1: # %atomicrmw.start
; RV64I-NEXT:    # =>This Loop Header: Depth=1
; RV64I-NEXT:    # Child Loop BB1_3 Depth 2
; RV64I-NEXT:    srlw a7, a4, a0
; RV64I-NEXT:    sext.w t0, a4
; RV64I-NEXT:    and t1, a7, a3
; RV64I-NEXT:    addiw a7, a7, 1
; RV64I-NEXT:    sltu t1, t1, a1
; RV64I-NEXT:    and a7, a7, a3
; RV64I-NEXT:    xori t1, t1, 1
; RV64I-NEXT:    addiw t1, t1, -1
; RV64I-NEXT:    and a7, t1, a7
; RV64I-NEXT:    sllw a7, a7, a0
; RV64I-NEXT:    and a4, a4, a5
; RV64I-NEXT:    or a7, a4, a7
; RV64I-NEXT:  .LBB1_3: # %atomicrmw.start
; RV64I-NEXT:    # Parent Loop BB1_1 Depth=1
; RV64I-NEXT:    # => This Inner Loop Header: Depth=2
; RV64I-NEXT:    lr.w.aqrl a4, (a2)
; RV64I-NEXT:    bne a4, t0, .LBB1_5
; RV64I-NEXT:  # %bb.4: # %atomicrmw.start
; RV64I-NEXT:    # in Loop: Header=BB1_3 Depth=2
; RV64I-NEXT:    sc.w.rl t1, a7, (a2)
; RV64I-NEXT:    bnez t1, .LBB1_3
; RV64I-NEXT:  .LBB1_5: # %atomicrmw.start
; RV64I-NEXT:    # in Loop: Header=BB1_1 Depth=1
; RV64I-NEXT:    xor a7, a4, t0
; RV64I-NEXT:    seqz a7, a7
; RV64I-NEXT:    bne a7, a6, .LBB1_1
; RV64I-NEXT:  # %bb.2: # %atomicrmw.end
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_uinc_wrap_i16:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a5, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    andi a0, a5, 24
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    lw a4, 0(a2)
; RV64IA-NEXT:    sllw a5, a3, a5
; RV64IA-NEXT:    not a5, a5
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    li a6, 1
; RV64IA-NEXT:  .LBB1_1: # %atomicrmw.start
; RV64IA-NEXT:    # =>This Loop Header: Depth=1
; RV64IA-NEXT:    # Child Loop BB1_3 Depth 2
; RV64IA-NEXT:    srlw a7, a4, a0
; RV64IA-NEXT:    sext.w t0, a4
; RV64IA-NEXT:    and t1, a7, a3
; RV64IA-NEXT:    addiw a7, a7, 1
; RV64IA-NEXT:    sltu t1, t1, a1
; RV64IA-NEXT:    and a7, a7, a3
; RV64IA-NEXT:    xori t1, t1, 1
; RV64IA-NEXT:    addiw t1, t1, -1
; RV64IA-NEXT:    and a7, t1, a7
; RV64IA-NEXT:    sllw a7, a7, a0
; RV64IA-NEXT:    and a4, a4, a5
; RV64IA-NEXT:    or a7, a4, a7
; RV64IA-NEXT:  .LBB1_3: # %atomicrmw.start
; RV64IA-NEXT:    # Parent Loop BB1_1 Depth=1
; RV64IA-NEXT:    # => This Inner Loop Header: Depth=2
; RV64IA-NEXT:    lr.w.aqrl a4, (a2)
; RV64IA-NEXT:    bne a4, t0, .LBB1_5
; RV64IA-NEXT:  # %bb.4: # %atomicrmw.start
; RV64IA-NEXT:    # in Loop: Header=BB1_3 Depth=2
; RV64IA-NEXT:    sc.w.rl t1, a7, (a2)
; RV64IA-NEXT:    bnez t1, .LBB1_3
; RV64IA-NEXT:  .LBB1_5: # %atomicrmw.start
; RV64IA-NEXT:    # in Loop: Header=BB1_1 Depth=1
; RV64IA-NEXT:    xor a7, a4, t0
; RV64IA-NEXT:    seqz a7, a7
; RV64IA-NEXT:    bne a7, a6, .LBB1_1
; RV64IA-NEXT:  # %bb.2: # %atomicrmw.end
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %result = atomicrmw uinc_wrap ptr %ptr, i16 %val seq_cst
  ret i16 %result
}

define i32 @atomicrmw_uinc_wrap_i32(ptr %ptr, i32 %val) {
;
;
; RV64I-LABEL: atomicrmw_uinc_wrap_i32:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lw a2, 0(a0)
; RV64I-NEXT:    sext.w a1, a1
; RV64I-NEXT:    li a3, 1
; RV64I-NEXT:  .LBB2_1: # %atomicrmw.start
; RV64I-NEXT:    # =>This Loop Header: Depth=1
; RV64I-NEXT:    # Child Loop BB2_3 Depth 2
; RV64I-NEXT:    addiw a4, a2, 1
; RV64I-NEXT:    sext.w a5, a2
; RV64I-NEXT:    sltu a2, a5, a1
; RV64I-NEXT:    xori a2, a2, 1
; RV64I-NEXT:    addi a2, a2, -1
; RV64I-NEXT:    and a4, a2, a4
; RV64I-NEXT:  .LBB2_3: # %atomicrmw.start
; RV64I-NEXT:    # Parent Loop BB2_1 Depth=1
; RV64I-NEXT:    # => This Inner Loop Header: Depth=2
; RV64I-NEXT:    lr.w.aqrl a2, (a0)
; RV64I-NEXT:    bne a2, a5, .LBB2_5
; RV64I-NEXT:  # %bb.4: # %atomicrmw.start
; RV64I-NEXT:    # in Loop: Header=BB2_3 Depth=2
; RV64I-NEXT:    sc.w.rl a6, a4, (a0)
; RV64I-NEXT:    bnez a6, .LBB2_3
; RV64I-NEXT:  .LBB2_5: # %atomicrmw.start
; RV64I-NEXT:    # in Loop: Header=BB2_1 Depth=1
; RV64I-NEXT:    xor a4, a2, a5
; RV64I-NEXT:    seqz a4, a4
; RV64I-NEXT:    bne a4, a3, .LBB2_1
; RV64I-NEXT:  # %bb.2: # %atomicrmw.end
; RV64I-NEXT:    mv a0, a2
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_uinc_wrap_i32:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    lw a2, 0(a0)
; RV64IA-NEXT:    sext.w a1, a1
; RV64IA-NEXT:    li a3, 1
; RV64IA-NEXT:  .LBB2_1: # %atomicrmw.start
; RV64IA-NEXT:    # =>This Loop Header: Depth=1
; RV64IA-NEXT:    # Child Loop BB2_3 Depth 2
; RV64IA-NEXT:    addiw a4, a2, 1
; RV64IA-NEXT:    sext.w a5, a2
; RV64IA-NEXT:    sltu a2, a5, a1
; RV64IA-NEXT:    xori a2, a2, 1
; RV64IA-NEXT:    addi a2, a2, -1
; RV64IA-NEXT:    and a4, a2, a4
; RV64IA-NEXT:  .LBB2_3: # %atomicrmw.start
; RV64IA-NEXT:    # Parent Loop BB2_1 Depth=1
; RV64IA-NEXT:    # => This Inner Loop Header: Depth=2
; RV64IA-NEXT:    lr.w.aqrl a2, (a0)
; RV64IA-NEXT:    bne a2, a5, .LBB2_5
; RV64IA-NEXT:  # %bb.4: # %atomicrmw.start
; RV64IA-NEXT:    # in Loop: Header=BB2_3 Depth=2
; RV64IA-NEXT:    sc.w.rl a6, a4, (a0)
; RV64IA-NEXT:    bnez a6, .LBB2_3
; RV64IA-NEXT:  .LBB2_5: # %atomicrmw.start
; RV64IA-NEXT:    # in Loop: Header=BB2_1 Depth=1
; RV64IA-NEXT:    xor a4, a2, a5
; RV64IA-NEXT:    seqz a4, a4
; RV64IA-NEXT:    bne a4, a3, .LBB2_1
; RV64IA-NEXT:  # %bb.2: # %atomicrmw.end
; RV64IA-NEXT:    mv a0, a2
; RV64IA-NEXT:    ret
  %result = atomicrmw uinc_wrap ptr %ptr, i32 %val seq_cst
  ret i32 %result
}

define i64 @atomicrmw_uinc_wrap_i64(ptr %ptr, i64 %val) {
;
;
; RV64I-LABEL: atomicrmw_uinc_wrap_i64:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ld a2, 0(a0)
; RV64I-NEXT:    li a3, 1
; RV64I-NEXT:  .LBB3_1: # %atomicrmw.start
; RV64I-NEXT:    # =>This Loop Header: Depth=1
; RV64I-NEXT:    # Child Loop BB3_3 Depth 2
; RV64I-NEXT:    mv a4, a2
; RV64I-NEXT:    addi a2, a2, 1
; RV64I-NEXT:    sltu a5, a4, a1
; RV64I-NEXT:    xori a5, a5, 1
; RV64I-NEXT:    addi a5, a5, -1
; RV64I-NEXT:    and a5, a5, a2
; RV64I-NEXT:  .LBB3_3: # %atomicrmw.start
; RV64I-NEXT:    # Parent Loop BB3_1 Depth=1
; RV64I-NEXT:    # => This Inner Loop Header: Depth=2
; RV64I-NEXT:    lr.d.aqrl a2, (a0)
; RV64I-NEXT:    bne a2, a4, .LBB3_5
; RV64I-NEXT:  # %bb.4: # %atomicrmw.start
; RV64I-NEXT:    # in Loop: Header=BB3_3 Depth=2
; RV64I-NEXT:    sc.d.rl a6, a5, (a0)
; RV64I-NEXT:    bnez a6, .LBB3_3
; RV64I-NEXT:  .LBB3_5: # %atomicrmw.start
; RV64I-NEXT:    # in Loop: Header=BB3_1 Depth=1
; RV64I-NEXT:    xor a4, a2, a4
; RV64I-NEXT:    seqz a4, a4
; RV64I-NEXT:    bne a4, a3, .LBB3_1
; RV64I-NEXT:  # %bb.2: # %atomicrmw.end
; RV64I-NEXT:    mv a0, a2
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_uinc_wrap_i64:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    ld a2, 0(a0)
; RV64IA-NEXT:    li a3, 1
; RV64IA-NEXT:  .LBB3_1: # %atomicrmw.start
; RV64IA-NEXT:    # =>This Loop Header: Depth=1
; RV64IA-NEXT:    # Child Loop BB3_3 Depth 2
; RV64IA-NEXT:    mv a4, a2
; RV64IA-NEXT:    addi a2, a2, 1
; RV64IA-NEXT:    sltu a5, a4, a1
; RV64IA-NEXT:    xori a5, a5, 1
; RV64IA-NEXT:    addi a5, a5, -1
; RV64IA-NEXT:    and a5, a5, a2
; RV64IA-NEXT:  .LBB3_3: # %atomicrmw.start
; RV64IA-NEXT:    # Parent Loop BB3_1 Depth=1
; RV64IA-NEXT:    # => This Inner Loop Header: Depth=2
; RV64IA-NEXT:    lr.d.aqrl a2, (a0)
; RV64IA-NEXT:    bne a2, a4, .LBB3_5
; RV64IA-NEXT:  # %bb.4: # %atomicrmw.start
; RV64IA-NEXT:    # in Loop: Header=BB3_3 Depth=2
; RV64IA-NEXT:    sc.d.rl a6, a5, (a0)
; RV64IA-NEXT:    bnez a6, .LBB3_3
; RV64IA-NEXT:  .LBB3_5: # %atomicrmw.start
; RV64IA-NEXT:    # in Loop: Header=BB3_1 Depth=1
; RV64IA-NEXT:    xor a4, a2, a4
; RV64IA-NEXT:    seqz a4, a4
; RV64IA-NEXT:    bne a4, a3, .LBB3_1
; RV64IA-NEXT:  # %bb.2: # %atomicrmw.end
; RV64IA-NEXT:    mv a0, a2
; RV64IA-NEXT:    ret
  %result = atomicrmw uinc_wrap ptr %ptr, i64 %val seq_cst
  ret i64 %result
}

define i8 @atomicrmw_udec_wrap_i8(ptr %ptr, i8 %val) {
;
;
; RV64I-LABEL: atomicrmw_udec_wrap_i8:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a3, a0, 3
; RV64I-NEXT:    li a4, 255
; RV64I-NEXT:    andi a0, a3, 24
; RV64I-NEXT:    sllw a4, a4, a3
; RV64I-NEXT:    lw a3, 0(a2)
; RV64I-NEXT:    not a4, a4
; RV64I-NEXT:    zext.b a5, a1
; RV64I-NEXT:    li a6, 1
; RV64I-NEXT:    j .LBB4_2
; RV64I-NEXT:  .LBB4_1: # %atomicrmw.start
; RV64I-NEXT:    # in Loop: Header=BB4_2 Depth=1
; RV64I-NEXT:    sext.w a7, a3
; RV64I-NEXT:    zext.b t0, t0
; RV64I-NEXT:    sllw t0, t0, a0
; RV64I-NEXT:    and a3, a3, a4
; RV64I-NEXT:    or t0, a3, t0
; RV64I-NEXT:  .LBB4_5: # %atomicrmw.start
; RV64I-NEXT:    # Parent Loop BB4_2 Depth=1
; RV64I-NEXT:    # => This Inner Loop Header: Depth=2
; RV64I-NEXT:    lr.w.aqrl a3, (a2)
; RV64I-NEXT:    bne a3, a7, .LBB4_7
; RV64I-NEXT:  # %bb.6: # %atomicrmw.start
; RV64I-NEXT:    # in Loop: Header=BB4_5 Depth=2
; RV64I-NEXT:    sc.w.rl t1, t0, (a2)
; RV64I-NEXT:    bnez t1, .LBB4_5
; RV64I-NEXT:  .LBB4_7: # %atomicrmw.start
; RV64I-NEXT:    # in Loop: Header=BB4_2 Depth=1
; RV64I-NEXT:    xor a7, a3, a7
; RV64I-NEXT:    seqz a7, a7
; RV64I-NEXT:    beq a7, a6, .LBB4_4
; RV64I-NEXT:  .LBB4_2: # %atomicrmw.start
; RV64I-NEXT:    # =>This Loop Header: Depth=1
; RV64I-NEXT:    # Child Loop BB4_5 Depth 2
; RV64I-NEXT:    srlw a7, a3, a0
; RV64I-NEXT:    zext.b t0, a7
; RV64I-NEXT:    seqz t1, t0
; RV64I-NEXT:    sltu t0, a5, t0
; RV64I-NEXT:    or t1, t1, t0
; RV64I-NEXT:    mv t0, a1
; RV64I-NEXT:    bnez t1, .LBB4_1
; RV64I-NEXT:  # %bb.3: # %atomicrmw.start
; RV64I-NEXT:    # in Loop: Header=BB4_2 Depth=1
; RV64I-NEXT:    addi t0, a7, -1
; RV64I-NEXT:    j .LBB4_1
; RV64I-NEXT:  .LBB4_4: # %atomicrmw.end
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_udec_wrap_i8:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a3, a0, 3
; RV64IA-NEXT:    li a4, 255
; RV64IA-NEXT:    andi a0, a3, 24
; RV64IA-NEXT:    sllw a4, a4, a3
; RV64IA-NEXT:    lw a3, 0(a2)
; RV64IA-NEXT:    not a4, a4
; RV64IA-NEXT:    zext.b a5, a1
; RV64IA-NEXT:    li a6, 1
; RV64IA-NEXT:    j .LBB4_2
; RV64IA-NEXT:  .LBB4_1: # %atomicrmw.start
; RV64IA-NEXT:    # in Loop: Header=BB4_2 Depth=1
; RV64IA-NEXT:    sext.w a7, a3
; RV64IA-NEXT:    zext.b t0, t0
; RV64IA-NEXT:    sllw t0, t0, a0
; RV64IA-NEXT:    and a3, a3, a4
; RV64IA-NEXT:    or t0, a3, t0
; RV64IA-NEXT:  .LBB4_5: # %atomicrmw.start
; RV64IA-NEXT:    # Parent Loop BB4_2 Depth=1
; RV64IA-NEXT:    # => This Inner Loop Header: Depth=2
; RV64IA-NEXT:    lr.w.aqrl a3, (a2)
; RV64IA-NEXT:    bne a3, a7, .LBB4_7
; RV64IA-NEXT:  # %bb.6: # %atomicrmw.start
; RV64IA-NEXT:    # in Loop: Header=BB4_5 Depth=2
; RV64IA-NEXT:    sc.w.rl t1, t0, (a2)
; RV64IA-NEXT:    bnez t1, .LBB4_5
; RV64IA-NEXT:  .LBB4_7: # %atomicrmw.start
; RV64IA-NEXT:    # in Loop: Header=BB4_2 Depth=1
; RV64IA-NEXT:    xor a7, a3, a7
; RV64IA-NEXT:    seqz a7, a7
; RV64IA-NEXT:    beq a7, a6, .LBB4_4
; RV64IA-NEXT:  .LBB4_2: # %atomicrmw.start
; RV64IA-NEXT:    # =>This Loop Header: Depth=1
; RV64IA-NEXT:    # Child Loop BB4_5 Depth 2
; RV64IA-NEXT:    srlw a7, a3, a0
; RV64IA-NEXT:    zext.b t0, a7
; RV64IA-NEXT:    seqz t1, t0
; RV64IA-NEXT:    sltu t0, a5, t0
; RV64IA-NEXT:    or t1, t1, t0
; RV64IA-NEXT:    mv t0, a1
; RV64IA-NEXT:    bnez t1, .LBB4_1
; RV64IA-NEXT:  # %bb.3: # %atomicrmw.start
; RV64IA-NEXT:    # in Loop: Header=BB4_2 Depth=1
; RV64IA-NEXT:    addi t0, a7, -1
; RV64IA-NEXT:    j .LBB4_1
; RV64IA-NEXT:  .LBB4_4: # %atomicrmw.end
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %result = atomicrmw udec_wrap ptr %ptr, i8 %val seq_cst
  ret i8 %result
}

define i16 @atomicrmw_udec_wrap_i16(ptr %ptr, i16 %val) {
;
;
; RV64I-LABEL: atomicrmw_udec_wrap_i16:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a5, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    andi a0, a5, 24
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    lw a4, 0(a2)
; RV64I-NEXT:    sllw a5, a3, a5
; RV64I-NEXT:    not a5, a5
; RV64I-NEXT:    and a6, a1, a3
; RV64I-NEXT:    li a7, 1
; RV64I-NEXT:    j .LBB5_2
; RV64I-NEXT:  .LBB5_1: # %atomicrmw.start
; RV64I-NEXT:    # in Loop: Header=BB5_2 Depth=1
; RV64I-NEXT:    sext.w t0, a4
; RV64I-NEXT:    and t1, t1, a3
; RV64I-NEXT:    sllw t1, t1, a0
; RV64I-NEXT:    and a4, a4, a5
; RV64I-NEXT:    or t1, a4, t1
; RV64I-NEXT:  .LBB5_5: # %atomicrmw.start
; RV64I-NEXT:    # Parent Loop BB5_2 Depth=1
; RV64I-NEXT:    # => This Inner Loop Header: Depth=2
; RV64I-NEXT:    lr.w.aqrl a4, (a2)
; RV64I-NEXT:    bne a4, t0, .LBB5_7
; RV64I-NEXT:  # %bb.6: # %atomicrmw.start
; RV64I-NEXT:    # in Loop: Header=BB5_5 Depth=2
; RV64I-NEXT:    sc.w.rl t2, t1, (a2)
; RV64I-NEXT:    bnez t2, .LBB5_5
; RV64I-NEXT:  .LBB5_7: # %atomicrmw.start
; RV64I-NEXT:    # in Loop: Header=BB5_2 Depth=1
; RV64I-NEXT:    xor t0, a4, t0
; RV64I-NEXT:    seqz t0, t0
; RV64I-NEXT:    beq t0, a7, .LBB5_4
; RV64I-NEXT:  .LBB5_2: # %atomicrmw.start
; RV64I-NEXT:    # =>This Loop Header: Depth=1
; RV64I-NEXT:    # Child Loop BB5_5 Depth 2
; RV64I-NEXT:    srlw t0, a4, a0
; RV64I-NEXT:    and t1, t0, a3
; RV64I-NEXT:    seqz t2, t1
; RV64I-NEXT:    sltu t1, a6, t1
; RV64I-NEXT:    or t2, t2, t1
; RV64I-NEXT:    mv t1, a1
; RV64I-NEXT:    bnez t2, .LBB5_1
; RV64I-NEXT:  # %bb.3: # %atomicrmw.start
; RV64I-NEXT:    # in Loop: Header=BB5_2 Depth=1
; RV64I-NEXT:    addi t1, t0, -1
; RV64I-NEXT:    j .LBB5_1
; RV64I-NEXT:  .LBB5_4: # %atomicrmw.end
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_udec_wrap_i16:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a5, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    andi a0, a5, 24
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    lw a4, 0(a2)
; RV64IA-NEXT:    sllw a5, a3, a5
; RV64IA-NEXT:    not a5, a5
; RV64IA-NEXT:    and a6, a1, a3
; RV64IA-NEXT:    li a7, 1
; RV64IA-NEXT:    j .LBB5_2
; RV64IA-NEXT:  .LBB5_1: # %atomicrmw.start
; RV64IA-NEXT:    # in Loop: Header=BB5_2 Depth=1
; RV64IA-NEXT:    sext.w t0, a4
; RV64IA-NEXT:    and t1, t1, a3
; RV64IA-NEXT:    sllw t1, t1, a0
; RV64IA-NEXT:    and a4, a4, a5
; RV64IA-NEXT:    or t1, a4, t1
; RV64IA-NEXT:  .LBB5_5: # %atomicrmw.start
; RV64IA-NEXT:    # Parent Loop BB5_2 Depth=1
; RV64IA-NEXT:    # => This Inner Loop Header: Depth=2
; RV64IA-NEXT:    lr.w.aqrl a4, (a2)
; RV64IA-NEXT:    bne a4, t0, .LBB5_7
; RV64IA-NEXT:  # %bb.6: # %atomicrmw.start
; RV64IA-NEXT:    # in Loop: Header=BB5_5 Depth=2
; RV64IA-NEXT:    sc.w.rl t2, t1, (a2)
; RV64IA-NEXT:    bnez t2, .LBB5_5
; RV64IA-NEXT:  .LBB5_7: # %atomicrmw.start
; RV64IA-NEXT:    # in Loop: Header=BB5_2 Depth=1
; RV64IA-NEXT:    xor t0, a4, t0
; RV64IA-NEXT:    seqz t0, t0
; RV64IA-NEXT:    beq t0, a7, .LBB5_4
; RV64IA-NEXT:  .LBB5_2: # %atomicrmw.start
; RV64IA-NEXT:    # =>This Loop Header: Depth=1
; RV64IA-NEXT:    # Child Loop BB5_5 Depth 2
; RV64IA-NEXT:    srlw t0, a4, a0
; RV64IA-NEXT:    and t1, t0, a3
; RV64IA-NEXT:    seqz t2, t1
; RV64IA-NEXT:    sltu t1, a6, t1
; RV64IA-NEXT:    or t2, t2, t1
; RV64IA-NEXT:    mv t1, a1
; RV64IA-NEXT:    bnez t2, .LBB5_1
; RV64IA-NEXT:  # %bb.3: # %atomicrmw.start
; RV64IA-NEXT:    # in Loop: Header=BB5_2 Depth=1
; RV64IA-NEXT:    addi t1, t0, -1
; RV64IA-NEXT:    j .LBB5_1
; RV64IA-NEXT:  .LBB5_4: # %atomicrmw.end
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %result = atomicrmw udec_wrap ptr %ptr, i16 %val seq_cst
  ret i16 %result
}

define i32 @atomicrmw_udec_wrap_i32(ptr %ptr, i32 %val) {
;
;
; RV64I-LABEL: atomicrmw_udec_wrap_i32:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lw a2, 0(a0)
; RV64I-NEXT:    sext.w a3, a1
; RV64I-NEXT:    li a4, 1
; RV64I-NEXT:    j .LBB6_2
; RV64I-NEXT:  .LBB6_1: # %atomicrmw.start
; RV64I-NEXT:    # in Loop: Header=BB6_2 Depth=1
; RV64I-NEXT:  .LBB6_5: # %atomicrmw.start
; RV64I-NEXT:    # Parent Loop BB6_2 Depth=1
; RV64I-NEXT:    # => This Inner Loop Header: Depth=2
; RV64I-NEXT:    lr.w.aqrl a2, (a0)
; RV64I-NEXT:    bne a2, a5, .LBB6_7
; RV64I-NEXT:  # %bb.6: # %atomicrmw.start
; RV64I-NEXT:    # in Loop: Header=BB6_5 Depth=2
; RV64I-NEXT:    sc.w.rl a7, a6, (a0)
; RV64I-NEXT:    bnez a7, .LBB6_5
; RV64I-NEXT:  .LBB6_7: # %atomicrmw.start
; RV64I-NEXT:    # in Loop: Header=BB6_2 Depth=1
; RV64I-NEXT:    xor a5, a2, a5
; RV64I-NEXT:    seqz a5, a5
; RV64I-NEXT:    beq a5, a4, .LBB6_4
; RV64I-NEXT:  .LBB6_2: # %atomicrmw.start
; RV64I-NEXT:    # =>This Loop Header: Depth=1
; RV64I-NEXT:    # Child Loop BB6_5 Depth 2
; RV64I-NEXT:    sext.w a5, a2
; RV64I-NEXT:    seqz a6, a5
; RV64I-NEXT:    sltu a7, a3, a5
; RV64I-NEXT:    or a7, a6, a7
; RV64I-NEXT:    mv a6, a1
; RV64I-NEXT:    bnez a7, .LBB6_1
; RV64I-NEXT:  # %bb.3: # %atomicrmw.start
; RV64I-NEXT:    # in Loop: Header=BB6_2 Depth=1
; RV64I-NEXT:    addiw a6, a2, -1
; RV64I-NEXT:    j .LBB6_1
; RV64I-NEXT:  .LBB6_4: # %atomicrmw.end
; RV64I-NEXT:    mv a0, a2
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_udec_wrap_i32:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    lw a2, 0(a0)
; RV64IA-NEXT:    sext.w a3, a1
; RV64IA-NEXT:    li a4, 1
; RV64IA-NEXT:    j .LBB6_2
; RV64IA-NEXT:  .LBB6_1: # %atomicrmw.start
; RV64IA-NEXT:    # in Loop: Header=BB6_2 Depth=1
; RV64IA-NEXT:  .LBB6_5: # %atomicrmw.start
; RV64IA-NEXT:    # Parent Loop BB6_2 Depth=1
; RV64IA-NEXT:    # => This Inner Loop Header: Depth=2
; RV64IA-NEXT:    lr.w.aqrl a2, (a0)
; RV64IA-NEXT:    bne a2, a5, .LBB6_7
; RV64IA-NEXT:  # %bb.6: # %atomicrmw.start
; RV64IA-NEXT:    # in Loop: Header=BB6_5 Depth=2
; RV64IA-NEXT:    sc.w.rl a7, a6, (a0)
; RV64IA-NEXT:    bnez a7, .LBB6_5
; RV64IA-NEXT:  .LBB6_7: # %atomicrmw.start
; RV64IA-NEXT:    # in Loop: Header=BB6_2 Depth=1
; RV64IA-NEXT:    xor a5, a2, a5
; RV64IA-NEXT:    seqz a5, a5
; RV64IA-NEXT:    beq a5, a4, .LBB6_4
; RV64IA-NEXT:  .LBB6_2: # %atomicrmw.start
; RV64IA-NEXT:    # =>This Loop Header: Depth=1
; RV64IA-NEXT:    # Child Loop BB6_5 Depth 2
; RV64IA-NEXT:    sext.w a5, a2
; RV64IA-NEXT:    seqz a6, a5
; RV64IA-NEXT:    sltu a7, a3, a5
; RV64IA-NEXT:    or a7, a6, a7
; RV64IA-NEXT:    mv a6, a1
; RV64IA-NEXT:    bnez a7, .LBB6_1
; RV64IA-NEXT:  # %bb.3: # %atomicrmw.start
; RV64IA-NEXT:    # in Loop: Header=BB6_2 Depth=1
; RV64IA-NEXT:    addiw a6, a2, -1
; RV64IA-NEXT:    j .LBB6_1
; RV64IA-NEXT:  .LBB6_4: # %atomicrmw.end
; RV64IA-NEXT:    mv a0, a2
; RV64IA-NEXT:    ret
  %result = atomicrmw udec_wrap ptr %ptr, i32 %val seq_cst
  ret i32 %result
}

define i64 @atomicrmw_udec_wrap_i64(ptr %ptr, i64 %val) {
;
;
; RV64I-LABEL: atomicrmw_udec_wrap_i64:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ld a4, 0(a0)
; RV64I-NEXT:    li a3, 1
; RV64I-NEXT:    j .LBB7_2
; RV64I-NEXT:  .LBB7_1: # %atomicrmw.start
; RV64I-NEXT:    # in Loop: Header=BB7_2 Depth=1
; RV64I-NEXT:  .LBB7_5: # %atomicrmw.start
; RV64I-NEXT:    # Parent Loop BB7_2 Depth=1
; RV64I-NEXT:    # => This Inner Loop Header: Depth=2
; RV64I-NEXT:    lr.d.aqrl a2, (a0)
; RV64I-NEXT:    bne a2, a4, .LBB7_7
; RV64I-NEXT:  # %bb.6: # %atomicrmw.start
; RV64I-NEXT:    # in Loop: Header=BB7_5 Depth=2
; RV64I-NEXT:    sc.d.rl a6, a5, (a0)
; RV64I-NEXT:    bnez a6, .LBB7_5
; RV64I-NEXT:  .LBB7_7: # %atomicrmw.start
; RV64I-NEXT:    # in Loop: Header=BB7_2 Depth=1
; RV64I-NEXT:    xor a4, a2, a4
; RV64I-NEXT:    seqz a5, a4
; RV64I-NEXT:    mv a4, a2
; RV64I-NEXT:    beq a5, a3, .LBB7_4
; RV64I-NEXT:  .LBB7_2: # %atomicrmw.start
; RV64I-NEXT:    # =>This Loop Header: Depth=1
; RV64I-NEXT:    # Child Loop BB7_5 Depth 2
; RV64I-NEXT:    seqz a2, a4
; RV64I-NEXT:    sltu a5, a1, a4
; RV64I-NEXT:    or a2, a2, a5
; RV64I-NEXT:    mv a5, a1
; RV64I-NEXT:    bnez a2, .LBB7_1
; RV64I-NEXT:  # %bb.3: # %atomicrmw.start
; RV64I-NEXT:    # in Loop: Header=BB7_2 Depth=1
; RV64I-NEXT:    addi a5, a4, -1
; RV64I-NEXT:    j .LBB7_1
; RV64I-NEXT:  .LBB7_4: # %atomicrmw.end
; RV64I-NEXT:    mv a0, a2
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_udec_wrap_i64:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    ld a4, 0(a0)
; RV64IA-NEXT:    li a3, 1
; RV64IA-NEXT:    j .LBB7_2
; RV64IA-NEXT:  .LBB7_1: # %atomicrmw.start
; RV64IA-NEXT:    # in Loop: Header=BB7_2 Depth=1
; RV64IA-NEXT:  .LBB7_5: # %atomicrmw.start
; RV64IA-NEXT:    # Parent Loop BB7_2 Depth=1
; RV64IA-NEXT:    # => This Inner Loop Header: Depth=2
; RV64IA-NEXT:    lr.d.aqrl a2, (a0)
; RV64IA-NEXT:    bne a2, a4, .LBB7_7
; RV64IA-NEXT:  # %bb.6: # %atomicrmw.start
; RV64IA-NEXT:    # in Loop: Header=BB7_5 Depth=2
; RV64IA-NEXT:    sc.d.rl a6, a5, (a0)
; RV64IA-NEXT:    bnez a6, .LBB7_5
; RV64IA-NEXT:  .LBB7_7: # %atomicrmw.start
; RV64IA-NEXT:    # in Loop: Header=BB7_2 Depth=1
; RV64IA-NEXT:    xor a4, a2, a4
; RV64IA-NEXT:    seqz a5, a4
; RV64IA-NEXT:    mv a4, a2
; RV64IA-NEXT:    beq a5, a3, .LBB7_4
; RV64IA-NEXT:  .LBB7_2: # %atomicrmw.start
; RV64IA-NEXT:    # =>This Loop Header: Depth=1
; RV64IA-NEXT:    # Child Loop BB7_5 Depth 2
; RV64IA-NEXT:    seqz a2, a4
; RV64IA-NEXT:    sltu a5, a1, a4
; RV64IA-NEXT:    or a2, a2, a5
; RV64IA-NEXT:    mv a5, a1
; RV64IA-NEXT:    bnez a2, .LBB7_1
; RV64IA-NEXT:  # %bb.3: # %atomicrmw.start
; RV64IA-NEXT:    # in Loop: Header=BB7_2 Depth=1
; RV64IA-NEXT:    addi a5, a4, -1
; RV64IA-NEXT:    j .LBB7_1
; RV64IA-NEXT:  .LBB7_4: # %atomicrmw.end
; RV64IA-NEXT:    mv a0, a2
; RV64IA-NEXT:    ret
  %result = atomicrmw udec_wrap ptr %ptr, i64 %val seq_cst
  ret i64 %result
}
