; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ysx64 -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV64I %s
; RUN: llc -mtriple=ysx64 -mattr=+zalrsc -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV64I-ZALRSC %s



; RUN: llc -mtriple=ysx64 -mattr=+a -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefixes=RV64IA %s



define i8 @atomic_load_i8_unordered(ptr %a) nounwind {
;
;
;
; RV64I-LABEL: atomic_load_i8_unordered:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lb a0, 0(a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_load_i8_unordered:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    lb a0, 0(a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i8_unordered:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    lb a0, 0(a0)
; RV64IA-NEXT:    ret
  %1 = load atomic i8, ptr %a unordered, align 1
  ret i8 %1
}

define i8 @atomic_load_i8_monotonic(ptr %a) nounwind {
;
;
;
; RV64I-LABEL: atomic_load_i8_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lb a0, 0(a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_load_i8_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    lb a0, 0(a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i8_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    lb a0, 0(a0)
; RV64IA-NEXT:    ret
  %1 = load atomic i8, ptr %a monotonic, align 1
  ret i8 %1
}

define i8 @atomic_load_i8_acquire(ptr %a) nounwind {
;
;
;
;
; RV64I-LABEL: atomic_load_i8_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lb a0, 0(a0)
; RV64I-NEXT:    fence r, rw
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_load_i8_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    lb a0, 0(a0)
; RV64I-ZALRSC-NEXT:    fence r, rw
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i8_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    lb a0, 0(a0)
; RV64IA-NEXT:    fence r, rw
; RV64IA-NEXT:    ret
  %1 = load atomic i8, ptr %a acquire, align 1
  ret i8 %1
}

define i8 @atomic_load_i8_seq_cst(ptr %a) nounwind {
;
;
;
;
; RV64I-LABEL: atomic_load_i8_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    fence rw, rw
; RV64I-NEXT:    lb a0, 0(a0)
; RV64I-NEXT:    fence r, rw
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_load_i8_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    fence rw, rw
; RV64I-ZALRSC-NEXT:    lb a0, 0(a0)
; RV64I-ZALRSC-NEXT:    fence r, rw
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i8_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    fence rw, rw
; RV64IA-NEXT:    lb a0, 0(a0)
; RV64IA-NEXT:    fence r, rw
; RV64IA-NEXT:    ret
  %1 = load atomic i8, ptr %a seq_cst, align 1
  ret i8 %1
}

define i16 @atomic_load_i16_unordered(ptr %a) nounwind {
;
;
;
; RV64I-LABEL: atomic_load_i16_unordered:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lh a0, 0(a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_load_i16_unordered:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    lh a0, 0(a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i16_unordered:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    lh a0, 0(a0)
; RV64IA-NEXT:    ret
  %1 = load atomic i16, ptr %a unordered, align 2
  ret i16 %1
}

define i16 @atomic_load_i16_monotonic(ptr %a) nounwind {
;
;
;
; RV64I-LABEL: atomic_load_i16_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lh a0, 0(a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_load_i16_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    lh a0, 0(a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i16_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    lh a0, 0(a0)
; RV64IA-NEXT:    ret
  %1 = load atomic i16, ptr %a monotonic, align 2
  ret i16 %1
}

define i16 @atomic_load_i16_acquire(ptr %a) nounwind {
;
;
;
;
; RV64I-LABEL: atomic_load_i16_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lh a0, 0(a0)
; RV64I-NEXT:    fence r, rw
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_load_i16_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    lh a0, 0(a0)
; RV64I-ZALRSC-NEXT:    fence r, rw
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i16_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    lh a0, 0(a0)
; RV64IA-NEXT:    fence r, rw
; RV64IA-NEXT:    ret
  %1 = load atomic i16, ptr %a acquire, align 2
  ret i16 %1
}

define i16 @atomic_load_i16_seq_cst(ptr %a) nounwind {
;
;
;
;
; RV64I-LABEL: atomic_load_i16_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    fence rw, rw
; RV64I-NEXT:    lh a0, 0(a0)
; RV64I-NEXT:    fence r, rw
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_load_i16_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    fence rw, rw
; RV64I-ZALRSC-NEXT:    lh a0, 0(a0)
; RV64I-ZALRSC-NEXT:    fence r, rw
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i16_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    fence rw, rw
; RV64IA-NEXT:    lh a0, 0(a0)
; RV64IA-NEXT:    fence r, rw
; RV64IA-NEXT:    ret
  %1 = load atomic i16, ptr %a seq_cst, align 2
  ret i16 %1
}

define i32 @atomic_load_i32_unordered(ptr %a) nounwind {
;
;
;
; RV64I-LABEL: atomic_load_i32_unordered:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lw a0, 0(a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_load_i32_unordered:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    lw a0, 0(a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i32_unordered:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    lw a0, 0(a0)
; RV64IA-NEXT:    ret
  %1 = load atomic i32, ptr %a unordered, align 4
  ret i32 %1
}

define i32 @atomic_load_i32_monotonic(ptr %a) nounwind {
;
;
;
; RV64I-LABEL: atomic_load_i32_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lw a0, 0(a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_load_i32_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    lw a0, 0(a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i32_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    lw a0, 0(a0)
; RV64IA-NEXT:    ret
  %1 = load atomic i32, ptr %a monotonic, align 4
  ret i32 %1
}

define i32 @atomic_load_i32_acquire(ptr %a) nounwind {
;
;
;
;
; RV64I-LABEL: atomic_load_i32_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lw a0, 0(a0)
; RV64I-NEXT:    fence r, rw
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_load_i32_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    lw a0, 0(a0)
; RV64I-ZALRSC-NEXT:    fence r, rw
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i32_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    lw a0, 0(a0)
; RV64IA-NEXT:    fence r, rw
; RV64IA-NEXT:    ret
  %1 = load atomic i32, ptr %a acquire, align 4
  ret i32 %1
}

define i32 @atomic_load_i32_seq_cst(ptr %a) nounwind {
;
;
;
;
; RV64I-LABEL: atomic_load_i32_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    fence rw, rw
; RV64I-NEXT:    lw a0, 0(a0)
; RV64I-NEXT:    fence r, rw
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_load_i32_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    fence rw, rw
; RV64I-ZALRSC-NEXT:    lw a0, 0(a0)
; RV64I-ZALRSC-NEXT:    fence r, rw
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i32_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    fence rw, rw
; RV64IA-NEXT:    lw a0, 0(a0)
; RV64IA-NEXT:    fence r, rw
; RV64IA-NEXT:    ret
  %1 = load atomic i32, ptr %a seq_cst, align 4
  ret i32 %1
}

define i64 @atomic_load_i64_unordered(ptr %a) nounwind {
;
;
;
; RV64I-LABEL: atomic_load_i64_unordered:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ld a0, 0(a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_load_i64_unordered:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    ld a0, 0(a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i64_unordered:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    ld a0, 0(a0)
; RV64IA-NEXT:    ret
  %1 = load atomic i64, ptr %a unordered, align 8
  ret i64 %1
}

define i64 @atomic_load_i64_monotonic(ptr %a) nounwind {
;
;
;
; RV64I-LABEL: atomic_load_i64_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ld a0, 0(a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_load_i64_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    ld a0, 0(a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i64_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    ld a0, 0(a0)
; RV64IA-NEXT:    ret
  %1 = load atomic i64, ptr %a monotonic, align 8
  ret i64 %1
}

define i64 @atomic_load_i64_acquire(ptr %a) nounwind {
;
;
;
; RV64I-LABEL: atomic_load_i64_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ld a0, 0(a0)
; RV64I-NEXT:    fence r, rw
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_load_i64_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    ld a0, 0(a0)
; RV64I-ZALRSC-NEXT:    fence r, rw
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i64_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    ld a0, 0(a0)
; RV64IA-NEXT:    fence r, rw
; RV64IA-NEXT:    ret
  %1 = load atomic i64, ptr %a acquire, align 8
  ret i64 %1
}

define i64 @atomic_load_i64_seq_cst(ptr %a) nounwind {
;
;
;
; RV64I-LABEL: atomic_load_i64_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    fence rw, rw
; RV64I-NEXT:    ld a0, 0(a0)
; RV64I-NEXT:    fence r, rw
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_load_i64_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    fence rw, rw
; RV64I-ZALRSC-NEXT:    ld a0, 0(a0)
; RV64I-ZALRSC-NEXT:    fence r, rw
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i64_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    fence rw, rw
; RV64IA-NEXT:    ld a0, 0(a0)
; RV64IA-NEXT:    fence r, rw
; RV64IA-NEXT:    ret
  %1 = load atomic i64, ptr %a seq_cst, align 8
  ret i64 %1
}

define void @atomic_store_i8_unordered(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomic_store_i8_unordered:
; RV64I:       # %bb.0:
; RV64I-NEXT:    sb a1, 0(a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_store_i8_unordered:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    sb a1, 0(a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_store_i8_unordered:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    sb a1, 0(a0)
; RV64IA-NEXT:    ret
  store atomic i8 %b, ptr %a unordered, align 1
  ret void
}

define void @atomic_store_i8_monotonic(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomic_store_i8_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    sb a1, 0(a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_store_i8_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    sb a1, 0(a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_store_i8_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    sb a1, 0(a0)
; RV64IA-NEXT:    ret
  store atomic i8 %b, ptr %a monotonic, align 1
  ret void
}

define void @atomic_store_i8_release(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomic_store_i8_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    fence rw, w
; RV64I-NEXT:    sb a1, 0(a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_store_i8_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    fence rw, w
; RV64I-ZALRSC-NEXT:    sb a1, 0(a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_store_i8_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    fence rw, w
; RV64IA-NEXT:    sb a1, 0(a0)
; RV64IA-NEXT:    ret
  store atomic i8 %b, ptr %a release, align 1
  ret void
}

define void @atomic_store_i8_seq_cst(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomic_store_i8_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    fence rw, w
; RV64I-NEXT:    sb a1, 0(a0)
; RV64I-NEXT:    fence rw, rw
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_store_i8_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    fence rw, w
; RV64I-ZALRSC-NEXT:    sb a1, 0(a0)
; RV64I-ZALRSC-NEXT:    fence rw, rw
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_store_i8_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    fence rw, w
; RV64IA-NEXT:    sb a1, 0(a0)
; RV64IA-NEXT:    fence rw, rw
; RV64IA-NEXT:    ret
  store atomic i8 %b, ptr %a seq_cst, align 1
  ret void
}

define void @atomic_store_i16_unordered(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomic_store_i16_unordered:
; RV64I:       # %bb.0:
; RV64I-NEXT:    sh a1, 0(a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_store_i16_unordered:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    sh a1, 0(a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_store_i16_unordered:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    sh a1, 0(a0)
; RV64IA-NEXT:    ret
  store atomic i16 %b, ptr %a unordered, align 2
  ret void
}

define void @atomic_store_i16_monotonic(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomic_store_i16_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    sh a1, 0(a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_store_i16_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    sh a1, 0(a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_store_i16_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    sh a1, 0(a0)
; RV64IA-NEXT:    ret
  store atomic i16 %b, ptr %a monotonic, align 2
  ret void
}

define void @atomic_store_i16_release(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomic_store_i16_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    fence rw, w
; RV64I-NEXT:    sh a1, 0(a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_store_i16_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    fence rw, w
; RV64I-ZALRSC-NEXT:    sh a1, 0(a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_store_i16_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    fence rw, w
; RV64IA-NEXT:    sh a1, 0(a0)
; RV64IA-NEXT:    ret
  store atomic i16 %b, ptr %a release, align 2
  ret void
}

define void @atomic_store_i16_seq_cst(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomic_store_i16_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    fence rw, w
; RV64I-NEXT:    sh a1, 0(a0)
; RV64I-NEXT:    fence rw, rw
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_store_i16_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    fence rw, w
; RV64I-ZALRSC-NEXT:    sh a1, 0(a0)
; RV64I-ZALRSC-NEXT:    fence rw, rw
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_store_i16_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    fence rw, w
; RV64IA-NEXT:    sh a1, 0(a0)
; RV64IA-NEXT:    fence rw, rw
; RV64IA-NEXT:    ret
  store atomic i16 %b, ptr %a seq_cst, align 2
  ret void
}

define void @atomic_store_i32_unordered(ptr %a, i32 %b) nounwind {
;
;
;
; RV64I-LABEL: atomic_store_i32_unordered:
; RV64I:       # %bb.0:
; RV64I-NEXT:    sw a1, 0(a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_store_i32_unordered:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    sw a1, 0(a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_store_i32_unordered:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    sw a1, 0(a0)
; RV64IA-NEXT:    ret
  store atomic i32 %b, ptr %a unordered, align 4
  ret void
}

define void @atomic_store_i32_monotonic(ptr %a, i32 %b) nounwind {
;
;
;
; RV64I-LABEL: atomic_store_i32_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    sw a1, 0(a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_store_i32_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    sw a1, 0(a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_store_i32_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    sw a1, 0(a0)
; RV64IA-NEXT:    ret
  store atomic i32 %b, ptr %a monotonic, align 4
  ret void
}

define void @atomic_store_i32_release(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomic_store_i32_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    fence rw, w
; RV64I-NEXT:    sw a1, 0(a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_store_i32_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    fence rw, w
; RV64I-ZALRSC-NEXT:    sw a1, 0(a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_store_i32_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    fence rw, w
; RV64IA-NEXT:    sw a1, 0(a0)
; RV64IA-NEXT:    ret
  store atomic i32 %b, ptr %a release, align 4
  ret void
}

define void @atomic_store_i32_seq_cst(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomic_store_i32_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    fence rw, w
; RV64I-NEXT:    sw a1, 0(a0)
; RV64I-NEXT:    fence rw, rw
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_store_i32_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    fence rw, w
; RV64I-ZALRSC-NEXT:    sw a1, 0(a0)
; RV64I-ZALRSC-NEXT:    fence rw, rw
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_store_i32_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    fence rw, w
; RV64IA-NEXT:    sw a1, 0(a0)
; RV64IA-NEXT:    fence rw, rw
; RV64IA-NEXT:    ret
  store atomic i32 %b, ptr %a seq_cst, align 4
  ret void
}

define void @atomic_store_i64_unordered(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomic_store_i64_unordered:
; RV64I:       # %bb.0:
; RV64I-NEXT:    sd a1, 0(a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_store_i64_unordered:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    sd a1, 0(a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_store_i64_unordered:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    sd a1, 0(a0)
; RV64IA-NEXT:    ret
  store atomic i64 %b, ptr %a unordered, align 8
  ret void
}

define void @atomic_store_i64_monotonic(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomic_store_i64_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    sd a1, 0(a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_store_i64_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    sd a1, 0(a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_store_i64_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    sd a1, 0(a0)
; RV64IA-NEXT:    ret
  store atomic i64 %b, ptr %a monotonic, align 8
  ret void
}

define void @atomic_store_i64_release(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomic_store_i64_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    fence rw, w
; RV64I-NEXT:    sd a1, 0(a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_store_i64_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    fence rw, w
; RV64I-ZALRSC-NEXT:    sd a1, 0(a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_store_i64_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    fence rw, w
; RV64IA-NEXT:    sd a1, 0(a0)
; RV64IA-NEXT:    ret
  store atomic i64 %b, ptr %a release, align 8
  ret void
}

define void @atomic_store_i64_seq_cst(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomic_store_i64_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    fence rw, w
; RV64I-NEXT:    sd a1, 0(a0)
; RV64I-NEXT:    fence rw, rw
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_store_i64_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    fence rw, w
; RV64I-ZALRSC-NEXT:    sd a1, 0(a0)
; RV64I-ZALRSC-NEXT:    fence rw, rw
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomic_store_i64_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    fence rw, w
; RV64IA-NEXT:    sd a1, 0(a0)
; RV64IA-NEXT:    fence rw, rw
; RV64IA-NEXT:    ret
  store atomic i64 %b, ptr %a seq_cst, align 8
  ret void
}
