; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O3 -mtriple=ysx64 -mattr=+a -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefixes=RV64 %s

define void @amoswap_w_discard(ptr %a, i32 %b) nounwind {
;
; RV64-LABEL: amoswap_w_discard:
; RV64:       # %bb.0:
; RV64-NEXT:    amoswap.w.aqrl a0, a1, (a0)
; RV64-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i32 %b seq_cst
  ret void
}

define void @amoswap_d_discard(ptr %a, i64 %b) nounwind {
;
; RV64-LABEL: amoswap_d_discard:
; RV64:       # %bb.0:
; RV64-NEXT:    amoswap.d.aqrl a0, a1, (a0)
; RV64-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i64 %b seq_cst
  ret void
}

define void @amoadd_w_discard(ptr %a, i32 %b) nounwind {
;
; RV64-LABEL: amoadd_w_discard:
; RV64:       # %bb.0:
; RV64-NEXT:    amoadd.w.aqrl a0, a1, (a0)
; RV64-NEXT:    ret
  %1 = atomicrmw add ptr %a, i32 %b seq_cst
  ret void
}

define void @amoadd_d_discard(ptr %a, i64 %b) nounwind {
;
; RV64-LABEL: amoadd_d_discard:
; RV64:       # %bb.0:
; RV64-NEXT:    amoadd.d.aqrl a0, a1, (a0)
; RV64-NEXT:    ret
  %1 = atomicrmw add ptr %a, i64 %b seq_cst
  ret void
}

define void @amoand_w_discard(ptr %a, i32 %b) nounwind {
;
; RV64-LABEL: amoand_w_discard:
; RV64:       # %bb.0:
; RV64-NEXT:    amoand.w.aqrl a0, a1, (a0)
; RV64-NEXT:    ret
  %1 = atomicrmw and ptr %a, i32 %b seq_cst
  ret void
}

define void @amoand_d_discard(ptr %a, i64 %b) nounwind {
;
; RV64-LABEL: amoand_d_discard:
; RV64:       # %bb.0:
; RV64-NEXT:    amoand.d.aqrl a0, a1, (a0)
; RV64-NEXT:    ret
  %1 = atomicrmw and ptr %a, i64 %b seq_cst
  ret void
}

define void @amoor_w_discard(ptr %a, i32 %b) nounwind {
;
; RV64-LABEL: amoor_w_discard:
; RV64:       # %bb.0:
; RV64-NEXT:    amoor.w.aqrl a0, a1, (a0)
; RV64-NEXT:    ret
  %1 = atomicrmw or ptr %a, i32 %b seq_cst
  ret void
}

define void @amoor_d_discard(ptr %a, i64 %b) nounwind {
;
; RV64-LABEL: amoor_d_discard:
; RV64:       # %bb.0:
; RV64-NEXT:    amoor.d.aqrl a0, a1, (a0)
; RV64-NEXT:    ret
  %1 = atomicrmw or ptr %a, i64 %b seq_cst
  ret void
}

define void @amoxor_w_discard(ptr %a, i32 %b) nounwind {
;
; RV64-LABEL: amoxor_w_discard:
; RV64:       # %bb.0:
; RV64-NEXT:    amoor.w.aqrl a0, a1, (a0)
; RV64-NEXT:    ret
  %1 = atomicrmw or ptr %a, i32 %b seq_cst
  ret void
}

define void @amoxor_d_discard(ptr %a, i64 %b) nounwind {
;
; RV64-LABEL: amoxor_d_discard:
; RV64:       # %bb.0:
; RV64-NEXT:    amoor.d.aqrl a0, a1, (a0)
; RV64-NEXT:    ret
  %1 = atomicrmw or ptr %a, i64 %b seq_cst
  ret void
}

define void @amomax_w_discard(ptr %a, i32 %b) nounwind {
;
; RV64-LABEL: amomax_w_discard:
; RV64:       # %bb.0:
; RV64-NEXT:    amomax.w.aqrl a0, a1, (a0)
; RV64-NEXT:    ret
  %1 = atomicrmw max ptr %a, i32 %b seq_cst
  ret void
}

define void @amomax_d_discard(ptr %a, i64 %b) nounwind {
;
; RV64-LABEL: amomax_d_discard:
; RV64:       # %bb.0:
; RV64-NEXT:    amomax.d.aqrl a0, a1, (a0)
; RV64-NEXT:    ret
  %1 = atomicrmw max ptr %a, i64 %b seq_cst
  ret void
}

define void @amomaxu_w_discard(ptr %a, i32 %b) nounwind {
;
; RV64-LABEL: amomaxu_w_discard:
; RV64:       # %bb.0:
; RV64-NEXT:    amomaxu.w.aqrl a0, a1, (a0)
; RV64-NEXT:    ret
  %1 = atomicrmw umax ptr %a, i32 %b seq_cst
  ret void
}

define void @amomaxu_d_discard(ptr %a, i64 %b) nounwind {
;
; RV64-LABEL: amomaxu_d_discard:
; RV64:       # %bb.0:
; RV64-NEXT:    amomaxu.d.aqrl a0, a1, (a0)
; RV64-NEXT:    ret
  %1 = atomicrmw umax ptr %a, i64 %b seq_cst
  ret void
}

define void @amomin_w_discard(ptr %a, i32 %b) nounwind {
;
; RV64-LABEL: amomin_w_discard:
; RV64:       # %bb.0:
; RV64-NEXT:    amomin.w.aqrl a0, a1, (a0)
; RV64-NEXT:    ret
  %1 = atomicrmw min ptr %a, i32 %b seq_cst
  ret void
}

define void @amomin_d_discard(ptr %a, i64 %b) nounwind {
;
; RV64-LABEL: amomin_d_discard:
; RV64:       # %bb.0:
; RV64-NEXT:    amomin.d.aqrl a0, a1, (a0)
; RV64-NEXT:    ret
  %1 = atomicrmw min ptr %a, i64 %b seq_cst
  ret void
}

define void @amominu_w_discard(ptr %a, i32 %b) nounwind {
;
; RV64-LABEL: amominu_w_discard:
; RV64:       # %bb.0:
; RV64-NEXT:    amominu.w.aqrl a0, a1, (a0)
; RV64-NEXT:    ret
  %1 = atomicrmw umin ptr %a, i32 %b seq_cst
  ret void
}

define void @amominu_d_discard(ptr %a, i64 %b) nounwind {
;
; RV64-LABEL: amominu_d_discard:
; RV64:       # %bb.0:
; RV64-NEXT:    amominu.d.aqrl a0, a1, (a0)
; RV64-NEXT:    ret
  %1 = atomicrmw umin ptr %a, i64 %b seq_cst
  ret void
}
