; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ysx64 -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV64I %s
; RUN: llc -mtriple=ysx64 -mattr=+zalrsc -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefixes=RV64I-ZALRSC %s
; RUN: llc -mtriple=ysx64 -mattr=+a -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefixes=RV64IA %s




define i8 @atomicrmw_xchg_i8_monotonic(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xchg_i8_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB0_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a4, (a2)
; RV64I-NEXT:    mv a5, a1
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB0_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_i8_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB0_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a4, (a2)
; RV64I-ZALRSC-NEXT:    mv a5, a1
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB0_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_i8_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB0_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a4, (a2)
; RV64IA-NEXT:    mv a5, a1
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB0_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i8 %b monotonic
  ret i8 %1
}

define i8 @atomicrmw_xchg_i8_acquire(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xchg_i8_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB1_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a4, (a2)
; RV64I-NEXT:    mv a5, a1
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB1_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_i8_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB1_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a4, (a2)
; RV64I-ZALRSC-NEXT:    mv a5, a1
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB1_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_i8_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB1_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a4, (a2)
; RV64IA-NEXT:    mv a5, a1
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB1_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i8 %b acquire
  ret i8 %1
}

define i8 @atomicrmw_xchg_i8_release(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xchg_i8_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB2_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a4, (a2)
; RV64I-NEXT:    mv a5, a1
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB2_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_i8_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB2_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a4, (a2)
; RV64I-ZALRSC-NEXT:    mv a5, a1
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB2_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_i8_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB2_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a4, (a2)
; RV64IA-NEXT:    mv a5, a1
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB2_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i8 %b release
  ret i8 %1
}

define i8 @atomicrmw_xchg_i8_acq_rel(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xchg_i8_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB3_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a4, (a2)
; RV64I-NEXT:    mv a5, a1
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB3_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_i8_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB3_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a4, (a2)
; RV64I-ZALRSC-NEXT:    mv a5, a1
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB3_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_i8_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB3_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a4, (a2)
; RV64IA-NEXT:    mv a5, a1
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB3_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i8 %b acq_rel
  ret i8 %1
}

define i8 @atomicrmw_xchg_i8_seq_cst(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xchg_i8_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB4_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aqrl a4, (a2)
; RV64I-NEXT:    mv a5, a1
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB4_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_i8_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB4_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aqrl a4, (a2)
; RV64I-ZALRSC-NEXT:    mv a5, a1
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB4_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_i8_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB4_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aqrl a4, (a2)
; RV64IA-NEXT:    mv a5, a1
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB4_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i8 %b seq_cst
  ret i8 %1
}

; Ensure the following 'atomicrmw xchg a, {0,-1}` cases are lowered to an
; amoand or amoor with appropriate mask.

define i8 @atomicrmw_xchg_0_i8_monotonic(ptr %a) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xchg_0_i8_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a1, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a2, 255
; RV64I-NEXT:    sllw a2, a2, a0
; RV64I-NEXT:    not a2, a2
; RV64I-NEXT:    amoand.w a1, a2, (a1)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_0_i8_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a1, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a2, 255
; RV64I-ZALRSC-NEXT:    sllw a2, a2, a0
; RV64I-ZALRSC-NEXT:    not a2, a2
; RV64I-ZALRSC-NEXT:    amoand.w a1, a2, (a1)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_0_i8_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a1, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a2, 255
; RV64IA-NEXT:    sllw a2, a2, a0
; RV64IA-NEXT:    not a2, a2
; RV64IA-NEXT:    amoand.w a1, a2, (a1)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i8 0 monotonic
  ret i8 %1
}

define i8 @atomicrmw_xchg_0_i8_acquire(ptr %a) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xchg_0_i8_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a1, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a2, 255
; RV64I-NEXT:    sllw a2, a2, a0
; RV64I-NEXT:    not a2, a2
; RV64I-NEXT:    amoand.w.aq a1, a2, (a1)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_0_i8_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a1, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a2, 255
; RV64I-ZALRSC-NEXT:    sllw a2, a2, a0
; RV64I-ZALRSC-NEXT:    not a2, a2
; RV64I-ZALRSC-NEXT:    amoand.w.aq a1, a2, (a1)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_0_i8_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a1, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a2, 255
; RV64IA-NEXT:    sllw a2, a2, a0
; RV64IA-NEXT:    not a2, a2
; RV64IA-NEXT:    amoand.w.aq a1, a2, (a1)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i8 0 acquire
  ret i8 %1
}

define i8 @atomicrmw_xchg_0_i8_release(ptr %a) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xchg_0_i8_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a1, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a2, 255
; RV64I-NEXT:    sllw a2, a2, a0
; RV64I-NEXT:    not a2, a2
; RV64I-NEXT:    amoand.w.rl a1, a2, (a1)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_0_i8_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a1, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a2, 255
; RV64I-ZALRSC-NEXT:    sllw a2, a2, a0
; RV64I-ZALRSC-NEXT:    not a2, a2
; RV64I-ZALRSC-NEXT:    amoand.w.rl a1, a2, (a1)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_0_i8_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a1, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a2, 255
; RV64IA-NEXT:    sllw a2, a2, a0
; RV64IA-NEXT:    not a2, a2
; RV64IA-NEXT:    amoand.w.rl a1, a2, (a1)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i8 0 release
  ret i8 %1
}

define i8 @atomicrmw_xchg_0_i8_acq_rel(ptr %a) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xchg_0_i8_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a1, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a2, 255
; RV64I-NEXT:    sllw a2, a2, a0
; RV64I-NEXT:    not a2, a2
; RV64I-NEXT:    amoand.w.aqrl a1, a2, (a1)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_0_i8_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a1, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a2, 255
; RV64I-ZALRSC-NEXT:    sllw a2, a2, a0
; RV64I-ZALRSC-NEXT:    not a2, a2
; RV64I-ZALRSC-NEXT:    amoand.w.aqrl a1, a2, (a1)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_0_i8_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a1, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a2, 255
; RV64IA-NEXT:    sllw a2, a2, a0
; RV64IA-NEXT:    not a2, a2
; RV64IA-NEXT:    amoand.w.aqrl a1, a2, (a1)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i8 0 acq_rel
  ret i8 %1
}

define i8 @atomicrmw_xchg_0_i8_seq_cst(ptr %a) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xchg_0_i8_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a1, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a2, 255
; RV64I-NEXT:    sllw a2, a2, a0
; RV64I-NEXT:    not a2, a2
; RV64I-NEXT:    amoand.w.aqrl a1, a2, (a1)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_0_i8_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a1, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a2, 255
; RV64I-ZALRSC-NEXT:    sllw a2, a2, a0
; RV64I-ZALRSC-NEXT:    not a2, a2
; RV64I-ZALRSC-NEXT:    amoand.w.aqrl a1, a2, (a1)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_0_i8_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a1, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a2, 255
; RV64IA-NEXT:    sllw a2, a2, a0
; RV64IA-NEXT:    not a2, a2
; RV64IA-NEXT:    amoand.w.aqrl a1, a2, (a1)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i8 0 seq_cst
  ret i8 %1
}

define i8 @atomicrmw_xchg_minus_1_i8_monotonic(ptr %a) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xchg_minus_1_i8_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a1, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a2, 255
; RV64I-NEXT:    sllw a2, a2, a0
; RV64I-NEXT:    amoor.w a1, a2, (a1)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_minus_1_i8_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a1, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a2, 255
; RV64I-ZALRSC-NEXT:    sllw a2, a2, a0
; RV64I-ZALRSC-NEXT:    amoor.w a1, a2, (a1)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_minus_1_i8_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a1, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a2, 255
; RV64IA-NEXT:    sllw a2, a2, a0
; RV64IA-NEXT:    amoor.w a1, a2, (a1)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i8 -1 monotonic
  ret i8 %1
}

define i8 @atomicrmw_xchg_minus_1_i8_acquire(ptr %a) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xchg_minus_1_i8_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a1, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a2, 255
; RV64I-NEXT:    sllw a2, a2, a0
; RV64I-NEXT:    amoor.w.aq a1, a2, (a1)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_minus_1_i8_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a1, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a2, 255
; RV64I-ZALRSC-NEXT:    sllw a2, a2, a0
; RV64I-ZALRSC-NEXT:    amoor.w.aq a1, a2, (a1)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_minus_1_i8_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a1, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a2, 255
; RV64IA-NEXT:    sllw a2, a2, a0
; RV64IA-NEXT:    amoor.w.aq a1, a2, (a1)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i8 -1 acquire
  ret i8 %1
}

define i8 @atomicrmw_xchg_minus_1_i8_release(ptr %a) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xchg_minus_1_i8_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a1, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a2, 255
; RV64I-NEXT:    sllw a2, a2, a0
; RV64I-NEXT:    amoor.w.rl a1, a2, (a1)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_minus_1_i8_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a1, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a2, 255
; RV64I-ZALRSC-NEXT:    sllw a2, a2, a0
; RV64I-ZALRSC-NEXT:    amoor.w.rl a1, a2, (a1)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_minus_1_i8_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a1, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a2, 255
; RV64IA-NEXT:    sllw a2, a2, a0
; RV64IA-NEXT:    amoor.w.rl a1, a2, (a1)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i8 -1 release
  ret i8 %1
}

define i8 @atomicrmw_xchg_minus_1_i8_acq_rel(ptr %a) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xchg_minus_1_i8_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a1, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a2, 255
; RV64I-NEXT:    sllw a2, a2, a0
; RV64I-NEXT:    amoor.w.aqrl a1, a2, (a1)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_minus_1_i8_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a1, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a2, 255
; RV64I-ZALRSC-NEXT:    sllw a2, a2, a0
; RV64I-ZALRSC-NEXT:    amoor.w.aqrl a1, a2, (a1)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_minus_1_i8_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a1, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a2, 255
; RV64IA-NEXT:    sllw a2, a2, a0
; RV64IA-NEXT:    amoor.w.aqrl a1, a2, (a1)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i8 -1 acq_rel
  ret i8 %1
}

define i8 @atomicrmw_xchg_minus_1_i8_seq_cst(ptr %a) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xchg_minus_1_i8_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a1, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a2, 255
; RV64I-NEXT:    sllw a2, a2, a0
; RV64I-NEXT:    amoor.w.aqrl a1, a2, (a1)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_minus_1_i8_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a1, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a2, 255
; RV64I-ZALRSC-NEXT:    sllw a2, a2, a0
; RV64I-ZALRSC-NEXT:    amoor.w.aqrl a1, a2, (a1)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_minus_1_i8_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a1, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a2, 255
; RV64IA-NEXT:    sllw a2, a2, a0
; RV64IA-NEXT:    amoor.w.aqrl a1, a2, (a1)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i8 -1 seq_cst
  ret i8 %1
}

define i8 @atomicrmw_add_i8_monotonic(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_add_i8_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB15_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a4, (a2)
; RV64I-NEXT:    add a5, a4, a1
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB15_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_add_i8_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB15_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a4, (a2)
; RV64I-ZALRSC-NEXT:    add a5, a4, a1
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB15_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_add_i8_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB15_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a4, (a2)
; RV64IA-NEXT:    add a5, a4, a1
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB15_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw add ptr %a, i8 %b monotonic
  ret i8 %1
}

define i8 @atomicrmw_add_i8_acquire(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_add_i8_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB16_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a4, (a2)
; RV64I-NEXT:    add a5, a4, a1
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB16_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_add_i8_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB16_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a4, (a2)
; RV64I-ZALRSC-NEXT:    add a5, a4, a1
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB16_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_add_i8_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB16_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a4, (a2)
; RV64IA-NEXT:    add a5, a4, a1
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB16_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw add ptr %a, i8 %b acquire
  ret i8 %1
}

define i8 @atomicrmw_add_i8_release(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_add_i8_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB17_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a4, (a2)
; RV64I-NEXT:    add a5, a4, a1
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB17_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_add_i8_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB17_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a4, (a2)
; RV64I-ZALRSC-NEXT:    add a5, a4, a1
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB17_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_add_i8_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB17_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a4, (a2)
; RV64IA-NEXT:    add a5, a4, a1
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB17_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw add ptr %a, i8 %b release
  ret i8 %1
}

define i8 @atomicrmw_add_i8_acq_rel(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_add_i8_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB18_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a4, (a2)
; RV64I-NEXT:    add a5, a4, a1
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB18_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_add_i8_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB18_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a4, (a2)
; RV64I-ZALRSC-NEXT:    add a5, a4, a1
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB18_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_add_i8_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB18_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a4, (a2)
; RV64IA-NEXT:    add a5, a4, a1
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB18_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw add ptr %a, i8 %b acq_rel
  ret i8 %1
}

define i8 @atomicrmw_add_i8_seq_cst(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_add_i8_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB19_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aqrl a4, (a2)
; RV64I-NEXT:    add a5, a4, a1
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB19_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_add_i8_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB19_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aqrl a4, (a2)
; RV64I-ZALRSC-NEXT:    add a5, a4, a1
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB19_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_add_i8_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB19_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aqrl a4, (a2)
; RV64IA-NEXT:    add a5, a4, a1
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB19_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw add ptr %a, i8 %b seq_cst
  ret i8 %1
}

define i8 @atomicrmw_sub_i8_monotonic(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_sub_i8_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB20_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a4, (a2)
; RV64I-NEXT:    sub a5, a4, a1
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB20_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_sub_i8_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB20_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a4, (a2)
; RV64I-ZALRSC-NEXT:    sub a5, a4, a1
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB20_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_sub_i8_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB20_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a4, (a2)
; RV64IA-NEXT:    sub a5, a4, a1
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB20_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw sub ptr %a, i8 %b monotonic
  ret i8 %1
}

define i8 @atomicrmw_sub_i8_acquire(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_sub_i8_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB21_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a4, (a2)
; RV64I-NEXT:    sub a5, a4, a1
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB21_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_sub_i8_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB21_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a4, (a2)
; RV64I-ZALRSC-NEXT:    sub a5, a4, a1
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB21_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_sub_i8_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB21_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a4, (a2)
; RV64IA-NEXT:    sub a5, a4, a1
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB21_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw sub ptr %a, i8 %b acquire
  ret i8 %1
}

define i8 @atomicrmw_sub_i8_release(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_sub_i8_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB22_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a4, (a2)
; RV64I-NEXT:    sub a5, a4, a1
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB22_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_sub_i8_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB22_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a4, (a2)
; RV64I-ZALRSC-NEXT:    sub a5, a4, a1
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB22_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_sub_i8_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB22_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a4, (a2)
; RV64IA-NEXT:    sub a5, a4, a1
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB22_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw sub ptr %a, i8 %b release
  ret i8 %1
}

define i8 @atomicrmw_sub_i8_acq_rel(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_sub_i8_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB23_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a4, (a2)
; RV64I-NEXT:    sub a5, a4, a1
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB23_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_sub_i8_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB23_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a4, (a2)
; RV64I-ZALRSC-NEXT:    sub a5, a4, a1
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB23_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_sub_i8_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB23_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a4, (a2)
; RV64IA-NEXT:    sub a5, a4, a1
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB23_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw sub ptr %a, i8 %b acq_rel
  ret i8 %1
}

define i8 @atomicrmw_sub_i8_seq_cst(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_sub_i8_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB24_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aqrl a4, (a2)
; RV64I-NEXT:    sub a5, a4, a1
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB24_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_sub_i8_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB24_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aqrl a4, (a2)
; RV64I-ZALRSC-NEXT:    sub a5, a4, a1
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB24_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_sub_i8_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB24_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aqrl a4, (a2)
; RV64IA-NEXT:    sub a5, a4, a1
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB24_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw sub ptr %a, i8 %b seq_cst
  ret i8 %1
}

define i8 @atomicrmw_and_i8_monotonic(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_and_i8_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    not a3, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    or a1, a1, a3
; RV64I-NEXT:    amoand.w a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_and_i8_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    not a3, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    or a1, a1, a3
; RV64I-ZALRSC-NEXT:    amoand.w a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_and_i8_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    not a3, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    or a1, a1, a3
; RV64IA-NEXT:    amoand.w a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw and ptr %a, i8 %b monotonic
  ret i8 %1
}

define i8 @atomicrmw_and_i8_acquire(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_and_i8_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    not a3, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    or a1, a1, a3
; RV64I-NEXT:    amoand.w.aq a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_and_i8_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    not a3, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    or a1, a1, a3
; RV64I-ZALRSC-NEXT:    amoand.w.aq a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_and_i8_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    not a3, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    or a1, a1, a3
; RV64IA-NEXT:    amoand.w.aq a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw and ptr %a, i8 %b acquire
  ret i8 %1
}

define i8 @atomicrmw_and_i8_release(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_and_i8_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    not a3, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    or a1, a1, a3
; RV64I-NEXT:    amoand.w.rl a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_and_i8_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    not a3, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    or a1, a1, a3
; RV64I-ZALRSC-NEXT:    amoand.w.rl a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_and_i8_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    not a3, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    or a1, a1, a3
; RV64IA-NEXT:    amoand.w.rl a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw and ptr %a, i8 %b release
  ret i8 %1
}

define i8 @atomicrmw_and_i8_acq_rel(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_and_i8_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    not a3, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    or a1, a1, a3
; RV64I-NEXT:    amoand.w.aqrl a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_and_i8_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    not a3, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    or a1, a1, a3
; RV64I-ZALRSC-NEXT:    amoand.w.aqrl a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_and_i8_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    not a3, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    or a1, a1, a3
; RV64IA-NEXT:    amoand.w.aqrl a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw and ptr %a, i8 %b acq_rel
  ret i8 %1
}

define i8 @atomicrmw_and_i8_seq_cst(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_and_i8_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    not a3, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    or a1, a1, a3
; RV64I-NEXT:    amoand.w.aqrl a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_and_i8_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    not a3, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    or a1, a1, a3
; RV64I-ZALRSC-NEXT:    amoand.w.aqrl a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_and_i8_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    not a3, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    or a1, a1, a3
; RV64IA-NEXT:    amoand.w.aqrl a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw and ptr %a, i8 %b seq_cst
  ret i8 %1
}

define i8 @atomicrmw_nand_i8_monotonic(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_nand_i8_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB30_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a4, (a2)
; RV64I-NEXT:    and a5, a4, a1
; RV64I-NEXT:    not a5, a5
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB30_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_nand_i8_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB30_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a4, (a2)
; RV64I-ZALRSC-NEXT:    and a5, a4, a1
; RV64I-ZALRSC-NEXT:    not a5, a5
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB30_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_nand_i8_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB30_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a4, (a2)
; RV64IA-NEXT:    and a5, a4, a1
; RV64IA-NEXT:    not a5, a5
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB30_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw nand ptr %a, i8 %b monotonic
  ret i8 %1
}

define i8 @atomicrmw_nand_i8_acquire(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_nand_i8_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB31_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a4, (a2)
; RV64I-NEXT:    and a5, a4, a1
; RV64I-NEXT:    not a5, a5
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB31_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_nand_i8_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB31_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a4, (a2)
; RV64I-ZALRSC-NEXT:    and a5, a4, a1
; RV64I-ZALRSC-NEXT:    not a5, a5
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB31_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_nand_i8_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB31_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a4, (a2)
; RV64IA-NEXT:    and a5, a4, a1
; RV64IA-NEXT:    not a5, a5
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB31_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw nand ptr %a, i8 %b acquire
  ret i8 %1
}

define i8 @atomicrmw_nand_i8_release(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_nand_i8_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB32_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a4, (a2)
; RV64I-NEXT:    and a5, a4, a1
; RV64I-NEXT:    not a5, a5
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB32_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_nand_i8_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB32_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a4, (a2)
; RV64I-ZALRSC-NEXT:    and a5, a4, a1
; RV64I-ZALRSC-NEXT:    not a5, a5
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB32_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_nand_i8_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB32_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a4, (a2)
; RV64IA-NEXT:    and a5, a4, a1
; RV64IA-NEXT:    not a5, a5
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB32_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw nand ptr %a, i8 %b release
  ret i8 %1
}

define i8 @atomicrmw_nand_i8_acq_rel(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_nand_i8_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB33_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a4, (a2)
; RV64I-NEXT:    and a5, a4, a1
; RV64I-NEXT:    not a5, a5
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB33_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_nand_i8_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB33_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a4, (a2)
; RV64I-ZALRSC-NEXT:    and a5, a4, a1
; RV64I-ZALRSC-NEXT:    not a5, a5
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB33_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_nand_i8_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB33_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a4, (a2)
; RV64IA-NEXT:    and a5, a4, a1
; RV64IA-NEXT:    not a5, a5
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB33_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw nand ptr %a, i8 %b acq_rel
  ret i8 %1
}

define i8 @atomicrmw_nand_i8_seq_cst(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_nand_i8_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB34_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aqrl a4, (a2)
; RV64I-NEXT:    and a5, a4, a1
; RV64I-NEXT:    not a5, a5
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB34_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_nand_i8_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB34_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aqrl a4, (a2)
; RV64I-ZALRSC-NEXT:    and a5, a4, a1
; RV64I-ZALRSC-NEXT:    not a5, a5
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB34_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_nand_i8_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB34_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aqrl a4, (a2)
; RV64IA-NEXT:    and a5, a4, a1
; RV64IA-NEXT:    not a5, a5
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB34_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw nand ptr %a, i8 %b seq_cst
  ret i8 %1
}

define i8 @atomicrmw_or_i8_monotonic(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_or_i8_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    amoor.w a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_or_i8_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    amoor.w a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_or_i8_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    amoor.w a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw or ptr %a, i8 %b monotonic
  ret i8 %1
}

define i8 @atomicrmw_or_i8_acquire(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_or_i8_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    amoor.w.aq a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_or_i8_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    amoor.w.aq a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_or_i8_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    amoor.w.aq a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw or ptr %a, i8 %b acquire
  ret i8 %1
}

define i8 @atomicrmw_or_i8_release(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_or_i8_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    amoor.w.rl a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_or_i8_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    amoor.w.rl a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_or_i8_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    amoor.w.rl a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw or ptr %a, i8 %b release
  ret i8 %1
}

define i8 @atomicrmw_or_i8_acq_rel(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_or_i8_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    amoor.w.aqrl a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_or_i8_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    amoor.w.aqrl a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_or_i8_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    amoor.w.aqrl a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw or ptr %a, i8 %b acq_rel
  ret i8 %1
}

define i8 @atomicrmw_or_i8_seq_cst(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_or_i8_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    amoor.w.aqrl a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_or_i8_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    amoor.w.aqrl a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_or_i8_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    amoor.w.aqrl a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw or ptr %a, i8 %b seq_cst
  ret i8 %1
}

define i8 @atomicrmw_xor_i8_monotonic(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xor_i8_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    amoxor.w a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xor_i8_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    amoxor.w a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xor_i8_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    amoxor.w a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xor ptr %a, i8 %b monotonic
  ret i8 %1
}

define i8 @atomicrmw_xor_i8_acquire(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xor_i8_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    amoxor.w.aq a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xor_i8_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    amoxor.w.aq a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xor_i8_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    amoxor.w.aq a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xor ptr %a, i8 %b acquire
  ret i8 %1
}

define i8 @atomicrmw_xor_i8_release(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xor_i8_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    amoxor.w.rl a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xor_i8_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    amoxor.w.rl a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xor_i8_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    amoxor.w.rl a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xor ptr %a, i8 %b release
  ret i8 %1
}

define i8 @atomicrmw_xor_i8_acq_rel(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xor_i8_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    amoxor.w.aqrl a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xor_i8_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    amoxor.w.aqrl a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xor_i8_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    amoxor.w.aqrl a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xor ptr %a, i8 %b acq_rel
  ret i8 %1
}

define i8 @atomicrmw_xor_i8_seq_cst(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xor_i8_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    amoxor.w.aqrl a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xor_i8_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    amoxor.w.aqrl a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xor_i8_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    amoxor.w.aqrl a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xor ptr %a, i8 %b seq_cst
  ret i8 %1
}

define i8 @atomicrmw_max_i8_monotonic(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_max_i8_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    slli a1, a1, 56
; RV64I-NEXT:    andi a4, a0, 24
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    srai a1, a1, 56
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    xori a4, a4, 56
; RV64I-NEXT:  .LBB45_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a5, (a2)
; RV64I-NEXT:    and a7, a5, a3
; RV64I-NEXT:    mv a6, a5
; RV64I-NEXT:    sll a7, a7, a4
; RV64I-NEXT:    sra a7, a7, a4
; RV64I-NEXT:    bge a7, a1, .LBB45_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB45_1 Depth=1
; RV64I-NEXT:    xor a6, a5, a1
; RV64I-NEXT:    and a6, a6, a3
; RV64I-NEXT:    xor a6, a5, a6
; RV64I-NEXT:  .LBB45_3: # in Loop: Header=BB45_1 Depth=1
; RV64I-NEXT:    sc.w a6, a6, (a2)
; RV64I-NEXT:    bnez a6, .LBB45_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a5, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_max_i8_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    slli a1, a1, 56
; RV64I-ZALRSC-NEXT:    andi a4, a0, 24
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    srai a1, a1, 56
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    xori a4, a4, 56
; RV64I-ZALRSC-NEXT:  .LBB45_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a5, (a2)
; RV64I-ZALRSC-NEXT:    and a7, a5, a3
; RV64I-ZALRSC-NEXT:    mv a6, a5
; RV64I-ZALRSC-NEXT:    sll a7, a7, a4
; RV64I-ZALRSC-NEXT:    sra a7, a7, a4
; RV64I-ZALRSC-NEXT:    bge a7, a1, .LBB45_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB45_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a6, a5, a1
; RV64I-ZALRSC-NEXT:    and a6, a6, a3
; RV64I-ZALRSC-NEXT:    xor a6, a5, a6
; RV64I-ZALRSC-NEXT:  .LBB45_3: # in Loop: Header=BB45_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w a6, a6, (a2)
; RV64I-ZALRSC-NEXT:    bnez a6, .LBB45_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a5, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_max_i8_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    slli a1, a1, 56
; RV64IA-NEXT:    andi a4, a0, 24
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    srai a1, a1, 56
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    xori a4, a4, 56
; RV64IA-NEXT:  .LBB45_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a5, (a2)
; RV64IA-NEXT:    and a7, a5, a3
; RV64IA-NEXT:    mv a6, a5
; RV64IA-NEXT:    sll a7, a7, a4
; RV64IA-NEXT:    sra a7, a7, a4
; RV64IA-NEXT:    bge a7, a1, .LBB45_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB45_1 Depth=1
; RV64IA-NEXT:    xor a6, a5, a1
; RV64IA-NEXT:    and a6, a6, a3
; RV64IA-NEXT:    xor a6, a5, a6
; RV64IA-NEXT:  .LBB45_3: # in Loop: Header=BB45_1 Depth=1
; RV64IA-NEXT:    sc.w a6, a6, (a2)
; RV64IA-NEXT:    bnez a6, .LBB45_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a5, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw max ptr %a, i8 %b monotonic
  ret i8 %1
}

define i8 @atomicrmw_max_i8_acquire(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_max_i8_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    slli a1, a1, 56
; RV64I-NEXT:    andi a4, a0, 24
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    srai a1, a1, 56
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    xori a4, a4, 56
; RV64I-NEXT:  .LBB46_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a5, (a2)
; RV64I-NEXT:    and a7, a5, a3
; RV64I-NEXT:    mv a6, a5
; RV64I-NEXT:    sll a7, a7, a4
; RV64I-NEXT:    sra a7, a7, a4
; RV64I-NEXT:    bge a7, a1, .LBB46_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB46_1 Depth=1
; RV64I-NEXT:    xor a6, a5, a1
; RV64I-NEXT:    and a6, a6, a3
; RV64I-NEXT:    xor a6, a5, a6
; RV64I-NEXT:  .LBB46_3: # in Loop: Header=BB46_1 Depth=1
; RV64I-NEXT:    sc.w a6, a6, (a2)
; RV64I-NEXT:    bnez a6, .LBB46_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a5, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_max_i8_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    slli a1, a1, 56
; RV64I-ZALRSC-NEXT:    andi a4, a0, 24
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    srai a1, a1, 56
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    xori a4, a4, 56
; RV64I-ZALRSC-NEXT:  .LBB46_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a5, (a2)
; RV64I-ZALRSC-NEXT:    and a7, a5, a3
; RV64I-ZALRSC-NEXT:    mv a6, a5
; RV64I-ZALRSC-NEXT:    sll a7, a7, a4
; RV64I-ZALRSC-NEXT:    sra a7, a7, a4
; RV64I-ZALRSC-NEXT:    bge a7, a1, .LBB46_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB46_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a6, a5, a1
; RV64I-ZALRSC-NEXT:    and a6, a6, a3
; RV64I-ZALRSC-NEXT:    xor a6, a5, a6
; RV64I-ZALRSC-NEXT:  .LBB46_3: # in Loop: Header=BB46_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w a6, a6, (a2)
; RV64I-ZALRSC-NEXT:    bnez a6, .LBB46_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a5, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_max_i8_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    slli a1, a1, 56
; RV64IA-NEXT:    andi a4, a0, 24
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    srai a1, a1, 56
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    xori a4, a4, 56
; RV64IA-NEXT:  .LBB46_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a5, (a2)
; RV64IA-NEXT:    and a7, a5, a3
; RV64IA-NEXT:    mv a6, a5
; RV64IA-NEXT:    sll a7, a7, a4
; RV64IA-NEXT:    sra a7, a7, a4
; RV64IA-NEXT:    bge a7, a1, .LBB46_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB46_1 Depth=1
; RV64IA-NEXT:    xor a6, a5, a1
; RV64IA-NEXT:    and a6, a6, a3
; RV64IA-NEXT:    xor a6, a5, a6
; RV64IA-NEXT:  .LBB46_3: # in Loop: Header=BB46_1 Depth=1
; RV64IA-NEXT:    sc.w a6, a6, (a2)
; RV64IA-NEXT:    bnez a6, .LBB46_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a5, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw max ptr %a, i8 %b acquire
  ret i8 %1
}

define i8 @atomicrmw_max_i8_release(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_max_i8_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    slli a1, a1, 56
; RV64I-NEXT:    andi a4, a0, 24
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    srai a1, a1, 56
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    xori a4, a4, 56
; RV64I-NEXT:  .LBB47_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a5, (a2)
; RV64I-NEXT:    and a7, a5, a3
; RV64I-NEXT:    mv a6, a5
; RV64I-NEXT:    sll a7, a7, a4
; RV64I-NEXT:    sra a7, a7, a4
; RV64I-NEXT:    bge a7, a1, .LBB47_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB47_1 Depth=1
; RV64I-NEXT:    xor a6, a5, a1
; RV64I-NEXT:    and a6, a6, a3
; RV64I-NEXT:    xor a6, a5, a6
; RV64I-NEXT:  .LBB47_3: # in Loop: Header=BB47_1 Depth=1
; RV64I-NEXT:    sc.w.rl a6, a6, (a2)
; RV64I-NEXT:    bnez a6, .LBB47_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a5, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_max_i8_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    slli a1, a1, 56
; RV64I-ZALRSC-NEXT:    andi a4, a0, 24
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    srai a1, a1, 56
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    xori a4, a4, 56
; RV64I-ZALRSC-NEXT:  .LBB47_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a5, (a2)
; RV64I-ZALRSC-NEXT:    and a7, a5, a3
; RV64I-ZALRSC-NEXT:    mv a6, a5
; RV64I-ZALRSC-NEXT:    sll a7, a7, a4
; RV64I-ZALRSC-NEXT:    sra a7, a7, a4
; RV64I-ZALRSC-NEXT:    bge a7, a1, .LBB47_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB47_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a6, a5, a1
; RV64I-ZALRSC-NEXT:    and a6, a6, a3
; RV64I-ZALRSC-NEXT:    xor a6, a5, a6
; RV64I-ZALRSC-NEXT:  .LBB47_3: # in Loop: Header=BB47_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w.rl a6, a6, (a2)
; RV64I-ZALRSC-NEXT:    bnez a6, .LBB47_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a5, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_max_i8_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    slli a1, a1, 56
; RV64IA-NEXT:    andi a4, a0, 24
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    srai a1, a1, 56
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    xori a4, a4, 56
; RV64IA-NEXT:  .LBB47_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a5, (a2)
; RV64IA-NEXT:    and a7, a5, a3
; RV64IA-NEXT:    mv a6, a5
; RV64IA-NEXT:    sll a7, a7, a4
; RV64IA-NEXT:    sra a7, a7, a4
; RV64IA-NEXT:    bge a7, a1, .LBB47_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB47_1 Depth=1
; RV64IA-NEXT:    xor a6, a5, a1
; RV64IA-NEXT:    and a6, a6, a3
; RV64IA-NEXT:    xor a6, a5, a6
; RV64IA-NEXT:  .LBB47_3: # in Loop: Header=BB47_1 Depth=1
; RV64IA-NEXT:    sc.w.rl a6, a6, (a2)
; RV64IA-NEXT:    bnez a6, .LBB47_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a5, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw max ptr %a, i8 %b release
  ret i8 %1
}

define i8 @atomicrmw_max_i8_acq_rel(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_max_i8_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    slli a1, a1, 56
; RV64I-NEXT:    andi a4, a0, 24
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    srai a1, a1, 56
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    xori a4, a4, 56
; RV64I-NEXT:  .LBB48_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a5, (a2)
; RV64I-NEXT:    and a7, a5, a3
; RV64I-NEXT:    mv a6, a5
; RV64I-NEXT:    sll a7, a7, a4
; RV64I-NEXT:    sra a7, a7, a4
; RV64I-NEXT:    bge a7, a1, .LBB48_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB48_1 Depth=1
; RV64I-NEXT:    xor a6, a5, a1
; RV64I-NEXT:    and a6, a6, a3
; RV64I-NEXT:    xor a6, a5, a6
; RV64I-NEXT:  .LBB48_3: # in Loop: Header=BB48_1 Depth=1
; RV64I-NEXT:    sc.w.rl a6, a6, (a2)
; RV64I-NEXT:    bnez a6, .LBB48_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a5, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_max_i8_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    slli a1, a1, 56
; RV64I-ZALRSC-NEXT:    andi a4, a0, 24
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    srai a1, a1, 56
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    xori a4, a4, 56
; RV64I-ZALRSC-NEXT:  .LBB48_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a5, (a2)
; RV64I-ZALRSC-NEXT:    and a7, a5, a3
; RV64I-ZALRSC-NEXT:    mv a6, a5
; RV64I-ZALRSC-NEXT:    sll a7, a7, a4
; RV64I-ZALRSC-NEXT:    sra a7, a7, a4
; RV64I-ZALRSC-NEXT:    bge a7, a1, .LBB48_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB48_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a6, a5, a1
; RV64I-ZALRSC-NEXT:    and a6, a6, a3
; RV64I-ZALRSC-NEXT:    xor a6, a5, a6
; RV64I-ZALRSC-NEXT:  .LBB48_3: # in Loop: Header=BB48_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w.rl a6, a6, (a2)
; RV64I-ZALRSC-NEXT:    bnez a6, .LBB48_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a5, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_max_i8_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    slli a1, a1, 56
; RV64IA-NEXT:    andi a4, a0, 24
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    srai a1, a1, 56
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    xori a4, a4, 56
; RV64IA-NEXT:  .LBB48_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a5, (a2)
; RV64IA-NEXT:    and a7, a5, a3
; RV64IA-NEXT:    mv a6, a5
; RV64IA-NEXT:    sll a7, a7, a4
; RV64IA-NEXT:    sra a7, a7, a4
; RV64IA-NEXT:    bge a7, a1, .LBB48_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB48_1 Depth=1
; RV64IA-NEXT:    xor a6, a5, a1
; RV64IA-NEXT:    and a6, a6, a3
; RV64IA-NEXT:    xor a6, a5, a6
; RV64IA-NEXT:  .LBB48_3: # in Loop: Header=BB48_1 Depth=1
; RV64IA-NEXT:    sc.w.rl a6, a6, (a2)
; RV64IA-NEXT:    bnez a6, .LBB48_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a5, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw max ptr %a, i8 %b acq_rel
  ret i8 %1
}

define i8 @atomicrmw_max_i8_seq_cst(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_max_i8_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    slli a1, a1, 56
; RV64I-NEXT:    andi a4, a0, 24
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    srai a1, a1, 56
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    xori a4, a4, 56
; RV64I-NEXT:  .LBB49_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aqrl a5, (a2)
; RV64I-NEXT:    and a7, a5, a3
; RV64I-NEXT:    mv a6, a5
; RV64I-NEXT:    sll a7, a7, a4
; RV64I-NEXT:    sra a7, a7, a4
; RV64I-NEXT:    bge a7, a1, .LBB49_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB49_1 Depth=1
; RV64I-NEXT:    xor a6, a5, a1
; RV64I-NEXT:    and a6, a6, a3
; RV64I-NEXT:    xor a6, a5, a6
; RV64I-NEXT:  .LBB49_3: # in Loop: Header=BB49_1 Depth=1
; RV64I-NEXT:    sc.w.rl a6, a6, (a2)
; RV64I-NEXT:    bnez a6, .LBB49_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a5, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_max_i8_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    slli a1, a1, 56
; RV64I-ZALRSC-NEXT:    andi a4, a0, 24
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    srai a1, a1, 56
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    xori a4, a4, 56
; RV64I-ZALRSC-NEXT:  .LBB49_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aqrl a5, (a2)
; RV64I-ZALRSC-NEXT:    and a7, a5, a3
; RV64I-ZALRSC-NEXT:    mv a6, a5
; RV64I-ZALRSC-NEXT:    sll a7, a7, a4
; RV64I-ZALRSC-NEXT:    sra a7, a7, a4
; RV64I-ZALRSC-NEXT:    bge a7, a1, .LBB49_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB49_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a6, a5, a1
; RV64I-ZALRSC-NEXT:    and a6, a6, a3
; RV64I-ZALRSC-NEXT:    xor a6, a5, a6
; RV64I-ZALRSC-NEXT:  .LBB49_3: # in Loop: Header=BB49_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w.rl a6, a6, (a2)
; RV64I-ZALRSC-NEXT:    bnez a6, .LBB49_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a5, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_max_i8_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    slli a1, a1, 56
; RV64IA-NEXT:    andi a4, a0, 24
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    srai a1, a1, 56
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    xori a4, a4, 56
; RV64IA-NEXT:  .LBB49_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aqrl a5, (a2)
; RV64IA-NEXT:    and a7, a5, a3
; RV64IA-NEXT:    mv a6, a5
; RV64IA-NEXT:    sll a7, a7, a4
; RV64IA-NEXT:    sra a7, a7, a4
; RV64IA-NEXT:    bge a7, a1, .LBB49_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB49_1 Depth=1
; RV64IA-NEXT:    xor a6, a5, a1
; RV64IA-NEXT:    and a6, a6, a3
; RV64IA-NEXT:    xor a6, a5, a6
; RV64IA-NEXT:  .LBB49_3: # in Loop: Header=BB49_1 Depth=1
; RV64IA-NEXT:    sc.w.rl a6, a6, (a2)
; RV64IA-NEXT:    bnez a6, .LBB49_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a5, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw max ptr %a, i8 %b seq_cst
  ret i8 %1
}

define i8 @atomicrmw_min_i8_monotonic(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_min_i8_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    slli a1, a1, 56
; RV64I-NEXT:    andi a4, a0, 24
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    srai a1, a1, 56
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    xori a4, a4, 56
; RV64I-NEXT:  .LBB50_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a5, (a2)
; RV64I-NEXT:    and a7, a5, a3
; RV64I-NEXT:    mv a6, a5
; RV64I-NEXT:    sll a7, a7, a4
; RV64I-NEXT:    sra a7, a7, a4
; RV64I-NEXT:    bge a1, a7, .LBB50_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB50_1 Depth=1
; RV64I-NEXT:    xor a6, a5, a1
; RV64I-NEXT:    and a6, a6, a3
; RV64I-NEXT:    xor a6, a5, a6
; RV64I-NEXT:  .LBB50_3: # in Loop: Header=BB50_1 Depth=1
; RV64I-NEXT:    sc.w a6, a6, (a2)
; RV64I-NEXT:    bnez a6, .LBB50_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a5, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_min_i8_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    slli a1, a1, 56
; RV64I-ZALRSC-NEXT:    andi a4, a0, 24
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    srai a1, a1, 56
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    xori a4, a4, 56
; RV64I-ZALRSC-NEXT:  .LBB50_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a5, (a2)
; RV64I-ZALRSC-NEXT:    and a7, a5, a3
; RV64I-ZALRSC-NEXT:    mv a6, a5
; RV64I-ZALRSC-NEXT:    sll a7, a7, a4
; RV64I-ZALRSC-NEXT:    sra a7, a7, a4
; RV64I-ZALRSC-NEXT:    bge a1, a7, .LBB50_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB50_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a6, a5, a1
; RV64I-ZALRSC-NEXT:    and a6, a6, a3
; RV64I-ZALRSC-NEXT:    xor a6, a5, a6
; RV64I-ZALRSC-NEXT:  .LBB50_3: # in Loop: Header=BB50_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w a6, a6, (a2)
; RV64I-ZALRSC-NEXT:    bnez a6, .LBB50_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a5, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_min_i8_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    slli a1, a1, 56
; RV64IA-NEXT:    andi a4, a0, 24
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    srai a1, a1, 56
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    xori a4, a4, 56
; RV64IA-NEXT:  .LBB50_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a5, (a2)
; RV64IA-NEXT:    and a7, a5, a3
; RV64IA-NEXT:    mv a6, a5
; RV64IA-NEXT:    sll a7, a7, a4
; RV64IA-NEXT:    sra a7, a7, a4
; RV64IA-NEXT:    bge a1, a7, .LBB50_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB50_1 Depth=1
; RV64IA-NEXT:    xor a6, a5, a1
; RV64IA-NEXT:    and a6, a6, a3
; RV64IA-NEXT:    xor a6, a5, a6
; RV64IA-NEXT:  .LBB50_3: # in Loop: Header=BB50_1 Depth=1
; RV64IA-NEXT:    sc.w a6, a6, (a2)
; RV64IA-NEXT:    bnez a6, .LBB50_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a5, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw min ptr %a, i8 %b monotonic
  ret i8 %1
}

define i8 @atomicrmw_min_i8_acquire(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_min_i8_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    slli a1, a1, 56
; RV64I-NEXT:    andi a4, a0, 24
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    srai a1, a1, 56
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    xori a4, a4, 56
; RV64I-NEXT:  .LBB51_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a5, (a2)
; RV64I-NEXT:    and a7, a5, a3
; RV64I-NEXT:    mv a6, a5
; RV64I-NEXT:    sll a7, a7, a4
; RV64I-NEXT:    sra a7, a7, a4
; RV64I-NEXT:    bge a1, a7, .LBB51_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB51_1 Depth=1
; RV64I-NEXT:    xor a6, a5, a1
; RV64I-NEXT:    and a6, a6, a3
; RV64I-NEXT:    xor a6, a5, a6
; RV64I-NEXT:  .LBB51_3: # in Loop: Header=BB51_1 Depth=1
; RV64I-NEXT:    sc.w a6, a6, (a2)
; RV64I-NEXT:    bnez a6, .LBB51_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a5, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_min_i8_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    slli a1, a1, 56
; RV64I-ZALRSC-NEXT:    andi a4, a0, 24
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    srai a1, a1, 56
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    xori a4, a4, 56
; RV64I-ZALRSC-NEXT:  .LBB51_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a5, (a2)
; RV64I-ZALRSC-NEXT:    and a7, a5, a3
; RV64I-ZALRSC-NEXT:    mv a6, a5
; RV64I-ZALRSC-NEXT:    sll a7, a7, a4
; RV64I-ZALRSC-NEXT:    sra a7, a7, a4
; RV64I-ZALRSC-NEXT:    bge a1, a7, .LBB51_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB51_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a6, a5, a1
; RV64I-ZALRSC-NEXT:    and a6, a6, a3
; RV64I-ZALRSC-NEXT:    xor a6, a5, a6
; RV64I-ZALRSC-NEXT:  .LBB51_3: # in Loop: Header=BB51_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w a6, a6, (a2)
; RV64I-ZALRSC-NEXT:    bnez a6, .LBB51_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a5, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_min_i8_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    slli a1, a1, 56
; RV64IA-NEXT:    andi a4, a0, 24
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    srai a1, a1, 56
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    xori a4, a4, 56
; RV64IA-NEXT:  .LBB51_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a5, (a2)
; RV64IA-NEXT:    and a7, a5, a3
; RV64IA-NEXT:    mv a6, a5
; RV64IA-NEXT:    sll a7, a7, a4
; RV64IA-NEXT:    sra a7, a7, a4
; RV64IA-NEXT:    bge a1, a7, .LBB51_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB51_1 Depth=1
; RV64IA-NEXT:    xor a6, a5, a1
; RV64IA-NEXT:    and a6, a6, a3
; RV64IA-NEXT:    xor a6, a5, a6
; RV64IA-NEXT:  .LBB51_3: # in Loop: Header=BB51_1 Depth=1
; RV64IA-NEXT:    sc.w a6, a6, (a2)
; RV64IA-NEXT:    bnez a6, .LBB51_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a5, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw min ptr %a, i8 %b acquire
  ret i8 %1
}

define i8 @atomicrmw_min_i8_release(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_min_i8_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    slli a1, a1, 56
; RV64I-NEXT:    andi a4, a0, 24
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    srai a1, a1, 56
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    xori a4, a4, 56
; RV64I-NEXT:  .LBB52_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a5, (a2)
; RV64I-NEXT:    and a7, a5, a3
; RV64I-NEXT:    mv a6, a5
; RV64I-NEXT:    sll a7, a7, a4
; RV64I-NEXT:    sra a7, a7, a4
; RV64I-NEXT:    bge a1, a7, .LBB52_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB52_1 Depth=1
; RV64I-NEXT:    xor a6, a5, a1
; RV64I-NEXT:    and a6, a6, a3
; RV64I-NEXT:    xor a6, a5, a6
; RV64I-NEXT:  .LBB52_3: # in Loop: Header=BB52_1 Depth=1
; RV64I-NEXT:    sc.w.rl a6, a6, (a2)
; RV64I-NEXT:    bnez a6, .LBB52_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a5, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_min_i8_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    slli a1, a1, 56
; RV64I-ZALRSC-NEXT:    andi a4, a0, 24
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    srai a1, a1, 56
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    xori a4, a4, 56
; RV64I-ZALRSC-NEXT:  .LBB52_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a5, (a2)
; RV64I-ZALRSC-NEXT:    and a7, a5, a3
; RV64I-ZALRSC-NEXT:    mv a6, a5
; RV64I-ZALRSC-NEXT:    sll a7, a7, a4
; RV64I-ZALRSC-NEXT:    sra a7, a7, a4
; RV64I-ZALRSC-NEXT:    bge a1, a7, .LBB52_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB52_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a6, a5, a1
; RV64I-ZALRSC-NEXT:    and a6, a6, a3
; RV64I-ZALRSC-NEXT:    xor a6, a5, a6
; RV64I-ZALRSC-NEXT:  .LBB52_3: # in Loop: Header=BB52_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w.rl a6, a6, (a2)
; RV64I-ZALRSC-NEXT:    bnez a6, .LBB52_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a5, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_min_i8_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    slli a1, a1, 56
; RV64IA-NEXT:    andi a4, a0, 24
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    srai a1, a1, 56
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    xori a4, a4, 56
; RV64IA-NEXT:  .LBB52_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a5, (a2)
; RV64IA-NEXT:    and a7, a5, a3
; RV64IA-NEXT:    mv a6, a5
; RV64IA-NEXT:    sll a7, a7, a4
; RV64IA-NEXT:    sra a7, a7, a4
; RV64IA-NEXT:    bge a1, a7, .LBB52_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB52_1 Depth=1
; RV64IA-NEXT:    xor a6, a5, a1
; RV64IA-NEXT:    and a6, a6, a3
; RV64IA-NEXT:    xor a6, a5, a6
; RV64IA-NEXT:  .LBB52_3: # in Loop: Header=BB52_1 Depth=1
; RV64IA-NEXT:    sc.w.rl a6, a6, (a2)
; RV64IA-NEXT:    bnez a6, .LBB52_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a5, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw min ptr %a, i8 %b release
  ret i8 %1
}

define i8 @atomicrmw_min_i8_acq_rel(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_min_i8_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    slli a1, a1, 56
; RV64I-NEXT:    andi a4, a0, 24
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    srai a1, a1, 56
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    xori a4, a4, 56
; RV64I-NEXT:  .LBB53_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a5, (a2)
; RV64I-NEXT:    and a7, a5, a3
; RV64I-NEXT:    mv a6, a5
; RV64I-NEXT:    sll a7, a7, a4
; RV64I-NEXT:    sra a7, a7, a4
; RV64I-NEXT:    bge a1, a7, .LBB53_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB53_1 Depth=1
; RV64I-NEXT:    xor a6, a5, a1
; RV64I-NEXT:    and a6, a6, a3
; RV64I-NEXT:    xor a6, a5, a6
; RV64I-NEXT:  .LBB53_3: # in Loop: Header=BB53_1 Depth=1
; RV64I-NEXT:    sc.w.rl a6, a6, (a2)
; RV64I-NEXT:    bnez a6, .LBB53_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a5, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_min_i8_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    slli a1, a1, 56
; RV64I-ZALRSC-NEXT:    andi a4, a0, 24
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    srai a1, a1, 56
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    xori a4, a4, 56
; RV64I-ZALRSC-NEXT:  .LBB53_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a5, (a2)
; RV64I-ZALRSC-NEXT:    and a7, a5, a3
; RV64I-ZALRSC-NEXT:    mv a6, a5
; RV64I-ZALRSC-NEXT:    sll a7, a7, a4
; RV64I-ZALRSC-NEXT:    sra a7, a7, a4
; RV64I-ZALRSC-NEXT:    bge a1, a7, .LBB53_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB53_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a6, a5, a1
; RV64I-ZALRSC-NEXT:    and a6, a6, a3
; RV64I-ZALRSC-NEXT:    xor a6, a5, a6
; RV64I-ZALRSC-NEXT:  .LBB53_3: # in Loop: Header=BB53_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w.rl a6, a6, (a2)
; RV64I-ZALRSC-NEXT:    bnez a6, .LBB53_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a5, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_min_i8_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    slli a1, a1, 56
; RV64IA-NEXT:    andi a4, a0, 24
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    srai a1, a1, 56
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    xori a4, a4, 56
; RV64IA-NEXT:  .LBB53_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a5, (a2)
; RV64IA-NEXT:    and a7, a5, a3
; RV64IA-NEXT:    mv a6, a5
; RV64IA-NEXT:    sll a7, a7, a4
; RV64IA-NEXT:    sra a7, a7, a4
; RV64IA-NEXT:    bge a1, a7, .LBB53_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB53_1 Depth=1
; RV64IA-NEXT:    xor a6, a5, a1
; RV64IA-NEXT:    and a6, a6, a3
; RV64IA-NEXT:    xor a6, a5, a6
; RV64IA-NEXT:  .LBB53_3: # in Loop: Header=BB53_1 Depth=1
; RV64IA-NEXT:    sc.w.rl a6, a6, (a2)
; RV64IA-NEXT:    bnez a6, .LBB53_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a5, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw min ptr %a, i8 %b acq_rel
  ret i8 %1
}

define i8 @atomicrmw_min_i8_seq_cst(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_min_i8_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    slli a1, a1, 56
; RV64I-NEXT:    andi a4, a0, 24
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    srai a1, a1, 56
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    xori a4, a4, 56
; RV64I-NEXT:  .LBB54_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aqrl a5, (a2)
; RV64I-NEXT:    and a7, a5, a3
; RV64I-NEXT:    mv a6, a5
; RV64I-NEXT:    sll a7, a7, a4
; RV64I-NEXT:    sra a7, a7, a4
; RV64I-NEXT:    bge a1, a7, .LBB54_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB54_1 Depth=1
; RV64I-NEXT:    xor a6, a5, a1
; RV64I-NEXT:    and a6, a6, a3
; RV64I-NEXT:    xor a6, a5, a6
; RV64I-NEXT:  .LBB54_3: # in Loop: Header=BB54_1 Depth=1
; RV64I-NEXT:    sc.w.rl a6, a6, (a2)
; RV64I-NEXT:    bnez a6, .LBB54_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a5, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_min_i8_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    slli a1, a1, 56
; RV64I-ZALRSC-NEXT:    andi a4, a0, 24
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    srai a1, a1, 56
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    xori a4, a4, 56
; RV64I-ZALRSC-NEXT:  .LBB54_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aqrl a5, (a2)
; RV64I-ZALRSC-NEXT:    and a7, a5, a3
; RV64I-ZALRSC-NEXT:    mv a6, a5
; RV64I-ZALRSC-NEXT:    sll a7, a7, a4
; RV64I-ZALRSC-NEXT:    sra a7, a7, a4
; RV64I-ZALRSC-NEXT:    bge a1, a7, .LBB54_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB54_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a6, a5, a1
; RV64I-ZALRSC-NEXT:    and a6, a6, a3
; RV64I-ZALRSC-NEXT:    xor a6, a5, a6
; RV64I-ZALRSC-NEXT:  .LBB54_3: # in Loop: Header=BB54_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w.rl a6, a6, (a2)
; RV64I-ZALRSC-NEXT:    bnez a6, .LBB54_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a5, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_min_i8_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    slli a1, a1, 56
; RV64IA-NEXT:    andi a4, a0, 24
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    srai a1, a1, 56
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    xori a4, a4, 56
; RV64IA-NEXT:  .LBB54_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aqrl a5, (a2)
; RV64IA-NEXT:    and a7, a5, a3
; RV64IA-NEXT:    mv a6, a5
; RV64IA-NEXT:    sll a7, a7, a4
; RV64IA-NEXT:    sra a7, a7, a4
; RV64IA-NEXT:    bge a1, a7, .LBB54_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB54_1 Depth=1
; RV64IA-NEXT:    xor a6, a5, a1
; RV64IA-NEXT:    and a6, a6, a3
; RV64IA-NEXT:    xor a6, a5, a6
; RV64IA-NEXT:  .LBB54_3: # in Loop: Header=BB54_1 Depth=1
; RV64IA-NEXT:    sc.w.rl a6, a6, (a2)
; RV64IA-NEXT:    bnez a6, .LBB54_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a5, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw min ptr %a, i8 %b seq_cst
  ret i8 %1
}

define i8 @atomicrmw_umax_i8_monotonic(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_umax_i8_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB55_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a4, (a2)
; RV64I-NEXT:    and a6, a4, a3
; RV64I-NEXT:    mv a5, a4
; RV64I-NEXT:    bgeu a6, a1, .LBB55_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB55_1 Depth=1
; RV64I-NEXT:    xor a5, a4, a1
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:  .LBB55_3: # in Loop: Header=BB55_1 Depth=1
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB55_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umax_i8_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB55_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a4, (a2)
; RV64I-ZALRSC-NEXT:    and a6, a4, a3
; RV64I-ZALRSC-NEXT:    mv a5, a4
; RV64I-ZALRSC-NEXT:    bgeu a6, a1, .LBB55_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB55_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a5, a4, a1
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:  .LBB55_3: # in Loop: Header=BB55_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB55_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umax_i8_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB55_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a4, (a2)
; RV64IA-NEXT:    and a6, a4, a3
; RV64IA-NEXT:    mv a5, a4
; RV64IA-NEXT:    bgeu a6, a1, .LBB55_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB55_1 Depth=1
; RV64IA-NEXT:    xor a5, a4, a1
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:  .LBB55_3: # in Loop: Header=BB55_1 Depth=1
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB55_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw umax ptr %a, i8 %b monotonic
  ret i8 %1
}

define i8 @atomicrmw_umax_i8_acquire(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_umax_i8_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB56_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a4, (a2)
; RV64I-NEXT:    and a6, a4, a3
; RV64I-NEXT:    mv a5, a4
; RV64I-NEXT:    bgeu a6, a1, .LBB56_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB56_1 Depth=1
; RV64I-NEXT:    xor a5, a4, a1
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:  .LBB56_3: # in Loop: Header=BB56_1 Depth=1
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB56_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umax_i8_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB56_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a4, (a2)
; RV64I-ZALRSC-NEXT:    and a6, a4, a3
; RV64I-ZALRSC-NEXT:    mv a5, a4
; RV64I-ZALRSC-NEXT:    bgeu a6, a1, .LBB56_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB56_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a5, a4, a1
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:  .LBB56_3: # in Loop: Header=BB56_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB56_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umax_i8_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB56_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a4, (a2)
; RV64IA-NEXT:    and a6, a4, a3
; RV64IA-NEXT:    mv a5, a4
; RV64IA-NEXT:    bgeu a6, a1, .LBB56_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB56_1 Depth=1
; RV64IA-NEXT:    xor a5, a4, a1
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:  .LBB56_3: # in Loop: Header=BB56_1 Depth=1
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB56_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw umax ptr %a, i8 %b acquire
  ret i8 %1
}

define i8 @atomicrmw_umax_i8_release(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_umax_i8_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB57_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a4, (a2)
; RV64I-NEXT:    and a6, a4, a3
; RV64I-NEXT:    mv a5, a4
; RV64I-NEXT:    bgeu a6, a1, .LBB57_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB57_1 Depth=1
; RV64I-NEXT:    xor a5, a4, a1
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:  .LBB57_3: # in Loop: Header=BB57_1 Depth=1
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB57_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umax_i8_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB57_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a4, (a2)
; RV64I-ZALRSC-NEXT:    and a6, a4, a3
; RV64I-ZALRSC-NEXT:    mv a5, a4
; RV64I-ZALRSC-NEXT:    bgeu a6, a1, .LBB57_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB57_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a5, a4, a1
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:  .LBB57_3: # in Loop: Header=BB57_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB57_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umax_i8_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB57_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a4, (a2)
; RV64IA-NEXT:    and a6, a4, a3
; RV64IA-NEXT:    mv a5, a4
; RV64IA-NEXT:    bgeu a6, a1, .LBB57_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB57_1 Depth=1
; RV64IA-NEXT:    xor a5, a4, a1
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:  .LBB57_3: # in Loop: Header=BB57_1 Depth=1
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB57_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw umax ptr %a, i8 %b release
  ret i8 %1
}

define i8 @atomicrmw_umax_i8_acq_rel(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_umax_i8_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB58_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a4, (a2)
; RV64I-NEXT:    and a6, a4, a3
; RV64I-NEXT:    mv a5, a4
; RV64I-NEXT:    bgeu a6, a1, .LBB58_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB58_1 Depth=1
; RV64I-NEXT:    xor a5, a4, a1
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:  .LBB58_3: # in Loop: Header=BB58_1 Depth=1
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB58_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umax_i8_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB58_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a4, (a2)
; RV64I-ZALRSC-NEXT:    and a6, a4, a3
; RV64I-ZALRSC-NEXT:    mv a5, a4
; RV64I-ZALRSC-NEXT:    bgeu a6, a1, .LBB58_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB58_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a5, a4, a1
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:  .LBB58_3: # in Loop: Header=BB58_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB58_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umax_i8_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB58_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a4, (a2)
; RV64IA-NEXT:    and a6, a4, a3
; RV64IA-NEXT:    mv a5, a4
; RV64IA-NEXT:    bgeu a6, a1, .LBB58_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB58_1 Depth=1
; RV64IA-NEXT:    xor a5, a4, a1
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:  .LBB58_3: # in Loop: Header=BB58_1 Depth=1
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB58_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw umax ptr %a, i8 %b acq_rel
  ret i8 %1
}

define i8 @atomicrmw_umax_i8_seq_cst(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_umax_i8_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB59_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aqrl a4, (a2)
; RV64I-NEXT:    and a6, a4, a3
; RV64I-NEXT:    mv a5, a4
; RV64I-NEXT:    bgeu a6, a1, .LBB59_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB59_1 Depth=1
; RV64I-NEXT:    xor a5, a4, a1
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:  .LBB59_3: # in Loop: Header=BB59_1 Depth=1
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB59_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umax_i8_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB59_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aqrl a4, (a2)
; RV64I-ZALRSC-NEXT:    and a6, a4, a3
; RV64I-ZALRSC-NEXT:    mv a5, a4
; RV64I-ZALRSC-NEXT:    bgeu a6, a1, .LBB59_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB59_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a5, a4, a1
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:  .LBB59_3: # in Loop: Header=BB59_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB59_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umax_i8_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB59_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aqrl a4, (a2)
; RV64IA-NEXT:    and a6, a4, a3
; RV64IA-NEXT:    mv a5, a4
; RV64IA-NEXT:    bgeu a6, a1, .LBB59_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB59_1 Depth=1
; RV64IA-NEXT:    xor a5, a4, a1
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:  .LBB59_3: # in Loop: Header=BB59_1 Depth=1
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB59_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw umax ptr %a, i8 %b seq_cst
  ret i8 %1
}

define i8 @atomicrmw_umin_i8_monotonic(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_umin_i8_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB60_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a4, (a2)
; RV64I-NEXT:    and a6, a4, a3
; RV64I-NEXT:    mv a5, a4
; RV64I-NEXT:    bgeu a1, a6, .LBB60_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB60_1 Depth=1
; RV64I-NEXT:    xor a5, a4, a1
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:  .LBB60_3: # in Loop: Header=BB60_1 Depth=1
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB60_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umin_i8_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB60_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a4, (a2)
; RV64I-ZALRSC-NEXT:    and a6, a4, a3
; RV64I-ZALRSC-NEXT:    mv a5, a4
; RV64I-ZALRSC-NEXT:    bgeu a1, a6, .LBB60_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB60_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a5, a4, a1
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:  .LBB60_3: # in Loop: Header=BB60_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB60_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umin_i8_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB60_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a4, (a2)
; RV64IA-NEXT:    and a6, a4, a3
; RV64IA-NEXT:    mv a5, a4
; RV64IA-NEXT:    bgeu a1, a6, .LBB60_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB60_1 Depth=1
; RV64IA-NEXT:    xor a5, a4, a1
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:  .LBB60_3: # in Loop: Header=BB60_1 Depth=1
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB60_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw umin ptr %a, i8 %b monotonic
  ret i8 %1
}

define i8 @atomicrmw_umin_i8_acquire(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_umin_i8_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB61_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a4, (a2)
; RV64I-NEXT:    and a6, a4, a3
; RV64I-NEXT:    mv a5, a4
; RV64I-NEXT:    bgeu a1, a6, .LBB61_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB61_1 Depth=1
; RV64I-NEXT:    xor a5, a4, a1
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:  .LBB61_3: # in Loop: Header=BB61_1 Depth=1
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB61_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umin_i8_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB61_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a4, (a2)
; RV64I-ZALRSC-NEXT:    and a6, a4, a3
; RV64I-ZALRSC-NEXT:    mv a5, a4
; RV64I-ZALRSC-NEXT:    bgeu a1, a6, .LBB61_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB61_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a5, a4, a1
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:  .LBB61_3: # in Loop: Header=BB61_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB61_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umin_i8_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB61_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a4, (a2)
; RV64IA-NEXT:    and a6, a4, a3
; RV64IA-NEXT:    mv a5, a4
; RV64IA-NEXT:    bgeu a1, a6, .LBB61_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB61_1 Depth=1
; RV64IA-NEXT:    xor a5, a4, a1
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:  .LBB61_3: # in Loop: Header=BB61_1 Depth=1
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB61_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw umin ptr %a, i8 %b acquire
  ret i8 %1
}

define i8 @atomicrmw_umin_i8_release(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_umin_i8_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB62_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a4, (a2)
; RV64I-NEXT:    and a6, a4, a3
; RV64I-NEXT:    mv a5, a4
; RV64I-NEXT:    bgeu a1, a6, .LBB62_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB62_1 Depth=1
; RV64I-NEXT:    xor a5, a4, a1
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:  .LBB62_3: # in Loop: Header=BB62_1 Depth=1
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB62_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umin_i8_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB62_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a4, (a2)
; RV64I-ZALRSC-NEXT:    and a6, a4, a3
; RV64I-ZALRSC-NEXT:    mv a5, a4
; RV64I-ZALRSC-NEXT:    bgeu a1, a6, .LBB62_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB62_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a5, a4, a1
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:  .LBB62_3: # in Loop: Header=BB62_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB62_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umin_i8_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB62_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a4, (a2)
; RV64IA-NEXT:    and a6, a4, a3
; RV64IA-NEXT:    mv a5, a4
; RV64IA-NEXT:    bgeu a1, a6, .LBB62_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB62_1 Depth=1
; RV64IA-NEXT:    xor a5, a4, a1
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:  .LBB62_3: # in Loop: Header=BB62_1 Depth=1
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB62_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw umin ptr %a, i8 %b release
  ret i8 %1
}

define i8 @atomicrmw_umin_i8_acq_rel(ptr %a, i8 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_umin_i8_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB63_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a4, (a2)
; RV64I-NEXT:    and a6, a4, a3
; RV64I-NEXT:    mv a5, a4
; RV64I-NEXT:    bgeu a1, a6, .LBB63_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB63_1 Depth=1
; RV64I-NEXT:    xor a5, a4, a1
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:  .LBB63_3: # in Loop: Header=BB63_1 Depth=1
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB63_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umin_i8_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB63_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a4, (a2)
; RV64I-ZALRSC-NEXT:    and a6, a4, a3
; RV64I-ZALRSC-NEXT:    mv a5, a4
; RV64I-ZALRSC-NEXT:    bgeu a1, a6, .LBB63_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB63_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a5, a4, a1
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:  .LBB63_3: # in Loop: Header=BB63_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB63_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umin_i8_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB63_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a4, (a2)
; RV64IA-NEXT:    and a6, a4, a3
; RV64IA-NEXT:    mv a5, a4
; RV64IA-NEXT:    bgeu a1, a6, .LBB63_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB63_1 Depth=1
; RV64IA-NEXT:    xor a5, a4, a1
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:  .LBB63_3: # in Loop: Header=BB63_1 Depth=1
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB63_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw umin ptr %a, i8 %b acq_rel
  ret i8 %1
}

define i8 @atomicrmw_umin_i8_seq_cst(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_umin_i8_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB64_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aqrl a4, (a2)
; RV64I-NEXT:    and a6, a4, a3
; RV64I-NEXT:    mv a5, a4
; RV64I-NEXT:    bgeu a1, a6, .LBB64_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB64_1 Depth=1
; RV64I-NEXT:    xor a5, a4, a1
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:  .LBB64_3: # in Loop: Header=BB64_1 Depth=1
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB64_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umin_i8_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB64_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aqrl a4, (a2)
; RV64I-ZALRSC-NEXT:    and a6, a4, a3
; RV64I-ZALRSC-NEXT:    mv a5, a4
; RV64I-ZALRSC-NEXT:    bgeu a1, a6, .LBB64_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB64_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a5, a4, a1
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:  .LBB64_3: # in Loop: Header=BB64_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB64_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umin_i8_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB64_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aqrl a4, (a2)
; RV64IA-NEXT:    and a6, a4, a3
; RV64IA-NEXT:    mv a5, a4
; RV64IA-NEXT:    bgeu a1, a6, .LBB64_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB64_1 Depth=1
; RV64IA-NEXT:    xor a5, a4, a1
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:  .LBB64_3: # in Loop: Header=BB64_1 Depth=1
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB64_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw umin ptr %a, i8 %b seq_cst
  ret i8 %1
}

define i16 @atomicrmw_xchg_i16_monotonic(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xchg_i16_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB65_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a3, (a2)
; RV64I-NEXT:    mv a5, a1
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB65_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_i16_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB65_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a3, (a2)
; RV64I-ZALRSC-NEXT:    mv a5, a1
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB65_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_i16_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB65_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a3, (a2)
; RV64IA-NEXT:    mv a5, a1
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB65_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i16 %b monotonic
  ret i16 %1
}

define i16 @atomicrmw_xchg_i16_acquire(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xchg_i16_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB66_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a3, (a2)
; RV64I-NEXT:    mv a5, a1
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB66_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_i16_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB66_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a3, (a2)
; RV64I-ZALRSC-NEXT:    mv a5, a1
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB66_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_i16_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB66_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a3, (a2)
; RV64IA-NEXT:    mv a5, a1
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB66_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i16 %b acquire
  ret i16 %1
}

define i16 @atomicrmw_xchg_i16_release(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xchg_i16_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB67_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a3, (a2)
; RV64I-NEXT:    mv a5, a1
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB67_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_i16_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB67_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a3, (a2)
; RV64I-ZALRSC-NEXT:    mv a5, a1
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB67_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_i16_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB67_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a3, (a2)
; RV64IA-NEXT:    mv a5, a1
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB67_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i16 %b release
  ret i16 %1
}

define i16 @atomicrmw_xchg_i16_acq_rel(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xchg_i16_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB68_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a3, (a2)
; RV64I-NEXT:    mv a5, a1
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB68_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_i16_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB68_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a3, (a2)
; RV64I-ZALRSC-NEXT:    mv a5, a1
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB68_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_i16_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB68_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a3, (a2)
; RV64IA-NEXT:    mv a5, a1
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB68_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i16 %b acq_rel
  ret i16 %1
}

define i16 @atomicrmw_xchg_i16_seq_cst(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xchg_i16_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB69_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aqrl a3, (a2)
; RV64I-NEXT:    mv a5, a1
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB69_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_i16_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB69_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aqrl a3, (a2)
; RV64I-ZALRSC-NEXT:    mv a5, a1
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB69_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_i16_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB69_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aqrl a3, (a2)
; RV64IA-NEXT:    mv a5, a1
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB69_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i16 %b seq_cst
  ret i16 %1
}

; Ensure the following 'atomicrmw xchg a, {0,-1}` cases are lowered to an
; amoand or amoor with appropriate mask.

define i16 @atomicrmw_xchg_0_i16_monotonic(ptr %a) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xchg_0_i16_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a1, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a2, 16
; RV64I-NEXT:    addi a2, a2, -1
; RV64I-NEXT:    sllw a2, a2, a0
; RV64I-NEXT:    not a2, a2
; RV64I-NEXT:    amoand.w a1, a2, (a1)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_0_i16_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a1, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a2, 16
; RV64I-ZALRSC-NEXT:    addi a2, a2, -1
; RV64I-ZALRSC-NEXT:    sllw a2, a2, a0
; RV64I-ZALRSC-NEXT:    not a2, a2
; RV64I-ZALRSC-NEXT:    amoand.w a1, a2, (a1)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_0_i16_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a1, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a2, 16
; RV64IA-NEXT:    addi a2, a2, -1
; RV64IA-NEXT:    sllw a2, a2, a0
; RV64IA-NEXT:    not a2, a2
; RV64IA-NEXT:    amoand.w a1, a2, (a1)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i16 0 monotonic
  ret i16 %1
}

define i16 @atomicrmw_xchg_0_i16_acquire(ptr %a) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xchg_0_i16_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a1, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a2, 16
; RV64I-NEXT:    addi a2, a2, -1
; RV64I-NEXT:    sllw a2, a2, a0
; RV64I-NEXT:    not a2, a2
; RV64I-NEXT:    amoand.w.aq a1, a2, (a1)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_0_i16_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a1, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a2, 16
; RV64I-ZALRSC-NEXT:    addi a2, a2, -1
; RV64I-ZALRSC-NEXT:    sllw a2, a2, a0
; RV64I-ZALRSC-NEXT:    not a2, a2
; RV64I-ZALRSC-NEXT:    amoand.w.aq a1, a2, (a1)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_0_i16_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a1, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a2, 16
; RV64IA-NEXT:    addi a2, a2, -1
; RV64IA-NEXT:    sllw a2, a2, a0
; RV64IA-NEXT:    not a2, a2
; RV64IA-NEXT:    amoand.w.aq a1, a2, (a1)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i16 0 acquire
  ret i16 %1
}

define i16 @atomicrmw_xchg_0_i16_release(ptr %a) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xchg_0_i16_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a1, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a2, 16
; RV64I-NEXT:    addi a2, a2, -1
; RV64I-NEXT:    sllw a2, a2, a0
; RV64I-NEXT:    not a2, a2
; RV64I-NEXT:    amoand.w.rl a1, a2, (a1)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_0_i16_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a1, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a2, 16
; RV64I-ZALRSC-NEXT:    addi a2, a2, -1
; RV64I-ZALRSC-NEXT:    sllw a2, a2, a0
; RV64I-ZALRSC-NEXT:    not a2, a2
; RV64I-ZALRSC-NEXT:    amoand.w.rl a1, a2, (a1)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_0_i16_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a1, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a2, 16
; RV64IA-NEXT:    addi a2, a2, -1
; RV64IA-NEXT:    sllw a2, a2, a0
; RV64IA-NEXT:    not a2, a2
; RV64IA-NEXT:    amoand.w.rl a1, a2, (a1)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i16 0 release
  ret i16 %1
}

define i16 @atomicrmw_xchg_0_i16_acq_rel(ptr %a) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xchg_0_i16_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a1, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a2, 16
; RV64I-NEXT:    addi a2, a2, -1
; RV64I-NEXT:    sllw a2, a2, a0
; RV64I-NEXT:    not a2, a2
; RV64I-NEXT:    amoand.w.aqrl a1, a2, (a1)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_0_i16_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a1, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a2, 16
; RV64I-ZALRSC-NEXT:    addi a2, a2, -1
; RV64I-ZALRSC-NEXT:    sllw a2, a2, a0
; RV64I-ZALRSC-NEXT:    not a2, a2
; RV64I-ZALRSC-NEXT:    amoand.w.aqrl a1, a2, (a1)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_0_i16_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a1, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a2, 16
; RV64IA-NEXT:    addi a2, a2, -1
; RV64IA-NEXT:    sllw a2, a2, a0
; RV64IA-NEXT:    not a2, a2
; RV64IA-NEXT:    amoand.w.aqrl a1, a2, (a1)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i16 0 acq_rel
  ret i16 %1
}

define i16 @atomicrmw_xchg_0_i16_seq_cst(ptr %a) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xchg_0_i16_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a1, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a2, 16
; RV64I-NEXT:    addi a2, a2, -1
; RV64I-NEXT:    sllw a2, a2, a0
; RV64I-NEXT:    not a2, a2
; RV64I-NEXT:    amoand.w.aqrl a1, a2, (a1)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_0_i16_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a1, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a2, 16
; RV64I-ZALRSC-NEXT:    addi a2, a2, -1
; RV64I-ZALRSC-NEXT:    sllw a2, a2, a0
; RV64I-ZALRSC-NEXT:    not a2, a2
; RV64I-ZALRSC-NEXT:    amoand.w.aqrl a1, a2, (a1)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_0_i16_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a1, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a2, 16
; RV64IA-NEXT:    addi a2, a2, -1
; RV64IA-NEXT:    sllw a2, a2, a0
; RV64IA-NEXT:    not a2, a2
; RV64IA-NEXT:    amoand.w.aqrl a1, a2, (a1)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i16 0 seq_cst
  ret i16 %1
}

define i16 @atomicrmw_xchg_minus_1_i16_monotonic(ptr %a) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xchg_minus_1_i16_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a1, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a2, 16
; RV64I-NEXT:    addi a2, a2, -1
; RV64I-NEXT:    sllw a2, a2, a0
; RV64I-NEXT:    amoor.w a1, a2, (a1)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_minus_1_i16_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a1, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a2, 16
; RV64I-ZALRSC-NEXT:    addi a2, a2, -1
; RV64I-ZALRSC-NEXT:    sllw a2, a2, a0
; RV64I-ZALRSC-NEXT:    amoor.w a1, a2, (a1)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_minus_1_i16_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a1, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a2, 16
; RV64IA-NEXT:    addi a2, a2, -1
; RV64IA-NEXT:    sllw a2, a2, a0
; RV64IA-NEXT:    amoor.w a1, a2, (a1)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i16 -1 monotonic
  ret i16 %1
}

define i16 @atomicrmw_xchg_minus_1_i16_acquire(ptr %a) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xchg_minus_1_i16_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a1, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a2, 16
; RV64I-NEXT:    addi a2, a2, -1
; RV64I-NEXT:    sllw a2, a2, a0
; RV64I-NEXT:    amoor.w.aq a1, a2, (a1)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_minus_1_i16_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a1, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a2, 16
; RV64I-ZALRSC-NEXT:    addi a2, a2, -1
; RV64I-ZALRSC-NEXT:    sllw a2, a2, a0
; RV64I-ZALRSC-NEXT:    amoor.w.aq a1, a2, (a1)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_minus_1_i16_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a1, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a2, 16
; RV64IA-NEXT:    addi a2, a2, -1
; RV64IA-NEXT:    sllw a2, a2, a0
; RV64IA-NEXT:    amoor.w.aq a1, a2, (a1)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i16 -1 acquire
  ret i16 %1
}

define i16 @atomicrmw_xchg_minus_1_i16_release(ptr %a) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xchg_minus_1_i16_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a1, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a2, 16
; RV64I-NEXT:    addi a2, a2, -1
; RV64I-NEXT:    sllw a2, a2, a0
; RV64I-NEXT:    amoor.w.rl a1, a2, (a1)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_minus_1_i16_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a1, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a2, 16
; RV64I-ZALRSC-NEXT:    addi a2, a2, -1
; RV64I-ZALRSC-NEXT:    sllw a2, a2, a0
; RV64I-ZALRSC-NEXT:    amoor.w.rl a1, a2, (a1)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_minus_1_i16_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a1, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a2, 16
; RV64IA-NEXT:    addi a2, a2, -1
; RV64IA-NEXT:    sllw a2, a2, a0
; RV64IA-NEXT:    amoor.w.rl a1, a2, (a1)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i16 -1 release
  ret i16 %1
}

define i16 @atomicrmw_xchg_minus_1_i16_acq_rel(ptr %a) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xchg_minus_1_i16_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a1, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a2, 16
; RV64I-NEXT:    addi a2, a2, -1
; RV64I-NEXT:    sllw a2, a2, a0
; RV64I-NEXT:    amoor.w.aqrl a1, a2, (a1)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_minus_1_i16_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a1, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a2, 16
; RV64I-ZALRSC-NEXT:    addi a2, a2, -1
; RV64I-ZALRSC-NEXT:    sllw a2, a2, a0
; RV64I-ZALRSC-NEXT:    amoor.w.aqrl a1, a2, (a1)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_minus_1_i16_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a1, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a2, 16
; RV64IA-NEXT:    addi a2, a2, -1
; RV64IA-NEXT:    sllw a2, a2, a0
; RV64IA-NEXT:    amoor.w.aqrl a1, a2, (a1)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i16 -1 acq_rel
  ret i16 %1
}

define i16 @atomicrmw_xchg_minus_1_i16_seq_cst(ptr %a) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xchg_minus_1_i16_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a1, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a2, 16
; RV64I-NEXT:    addi a2, a2, -1
; RV64I-NEXT:    sllw a2, a2, a0
; RV64I-NEXT:    amoor.w.aqrl a1, a2, (a1)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_minus_1_i16_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a1, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a2, 16
; RV64I-ZALRSC-NEXT:    addi a2, a2, -1
; RV64I-ZALRSC-NEXT:    sllw a2, a2, a0
; RV64I-ZALRSC-NEXT:    amoor.w.aqrl a1, a2, (a1)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_minus_1_i16_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a1, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a2, 16
; RV64IA-NEXT:    addi a2, a2, -1
; RV64IA-NEXT:    sllw a2, a2, a0
; RV64IA-NEXT:    amoor.w.aqrl a1, a2, (a1)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i16 -1 seq_cst
  ret i16 %1
}

define i16 @atomicrmw_add_i16_monotonic(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_add_i16_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB80_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a3, (a2)
; RV64I-NEXT:    add a5, a3, a1
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB80_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_add_i16_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB80_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a3, (a2)
; RV64I-ZALRSC-NEXT:    add a5, a3, a1
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB80_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_add_i16_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB80_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a3, (a2)
; RV64IA-NEXT:    add a5, a3, a1
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB80_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw add ptr %a, i16 %b monotonic
  ret i16 %1
}

define i16 @atomicrmw_add_i16_acquire(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_add_i16_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB81_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a3, (a2)
; RV64I-NEXT:    add a5, a3, a1
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB81_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_add_i16_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB81_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a3, (a2)
; RV64I-ZALRSC-NEXT:    add a5, a3, a1
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB81_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_add_i16_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB81_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a3, (a2)
; RV64IA-NEXT:    add a5, a3, a1
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB81_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw add ptr %a, i16 %b acquire
  ret i16 %1
}

define i16 @atomicrmw_add_i16_release(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_add_i16_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB82_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a3, (a2)
; RV64I-NEXT:    add a5, a3, a1
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB82_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_add_i16_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB82_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a3, (a2)
; RV64I-ZALRSC-NEXT:    add a5, a3, a1
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB82_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_add_i16_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB82_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a3, (a2)
; RV64IA-NEXT:    add a5, a3, a1
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB82_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw add ptr %a, i16 %b release
  ret i16 %1
}

define i16 @atomicrmw_add_i16_acq_rel(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_add_i16_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB83_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a3, (a2)
; RV64I-NEXT:    add a5, a3, a1
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB83_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_add_i16_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB83_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a3, (a2)
; RV64I-ZALRSC-NEXT:    add a5, a3, a1
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB83_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_add_i16_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB83_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a3, (a2)
; RV64IA-NEXT:    add a5, a3, a1
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB83_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw add ptr %a, i16 %b acq_rel
  ret i16 %1
}

define i16 @atomicrmw_add_i16_seq_cst(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_add_i16_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB84_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aqrl a3, (a2)
; RV64I-NEXT:    add a5, a3, a1
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB84_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_add_i16_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB84_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aqrl a3, (a2)
; RV64I-ZALRSC-NEXT:    add a5, a3, a1
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB84_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_add_i16_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB84_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aqrl a3, (a2)
; RV64IA-NEXT:    add a5, a3, a1
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB84_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw add ptr %a, i16 %b seq_cst
  ret i16 %1
}

define i16 @atomicrmw_sub_i16_monotonic(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_sub_i16_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB85_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a3, (a2)
; RV64I-NEXT:    sub a5, a3, a1
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB85_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_sub_i16_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB85_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a3, (a2)
; RV64I-ZALRSC-NEXT:    sub a5, a3, a1
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB85_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_sub_i16_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB85_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a3, (a2)
; RV64IA-NEXT:    sub a5, a3, a1
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB85_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw sub ptr %a, i16 %b monotonic
  ret i16 %1
}

define i16 @atomicrmw_sub_i16_acquire(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_sub_i16_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB86_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a3, (a2)
; RV64I-NEXT:    sub a5, a3, a1
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB86_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_sub_i16_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB86_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a3, (a2)
; RV64I-ZALRSC-NEXT:    sub a5, a3, a1
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB86_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_sub_i16_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB86_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a3, (a2)
; RV64IA-NEXT:    sub a5, a3, a1
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB86_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw sub ptr %a, i16 %b acquire
  ret i16 %1
}

define i16 @atomicrmw_sub_i16_release(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_sub_i16_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB87_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a3, (a2)
; RV64I-NEXT:    sub a5, a3, a1
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB87_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_sub_i16_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB87_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a3, (a2)
; RV64I-ZALRSC-NEXT:    sub a5, a3, a1
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB87_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_sub_i16_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB87_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a3, (a2)
; RV64IA-NEXT:    sub a5, a3, a1
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB87_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw sub ptr %a, i16 %b release
  ret i16 %1
}

define i16 @atomicrmw_sub_i16_acq_rel(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_sub_i16_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB88_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a3, (a2)
; RV64I-NEXT:    sub a5, a3, a1
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB88_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_sub_i16_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB88_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a3, (a2)
; RV64I-ZALRSC-NEXT:    sub a5, a3, a1
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB88_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_sub_i16_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB88_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a3, (a2)
; RV64IA-NEXT:    sub a5, a3, a1
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB88_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw sub ptr %a, i16 %b acq_rel
  ret i16 %1
}

define i16 @atomicrmw_sub_i16_seq_cst(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_sub_i16_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB89_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aqrl a3, (a2)
; RV64I-NEXT:    sub a5, a3, a1
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB89_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_sub_i16_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB89_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aqrl a3, (a2)
; RV64I-ZALRSC-NEXT:    sub a5, a3, a1
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB89_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_sub_i16_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB89_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aqrl a3, (a2)
; RV64IA-NEXT:    sub a5, a3, a1
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB89_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw sub ptr %a, i16 %b seq_cst
  ret i16 %1
}

define i16 @atomicrmw_and_i16_monotonic(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_and_i16_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    not a3, a4
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    or a1, a1, a3
; RV64I-NEXT:    amoand.w a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_and_i16_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    not a3, a4
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    or a1, a1, a3
; RV64I-ZALRSC-NEXT:    amoand.w a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_and_i16_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    not a3, a4
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    or a1, a1, a3
; RV64IA-NEXT:    amoand.w a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw and ptr %a, i16 %b monotonic
  ret i16 %1
}

define i16 @atomicrmw_and_i16_acquire(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_and_i16_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    not a3, a4
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    or a1, a1, a3
; RV64I-NEXT:    amoand.w.aq a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_and_i16_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    not a3, a4
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    or a1, a1, a3
; RV64I-ZALRSC-NEXT:    amoand.w.aq a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_and_i16_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    not a3, a4
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    or a1, a1, a3
; RV64IA-NEXT:    amoand.w.aq a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw and ptr %a, i16 %b acquire
  ret i16 %1
}

define i16 @atomicrmw_and_i16_release(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_and_i16_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    not a3, a4
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    or a1, a1, a3
; RV64I-NEXT:    amoand.w.rl a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_and_i16_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    not a3, a4
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    or a1, a1, a3
; RV64I-ZALRSC-NEXT:    amoand.w.rl a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_and_i16_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    not a3, a4
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    or a1, a1, a3
; RV64IA-NEXT:    amoand.w.rl a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw and ptr %a, i16 %b release
  ret i16 %1
}

define i16 @atomicrmw_and_i16_acq_rel(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_and_i16_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    not a3, a4
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    or a1, a1, a3
; RV64I-NEXT:    amoand.w.aqrl a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_and_i16_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    not a3, a4
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    or a1, a1, a3
; RV64I-ZALRSC-NEXT:    amoand.w.aqrl a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_and_i16_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    not a3, a4
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    or a1, a1, a3
; RV64IA-NEXT:    amoand.w.aqrl a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw and ptr %a, i16 %b acq_rel
  ret i16 %1
}

define i16 @atomicrmw_and_i16_seq_cst(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_and_i16_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    not a3, a4
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    or a1, a1, a3
; RV64I-NEXT:    amoand.w.aqrl a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_and_i16_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    not a3, a4
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    or a1, a1, a3
; RV64I-ZALRSC-NEXT:    amoand.w.aqrl a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_and_i16_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    not a3, a4
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    or a1, a1, a3
; RV64IA-NEXT:    amoand.w.aqrl a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw and ptr %a, i16 %b seq_cst
  ret i16 %1
}

define i16 @atomicrmw_nand_i16_monotonic(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_nand_i16_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB95_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a3, (a2)
; RV64I-NEXT:    and a5, a3, a1
; RV64I-NEXT:    not a5, a5
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB95_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_nand_i16_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB95_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a3, (a2)
; RV64I-ZALRSC-NEXT:    and a5, a3, a1
; RV64I-ZALRSC-NEXT:    not a5, a5
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB95_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_nand_i16_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB95_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a3, (a2)
; RV64IA-NEXT:    and a5, a3, a1
; RV64IA-NEXT:    not a5, a5
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB95_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw nand ptr %a, i16 %b monotonic
  ret i16 %1
}

define i16 @atomicrmw_nand_i16_acquire(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_nand_i16_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB96_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a3, (a2)
; RV64I-NEXT:    and a5, a3, a1
; RV64I-NEXT:    not a5, a5
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB96_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_nand_i16_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB96_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a3, (a2)
; RV64I-ZALRSC-NEXT:    and a5, a3, a1
; RV64I-ZALRSC-NEXT:    not a5, a5
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB96_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_nand_i16_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB96_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a3, (a2)
; RV64IA-NEXT:    and a5, a3, a1
; RV64IA-NEXT:    not a5, a5
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB96_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw nand ptr %a, i16 %b acquire
  ret i16 %1
}

define i16 @atomicrmw_nand_i16_release(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_nand_i16_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB97_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a3, (a2)
; RV64I-NEXT:    and a5, a3, a1
; RV64I-NEXT:    not a5, a5
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB97_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_nand_i16_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB97_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a3, (a2)
; RV64I-ZALRSC-NEXT:    and a5, a3, a1
; RV64I-ZALRSC-NEXT:    not a5, a5
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB97_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_nand_i16_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB97_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a3, (a2)
; RV64IA-NEXT:    and a5, a3, a1
; RV64IA-NEXT:    not a5, a5
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB97_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw nand ptr %a, i16 %b release
  ret i16 %1
}

define i16 @atomicrmw_nand_i16_acq_rel(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_nand_i16_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB98_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a3, (a2)
; RV64I-NEXT:    and a5, a3, a1
; RV64I-NEXT:    not a5, a5
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB98_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_nand_i16_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB98_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a3, (a2)
; RV64I-ZALRSC-NEXT:    and a5, a3, a1
; RV64I-ZALRSC-NEXT:    not a5, a5
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB98_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_nand_i16_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB98_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a3, (a2)
; RV64IA-NEXT:    and a5, a3, a1
; RV64IA-NEXT:    not a5, a5
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB98_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw nand ptr %a, i16 %b acq_rel
  ret i16 %1
}

define i16 @atomicrmw_nand_i16_seq_cst(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_nand_i16_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB99_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aqrl a3, (a2)
; RV64I-NEXT:    and a5, a3, a1
; RV64I-NEXT:    not a5, a5
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB99_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_nand_i16_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB99_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aqrl a3, (a2)
; RV64I-ZALRSC-NEXT:    and a5, a3, a1
; RV64I-ZALRSC-NEXT:    not a5, a5
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB99_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_nand_i16_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB99_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aqrl a3, (a2)
; RV64IA-NEXT:    and a5, a3, a1
; RV64IA-NEXT:    not a5, a5
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB99_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw nand ptr %a, i16 %b seq_cst
  ret i16 %1
}

define i16 @atomicrmw_or_i16_monotonic(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_or_i16_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    slli a1, a1, 48
; RV64I-NEXT:    srli a1, a1, 48
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    amoor.w a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_or_i16_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    slli a1, a1, 48
; RV64I-ZALRSC-NEXT:    srli a1, a1, 48
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    amoor.w a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_or_i16_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    slli a1, a1, 48
; RV64IA-NEXT:    srli a1, a1, 48
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    amoor.w a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw or ptr %a, i16 %b monotonic
  ret i16 %1
}

define i16 @atomicrmw_or_i16_acquire(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_or_i16_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    slli a1, a1, 48
; RV64I-NEXT:    srli a1, a1, 48
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    amoor.w.aq a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_or_i16_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    slli a1, a1, 48
; RV64I-ZALRSC-NEXT:    srli a1, a1, 48
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    amoor.w.aq a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_or_i16_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    slli a1, a1, 48
; RV64IA-NEXT:    srli a1, a1, 48
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    amoor.w.aq a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw or ptr %a, i16 %b acquire
  ret i16 %1
}

define i16 @atomicrmw_or_i16_release(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_or_i16_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    slli a1, a1, 48
; RV64I-NEXT:    srli a1, a1, 48
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    amoor.w.rl a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_or_i16_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    slli a1, a1, 48
; RV64I-ZALRSC-NEXT:    srli a1, a1, 48
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    amoor.w.rl a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_or_i16_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    slli a1, a1, 48
; RV64IA-NEXT:    srli a1, a1, 48
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    amoor.w.rl a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw or ptr %a, i16 %b release
  ret i16 %1
}

define i16 @atomicrmw_or_i16_acq_rel(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_or_i16_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    slli a1, a1, 48
; RV64I-NEXT:    srli a1, a1, 48
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    amoor.w.aqrl a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_or_i16_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    slli a1, a1, 48
; RV64I-ZALRSC-NEXT:    srli a1, a1, 48
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    amoor.w.aqrl a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_or_i16_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    slli a1, a1, 48
; RV64IA-NEXT:    srli a1, a1, 48
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    amoor.w.aqrl a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw or ptr %a, i16 %b acq_rel
  ret i16 %1
}

define i16 @atomicrmw_or_i16_seq_cst(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_or_i16_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    slli a1, a1, 48
; RV64I-NEXT:    srli a1, a1, 48
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    amoor.w.aqrl a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_or_i16_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    slli a1, a1, 48
; RV64I-ZALRSC-NEXT:    srli a1, a1, 48
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    amoor.w.aqrl a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_or_i16_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    slli a1, a1, 48
; RV64IA-NEXT:    srli a1, a1, 48
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    amoor.w.aqrl a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw or ptr %a, i16 %b seq_cst
  ret i16 %1
}

define i16 @atomicrmw_xor_i16_monotonic(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xor_i16_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    slli a1, a1, 48
; RV64I-NEXT:    srli a1, a1, 48
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    amoxor.w a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xor_i16_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    slli a1, a1, 48
; RV64I-ZALRSC-NEXT:    srli a1, a1, 48
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    amoxor.w a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xor_i16_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    slli a1, a1, 48
; RV64IA-NEXT:    srli a1, a1, 48
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    amoxor.w a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xor ptr %a, i16 %b monotonic
  ret i16 %1
}

define i16 @atomicrmw_xor_i16_acquire(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xor_i16_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    slli a1, a1, 48
; RV64I-NEXT:    srli a1, a1, 48
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    amoxor.w.aq a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xor_i16_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    slli a1, a1, 48
; RV64I-ZALRSC-NEXT:    srli a1, a1, 48
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    amoxor.w.aq a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xor_i16_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    slli a1, a1, 48
; RV64IA-NEXT:    srli a1, a1, 48
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    amoxor.w.aq a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xor ptr %a, i16 %b acquire
  ret i16 %1
}

define i16 @atomicrmw_xor_i16_release(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xor_i16_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    slli a1, a1, 48
; RV64I-NEXT:    srli a1, a1, 48
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    amoxor.w.rl a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xor_i16_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    slli a1, a1, 48
; RV64I-ZALRSC-NEXT:    srli a1, a1, 48
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    amoxor.w.rl a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xor_i16_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    slli a1, a1, 48
; RV64IA-NEXT:    srli a1, a1, 48
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    amoxor.w.rl a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xor ptr %a, i16 %b release
  ret i16 %1
}

define i16 @atomicrmw_xor_i16_acq_rel(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xor_i16_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    slli a1, a1, 48
; RV64I-NEXT:    srli a1, a1, 48
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    amoxor.w.aqrl a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xor_i16_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    slli a1, a1, 48
; RV64I-ZALRSC-NEXT:    srli a1, a1, 48
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    amoxor.w.aqrl a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xor_i16_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    slli a1, a1, 48
; RV64IA-NEXT:    srli a1, a1, 48
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    amoxor.w.aqrl a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xor ptr %a, i16 %b acq_rel
  ret i16 %1
}

define i16 @atomicrmw_xor_i16_seq_cst(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xor_i16_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    slli a1, a1, 48
; RV64I-NEXT:    srli a1, a1, 48
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    amoxor.w.aqrl a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xor_i16_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    slli a1, a1, 48
; RV64I-ZALRSC-NEXT:    srli a1, a1, 48
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    amoxor.w.aqrl a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xor_i16_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    slli a1, a1, 48
; RV64IA-NEXT:    srli a1, a1, 48
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    amoxor.w.aqrl a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw xor ptr %a, i16 %b seq_cst
  ret i16 %1
}

define i16 @atomicrmw_max_i16_monotonic(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_max_i16_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    slli a1, a1, 48
; RV64I-NEXT:    li a4, 48
; RV64I-NEXT:    andi a5, a0, 24
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    srai a1, a1, 48
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    sub a4, a4, a5
; RV64I-NEXT:  .LBB110_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a5, (a2)
; RV64I-NEXT:    and a7, a5, a3
; RV64I-NEXT:    mv a6, a5
; RV64I-NEXT:    sll a7, a7, a4
; RV64I-NEXT:    sra a7, a7, a4
; RV64I-NEXT:    bge a7, a1, .LBB110_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB110_1 Depth=1
; RV64I-NEXT:    xor a6, a5, a1
; RV64I-NEXT:    and a6, a6, a3
; RV64I-NEXT:    xor a6, a5, a6
; RV64I-NEXT:  .LBB110_3: # in Loop: Header=BB110_1 Depth=1
; RV64I-NEXT:    sc.w a6, a6, (a2)
; RV64I-NEXT:    bnez a6, .LBB110_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a5, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_max_i16_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    slli a1, a1, 48
; RV64I-ZALRSC-NEXT:    li a4, 48
; RV64I-ZALRSC-NEXT:    andi a5, a0, 24
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    srai a1, a1, 48
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    sub a4, a4, a5
; RV64I-ZALRSC-NEXT:  .LBB110_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a5, (a2)
; RV64I-ZALRSC-NEXT:    and a7, a5, a3
; RV64I-ZALRSC-NEXT:    mv a6, a5
; RV64I-ZALRSC-NEXT:    sll a7, a7, a4
; RV64I-ZALRSC-NEXT:    sra a7, a7, a4
; RV64I-ZALRSC-NEXT:    bge a7, a1, .LBB110_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB110_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a6, a5, a1
; RV64I-ZALRSC-NEXT:    and a6, a6, a3
; RV64I-ZALRSC-NEXT:    xor a6, a5, a6
; RV64I-ZALRSC-NEXT:  .LBB110_3: # in Loop: Header=BB110_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w a6, a6, (a2)
; RV64I-ZALRSC-NEXT:    bnez a6, .LBB110_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a5, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_max_i16_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    slli a1, a1, 48
; RV64IA-NEXT:    li a4, 48
; RV64IA-NEXT:    andi a5, a0, 24
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    srai a1, a1, 48
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    sub a4, a4, a5
; RV64IA-NEXT:  .LBB110_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a5, (a2)
; RV64IA-NEXT:    and a7, a5, a3
; RV64IA-NEXT:    mv a6, a5
; RV64IA-NEXT:    sll a7, a7, a4
; RV64IA-NEXT:    sra a7, a7, a4
; RV64IA-NEXT:    bge a7, a1, .LBB110_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB110_1 Depth=1
; RV64IA-NEXT:    xor a6, a5, a1
; RV64IA-NEXT:    and a6, a6, a3
; RV64IA-NEXT:    xor a6, a5, a6
; RV64IA-NEXT:  .LBB110_3: # in Loop: Header=BB110_1 Depth=1
; RV64IA-NEXT:    sc.w a6, a6, (a2)
; RV64IA-NEXT:    bnez a6, .LBB110_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a5, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw max ptr %a, i16 %b monotonic
  ret i16 %1
}

define i16 @atomicrmw_max_i16_acquire(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_max_i16_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    slli a1, a1, 48
; RV64I-NEXT:    li a4, 48
; RV64I-NEXT:    andi a5, a0, 24
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    srai a1, a1, 48
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    sub a4, a4, a5
; RV64I-NEXT:  .LBB111_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a5, (a2)
; RV64I-NEXT:    and a7, a5, a3
; RV64I-NEXT:    mv a6, a5
; RV64I-NEXT:    sll a7, a7, a4
; RV64I-NEXT:    sra a7, a7, a4
; RV64I-NEXT:    bge a7, a1, .LBB111_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB111_1 Depth=1
; RV64I-NEXT:    xor a6, a5, a1
; RV64I-NEXT:    and a6, a6, a3
; RV64I-NEXT:    xor a6, a5, a6
; RV64I-NEXT:  .LBB111_3: # in Loop: Header=BB111_1 Depth=1
; RV64I-NEXT:    sc.w a6, a6, (a2)
; RV64I-NEXT:    bnez a6, .LBB111_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a5, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_max_i16_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    slli a1, a1, 48
; RV64I-ZALRSC-NEXT:    li a4, 48
; RV64I-ZALRSC-NEXT:    andi a5, a0, 24
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    srai a1, a1, 48
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    sub a4, a4, a5
; RV64I-ZALRSC-NEXT:  .LBB111_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a5, (a2)
; RV64I-ZALRSC-NEXT:    and a7, a5, a3
; RV64I-ZALRSC-NEXT:    mv a6, a5
; RV64I-ZALRSC-NEXT:    sll a7, a7, a4
; RV64I-ZALRSC-NEXT:    sra a7, a7, a4
; RV64I-ZALRSC-NEXT:    bge a7, a1, .LBB111_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB111_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a6, a5, a1
; RV64I-ZALRSC-NEXT:    and a6, a6, a3
; RV64I-ZALRSC-NEXT:    xor a6, a5, a6
; RV64I-ZALRSC-NEXT:  .LBB111_3: # in Loop: Header=BB111_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w a6, a6, (a2)
; RV64I-ZALRSC-NEXT:    bnez a6, .LBB111_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a5, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_max_i16_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    slli a1, a1, 48
; RV64IA-NEXT:    li a4, 48
; RV64IA-NEXT:    andi a5, a0, 24
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    srai a1, a1, 48
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    sub a4, a4, a5
; RV64IA-NEXT:  .LBB111_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a5, (a2)
; RV64IA-NEXT:    and a7, a5, a3
; RV64IA-NEXT:    mv a6, a5
; RV64IA-NEXT:    sll a7, a7, a4
; RV64IA-NEXT:    sra a7, a7, a4
; RV64IA-NEXT:    bge a7, a1, .LBB111_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB111_1 Depth=1
; RV64IA-NEXT:    xor a6, a5, a1
; RV64IA-NEXT:    and a6, a6, a3
; RV64IA-NEXT:    xor a6, a5, a6
; RV64IA-NEXT:  .LBB111_3: # in Loop: Header=BB111_1 Depth=1
; RV64IA-NEXT:    sc.w a6, a6, (a2)
; RV64IA-NEXT:    bnez a6, .LBB111_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a5, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw max ptr %a, i16 %b acquire
  ret i16 %1
}

define i16 @atomicrmw_max_i16_release(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_max_i16_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    slli a1, a1, 48
; RV64I-NEXT:    li a4, 48
; RV64I-NEXT:    andi a5, a0, 24
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    srai a1, a1, 48
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    sub a4, a4, a5
; RV64I-NEXT:  .LBB112_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a5, (a2)
; RV64I-NEXT:    and a7, a5, a3
; RV64I-NEXT:    mv a6, a5
; RV64I-NEXT:    sll a7, a7, a4
; RV64I-NEXT:    sra a7, a7, a4
; RV64I-NEXT:    bge a7, a1, .LBB112_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB112_1 Depth=1
; RV64I-NEXT:    xor a6, a5, a1
; RV64I-NEXT:    and a6, a6, a3
; RV64I-NEXT:    xor a6, a5, a6
; RV64I-NEXT:  .LBB112_3: # in Loop: Header=BB112_1 Depth=1
; RV64I-NEXT:    sc.w.rl a6, a6, (a2)
; RV64I-NEXT:    bnez a6, .LBB112_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a5, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_max_i16_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    slli a1, a1, 48
; RV64I-ZALRSC-NEXT:    li a4, 48
; RV64I-ZALRSC-NEXT:    andi a5, a0, 24
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    srai a1, a1, 48
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    sub a4, a4, a5
; RV64I-ZALRSC-NEXT:  .LBB112_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a5, (a2)
; RV64I-ZALRSC-NEXT:    and a7, a5, a3
; RV64I-ZALRSC-NEXT:    mv a6, a5
; RV64I-ZALRSC-NEXT:    sll a7, a7, a4
; RV64I-ZALRSC-NEXT:    sra a7, a7, a4
; RV64I-ZALRSC-NEXT:    bge a7, a1, .LBB112_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB112_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a6, a5, a1
; RV64I-ZALRSC-NEXT:    and a6, a6, a3
; RV64I-ZALRSC-NEXT:    xor a6, a5, a6
; RV64I-ZALRSC-NEXT:  .LBB112_3: # in Loop: Header=BB112_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w.rl a6, a6, (a2)
; RV64I-ZALRSC-NEXT:    bnez a6, .LBB112_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a5, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_max_i16_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    slli a1, a1, 48
; RV64IA-NEXT:    li a4, 48
; RV64IA-NEXT:    andi a5, a0, 24
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    srai a1, a1, 48
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    sub a4, a4, a5
; RV64IA-NEXT:  .LBB112_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a5, (a2)
; RV64IA-NEXT:    and a7, a5, a3
; RV64IA-NEXT:    mv a6, a5
; RV64IA-NEXT:    sll a7, a7, a4
; RV64IA-NEXT:    sra a7, a7, a4
; RV64IA-NEXT:    bge a7, a1, .LBB112_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB112_1 Depth=1
; RV64IA-NEXT:    xor a6, a5, a1
; RV64IA-NEXT:    and a6, a6, a3
; RV64IA-NEXT:    xor a6, a5, a6
; RV64IA-NEXT:  .LBB112_3: # in Loop: Header=BB112_1 Depth=1
; RV64IA-NEXT:    sc.w.rl a6, a6, (a2)
; RV64IA-NEXT:    bnez a6, .LBB112_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a5, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw max ptr %a, i16 %b release
  ret i16 %1
}

define i16 @atomicrmw_max_i16_acq_rel(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_max_i16_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    slli a1, a1, 48
; RV64I-NEXT:    li a4, 48
; RV64I-NEXT:    andi a5, a0, 24
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    srai a1, a1, 48
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    sub a4, a4, a5
; RV64I-NEXT:  .LBB113_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a5, (a2)
; RV64I-NEXT:    and a7, a5, a3
; RV64I-NEXT:    mv a6, a5
; RV64I-NEXT:    sll a7, a7, a4
; RV64I-NEXT:    sra a7, a7, a4
; RV64I-NEXT:    bge a7, a1, .LBB113_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB113_1 Depth=1
; RV64I-NEXT:    xor a6, a5, a1
; RV64I-NEXT:    and a6, a6, a3
; RV64I-NEXT:    xor a6, a5, a6
; RV64I-NEXT:  .LBB113_3: # in Loop: Header=BB113_1 Depth=1
; RV64I-NEXT:    sc.w.rl a6, a6, (a2)
; RV64I-NEXT:    bnez a6, .LBB113_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a5, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_max_i16_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    slli a1, a1, 48
; RV64I-ZALRSC-NEXT:    li a4, 48
; RV64I-ZALRSC-NEXT:    andi a5, a0, 24
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    srai a1, a1, 48
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    sub a4, a4, a5
; RV64I-ZALRSC-NEXT:  .LBB113_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a5, (a2)
; RV64I-ZALRSC-NEXT:    and a7, a5, a3
; RV64I-ZALRSC-NEXT:    mv a6, a5
; RV64I-ZALRSC-NEXT:    sll a7, a7, a4
; RV64I-ZALRSC-NEXT:    sra a7, a7, a4
; RV64I-ZALRSC-NEXT:    bge a7, a1, .LBB113_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB113_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a6, a5, a1
; RV64I-ZALRSC-NEXT:    and a6, a6, a3
; RV64I-ZALRSC-NEXT:    xor a6, a5, a6
; RV64I-ZALRSC-NEXT:  .LBB113_3: # in Loop: Header=BB113_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w.rl a6, a6, (a2)
; RV64I-ZALRSC-NEXT:    bnez a6, .LBB113_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a5, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_max_i16_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    slli a1, a1, 48
; RV64IA-NEXT:    li a4, 48
; RV64IA-NEXT:    andi a5, a0, 24
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    srai a1, a1, 48
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    sub a4, a4, a5
; RV64IA-NEXT:  .LBB113_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a5, (a2)
; RV64IA-NEXT:    and a7, a5, a3
; RV64IA-NEXT:    mv a6, a5
; RV64IA-NEXT:    sll a7, a7, a4
; RV64IA-NEXT:    sra a7, a7, a4
; RV64IA-NEXT:    bge a7, a1, .LBB113_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB113_1 Depth=1
; RV64IA-NEXT:    xor a6, a5, a1
; RV64IA-NEXT:    and a6, a6, a3
; RV64IA-NEXT:    xor a6, a5, a6
; RV64IA-NEXT:  .LBB113_3: # in Loop: Header=BB113_1 Depth=1
; RV64IA-NEXT:    sc.w.rl a6, a6, (a2)
; RV64IA-NEXT:    bnez a6, .LBB113_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a5, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw max ptr %a, i16 %b acq_rel
  ret i16 %1
}

define i16 @atomicrmw_max_i16_seq_cst(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_max_i16_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    slli a1, a1, 48
; RV64I-NEXT:    li a4, 48
; RV64I-NEXT:    andi a5, a0, 24
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    srai a1, a1, 48
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    sub a4, a4, a5
; RV64I-NEXT:  .LBB114_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aqrl a5, (a2)
; RV64I-NEXT:    and a7, a5, a3
; RV64I-NEXT:    mv a6, a5
; RV64I-NEXT:    sll a7, a7, a4
; RV64I-NEXT:    sra a7, a7, a4
; RV64I-NEXT:    bge a7, a1, .LBB114_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB114_1 Depth=1
; RV64I-NEXT:    xor a6, a5, a1
; RV64I-NEXT:    and a6, a6, a3
; RV64I-NEXT:    xor a6, a5, a6
; RV64I-NEXT:  .LBB114_3: # in Loop: Header=BB114_1 Depth=1
; RV64I-NEXT:    sc.w.rl a6, a6, (a2)
; RV64I-NEXT:    bnez a6, .LBB114_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a5, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_max_i16_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    slli a1, a1, 48
; RV64I-ZALRSC-NEXT:    li a4, 48
; RV64I-ZALRSC-NEXT:    andi a5, a0, 24
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    srai a1, a1, 48
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    sub a4, a4, a5
; RV64I-ZALRSC-NEXT:  .LBB114_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aqrl a5, (a2)
; RV64I-ZALRSC-NEXT:    and a7, a5, a3
; RV64I-ZALRSC-NEXT:    mv a6, a5
; RV64I-ZALRSC-NEXT:    sll a7, a7, a4
; RV64I-ZALRSC-NEXT:    sra a7, a7, a4
; RV64I-ZALRSC-NEXT:    bge a7, a1, .LBB114_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB114_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a6, a5, a1
; RV64I-ZALRSC-NEXT:    and a6, a6, a3
; RV64I-ZALRSC-NEXT:    xor a6, a5, a6
; RV64I-ZALRSC-NEXT:  .LBB114_3: # in Loop: Header=BB114_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w.rl a6, a6, (a2)
; RV64I-ZALRSC-NEXT:    bnez a6, .LBB114_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a5, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_max_i16_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    slli a1, a1, 48
; RV64IA-NEXT:    li a4, 48
; RV64IA-NEXT:    andi a5, a0, 24
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    srai a1, a1, 48
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    sub a4, a4, a5
; RV64IA-NEXT:  .LBB114_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aqrl a5, (a2)
; RV64IA-NEXT:    and a7, a5, a3
; RV64IA-NEXT:    mv a6, a5
; RV64IA-NEXT:    sll a7, a7, a4
; RV64IA-NEXT:    sra a7, a7, a4
; RV64IA-NEXT:    bge a7, a1, .LBB114_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB114_1 Depth=1
; RV64IA-NEXT:    xor a6, a5, a1
; RV64IA-NEXT:    and a6, a6, a3
; RV64IA-NEXT:    xor a6, a5, a6
; RV64IA-NEXT:  .LBB114_3: # in Loop: Header=BB114_1 Depth=1
; RV64IA-NEXT:    sc.w.rl a6, a6, (a2)
; RV64IA-NEXT:    bnez a6, .LBB114_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a5, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw max ptr %a, i16 %b seq_cst
  ret i16 %1
}

define i16 @atomicrmw_min_i16_monotonic(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_min_i16_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    slli a1, a1, 48
; RV64I-NEXT:    li a4, 48
; RV64I-NEXT:    andi a5, a0, 24
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    srai a1, a1, 48
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    sub a4, a4, a5
; RV64I-NEXT:  .LBB115_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a5, (a2)
; RV64I-NEXT:    and a7, a5, a3
; RV64I-NEXT:    mv a6, a5
; RV64I-NEXT:    sll a7, a7, a4
; RV64I-NEXT:    sra a7, a7, a4
; RV64I-NEXT:    bge a1, a7, .LBB115_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB115_1 Depth=1
; RV64I-NEXT:    xor a6, a5, a1
; RV64I-NEXT:    and a6, a6, a3
; RV64I-NEXT:    xor a6, a5, a6
; RV64I-NEXT:  .LBB115_3: # in Loop: Header=BB115_1 Depth=1
; RV64I-NEXT:    sc.w a6, a6, (a2)
; RV64I-NEXT:    bnez a6, .LBB115_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a5, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_min_i16_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    slli a1, a1, 48
; RV64I-ZALRSC-NEXT:    li a4, 48
; RV64I-ZALRSC-NEXT:    andi a5, a0, 24
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    srai a1, a1, 48
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    sub a4, a4, a5
; RV64I-ZALRSC-NEXT:  .LBB115_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a5, (a2)
; RV64I-ZALRSC-NEXT:    and a7, a5, a3
; RV64I-ZALRSC-NEXT:    mv a6, a5
; RV64I-ZALRSC-NEXT:    sll a7, a7, a4
; RV64I-ZALRSC-NEXT:    sra a7, a7, a4
; RV64I-ZALRSC-NEXT:    bge a1, a7, .LBB115_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB115_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a6, a5, a1
; RV64I-ZALRSC-NEXT:    and a6, a6, a3
; RV64I-ZALRSC-NEXT:    xor a6, a5, a6
; RV64I-ZALRSC-NEXT:  .LBB115_3: # in Loop: Header=BB115_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w a6, a6, (a2)
; RV64I-ZALRSC-NEXT:    bnez a6, .LBB115_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a5, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_min_i16_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    slli a1, a1, 48
; RV64IA-NEXT:    li a4, 48
; RV64IA-NEXT:    andi a5, a0, 24
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    srai a1, a1, 48
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    sub a4, a4, a5
; RV64IA-NEXT:  .LBB115_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a5, (a2)
; RV64IA-NEXT:    and a7, a5, a3
; RV64IA-NEXT:    mv a6, a5
; RV64IA-NEXT:    sll a7, a7, a4
; RV64IA-NEXT:    sra a7, a7, a4
; RV64IA-NEXT:    bge a1, a7, .LBB115_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB115_1 Depth=1
; RV64IA-NEXT:    xor a6, a5, a1
; RV64IA-NEXT:    and a6, a6, a3
; RV64IA-NEXT:    xor a6, a5, a6
; RV64IA-NEXT:  .LBB115_3: # in Loop: Header=BB115_1 Depth=1
; RV64IA-NEXT:    sc.w a6, a6, (a2)
; RV64IA-NEXT:    bnez a6, .LBB115_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a5, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw min ptr %a, i16 %b monotonic
  ret i16 %1
}

define i16 @atomicrmw_min_i16_acquire(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_min_i16_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    slli a1, a1, 48
; RV64I-NEXT:    li a4, 48
; RV64I-NEXT:    andi a5, a0, 24
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    srai a1, a1, 48
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    sub a4, a4, a5
; RV64I-NEXT:  .LBB116_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a5, (a2)
; RV64I-NEXT:    and a7, a5, a3
; RV64I-NEXT:    mv a6, a5
; RV64I-NEXT:    sll a7, a7, a4
; RV64I-NEXT:    sra a7, a7, a4
; RV64I-NEXT:    bge a1, a7, .LBB116_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB116_1 Depth=1
; RV64I-NEXT:    xor a6, a5, a1
; RV64I-NEXT:    and a6, a6, a3
; RV64I-NEXT:    xor a6, a5, a6
; RV64I-NEXT:  .LBB116_3: # in Loop: Header=BB116_1 Depth=1
; RV64I-NEXT:    sc.w a6, a6, (a2)
; RV64I-NEXT:    bnez a6, .LBB116_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a5, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_min_i16_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    slli a1, a1, 48
; RV64I-ZALRSC-NEXT:    li a4, 48
; RV64I-ZALRSC-NEXT:    andi a5, a0, 24
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    srai a1, a1, 48
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    sub a4, a4, a5
; RV64I-ZALRSC-NEXT:  .LBB116_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a5, (a2)
; RV64I-ZALRSC-NEXT:    and a7, a5, a3
; RV64I-ZALRSC-NEXT:    mv a6, a5
; RV64I-ZALRSC-NEXT:    sll a7, a7, a4
; RV64I-ZALRSC-NEXT:    sra a7, a7, a4
; RV64I-ZALRSC-NEXT:    bge a1, a7, .LBB116_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB116_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a6, a5, a1
; RV64I-ZALRSC-NEXT:    and a6, a6, a3
; RV64I-ZALRSC-NEXT:    xor a6, a5, a6
; RV64I-ZALRSC-NEXT:  .LBB116_3: # in Loop: Header=BB116_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w a6, a6, (a2)
; RV64I-ZALRSC-NEXT:    bnez a6, .LBB116_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a5, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_min_i16_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    slli a1, a1, 48
; RV64IA-NEXT:    li a4, 48
; RV64IA-NEXT:    andi a5, a0, 24
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    srai a1, a1, 48
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    sub a4, a4, a5
; RV64IA-NEXT:  .LBB116_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a5, (a2)
; RV64IA-NEXT:    and a7, a5, a3
; RV64IA-NEXT:    mv a6, a5
; RV64IA-NEXT:    sll a7, a7, a4
; RV64IA-NEXT:    sra a7, a7, a4
; RV64IA-NEXT:    bge a1, a7, .LBB116_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB116_1 Depth=1
; RV64IA-NEXT:    xor a6, a5, a1
; RV64IA-NEXT:    and a6, a6, a3
; RV64IA-NEXT:    xor a6, a5, a6
; RV64IA-NEXT:  .LBB116_3: # in Loop: Header=BB116_1 Depth=1
; RV64IA-NEXT:    sc.w a6, a6, (a2)
; RV64IA-NEXT:    bnez a6, .LBB116_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a5, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw min ptr %a, i16 %b acquire
  ret i16 %1
}

define i16 @atomicrmw_min_i16_release(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_min_i16_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    slli a1, a1, 48
; RV64I-NEXT:    li a4, 48
; RV64I-NEXT:    andi a5, a0, 24
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    srai a1, a1, 48
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    sub a4, a4, a5
; RV64I-NEXT:  .LBB117_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a5, (a2)
; RV64I-NEXT:    and a7, a5, a3
; RV64I-NEXT:    mv a6, a5
; RV64I-NEXT:    sll a7, a7, a4
; RV64I-NEXT:    sra a7, a7, a4
; RV64I-NEXT:    bge a1, a7, .LBB117_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB117_1 Depth=1
; RV64I-NEXT:    xor a6, a5, a1
; RV64I-NEXT:    and a6, a6, a3
; RV64I-NEXT:    xor a6, a5, a6
; RV64I-NEXT:  .LBB117_3: # in Loop: Header=BB117_1 Depth=1
; RV64I-NEXT:    sc.w.rl a6, a6, (a2)
; RV64I-NEXT:    bnez a6, .LBB117_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a5, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_min_i16_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    slli a1, a1, 48
; RV64I-ZALRSC-NEXT:    li a4, 48
; RV64I-ZALRSC-NEXT:    andi a5, a0, 24
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    srai a1, a1, 48
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    sub a4, a4, a5
; RV64I-ZALRSC-NEXT:  .LBB117_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a5, (a2)
; RV64I-ZALRSC-NEXT:    and a7, a5, a3
; RV64I-ZALRSC-NEXT:    mv a6, a5
; RV64I-ZALRSC-NEXT:    sll a7, a7, a4
; RV64I-ZALRSC-NEXT:    sra a7, a7, a4
; RV64I-ZALRSC-NEXT:    bge a1, a7, .LBB117_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB117_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a6, a5, a1
; RV64I-ZALRSC-NEXT:    and a6, a6, a3
; RV64I-ZALRSC-NEXT:    xor a6, a5, a6
; RV64I-ZALRSC-NEXT:  .LBB117_3: # in Loop: Header=BB117_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w.rl a6, a6, (a2)
; RV64I-ZALRSC-NEXT:    bnez a6, .LBB117_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a5, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_min_i16_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    slli a1, a1, 48
; RV64IA-NEXT:    li a4, 48
; RV64IA-NEXT:    andi a5, a0, 24
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    srai a1, a1, 48
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    sub a4, a4, a5
; RV64IA-NEXT:  .LBB117_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a5, (a2)
; RV64IA-NEXT:    and a7, a5, a3
; RV64IA-NEXT:    mv a6, a5
; RV64IA-NEXT:    sll a7, a7, a4
; RV64IA-NEXT:    sra a7, a7, a4
; RV64IA-NEXT:    bge a1, a7, .LBB117_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB117_1 Depth=1
; RV64IA-NEXT:    xor a6, a5, a1
; RV64IA-NEXT:    and a6, a6, a3
; RV64IA-NEXT:    xor a6, a5, a6
; RV64IA-NEXT:  .LBB117_3: # in Loop: Header=BB117_1 Depth=1
; RV64IA-NEXT:    sc.w.rl a6, a6, (a2)
; RV64IA-NEXT:    bnez a6, .LBB117_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a5, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw min ptr %a, i16 %b release
  ret i16 %1
}

define i16 @atomicrmw_min_i16_acq_rel(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_min_i16_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    slli a1, a1, 48
; RV64I-NEXT:    li a4, 48
; RV64I-NEXT:    andi a5, a0, 24
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    srai a1, a1, 48
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    sub a4, a4, a5
; RV64I-NEXT:  .LBB118_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a5, (a2)
; RV64I-NEXT:    and a7, a5, a3
; RV64I-NEXT:    mv a6, a5
; RV64I-NEXT:    sll a7, a7, a4
; RV64I-NEXT:    sra a7, a7, a4
; RV64I-NEXT:    bge a1, a7, .LBB118_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB118_1 Depth=1
; RV64I-NEXT:    xor a6, a5, a1
; RV64I-NEXT:    and a6, a6, a3
; RV64I-NEXT:    xor a6, a5, a6
; RV64I-NEXT:  .LBB118_3: # in Loop: Header=BB118_1 Depth=1
; RV64I-NEXT:    sc.w.rl a6, a6, (a2)
; RV64I-NEXT:    bnez a6, .LBB118_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a5, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_min_i16_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    slli a1, a1, 48
; RV64I-ZALRSC-NEXT:    li a4, 48
; RV64I-ZALRSC-NEXT:    andi a5, a0, 24
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    srai a1, a1, 48
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    sub a4, a4, a5
; RV64I-ZALRSC-NEXT:  .LBB118_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a5, (a2)
; RV64I-ZALRSC-NEXT:    and a7, a5, a3
; RV64I-ZALRSC-NEXT:    mv a6, a5
; RV64I-ZALRSC-NEXT:    sll a7, a7, a4
; RV64I-ZALRSC-NEXT:    sra a7, a7, a4
; RV64I-ZALRSC-NEXT:    bge a1, a7, .LBB118_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB118_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a6, a5, a1
; RV64I-ZALRSC-NEXT:    and a6, a6, a3
; RV64I-ZALRSC-NEXT:    xor a6, a5, a6
; RV64I-ZALRSC-NEXT:  .LBB118_3: # in Loop: Header=BB118_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w.rl a6, a6, (a2)
; RV64I-ZALRSC-NEXT:    bnez a6, .LBB118_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a5, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_min_i16_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    slli a1, a1, 48
; RV64IA-NEXT:    li a4, 48
; RV64IA-NEXT:    andi a5, a0, 24
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    srai a1, a1, 48
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    sub a4, a4, a5
; RV64IA-NEXT:  .LBB118_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a5, (a2)
; RV64IA-NEXT:    and a7, a5, a3
; RV64IA-NEXT:    mv a6, a5
; RV64IA-NEXT:    sll a7, a7, a4
; RV64IA-NEXT:    sra a7, a7, a4
; RV64IA-NEXT:    bge a1, a7, .LBB118_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB118_1 Depth=1
; RV64IA-NEXT:    xor a6, a5, a1
; RV64IA-NEXT:    and a6, a6, a3
; RV64IA-NEXT:    xor a6, a5, a6
; RV64IA-NEXT:  .LBB118_3: # in Loop: Header=BB118_1 Depth=1
; RV64IA-NEXT:    sc.w.rl a6, a6, (a2)
; RV64IA-NEXT:    bnez a6, .LBB118_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a5, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw min ptr %a, i16 %b acq_rel
  ret i16 %1
}

define i16 @atomicrmw_min_i16_seq_cst(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_min_i16_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    slli a1, a1, 48
; RV64I-NEXT:    li a4, 48
; RV64I-NEXT:    andi a5, a0, 24
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    srai a1, a1, 48
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    sub a4, a4, a5
; RV64I-NEXT:  .LBB119_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aqrl a5, (a2)
; RV64I-NEXT:    and a7, a5, a3
; RV64I-NEXT:    mv a6, a5
; RV64I-NEXT:    sll a7, a7, a4
; RV64I-NEXT:    sra a7, a7, a4
; RV64I-NEXT:    bge a1, a7, .LBB119_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB119_1 Depth=1
; RV64I-NEXT:    xor a6, a5, a1
; RV64I-NEXT:    and a6, a6, a3
; RV64I-NEXT:    xor a6, a5, a6
; RV64I-NEXT:  .LBB119_3: # in Loop: Header=BB119_1 Depth=1
; RV64I-NEXT:    sc.w.rl a6, a6, (a2)
; RV64I-NEXT:    bnez a6, .LBB119_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a5, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_min_i16_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    slli a1, a1, 48
; RV64I-ZALRSC-NEXT:    li a4, 48
; RV64I-ZALRSC-NEXT:    andi a5, a0, 24
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    srai a1, a1, 48
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    sub a4, a4, a5
; RV64I-ZALRSC-NEXT:  .LBB119_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aqrl a5, (a2)
; RV64I-ZALRSC-NEXT:    and a7, a5, a3
; RV64I-ZALRSC-NEXT:    mv a6, a5
; RV64I-ZALRSC-NEXT:    sll a7, a7, a4
; RV64I-ZALRSC-NEXT:    sra a7, a7, a4
; RV64I-ZALRSC-NEXT:    bge a1, a7, .LBB119_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB119_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a6, a5, a1
; RV64I-ZALRSC-NEXT:    and a6, a6, a3
; RV64I-ZALRSC-NEXT:    xor a6, a5, a6
; RV64I-ZALRSC-NEXT:  .LBB119_3: # in Loop: Header=BB119_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w.rl a6, a6, (a2)
; RV64I-ZALRSC-NEXT:    bnez a6, .LBB119_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a5, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_min_i16_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    slli a1, a1, 48
; RV64IA-NEXT:    li a4, 48
; RV64IA-NEXT:    andi a5, a0, 24
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    srai a1, a1, 48
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    sub a4, a4, a5
; RV64IA-NEXT:  .LBB119_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aqrl a5, (a2)
; RV64IA-NEXT:    and a7, a5, a3
; RV64IA-NEXT:    mv a6, a5
; RV64IA-NEXT:    sll a7, a7, a4
; RV64IA-NEXT:    sra a7, a7, a4
; RV64IA-NEXT:    bge a1, a7, .LBB119_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB119_1 Depth=1
; RV64IA-NEXT:    xor a6, a5, a1
; RV64IA-NEXT:    and a6, a6, a3
; RV64IA-NEXT:    xor a6, a5, a6
; RV64IA-NEXT:  .LBB119_3: # in Loop: Header=BB119_1 Depth=1
; RV64IA-NEXT:    sc.w.rl a6, a6, (a2)
; RV64IA-NEXT:    bnez a6, .LBB119_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a5, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw min ptr %a, i16 %b seq_cst
  ret i16 %1
}

define i16 @atomicrmw_umax_i16_monotonic(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_umax_i16_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB120_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a3, (a2)
; RV64I-NEXT:    and a6, a3, a4
; RV64I-NEXT:    mv a5, a3
; RV64I-NEXT:    bgeu a6, a1, .LBB120_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB120_1 Depth=1
; RV64I-NEXT:    xor a5, a3, a1
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:  .LBB120_3: # in Loop: Header=BB120_1 Depth=1
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB120_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umax_i16_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB120_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a3, (a2)
; RV64I-ZALRSC-NEXT:    and a6, a3, a4
; RV64I-ZALRSC-NEXT:    mv a5, a3
; RV64I-ZALRSC-NEXT:    bgeu a6, a1, .LBB120_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB120_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a5, a3, a1
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:  .LBB120_3: # in Loop: Header=BB120_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB120_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umax_i16_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB120_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a3, (a2)
; RV64IA-NEXT:    and a6, a3, a4
; RV64IA-NEXT:    mv a5, a3
; RV64IA-NEXT:    bgeu a6, a1, .LBB120_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB120_1 Depth=1
; RV64IA-NEXT:    xor a5, a3, a1
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:  .LBB120_3: # in Loop: Header=BB120_1 Depth=1
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB120_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw umax ptr %a, i16 %b monotonic
  ret i16 %1
}

define i16 @atomicrmw_umax_i16_acquire(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_umax_i16_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB121_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a3, (a2)
; RV64I-NEXT:    and a6, a3, a4
; RV64I-NEXT:    mv a5, a3
; RV64I-NEXT:    bgeu a6, a1, .LBB121_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB121_1 Depth=1
; RV64I-NEXT:    xor a5, a3, a1
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:  .LBB121_3: # in Loop: Header=BB121_1 Depth=1
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB121_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umax_i16_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB121_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a3, (a2)
; RV64I-ZALRSC-NEXT:    and a6, a3, a4
; RV64I-ZALRSC-NEXT:    mv a5, a3
; RV64I-ZALRSC-NEXT:    bgeu a6, a1, .LBB121_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB121_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a5, a3, a1
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:  .LBB121_3: # in Loop: Header=BB121_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB121_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umax_i16_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB121_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a3, (a2)
; RV64IA-NEXT:    and a6, a3, a4
; RV64IA-NEXT:    mv a5, a3
; RV64IA-NEXT:    bgeu a6, a1, .LBB121_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB121_1 Depth=1
; RV64IA-NEXT:    xor a5, a3, a1
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:  .LBB121_3: # in Loop: Header=BB121_1 Depth=1
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB121_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw umax ptr %a, i16 %b acquire
  ret i16 %1
}

define i16 @atomicrmw_umax_i16_release(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_umax_i16_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB122_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a3, (a2)
; RV64I-NEXT:    and a6, a3, a4
; RV64I-NEXT:    mv a5, a3
; RV64I-NEXT:    bgeu a6, a1, .LBB122_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB122_1 Depth=1
; RV64I-NEXT:    xor a5, a3, a1
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:  .LBB122_3: # in Loop: Header=BB122_1 Depth=1
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB122_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umax_i16_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB122_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a3, (a2)
; RV64I-ZALRSC-NEXT:    and a6, a3, a4
; RV64I-ZALRSC-NEXT:    mv a5, a3
; RV64I-ZALRSC-NEXT:    bgeu a6, a1, .LBB122_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB122_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a5, a3, a1
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:  .LBB122_3: # in Loop: Header=BB122_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB122_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umax_i16_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB122_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a3, (a2)
; RV64IA-NEXT:    and a6, a3, a4
; RV64IA-NEXT:    mv a5, a3
; RV64IA-NEXT:    bgeu a6, a1, .LBB122_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB122_1 Depth=1
; RV64IA-NEXT:    xor a5, a3, a1
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:  .LBB122_3: # in Loop: Header=BB122_1 Depth=1
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB122_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw umax ptr %a, i16 %b release
  ret i16 %1
}

define i16 @atomicrmw_umax_i16_acq_rel(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_umax_i16_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB123_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a3, (a2)
; RV64I-NEXT:    and a6, a3, a4
; RV64I-NEXT:    mv a5, a3
; RV64I-NEXT:    bgeu a6, a1, .LBB123_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB123_1 Depth=1
; RV64I-NEXT:    xor a5, a3, a1
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:  .LBB123_3: # in Loop: Header=BB123_1 Depth=1
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB123_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umax_i16_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB123_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a3, (a2)
; RV64I-ZALRSC-NEXT:    and a6, a3, a4
; RV64I-ZALRSC-NEXT:    mv a5, a3
; RV64I-ZALRSC-NEXT:    bgeu a6, a1, .LBB123_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB123_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a5, a3, a1
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:  .LBB123_3: # in Loop: Header=BB123_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB123_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umax_i16_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB123_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a3, (a2)
; RV64IA-NEXT:    and a6, a3, a4
; RV64IA-NEXT:    mv a5, a3
; RV64IA-NEXT:    bgeu a6, a1, .LBB123_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB123_1 Depth=1
; RV64IA-NEXT:    xor a5, a3, a1
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:  .LBB123_3: # in Loop: Header=BB123_1 Depth=1
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB123_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw umax ptr %a, i16 %b acq_rel
  ret i16 %1
}

define i16 @atomicrmw_umax_i16_seq_cst(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_umax_i16_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB124_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aqrl a3, (a2)
; RV64I-NEXT:    and a6, a3, a4
; RV64I-NEXT:    mv a5, a3
; RV64I-NEXT:    bgeu a6, a1, .LBB124_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB124_1 Depth=1
; RV64I-NEXT:    xor a5, a3, a1
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:  .LBB124_3: # in Loop: Header=BB124_1 Depth=1
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB124_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umax_i16_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB124_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aqrl a3, (a2)
; RV64I-ZALRSC-NEXT:    and a6, a3, a4
; RV64I-ZALRSC-NEXT:    mv a5, a3
; RV64I-ZALRSC-NEXT:    bgeu a6, a1, .LBB124_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB124_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a5, a3, a1
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:  .LBB124_3: # in Loop: Header=BB124_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB124_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umax_i16_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB124_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aqrl a3, (a2)
; RV64IA-NEXT:    and a6, a3, a4
; RV64IA-NEXT:    mv a5, a3
; RV64IA-NEXT:    bgeu a6, a1, .LBB124_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB124_1 Depth=1
; RV64IA-NEXT:    xor a5, a3, a1
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:  .LBB124_3: # in Loop: Header=BB124_1 Depth=1
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB124_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw umax ptr %a, i16 %b seq_cst
  ret i16 %1
}

define i16 @atomicrmw_umin_i16_monotonic(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_umin_i16_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB125_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a3, (a2)
; RV64I-NEXT:    and a6, a3, a4
; RV64I-NEXT:    mv a5, a3
; RV64I-NEXT:    bgeu a1, a6, .LBB125_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB125_1 Depth=1
; RV64I-NEXT:    xor a5, a3, a1
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:  .LBB125_3: # in Loop: Header=BB125_1 Depth=1
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB125_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umin_i16_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB125_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a3, (a2)
; RV64I-ZALRSC-NEXT:    and a6, a3, a4
; RV64I-ZALRSC-NEXT:    mv a5, a3
; RV64I-ZALRSC-NEXT:    bgeu a1, a6, .LBB125_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB125_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a5, a3, a1
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:  .LBB125_3: # in Loop: Header=BB125_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB125_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umin_i16_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB125_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a3, (a2)
; RV64IA-NEXT:    and a6, a3, a4
; RV64IA-NEXT:    mv a5, a3
; RV64IA-NEXT:    bgeu a1, a6, .LBB125_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB125_1 Depth=1
; RV64IA-NEXT:    xor a5, a3, a1
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:  .LBB125_3: # in Loop: Header=BB125_1 Depth=1
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB125_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw umin ptr %a, i16 %b monotonic
  ret i16 %1
}

define i16 @atomicrmw_umin_i16_acquire(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_umin_i16_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB126_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a3, (a2)
; RV64I-NEXT:    and a6, a3, a4
; RV64I-NEXT:    mv a5, a3
; RV64I-NEXT:    bgeu a1, a6, .LBB126_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB126_1 Depth=1
; RV64I-NEXT:    xor a5, a3, a1
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:  .LBB126_3: # in Loop: Header=BB126_1 Depth=1
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB126_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umin_i16_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB126_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a3, (a2)
; RV64I-ZALRSC-NEXT:    and a6, a3, a4
; RV64I-ZALRSC-NEXT:    mv a5, a3
; RV64I-ZALRSC-NEXT:    bgeu a1, a6, .LBB126_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB126_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a5, a3, a1
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:  .LBB126_3: # in Loop: Header=BB126_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB126_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umin_i16_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB126_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a3, (a2)
; RV64IA-NEXT:    and a6, a3, a4
; RV64IA-NEXT:    mv a5, a3
; RV64IA-NEXT:    bgeu a1, a6, .LBB126_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB126_1 Depth=1
; RV64IA-NEXT:    xor a5, a3, a1
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:  .LBB126_3: # in Loop: Header=BB126_1 Depth=1
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB126_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw umin ptr %a, i16 %b acquire
  ret i16 %1
}

define i16 @atomicrmw_umin_i16_release(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_umin_i16_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB127_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a3, (a2)
; RV64I-NEXT:    and a6, a3, a4
; RV64I-NEXT:    mv a5, a3
; RV64I-NEXT:    bgeu a1, a6, .LBB127_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB127_1 Depth=1
; RV64I-NEXT:    xor a5, a3, a1
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:  .LBB127_3: # in Loop: Header=BB127_1 Depth=1
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB127_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umin_i16_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB127_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a3, (a2)
; RV64I-ZALRSC-NEXT:    and a6, a3, a4
; RV64I-ZALRSC-NEXT:    mv a5, a3
; RV64I-ZALRSC-NEXT:    bgeu a1, a6, .LBB127_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB127_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a5, a3, a1
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:  .LBB127_3: # in Loop: Header=BB127_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB127_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umin_i16_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB127_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a3, (a2)
; RV64IA-NEXT:    and a6, a3, a4
; RV64IA-NEXT:    mv a5, a3
; RV64IA-NEXT:    bgeu a1, a6, .LBB127_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB127_1 Depth=1
; RV64IA-NEXT:    xor a5, a3, a1
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:  .LBB127_3: # in Loop: Header=BB127_1 Depth=1
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB127_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw umin ptr %a, i16 %b release
  ret i16 %1
}

define i16 @atomicrmw_umin_i16_acq_rel(ptr %a, i16 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_umin_i16_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB128_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a3, (a2)
; RV64I-NEXT:    and a6, a3, a4
; RV64I-NEXT:    mv a5, a3
; RV64I-NEXT:    bgeu a1, a6, .LBB128_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB128_1 Depth=1
; RV64I-NEXT:    xor a5, a3, a1
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:  .LBB128_3: # in Loop: Header=BB128_1 Depth=1
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB128_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umin_i16_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB128_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a3, (a2)
; RV64I-ZALRSC-NEXT:    and a6, a3, a4
; RV64I-ZALRSC-NEXT:    mv a5, a3
; RV64I-ZALRSC-NEXT:    bgeu a1, a6, .LBB128_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB128_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a5, a3, a1
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:  .LBB128_3: # in Loop: Header=BB128_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB128_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umin_i16_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB128_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a3, (a2)
; RV64IA-NEXT:    and a6, a3, a4
; RV64IA-NEXT:    mv a5, a3
; RV64IA-NEXT:    bgeu a1, a6, .LBB128_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB128_1 Depth=1
; RV64IA-NEXT:    xor a5, a3, a1
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:  .LBB128_3: # in Loop: Header=BB128_1 Depth=1
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB128_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw umin ptr %a, i16 %b acq_rel
  ret i16 %1
}

define i16 @atomicrmw_umin_i16_seq_cst(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_umin_i16_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB129_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aqrl a3, (a2)
; RV64I-NEXT:    and a6, a3, a4
; RV64I-NEXT:    mv a5, a3
; RV64I-NEXT:    bgeu a1, a6, .LBB129_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB129_1 Depth=1
; RV64I-NEXT:    xor a5, a3, a1
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:  .LBB129_3: # in Loop: Header=BB129_1 Depth=1
; RV64I-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB129_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umin_i16_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB129_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aqrl a3, (a2)
; RV64I-ZALRSC-NEXT:    and a6, a3, a4
; RV64I-ZALRSC-NEXT:    mv a5, a3
; RV64I-ZALRSC-NEXT:    bgeu a1, a6, .LBB129_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB129_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a5, a3, a1
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:  .LBB129_3: # in Loop: Header=BB129_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w.rl a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB129_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umin_i16_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB129_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aqrl a3, (a2)
; RV64IA-NEXT:    and a6, a3, a4
; RV64IA-NEXT:    mv a5, a3
; RV64IA-NEXT:    bgeu a1, a6, .LBB129_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB129_1 Depth=1
; RV64IA-NEXT:    xor a5, a3, a1
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:  .LBB129_3: # in Loop: Header=BB129_1 Depth=1
; RV64IA-NEXT:    sc.w.rl a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB129_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    ret
  %1 = atomicrmw umin ptr %a, i16 %b seq_cst
  ret i16 %1
}

define i32 @atomicrmw_xchg_i32_monotonic(ptr %a, i32 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xchg_i32_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoswap.w a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_i32_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoswap.w a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_i32_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoswap.w a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i32 %b monotonic
  ret i32 %1
}

define i32 @atomicrmw_xchg_i32_acquire(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xchg_i32_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoswap.w.aq a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_i32_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoswap.w.aq a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_i32_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoswap.w.aq a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i32 %b acquire
  ret i32 %1
}

define i32 @atomicrmw_xchg_i32_release(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xchg_i32_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoswap.w.rl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_i32_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoswap.w.rl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_i32_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoswap.w.rl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i32 %b release
  ret i32 %1
}

define i32 @atomicrmw_xchg_i32_acq_rel(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xchg_i32_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoswap.w.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_i32_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoswap.w.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_i32_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoswap.w.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i32 %b acq_rel
  ret i32 %1
}

define i32 @atomicrmw_xchg_i32_seq_cst(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xchg_i32_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoswap.w.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_i32_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoswap.w.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_i32_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoswap.w.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i32 %b seq_cst
  ret i32 %1
}

define i32 @atomicrmw_add_i32_monotonic(ptr %a, i32 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_add_i32_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoadd.w a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_add_i32_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoadd.w a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_add_i32_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoadd.w a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw add ptr %a, i32 %b monotonic
  ret i32 %1
}

define i32 @atomicrmw_add_i32_acquire(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_add_i32_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoadd.w.aq a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_add_i32_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoadd.w.aq a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_add_i32_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoadd.w.aq a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw add ptr %a, i32 %b acquire
  ret i32 %1
}

define i32 @atomicrmw_add_i32_release(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_add_i32_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoadd.w.rl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_add_i32_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoadd.w.rl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_add_i32_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoadd.w.rl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw add ptr %a, i32 %b release
  ret i32 %1
}

define i32 @atomicrmw_add_i32_acq_rel(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_add_i32_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoadd.w.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_add_i32_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoadd.w.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_add_i32_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoadd.w.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw add ptr %a, i32 %b acq_rel
  ret i32 %1
}

define i32 @atomicrmw_add_i32_seq_cst(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_add_i32_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoadd.w.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_add_i32_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoadd.w.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_add_i32_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoadd.w.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw add ptr %a, i32 %b seq_cst
  ret i32 %1
}

define i32 @atomicrmw_sub_i32_monotonic(ptr %a, i32 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_sub_i32_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    neg a1, a1
; RV64I-NEXT:    amoadd.w a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_sub_i32_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    neg a1, a1
; RV64I-ZALRSC-NEXT:    amoadd.w a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_sub_i32_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    neg a1, a1
; RV64IA-NEXT:    amoadd.w a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw sub ptr %a, i32 %b monotonic
  ret i32 %1
}

define i32 @atomicrmw_sub_i32_acquire(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_sub_i32_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    neg a1, a1
; RV64I-NEXT:    amoadd.w.aq a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_sub_i32_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    neg a1, a1
; RV64I-ZALRSC-NEXT:    amoadd.w.aq a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_sub_i32_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    neg a1, a1
; RV64IA-NEXT:    amoadd.w.aq a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw sub ptr %a, i32 %b acquire
  ret i32 %1
}

define i32 @atomicrmw_sub_i32_release(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_sub_i32_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    neg a1, a1
; RV64I-NEXT:    amoadd.w.rl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_sub_i32_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    neg a1, a1
; RV64I-ZALRSC-NEXT:    amoadd.w.rl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_sub_i32_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    neg a1, a1
; RV64IA-NEXT:    amoadd.w.rl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw sub ptr %a, i32 %b release
  ret i32 %1
}

define i32 @atomicrmw_sub_i32_acq_rel(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_sub_i32_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    neg a1, a1
; RV64I-NEXT:    amoadd.w.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_sub_i32_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    neg a1, a1
; RV64I-ZALRSC-NEXT:    amoadd.w.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_sub_i32_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    neg a1, a1
; RV64IA-NEXT:    amoadd.w.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw sub ptr %a, i32 %b acq_rel
  ret i32 %1
}

define i32 @atomicrmw_sub_i32_seq_cst(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_sub_i32_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    neg a1, a1
; RV64I-NEXT:    amoadd.w.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_sub_i32_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    neg a1, a1
; RV64I-ZALRSC-NEXT:    amoadd.w.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_sub_i32_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    neg a1, a1
; RV64IA-NEXT:    amoadd.w.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw sub ptr %a, i32 %b seq_cst
  ret i32 %1
}

define i32 @atomicrmw_and_i32_monotonic(ptr %a, i32 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_and_i32_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoand.w a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_and_i32_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoand.w a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_and_i32_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoand.w a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw and ptr %a, i32 %b monotonic
  ret i32 %1
}

define i32 @atomicrmw_and_i32_acquire(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_and_i32_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoand.w.aq a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_and_i32_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoand.w.aq a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_and_i32_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoand.w.aq a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw and ptr %a, i32 %b acquire
  ret i32 %1
}

define i32 @atomicrmw_and_i32_release(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_and_i32_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoand.w.rl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_and_i32_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoand.w.rl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_and_i32_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoand.w.rl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw and ptr %a, i32 %b release
  ret i32 %1
}

define i32 @atomicrmw_and_i32_acq_rel(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_and_i32_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoand.w.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_and_i32_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoand.w.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_and_i32_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoand.w.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw and ptr %a, i32 %b acq_rel
  ret i32 %1
}

define i32 @atomicrmw_and_i32_seq_cst(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_and_i32_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoand.w.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_and_i32_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoand.w.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_and_i32_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoand.w.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw and ptr %a, i32 %b seq_cst
  ret i32 %1
}

define i32 @atomicrmw_nand_i32_monotonic(ptr %a, i32 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_nand_i32_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:  .LBB150_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a2, (a0)
; RV64I-NEXT:    and a3, a2, a1
; RV64I-NEXT:    not a3, a3
; RV64I-NEXT:    sc.w a3, a3, (a0)
; RV64I-NEXT:    bnez a3, .LBB150_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    mv a0, a2
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_nand_i32_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:  .LBB150_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a2, (a0)
; RV64I-ZALRSC-NEXT:    and a3, a2, a1
; RV64I-ZALRSC-NEXT:    not a3, a3
; RV64I-ZALRSC-NEXT:    sc.w a3, a3, (a0)
; RV64I-ZALRSC-NEXT:    bnez a3, .LBB150_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    mv a0, a2
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_nand_i32_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:  .LBB150_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a2, (a0)
; RV64IA-NEXT:    and a3, a2, a1
; RV64IA-NEXT:    not a3, a3
; RV64IA-NEXT:    sc.w a3, a3, (a0)
; RV64IA-NEXT:    bnez a3, .LBB150_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    mv a0, a2
; RV64IA-NEXT:    ret
  %1 = atomicrmw nand ptr %a, i32 %b monotonic
  ret i32 %1
}

define i32 @atomicrmw_nand_i32_acquire(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_nand_i32_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:  .LBB151_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a2, (a0)
; RV64I-NEXT:    and a3, a2, a1
; RV64I-NEXT:    not a3, a3
; RV64I-NEXT:    sc.w a3, a3, (a0)
; RV64I-NEXT:    bnez a3, .LBB151_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    mv a0, a2
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_nand_i32_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:  .LBB151_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a2, (a0)
; RV64I-ZALRSC-NEXT:    and a3, a2, a1
; RV64I-ZALRSC-NEXT:    not a3, a3
; RV64I-ZALRSC-NEXT:    sc.w a3, a3, (a0)
; RV64I-ZALRSC-NEXT:    bnez a3, .LBB151_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    mv a0, a2
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_nand_i32_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:  .LBB151_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a2, (a0)
; RV64IA-NEXT:    and a3, a2, a1
; RV64IA-NEXT:    not a3, a3
; RV64IA-NEXT:    sc.w a3, a3, (a0)
; RV64IA-NEXT:    bnez a3, .LBB151_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    mv a0, a2
; RV64IA-NEXT:    ret
  %1 = atomicrmw nand ptr %a, i32 %b acquire
  ret i32 %1
}

define i32 @atomicrmw_nand_i32_release(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_nand_i32_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:  .LBB152_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a2, (a0)
; RV64I-NEXT:    and a3, a2, a1
; RV64I-NEXT:    not a3, a3
; RV64I-NEXT:    sc.w.rl a3, a3, (a0)
; RV64I-NEXT:    bnez a3, .LBB152_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    mv a0, a2
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_nand_i32_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:  .LBB152_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a2, (a0)
; RV64I-ZALRSC-NEXT:    and a3, a2, a1
; RV64I-ZALRSC-NEXT:    not a3, a3
; RV64I-ZALRSC-NEXT:    sc.w.rl a3, a3, (a0)
; RV64I-ZALRSC-NEXT:    bnez a3, .LBB152_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    mv a0, a2
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_nand_i32_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:  .LBB152_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a2, (a0)
; RV64IA-NEXT:    and a3, a2, a1
; RV64IA-NEXT:    not a3, a3
; RV64IA-NEXT:    sc.w.rl a3, a3, (a0)
; RV64IA-NEXT:    bnez a3, .LBB152_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    mv a0, a2
; RV64IA-NEXT:    ret
  %1 = atomicrmw nand ptr %a, i32 %b release
  ret i32 %1
}

define i32 @atomicrmw_nand_i32_acq_rel(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_nand_i32_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:  .LBB153_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aq a2, (a0)
; RV64I-NEXT:    and a3, a2, a1
; RV64I-NEXT:    not a3, a3
; RV64I-NEXT:    sc.w.rl a3, a3, (a0)
; RV64I-NEXT:    bnez a3, .LBB153_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    mv a0, a2
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_nand_i32_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:  .LBB153_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aq a2, (a0)
; RV64I-ZALRSC-NEXT:    and a3, a2, a1
; RV64I-ZALRSC-NEXT:    not a3, a3
; RV64I-ZALRSC-NEXT:    sc.w.rl a3, a3, (a0)
; RV64I-ZALRSC-NEXT:    bnez a3, .LBB153_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    mv a0, a2
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_nand_i32_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:  .LBB153_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aq a2, (a0)
; RV64IA-NEXT:    and a3, a2, a1
; RV64IA-NEXT:    not a3, a3
; RV64IA-NEXT:    sc.w.rl a3, a3, (a0)
; RV64IA-NEXT:    bnez a3, .LBB153_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    mv a0, a2
; RV64IA-NEXT:    ret
  %1 = atomicrmw nand ptr %a, i32 %b acq_rel
  ret i32 %1
}

define i32 @atomicrmw_nand_i32_seq_cst(ptr %a, i32 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_nand_i32_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:  .LBB154_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aqrl a2, (a0)
; RV64I-NEXT:    and a3, a2, a1
; RV64I-NEXT:    not a3, a3
; RV64I-NEXT:    sc.w.rl a3, a3, (a0)
; RV64I-NEXT:    bnez a3, .LBB154_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    mv a0, a2
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_nand_i32_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:  .LBB154_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aqrl a2, (a0)
; RV64I-ZALRSC-NEXT:    and a3, a2, a1
; RV64I-ZALRSC-NEXT:    not a3, a3
; RV64I-ZALRSC-NEXT:    sc.w.rl a3, a3, (a0)
; RV64I-ZALRSC-NEXT:    bnez a3, .LBB154_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    mv a0, a2
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_nand_i32_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:  .LBB154_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aqrl a2, (a0)
; RV64IA-NEXT:    and a3, a2, a1
; RV64IA-NEXT:    not a3, a3
; RV64IA-NEXT:    sc.w.rl a3, a3, (a0)
; RV64IA-NEXT:    bnez a3, .LBB154_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    mv a0, a2
; RV64IA-NEXT:    ret
  %1 = atomicrmw nand ptr %a, i32 %b seq_cst
  ret i32 %1
}

define i32 @atomicrmw_or_i32_monotonic(ptr %a, i32 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_or_i32_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoor.w a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_or_i32_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoor.w a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_or_i32_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoor.w a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw or ptr %a, i32 %b monotonic
  ret i32 %1
}

define i32 @atomicrmw_or_i32_acquire(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_or_i32_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoor.w.aq a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_or_i32_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoor.w.aq a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_or_i32_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoor.w.aq a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw or ptr %a, i32 %b acquire
  ret i32 %1
}

define i32 @atomicrmw_or_i32_release(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_or_i32_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoor.w.rl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_or_i32_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoor.w.rl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_or_i32_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoor.w.rl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw or ptr %a, i32 %b release
  ret i32 %1
}

define i32 @atomicrmw_or_i32_acq_rel(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_or_i32_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoor.w.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_or_i32_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoor.w.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_or_i32_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoor.w.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw or ptr %a, i32 %b acq_rel
  ret i32 %1
}

define i32 @atomicrmw_or_i32_seq_cst(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_or_i32_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoor.w.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_or_i32_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoor.w.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_or_i32_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoor.w.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw or ptr %a, i32 %b seq_cst
  ret i32 %1
}

define i32 @atomicrmw_xor_i32_monotonic(ptr %a, i32 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xor_i32_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoxor.w a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xor_i32_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoxor.w a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xor_i32_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoxor.w a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw xor ptr %a, i32 %b monotonic
  ret i32 %1
}

define i32 @atomicrmw_xor_i32_acquire(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xor_i32_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoxor.w.aq a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xor_i32_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoxor.w.aq a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xor_i32_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoxor.w.aq a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw xor ptr %a, i32 %b acquire
  ret i32 %1
}

define i32 @atomicrmw_xor_i32_release(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xor_i32_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoxor.w.rl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xor_i32_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoxor.w.rl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xor_i32_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoxor.w.rl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw xor ptr %a, i32 %b release
  ret i32 %1
}

define i32 @atomicrmw_xor_i32_acq_rel(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xor_i32_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoxor.w.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xor_i32_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoxor.w.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xor_i32_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoxor.w.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw xor ptr %a, i32 %b acq_rel
  ret i32 %1
}

define i32 @atomicrmw_xor_i32_seq_cst(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_xor_i32_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoxor.w.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xor_i32_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoxor.w.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xor_i32_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoxor.w.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw xor ptr %a, i32 %b seq_cst
  ret i32 %1
}

define i32 @atomicrmw_max_i32_monotonic(ptr %a, i32 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_max_i32_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomax.w a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_max_i32_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomax.w a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_max_i32_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomax.w a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw max ptr %a, i32 %b monotonic
  ret i32 %1
}

define i32 @atomicrmw_max_i32_acquire(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_max_i32_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomax.w.aq a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_max_i32_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomax.w.aq a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_max_i32_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomax.w.aq a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw max ptr %a, i32 %b acquire
  ret i32 %1
}

define i32 @atomicrmw_max_i32_release(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_max_i32_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomax.w.rl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_max_i32_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomax.w.rl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_max_i32_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomax.w.rl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw max ptr %a, i32 %b release
  ret i32 %1
}

define i32 @atomicrmw_max_i32_acq_rel(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_max_i32_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomax.w.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_max_i32_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomax.w.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_max_i32_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomax.w.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw max ptr %a, i32 %b acq_rel
  ret i32 %1
}

define i32 @atomicrmw_max_i32_seq_cst(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_max_i32_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomax.w.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_max_i32_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomax.w.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_max_i32_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomax.w.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw max ptr %a, i32 %b seq_cst
  ret i32 %1
}

define i32 @atomicrmw_min_i32_monotonic(ptr %a, i32 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_min_i32_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomin.w a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_min_i32_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomin.w a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_min_i32_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomin.w a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw min ptr %a, i32 %b monotonic
  ret i32 %1
}

define i32 @atomicrmw_min_i32_acquire(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_min_i32_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomin.w.aq a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_min_i32_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomin.w.aq a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_min_i32_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomin.w.aq a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw min ptr %a, i32 %b acquire
  ret i32 %1
}

define i32 @atomicrmw_min_i32_release(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_min_i32_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomin.w.rl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_min_i32_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomin.w.rl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_min_i32_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomin.w.rl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw min ptr %a, i32 %b release
  ret i32 %1
}

define i32 @atomicrmw_min_i32_acq_rel(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_min_i32_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomin.w.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_min_i32_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomin.w.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_min_i32_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomin.w.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw min ptr %a, i32 %b acq_rel
  ret i32 %1
}

define i32 @atomicrmw_min_i32_seq_cst(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_min_i32_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomin.w.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_min_i32_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomin.w.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_min_i32_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomin.w.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw min ptr %a, i32 %b seq_cst
  ret i32 %1
}

define i32 @atomicrmw_umax_i32_monotonic(ptr %a, i32 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_umax_i32_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomaxu.w a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umax_i32_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomaxu.w a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umax_i32_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomaxu.w a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw umax ptr %a, i32 %b monotonic
  ret i32 %1
}

define i32 @atomicrmw_umax_i32_acquire(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_umax_i32_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomaxu.w.aq a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umax_i32_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomaxu.w.aq a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umax_i32_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomaxu.w.aq a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw umax ptr %a, i32 %b acquire
  ret i32 %1
}

define i32 @atomicrmw_umax_i32_release(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_umax_i32_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomaxu.w.rl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umax_i32_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomaxu.w.rl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umax_i32_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomaxu.w.rl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw umax ptr %a, i32 %b release
  ret i32 %1
}

define i32 @atomicrmw_umax_i32_acq_rel(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_umax_i32_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomaxu.w.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umax_i32_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomaxu.w.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umax_i32_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomaxu.w.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw umax ptr %a, i32 %b acq_rel
  ret i32 %1
}

define i32 @atomicrmw_umax_i32_seq_cst(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_umax_i32_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomaxu.w.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umax_i32_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomaxu.w.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umax_i32_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomaxu.w.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw umax ptr %a, i32 %b seq_cst
  ret i32 %1
}

define i32 @atomicrmw_umin_i32_monotonic(ptr %a, i32 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_umin_i32_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amominu.w a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umin_i32_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amominu.w a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umin_i32_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amominu.w a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw umin ptr %a, i32 %b monotonic
  ret i32 %1
}

define i32 @atomicrmw_umin_i32_acquire(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_umin_i32_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amominu.w.aq a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umin_i32_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amominu.w.aq a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umin_i32_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amominu.w.aq a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw umin ptr %a, i32 %b acquire
  ret i32 %1
}

define i32 @atomicrmw_umin_i32_release(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_umin_i32_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amominu.w.rl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umin_i32_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amominu.w.rl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umin_i32_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amominu.w.rl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw umin ptr %a, i32 %b release
  ret i32 %1
}

define i32 @atomicrmw_umin_i32_acq_rel(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_umin_i32_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amominu.w.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umin_i32_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amominu.w.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umin_i32_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amominu.w.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw umin ptr %a, i32 %b acq_rel
  ret i32 %1
}

define i32 @atomicrmw_umin_i32_seq_cst(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_umin_i32_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amominu.w.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umin_i32_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amominu.w.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umin_i32_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amominu.w.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw umin ptr %a, i32 %b seq_cst
  ret i32 %1
}

define i64 @atomicrmw_xchg_i64_monotonic(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xchg_i64_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoswap.d a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_i64_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoswap.d a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_i64_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoswap.d a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i64 %b monotonic
  ret i64 %1
}

define i64 @atomicrmw_xchg_i64_acquire(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xchg_i64_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoswap.d.aq a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_i64_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoswap.d.aq a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_i64_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoswap.d.aq a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i64 %b acquire
  ret i64 %1
}

define i64 @atomicrmw_xchg_i64_release(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xchg_i64_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoswap.d.rl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_i64_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoswap.d.rl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_i64_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoswap.d.rl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i64 %b release
  ret i64 %1
}

define i64 @atomicrmw_xchg_i64_acq_rel(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xchg_i64_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoswap.d.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_i64_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoswap.d.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_i64_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoswap.d.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i64 %b acq_rel
  ret i64 %1
}

define i64 @atomicrmw_xchg_i64_seq_cst(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xchg_i64_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoswap.d.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_i64_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoswap.d.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_i64_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoswap.d.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i64 %b seq_cst
  ret i64 %1
}

define i64 @atomicrmw_add_i64_monotonic(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_add_i64_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoadd.d a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_add_i64_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoadd.d a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_add_i64_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoadd.d a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw add ptr %a, i64 %b monotonic
  ret i64 %1
}

define i64 @atomicrmw_add_i64_acquire(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_add_i64_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoadd.d.aq a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_add_i64_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoadd.d.aq a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_add_i64_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoadd.d.aq a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw add ptr %a, i64 %b acquire
  ret i64 %1
}

define i64 @atomicrmw_add_i64_release(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_add_i64_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoadd.d.rl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_add_i64_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoadd.d.rl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_add_i64_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoadd.d.rl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw add ptr %a, i64 %b release
  ret i64 %1
}

define i64 @atomicrmw_add_i64_acq_rel(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_add_i64_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoadd.d.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_add_i64_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoadd.d.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_add_i64_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoadd.d.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw add ptr %a, i64 %b acq_rel
  ret i64 %1
}

define i64 @atomicrmw_add_i64_seq_cst(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_add_i64_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoadd.d.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_add_i64_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoadd.d.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_add_i64_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoadd.d.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw add ptr %a, i64 %b seq_cst
  ret i64 %1
}

define i64 @atomicrmw_sub_i64_monotonic(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_sub_i64_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    neg a1, a1
; RV64I-NEXT:    amoadd.d a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_sub_i64_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    neg a1, a1
; RV64I-ZALRSC-NEXT:    amoadd.d a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_sub_i64_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    neg a1, a1
; RV64IA-NEXT:    amoadd.d a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw sub ptr %a, i64 %b monotonic
  ret i64 %1
}

define i64 @atomicrmw_sub_i64_acquire(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_sub_i64_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    neg a1, a1
; RV64I-NEXT:    amoadd.d.aq a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_sub_i64_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    neg a1, a1
; RV64I-ZALRSC-NEXT:    amoadd.d.aq a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_sub_i64_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    neg a1, a1
; RV64IA-NEXT:    amoadd.d.aq a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw sub ptr %a, i64 %b acquire
  ret i64 %1
}

define i64 @atomicrmw_sub_i64_release(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_sub_i64_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    neg a1, a1
; RV64I-NEXT:    amoadd.d.rl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_sub_i64_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    neg a1, a1
; RV64I-ZALRSC-NEXT:    amoadd.d.rl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_sub_i64_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    neg a1, a1
; RV64IA-NEXT:    amoadd.d.rl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw sub ptr %a, i64 %b release
  ret i64 %1
}

define i64 @atomicrmw_sub_i64_acq_rel(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_sub_i64_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    neg a1, a1
; RV64I-NEXT:    amoadd.d.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_sub_i64_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    neg a1, a1
; RV64I-ZALRSC-NEXT:    amoadd.d.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_sub_i64_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    neg a1, a1
; RV64IA-NEXT:    amoadd.d.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw sub ptr %a, i64 %b acq_rel
  ret i64 %1
}

define i64 @atomicrmw_sub_i64_seq_cst(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_sub_i64_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    neg a1, a1
; RV64I-NEXT:    amoadd.d.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_sub_i64_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    neg a1, a1
; RV64I-ZALRSC-NEXT:    amoadd.d.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_sub_i64_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    neg a1, a1
; RV64IA-NEXT:    amoadd.d.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw sub ptr %a, i64 %b seq_cst
  ret i64 %1
}

define i64 @atomicrmw_and_i64_monotonic(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_and_i64_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoand.d a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_and_i64_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoand.d a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_and_i64_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoand.d a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw and ptr %a, i64 %b monotonic
  ret i64 %1
}

define i64 @atomicrmw_and_i64_acquire(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_and_i64_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoand.d.aq a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_and_i64_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoand.d.aq a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_and_i64_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoand.d.aq a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw and ptr %a, i64 %b acquire
  ret i64 %1
}

define i64 @atomicrmw_and_i64_release(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_and_i64_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoand.d.rl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_and_i64_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoand.d.rl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_and_i64_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoand.d.rl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw and ptr %a, i64 %b release
  ret i64 %1
}

define i64 @atomicrmw_and_i64_acq_rel(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_and_i64_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoand.d.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_and_i64_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoand.d.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_and_i64_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoand.d.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw and ptr %a, i64 %b acq_rel
  ret i64 %1
}

define i64 @atomicrmw_and_i64_seq_cst(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_and_i64_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoand.d.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_and_i64_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoand.d.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_and_i64_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoand.d.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw and ptr %a, i64 %b seq_cst
  ret i64 %1
}

define i64 @atomicrmw_nand_i64_monotonic(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_nand_i64_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:  .LBB205_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.d a2, (a0)
; RV64I-NEXT:    and a3, a2, a1
; RV64I-NEXT:    not a3, a3
; RV64I-NEXT:    sc.d a3, a3, (a0)
; RV64I-NEXT:    bnez a3, .LBB205_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    mv a0, a2
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_nand_i64_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:  .LBB205_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.d a2, (a0)
; RV64I-ZALRSC-NEXT:    and a3, a2, a1
; RV64I-ZALRSC-NEXT:    not a3, a3
; RV64I-ZALRSC-NEXT:    sc.d a3, a3, (a0)
; RV64I-ZALRSC-NEXT:    bnez a3, .LBB205_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    mv a0, a2
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_nand_i64_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:  .LBB205_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.d a2, (a0)
; RV64IA-NEXT:    and a3, a2, a1
; RV64IA-NEXT:    not a3, a3
; RV64IA-NEXT:    sc.d a3, a3, (a0)
; RV64IA-NEXT:    bnez a3, .LBB205_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    mv a0, a2
; RV64IA-NEXT:    ret
  %1 = atomicrmw nand ptr %a, i64 %b monotonic
  ret i64 %1
}

define i64 @atomicrmw_nand_i64_acquire(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_nand_i64_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:  .LBB206_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.d.aq a2, (a0)
; RV64I-NEXT:    and a3, a2, a1
; RV64I-NEXT:    not a3, a3
; RV64I-NEXT:    sc.d a3, a3, (a0)
; RV64I-NEXT:    bnez a3, .LBB206_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    mv a0, a2
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_nand_i64_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:  .LBB206_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.d.aq a2, (a0)
; RV64I-ZALRSC-NEXT:    and a3, a2, a1
; RV64I-ZALRSC-NEXT:    not a3, a3
; RV64I-ZALRSC-NEXT:    sc.d a3, a3, (a0)
; RV64I-ZALRSC-NEXT:    bnez a3, .LBB206_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    mv a0, a2
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_nand_i64_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:  .LBB206_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.d.aq a2, (a0)
; RV64IA-NEXT:    and a3, a2, a1
; RV64IA-NEXT:    not a3, a3
; RV64IA-NEXT:    sc.d a3, a3, (a0)
; RV64IA-NEXT:    bnez a3, .LBB206_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    mv a0, a2
; RV64IA-NEXT:    ret
  %1 = atomicrmw nand ptr %a, i64 %b acquire
  ret i64 %1
}

define i64 @atomicrmw_nand_i64_release(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_nand_i64_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:  .LBB207_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.d a2, (a0)
; RV64I-NEXT:    and a3, a2, a1
; RV64I-NEXT:    not a3, a3
; RV64I-NEXT:    sc.d.rl a3, a3, (a0)
; RV64I-NEXT:    bnez a3, .LBB207_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    mv a0, a2
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_nand_i64_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:  .LBB207_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.d a2, (a0)
; RV64I-ZALRSC-NEXT:    and a3, a2, a1
; RV64I-ZALRSC-NEXT:    not a3, a3
; RV64I-ZALRSC-NEXT:    sc.d.rl a3, a3, (a0)
; RV64I-ZALRSC-NEXT:    bnez a3, .LBB207_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    mv a0, a2
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_nand_i64_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:  .LBB207_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.d a2, (a0)
; RV64IA-NEXT:    and a3, a2, a1
; RV64IA-NEXT:    not a3, a3
; RV64IA-NEXT:    sc.d.rl a3, a3, (a0)
; RV64IA-NEXT:    bnez a3, .LBB207_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    mv a0, a2
; RV64IA-NEXT:    ret
  %1 = atomicrmw nand ptr %a, i64 %b release
  ret i64 %1
}

define i64 @atomicrmw_nand_i64_acq_rel(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_nand_i64_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:  .LBB208_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.d.aq a2, (a0)
; RV64I-NEXT:    and a3, a2, a1
; RV64I-NEXT:    not a3, a3
; RV64I-NEXT:    sc.d.rl a3, a3, (a0)
; RV64I-NEXT:    bnez a3, .LBB208_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    mv a0, a2
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_nand_i64_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:  .LBB208_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.d.aq a2, (a0)
; RV64I-ZALRSC-NEXT:    and a3, a2, a1
; RV64I-ZALRSC-NEXT:    not a3, a3
; RV64I-ZALRSC-NEXT:    sc.d.rl a3, a3, (a0)
; RV64I-ZALRSC-NEXT:    bnez a3, .LBB208_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    mv a0, a2
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_nand_i64_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:  .LBB208_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.d.aq a2, (a0)
; RV64IA-NEXT:    and a3, a2, a1
; RV64IA-NEXT:    not a3, a3
; RV64IA-NEXT:    sc.d.rl a3, a3, (a0)
; RV64IA-NEXT:    bnez a3, .LBB208_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    mv a0, a2
; RV64IA-NEXT:    ret
  %1 = atomicrmw nand ptr %a, i64 %b acq_rel
  ret i64 %1
}

define i64 @atomicrmw_nand_i64_seq_cst(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_nand_i64_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:  .LBB209_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.d.aqrl a2, (a0)
; RV64I-NEXT:    and a3, a2, a1
; RV64I-NEXT:    not a3, a3
; RV64I-NEXT:    sc.d.rl a3, a3, (a0)
; RV64I-NEXT:    bnez a3, .LBB209_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    mv a0, a2
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_nand_i64_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:  .LBB209_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.d.aqrl a2, (a0)
; RV64I-ZALRSC-NEXT:    and a3, a2, a1
; RV64I-ZALRSC-NEXT:    not a3, a3
; RV64I-ZALRSC-NEXT:    sc.d.rl a3, a3, (a0)
; RV64I-ZALRSC-NEXT:    bnez a3, .LBB209_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    mv a0, a2
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_nand_i64_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:  .LBB209_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.d.aqrl a2, (a0)
; RV64IA-NEXT:    and a3, a2, a1
; RV64IA-NEXT:    not a3, a3
; RV64IA-NEXT:    sc.d.rl a3, a3, (a0)
; RV64IA-NEXT:    bnez a3, .LBB209_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    mv a0, a2
; RV64IA-NEXT:    ret
  %1 = atomicrmw nand ptr %a, i64 %b seq_cst
  ret i64 %1
}

define i64 @atomicrmw_or_i64_monotonic(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_or_i64_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoor.d a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_or_i64_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoor.d a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_or_i64_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoor.d a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw or ptr %a, i64 %b monotonic
  ret i64 %1
}

define i64 @atomicrmw_or_i64_acquire(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_or_i64_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoor.d.aq a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_or_i64_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoor.d.aq a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_or_i64_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoor.d.aq a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw or ptr %a, i64 %b acquire
  ret i64 %1
}

define i64 @atomicrmw_or_i64_release(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_or_i64_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoor.d.rl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_or_i64_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoor.d.rl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_or_i64_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoor.d.rl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw or ptr %a, i64 %b release
  ret i64 %1
}

define i64 @atomicrmw_or_i64_acq_rel(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_or_i64_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoor.d.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_or_i64_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoor.d.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_or_i64_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoor.d.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw or ptr %a, i64 %b acq_rel
  ret i64 %1
}

define i64 @atomicrmw_or_i64_seq_cst(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_or_i64_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoor.d.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_or_i64_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoor.d.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_or_i64_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoor.d.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw or ptr %a, i64 %b seq_cst
  ret i64 %1
}

define i64 @atomicrmw_xor_i64_monotonic(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xor_i64_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoxor.d a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xor_i64_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoxor.d a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xor_i64_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoxor.d a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw xor ptr %a, i64 %b monotonic
  ret i64 %1
}

define i64 @atomicrmw_xor_i64_acquire(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xor_i64_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoxor.d.aq a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xor_i64_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoxor.d.aq a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xor_i64_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoxor.d.aq a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw xor ptr %a, i64 %b acquire
  ret i64 %1
}

define i64 @atomicrmw_xor_i64_release(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xor_i64_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoxor.d.rl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xor_i64_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoxor.d.rl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xor_i64_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoxor.d.rl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw xor ptr %a, i64 %b release
  ret i64 %1
}

define i64 @atomicrmw_xor_i64_acq_rel(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xor_i64_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoxor.d.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xor_i64_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoxor.d.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xor_i64_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoxor.d.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw xor ptr %a, i64 %b acq_rel
  ret i64 %1
}

define i64 @atomicrmw_xor_i64_seq_cst(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xor_i64_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoxor.d.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xor_i64_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoxor.d.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xor_i64_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoxor.d.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw xor ptr %a, i64 %b seq_cst
  ret i64 %1
}

define i64 @atomicrmw_max_i64_monotonic(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_max_i64_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomax.d a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_max_i64_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomax.d a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_max_i64_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomax.d a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw max ptr %a, i64 %b monotonic
  ret i64 %1
}

define i64 @atomicrmw_max_i64_acquire(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_max_i64_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomax.d.aq a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_max_i64_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomax.d.aq a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_max_i64_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomax.d.aq a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw max ptr %a, i64 %b acquire
  ret i64 %1
}

define i64 @atomicrmw_max_i64_release(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_max_i64_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomax.d.rl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_max_i64_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomax.d.rl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_max_i64_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomax.d.rl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw max ptr %a, i64 %b release
  ret i64 %1
}

define i64 @atomicrmw_max_i64_acq_rel(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_max_i64_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomax.d.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_max_i64_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomax.d.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_max_i64_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomax.d.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw max ptr %a, i64 %b acq_rel
  ret i64 %1
}

define i64 @atomicrmw_max_i64_seq_cst(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_max_i64_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomax.d.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_max_i64_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomax.d.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_max_i64_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomax.d.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw max ptr %a, i64 %b seq_cst
  ret i64 %1
}

define i64 @atomicrmw_min_i64_monotonic(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_min_i64_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomin.d a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_min_i64_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomin.d a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_min_i64_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomin.d a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw min ptr %a, i64 %b monotonic
  ret i64 %1
}

define i64 @atomicrmw_min_i64_acquire(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_min_i64_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomin.d.aq a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_min_i64_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomin.d.aq a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_min_i64_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomin.d.aq a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw min ptr %a, i64 %b acquire
  ret i64 %1
}

define i64 @atomicrmw_min_i64_release(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_min_i64_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomin.d.rl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_min_i64_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomin.d.rl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_min_i64_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomin.d.rl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw min ptr %a, i64 %b release
  ret i64 %1
}

define i64 @atomicrmw_min_i64_acq_rel(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_min_i64_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomin.d.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_min_i64_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomin.d.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_min_i64_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomin.d.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw min ptr %a, i64 %b acq_rel
  ret i64 %1
}

define i64 @atomicrmw_min_i64_seq_cst(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_min_i64_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomin.d.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_min_i64_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomin.d.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_min_i64_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomin.d.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw min ptr %a, i64 %b seq_cst
  ret i64 %1
}

define i64 @atomicrmw_umax_i64_monotonic(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_umax_i64_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomaxu.d a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umax_i64_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomaxu.d a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umax_i64_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomaxu.d a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw umax ptr %a, i64 %b monotonic
  ret i64 %1
}

define i64 @atomicrmw_umax_i64_acquire(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_umax_i64_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomaxu.d.aq a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umax_i64_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomaxu.d.aq a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umax_i64_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomaxu.d.aq a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw umax ptr %a, i64 %b acquire
  ret i64 %1
}

define i64 @atomicrmw_umax_i64_release(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_umax_i64_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomaxu.d.rl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umax_i64_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomaxu.d.rl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umax_i64_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomaxu.d.rl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw umax ptr %a, i64 %b release
  ret i64 %1
}

define i64 @atomicrmw_umax_i64_acq_rel(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_umax_i64_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomaxu.d.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umax_i64_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomaxu.d.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umax_i64_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomaxu.d.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw umax ptr %a, i64 %b acq_rel
  ret i64 %1
}

define i64 @atomicrmw_umax_i64_seq_cst(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_umax_i64_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomaxu.d.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umax_i64_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomaxu.d.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umax_i64_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomaxu.d.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw umax ptr %a, i64 %b seq_cst
  ret i64 %1
}

define i64 @atomicrmw_umin_i64_monotonic(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_umin_i64_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amominu.d a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umin_i64_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amominu.d a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umin_i64_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amominu.d a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw umin ptr %a, i64 %b monotonic
  ret i64 %1
}

define i64 @atomicrmw_umin_i64_acquire(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_umin_i64_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amominu.d.aq a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umin_i64_acquire:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amominu.d.aq a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umin_i64_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amominu.d.aq a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw umin ptr %a, i64 %b acquire
  ret i64 %1
}

define i64 @atomicrmw_umin_i64_release(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_umin_i64_release:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amominu.d.rl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umin_i64_release:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amominu.d.rl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umin_i64_release:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amominu.d.rl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw umin ptr %a, i64 %b release
  ret i64 %1
}

define i64 @atomicrmw_umin_i64_acq_rel(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_umin_i64_acq_rel:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amominu.d.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umin_i64_acq_rel:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amominu.d.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umin_i64_acq_rel:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amominu.d.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw umin ptr %a, i64 %b acq_rel
  ret i64 %1
}

define i64 @atomicrmw_umin_i64_seq_cst(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_umin_i64_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amominu.d.aqrl a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umin_i64_seq_cst:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amominu.d.aqrl a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umin_i64_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amominu.d.aqrl a0, a1, (a0)
; RV64IA-NEXT:    ret
  %1 = atomicrmw umin ptr %a, i64 %b seq_cst
  ret i64 %1
}
