; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ysx64 -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV64I %s



; RUN: llc -mtriple=ysx64 -mattr=+a -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefixes=RV64IA %s



define zeroext i1 @atomic_load_i1_unordered(ptr %a) nounwind {
;
;
; RV64I-LABEL: atomic_load_i1_unordered:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lb a0, 0(a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i1_unordered:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    lb a0, 0(a0)
; RV64IA-NEXT:    ret
  %1 = load atomic i8, ptr %a unordered, align 1, !range !0, !noundef !1
  %2 = trunc nuw i8 %1 to i1
  ret i1 %2
}

define zeroext i1 @atomic_load_i1_monotonic(ptr %a) nounwind {
;
;
; RV64I-LABEL: atomic_load_i1_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lb a0, 0(a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i1_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    lb a0, 0(a0)
; RV64IA-NEXT:    ret
  %1 = load atomic i8, ptr %a monotonic, align 1, !range !0, !noundef !1
  %2 = trunc nuw i8 %1 to i1
  ret i1 %2
}

define zeroext i1 @atomic_load_i1_acquire(ptr %a) nounwind {
;
;
;
; RV64I-LABEL: atomic_load_i1_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lb a0, 0(a0)
; RV64I-NEXT:    fence r, rw
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i1_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    lb a0, 0(a0)
; RV64IA-NEXT:    fence r, rw
; RV64IA-NEXT:    ret
  %1 = load atomic i8, ptr %a acquire, align 1, !range !0, !noundef !1
  %2 = trunc nuw i8 %1 to i1
  ret i1 %2
}

define zeroext i1 @atomic_load_i1_seq_cst(ptr %a) nounwind {
;
;
;
; RV64I-LABEL: atomic_load_i1_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    fence rw, rw
; RV64I-NEXT:    lb a0, 0(a0)
; RV64I-NEXT:    fence r, rw
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i1_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    fence rw, rw
; RV64IA-NEXT:    lb a0, 0(a0)
; RV64IA-NEXT:    fence r, rw
; RV64IA-NEXT:    ret
  %1 = load atomic i8, ptr %a seq_cst, align 1, !range !0, !noundef !1
  %2 = trunc nuw i8 %1 to i1
  ret i1 %2
}

define zeroext i8 @atomic_load_i8_unordered(ptr %a) nounwind {
;
;
; RV64I-LABEL: atomic_load_i8_unordered:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lb a0, 0(a0)
; RV64I-NEXT:    zext.b a0, a0
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i8_unordered:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    lb a0, 0(a0)
; RV64IA-NEXT:    zext.b a0, a0
; RV64IA-NEXT:    ret
  %1 = load atomic i8, ptr %a unordered, align 1
  ret i8 %1
}

define zeroext i8 @atomic_load_i8_monotonic(ptr %a) nounwind {
;
;
; RV64I-LABEL: atomic_load_i8_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lb a0, 0(a0)
; RV64I-NEXT:    zext.b a0, a0
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i8_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    lb a0, 0(a0)
; RV64IA-NEXT:    zext.b a0, a0
; RV64IA-NEXT:    ret
  %1 = load atomic i8, ptr %a monotonic, align 1
  ret i8 %1
}

define zeroext i8 @atomic_load_i8_acquire(ptr %a) nounwind {
;
;
;
; RV64I-LABEL: atomic_load_i8_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lb a0, 0(a0)
; RV64I-NEXT:    fence r, rw
; RV64I-NEXT:    zext.b a0, a0
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i8_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    lb a0, 0(a0)
; RV64IA-NEXT:    fence r, rw
; RV64IA-NEXT:    zext.b a0, a0
; RV64IA-NEXT:    ret
  %1 = load atomic i8, ptr %a acquire, align 1
  ret i8 %1
}

define zeroext i8 @atomic_load_i8_seq_cst(ptr %a) nounwind {
;
;
;
; RV64I-LABEL: atomic_load_i8_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    fence rw, rw
; RV64I-NEXT:    lb a0, 0(a0)
; RV64I-NEXT:    zext.b a0, a0
; RV64I-NEXT:    fence r, rw
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i8_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    fence rw, rw
; RV64IA-NEXT:    lb a0, 0(a0)
; RV64IA-NEXT:    zext.b a0, a0
; RV64IA-NEXT:    fence r, rw
; RV64IA-NEXT:    ret
  %1 = load atomic i8, ptr %a seq_cst, align 1
  ret i8 %1
}

define zeroext i16 @atomic_load_i16_unordered(ptr %a) nounwind {
;
;
; RV64I-LABEL: atomic_load_i16_unordered:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lh a0, 0(a0)
; RV64I-NEXT:    slli a0, a0, 48
; RV64I-NEXT:    srli a0, a0, 48
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i16_unordered:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    lh a0, 0(a0)
; RV64IA-NEXT:    slli a0, a0, 48
; RV64IA-NEXT:    srli a0, a0, 48
; RV64IA-NEXT:    ret
  %1 = load atomic i16, ptr %a unordered, align 2
  ret i16 %1
}

define zeroext i16 @atomic_load_i16_monotonic(ptr %a) nounwind {
;
;
; RV64I-LABEL: atomic_load_i16_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lh a0, 0(a0)
; RV64I-NEXT:    slli a0, a0, 48
; RV64I-NEXT:    srli a0, a0, 48
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i16_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    lh a0, 0(a0)
; RV64IA-NEXT:    slli a0, a0, 48
; RV64IA-NEXT:    srli a0, a0, 48
; RV64IA-NEXT:    ret
  %1 = load atomic i16, ptr %a monotonic, align 2
  ret i16 %1
}

define zeroext i16 @atomic_load_i16_acquire(ptr %a) nounwind {
;
;
;
; RV64I-LABEL: atomic_load_i16_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lh a0, 0(a0)
; RV64I-NEXT:    fence r, rw
; RV64I-NEXT:    slli a0, a0, 48
; RV64I-NEXT:    srli a0, a0, 48
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i16_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    lh a0, 0(a0)
; RV64IA-NEXT:    fence r, rw
; RV64IA-NEXT:    slli a0, a0, 48
; RV64IA-NEXT:    srli a0, a0, 48
; RV64IA-NEXT:    ret
  %1 = load atomic i16, ptr %a acquire, align 2
  ret i16 %1
}

define zeroext i16 @atomic_load_i16_seq_cst(ptr %a) nounwind {
;
;
;
; RV64I-LABEL: atomic_load_i16_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    fence rw, rw
; RV64I-NEXT:    lh a0, 0(a0)
; RV64I-NEXT:    slli a0, a0, 48
; RV64I-NEXT:    srli a0, a0, 48
; RV64I-NEXT:    fence r, rw
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i16_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    fence rw, rw
; RV64IA-NEXT:    lh a0, 0(a0)
; RV64IA-NEXT:    slli a0, a0, 48
; RV64IA-NEXT:    srli a0, a0, 48
; RV64IA-NEXT:    fence r, rw
; RV64IA-NEXT:    ret
  %1 = load atomic i16, ptr %a seq_cst, align 2
  ret i16 %1
}

define zeroext i32 @atomic_load_i32_unordered(ptr %a) nounwind {
;
;
; RV64I-LABEL: atomic_load_i32_unordered:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lw a0, 0(a0)
; RV64I-NEXT:    slli a0, a0, 32
; RV64I-NEXT:    srli a0, a0, 32
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i32_unordered:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    lw a0, 0(a0)
; RV64IA-NEXT:    slli a0, a0, 32
; RV64IA-NEXT:    srli a0, a0, 32
; RV64IA-NEXT:    ret
  %1 = load atomic i32, ptr %a unordered, align 4
  ret i32 %1
}

define zeroext i32 @atomic_load_i32_monotonic(ptr %a) nounwind {
;
;
; RV64I-LABEL: atomic_load_i32_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lw a0, 0(a0)
; RV64I-NEXT:    slli a0, a0, 32
; RV64I-NEXT:    srli a0, a0, 32
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i32_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    lw a0, 0(a0)
; RV64IA-NEXT:    slli a0, a0, 32
; RV64IA-NEXT:    srli a0, a0, 32
; RV64IA-NEXT:    ret
  %1 = load atomic i32, ptr %a monotonic, align 4
  ret i32 %1
}

define zeroext i32 @atomic_load_i32_acquire(ptr %a) nounwind {
;
;
;
; RV64I-LABEL: atomic_load_i32_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lw a0, 0(a0)
; RV64I-NEXT:    fence r, rw
; RV64I-NEXT:    slli a0, a0, 32
; RV64I-NEXT:    srli a0, a0, 32
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i32_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    lw a0, 0(a0)
; RV64IA-NEXT:    fence r, rw
; RV64IA-NEXT:    slli a0, a0, 32
; RV64IA-NEXT:    srli a0, a0, 32
; RV64IA-NEXT:    ret
  %1 = load atomic i32, ptr %a acquire, align 4
  ret i32 %1
}

define zeroext i32 @atomic_load_i32_seq_cst(ptr %a) nounwind {
;
;
;
; RV64I-LABEL: atomic_load_i32_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    fence rw, rw
; RV64I-NEXT:    lw a0, 0(a0)
; RV64I-NEXT:    slli a0, a0, 32
; RV64I-NEXT:    srli a0, a0, 32
; RV64I-NEXT:    fence r, rw
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i32_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    fence rw, rw
; RV64IA-NEXT:    lw a0, 0(a0)
; RV64IA-NEXT:    slli a0, a0, 32
; RV64IA-NEXT:    srli a0, a0, 32
; RV64IA-NEXT:    fence r, rw
; RV64IA-NEXT:    ret
  %1 = load atomic i32, ptr %a seq_cst, align 4
  ret i32 %1
}

define zeroext i64 @atomic_load_i64_unordered(ptr %a) nounwind {
;
;
; RV64I-LABEL: atomic_load_i64_unordered:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ld a0, 0(a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i64_unordered:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    ld a0, 0(a0)
; RV64IA-NEXT:    ret
  %1 = load atomic i64, ptr %a unordered, align 8
  ret i64 %1
}

define zeroext i64 @atomic_load_i64_monotonic(ptr %a) nounwind {
;
;
; RV64I-LABEL: atomic_load_i64_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ld a0, 0(a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i64_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    ld a0, 0(a0)
; RV64IA-NEXT:    ret
  %1 = load atomic i64, ptr %a monotonic, align 8
  ret i64 %1
}

define zeroext i64 @atomic_load_i64_acquire(ptr %a) nounwind {
;
;
; RV64I-LABEL: atomic_load_i64_acquire:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ld a0, 0(a0)
; RV64I-NEXT:    fence r, rw
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i64_acquire:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    ld a0, 0(a0)
; RV64IA-NEXT:    fence r, rw
; RV64IA-NEXT:    ret
  %1 = load atomic i64, ptr %a acquire, align 8
  ret i64 %1
}

define zeroext i64 @atomic_load_i64_seq_cst(ptr %a) nounwind {
;
;
; RV64I-LABEL: atomic_load_i64_seq_cst:
; RV64I:       # %bb.0:
; RV64I-NEXT:    fence rw, rw
; RV64I-NEXT:    ld a0, 0(a0)
; RV64I-NEXT:    fence r, rw
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i64_seq_cst:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    fence rw, rw
; RV64IA-NEXT:    ld a0, 0(a0)
; RV64IA-NEXT:    fence r, rw
; RV64IA-NEXT:    ret
  %1 = load atomic i64, ptr %a seq_cst, align 8
  ret i64 %1
}

!0 = !{i8 0, i8 2}
!1 = !{}
