; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ysx64 -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV64I %s
; RUN: llc -mtriple=ysx64 -mattr=+a -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefixes=RV64IA %s
; RUN: llc -mtriple=ysx64 -mattr=+zalrsc -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefixes=RV64I-ZALRSC %s

define signext i8 @atomic_load_i8_unordered(ptr %a) nounwind {
;
;
;
; RV64I-LABEL: atomic_load_i8_unordered:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lb a0, 0(a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i8_unordered:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    lb a0, 0(a0)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_load_i8_unordered:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    lb a0, 0(a0)
; RV64I-ZALRSC-NEXT:    ret
  %1 = load atomic i8, ptr %a unordered, align 1
  ret i8 %1
}

define signext i16 @atomic_load_i16_unordered(ptr %a) nounwind {
;
;
;
; RV64I-LABEL: atomic_load_i16_unordered:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lh a0, 0(a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i16_unordered:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    lh a0, 0(a0)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_load_i16_unordered:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    lh a0, 0(a0)
; RV64I-ZALRSC-NEXT:    ret
  %1 = load atomic i16, ptr %a unordered, align 2
  ret i16 %1
}

define signext i32 @atomic_load_i32_unordered(ptr %a) nounwind {
;
;
;
; RV64I-LABEL: atomic_load_i32_unordered:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lw a0, 0(a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomic_load_i32_unordered:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    lw a0, 0(a0)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomic_load_i32_unordered:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    lw a0, 0(a0)
; RV64I-ZALRSC-NEXT:    ret
  %1 = load atomic i32, ptr %a unordered, align 4
  ret i32 %1
}

define signext i8 @atomicrmw_xchg_i8_monotonic(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xchg_i8_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB3_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a4, (a2)
; RV64I-NEXT:    mv a5, a1
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB3_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    slli a0, a0, 56
; RV64I-NEXT:    srai a0, a0, 56
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_i8_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB3_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a4, (a2)
; RV64IA-NEXT:    mv a5, a1
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB3_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    slli a0, a0, 56
; RV64IA-NEXT:    srai a0, a0, 56
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_i8_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB3_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a4, (a2)
; RV64I-ZALRSC-NEXT:    mv a5, a1
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB3_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    slli a0, a0, 56
; RV64I-ZALRSC-NEXT:    srai a0, a0, 56
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i8 %b monotonic
  ret i8 %1
}

define signext i8 @atomicrmw_add_i8_monotonic(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_add_i8_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB4_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a4, (a2)
; RV64I-NEXT:    add a5, a4, a1
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB4_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    slli a0, a0, 56
; RV64I-NEXT:    srai a0, a0, 56
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_add_i8_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB4_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a4, (a2)
; RV64IA-NEXT:    add a5, a4, a1
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB4_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    slli a0, a0, 56
; RV64IA-NEXT:    srai a0, a0, 56
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_add_i8_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB4_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a4, (a2)
; RV64I-ZALRSC-NEXT:    add a5, a4, a1
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB4_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    slli a0, a0, 56
; RV64I-ZALRSC-NEXT:    srai a0, a0, 56
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw add ptr %a, i8 %b monotonic
  ret i8 %1
}

define signext i8 @atomicrmw_sub_i8_monotonic(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_sub_i8_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB5_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a4, (a2)
; RV64I-NEXT:    sub a5, a4, a1
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB5_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    slli a0, a0, 56
; RV64I-NEXT:    srai a0, a0, 56
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_sub_i8_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB5_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a4, (a2)
; RV64IA-NEXT:    sub a5, a4, a1
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB5_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    slli a0, a0, 56
; RV64IA-NEXT:    srai a0, a0, 56
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_sub_i8_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB5_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a4, (a2)
; RV64I-ZALRSC-NEXT:    sub a5, a4, a1
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB5_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    slli a0, a0, 56
; RV64I-ZALRSC-NEXT:    srai a0, a0, 56
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw sub ptr %a, i8 %b monotonic
  ret i8 %1
}

define signext i8 @atomicrmw_and_i8_monotonic(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_and_i8_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    not a3, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    or a1, a1, a3
; RV64I-NEXT:    amoand.w a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    slli a0, a0, 56
; RV64I-NEXT:    srai a0, a0, 56
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_and_i8_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    not a3, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    or a1, a1, a3
; RV64IA-NEXT:    amoand.w a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    slli a0, a0, 56
; RV64IA-NEXT:    srai a0, a0, 56
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_and_i8_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    not a3, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    or a1, a1, a3
; RV64I-ZALRSC-NEXT:    amoand.w a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    slli a0, a0, 56
; RV64I-ZALRSC-NEXT:    srai a0, a0, 56
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw and ptr %a, i8 %b monotonic
  ret i8 %1
}

define signext i8 @atomicrmw_nand_i8_monotonic(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_nand_i8_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB7_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a4, (a2)
; RV64I-NEXT:    and a5, a4, a1
; RV64I-NEXT:    not a5, a5
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB7_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    slli a0, a0, 56
; RV64I-NEXT:    srai a0, a0, 56
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_nand_i8_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB7_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a4, (a2)
; RV64IA-NEXT:    and a5, a4, a1
; RV64IA-NEXT:    not a5, a5
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB7_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    slli a0, a0, 56
; RV64IA-NEXT:    srai a0, a0, 56
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_nand_i8_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB7_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a4, (a2)
; RV64I-ZALRSC-NEXT:    and a5, a4, a1
; RV64I-ZALRSC-NEXT:    not a5, a5
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB7_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    slli a0, a0, 56
; RV64I-ZALRSC-NEXT:    srai a0, a0, 56
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw nand ptr %a, i8 %b monotonic
  ret i8 %1
}

define signext i8 @atomicrmw_or_i8_monotonic(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_or_i8_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    amoor.w a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    slli a0, a0, 56
; RV64I-NEXT:    srai a0, a0, 56
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_or_i8_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    amoor.w a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    slli a0, a0, 56
; RV64IA-NEXT:    srai a0, a0, 56
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_or_i8_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    amoor.w a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    slli a0, a0, 56
; RV64I-ZALRSC-NEXT:    srai a0, a0, 56
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw or ptr %a, i8 %b monotonic
  ret i8 %1
}

define signext i8 @atomicrmw_xor_i8_monotonic(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xor_i8_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    amoxor.w a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    slli a0, a0, 56
; RV64I-NEXT:    srai a0, a0, 56
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xor_i8_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    amoxor.w a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    slli a0, a0, 56
; RV64IA-NEXT:    srai a0, a0, 56
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xor_i8_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    amoxor.w a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    slli a0, a0, 56
; RV64I-ZALRSC-NEXT:    srai a0, a0, 56
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw xor ptr %a, i8 %b monotonic
  ret i8 %1
}

define signext i8 @atomicrmw_max_i8_monotonic(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_max_i8_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    slli a1, a1, 56
; RV64I-NEXT:    andi a4, a0, 24
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    srai a1, a1, 56
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    xori a4, a4, 56
; RV64I-NEXT:  .LBB10_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a5, (a2)
; RV64I-NEXT:    and a7, a5, a3
; RV64I-NEXT:    mv a6, a5
; RV64I-NEXT:    sll a7, a7, a4
; RV64I-NEXT:    sra a7, a7, a4
; RV64I-NEXT:    bge a7, a1, .LBB10_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB10_1 Depth=1
; RV64I-NEXT:    xor a6, a5, a1
; RV64I-NEXT:    and a6, a6, a3
; RV64I-NEXT:    xor a6, a5, a6
; RV64I-NEXT:  .LBB10_3: # in Loop: Header=BB10_1 Depth=1
; RV64I-NEXT:    sc.w a6, a6, (a2)
; RV64I-NEXT:    bnez a6, .LBB10_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a5, a0
; RV64I-NEXT:    slli a0, a0, 56
; RV64I-NEXT:    srai a0, a0, 56
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_max_i8_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    slli a1, a1, 56
; RV64IA-NEXT:    andi a4, a0, 24
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    srai a1, a1, 56
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    xori a4, a4, 56
; RV64IA-NEXT:  .LBB10_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a5, (a2)
; RV64IA-NEXT:    and a7, a5, a3
; RV64IA-NEXT:    mv a6, a5
; RV64IA-NEXT:    sll a7, a7, a4
; RV64IA-NEXT:    sra a7, a7, a4
; RV64IA-NEXT:    bge a7, a1, .LBB10_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB10_1 Depth=1
; RV64IA-NEXT:    xor a6, a5, a1
; RV64IA-NEXT:    and a6, a6, a3
; RV64IA-NEXT:    xor a6, a5, a6
; RV64IA-NEXT:  .LBB10_3: # in Loop: Header=BB10_1 Depth=1
; RV64IA-NEXT:    sc.w a6, a6, (a2)
; RV64IA-NEXT:    bnez a6, .LBB10_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a5, a0
; RV64IA-NEXT:    slli a0, a0, 56
; RV64IA-NEXT:    srai a0, a0, 56
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_max_i8_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    slli a1, a1, 56
; RV64I-ZALRSC-NEXT:    andi a4, a0, 24
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    srai a1, a1, 56
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    xori a4, a4, 56
; RV64I-ZALRSC-NEXT:  .LBB10_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a5, (a2)
; RV64I-ZALRSC-NEXT:    and a7, a5, a3
; RV64I-ZALRSC-NEXT:    mv a6, a5
; RV64I-ZALRSC-NEXT:    sll a7, a7, a4
; RV64I-ZALRSC-NEXT:    sra a7, a7, a4
; RV64I-ZALRSC-NEXT:    bge a7, a1, .LBB10_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB10_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a6, a5, a1
; RV64I-ZALRSC-NEXT:    and a6, a6, a3
; RV64I-ZALRSC-NEXT:    xor a6, a5, a6
; RV64I-ZALRSC-NEXT:  .LBB10_3: # in Loop: Header=BB10_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w a6, a6, (a2)
; RV64I-ZALRSC-NEXT:    bnez a6, .LBB10_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a5, a0
; RV64I-ZALRSC-NEXT:    slli a0, a0, 56
; RV64I-ZALRSC-NEXT:    srai a0, a0, 56
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw max ptr %a, i8 %b monotonic
  ret i8 %1
}

define signext i8 @atomicrmw_min_i8_monotonic(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_min_i8_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    slli a1, a1, 56
; RV64I-NEXT:    andi a4, a0, 24
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    srai a1, a1, 56
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    xori a4, a4, 56
; RV64I-NEXT:  .LBB11_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a5, (a2)
; RV64I-NEXT:    and a7, a5, a3
; RV64I-NEXT:    mv a6, a5
; RV64I-NEXT:    sll a7, a7, a4
; RV64I-NEXT:    sra a7, a7, a4
; RV64I-NEXT:    bge a1, a7, .LBB11_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB11_1 Depth=1
; RV64I-NEXT:    xor a6, a5, a1
; RV64I-NEXT:    and a6, a6, a3
; RV64I-NEXT:    xor a6, a5, a6
; RV64I-NEXT:  .LBB11_3: # in Loop: Header=BB11_1 Depth=1
; RV64I-NEXT:    sc.w a6, a6, (a2)
; RV64I-NEXT:    bnez a6, .LBB11_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a5, a0
; RV64I-NEXT:    slli a0, a0, 56
; RV64I-NEXT:    srai a0, a0, 56
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_min_i8_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    slli a1, a1, 56
; RV64IA-NEXT:    andi a4, a0, 24
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    srai a1, a1, 56
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    xori a4, a4, 56
; RV64IA-NEXT:  .LBB11_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a5, (a2)
; RV64IA-NEXT:    and a7, a5, a3
; RV64IA-NEXT:    mv a6, a5
; RV64IA-NEXT:    sll a7, a7, a4
; RV64IA-NEXT:    sra a7, a7, a4
; RV64IA-NEXT:    bge a1, a7, .LBB11_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB11_1 Depth=1
; RV64IA-NEXT:    xor a6, a5, a1
; RV64IA-NEXT:    and a6, a6, a3
; RV64IA-NEXT:    xor a6, a5, a6
; RV64IA-NEXT:  .LBB11_3: # in Loop: Header=BB11_1 Depth=1
; RV64IA-NEXT:    sc.w a6, a6, (a2)
; RV64IA-NEXT:    bnez a6, .LBB11_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a5, a0
; RV64IA-NEXT:    slli a0, a0, 56
; RV64IA-NEXT:    srai a0, a0, 56
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_min_i8_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    slli a1, a1, 56
; RV64I-ZALRSC-NEXT:    andi a4, a0, 24
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    srai a1, a1, 56
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    xori a4, a4, 56
; RV64I-ZALRSC-NEXT:  .LBB11_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a5, (a2)
; RV64I-ZALRSC-NEXT:    and a7, a5, a3
; RV64I-ZALRSC-NEXT:    mv a6, a5
; RV64I-ZALRSC-NEXT:    sll a7, a7, a4
; RV64I-ZALRSC-NEXT:    sra a7, a7, a4
; RV64I-ZALRSC-NEXT:    bge a1, a7, .LBB11_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB11_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a6, a5, a1
; RV64I-ZALRSC-NEXT:    and a6, a6, a3
; RV64I-ZALRSC-NEXT:    xor a6, a5, a6
; RV64I-ZALRSC-NEXT:  .LBB11_3: # in Loop: Header=BB11_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w a6, a6, (a2)
; RV64I-ZALRSC-NEXT:    bnez a6, .LBB11_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a5, a0
; RV64I-ZALRSC-NEXT:    slli a0, a0, 56
; RV64I-ZALRSC-NEXT:    srai a0, a0, 56
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw min ptr %a, i8 %b monotonic
  ret i8 %1
}

define signext i8 @atomicrmw_umax_i8_monotonic(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_umax_i8_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB12_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a4, (a2)
; RV64I-NEXT:    and a6, a4, a3
; RV64I-NEXT:    mv a5, a4
; RV64I-NEXT:    bgeu a6, a1, .LBB12_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB12_1 Depth=1
; RV64I-NEXT:    xor a5, a4, a1
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:  .LBB12_3: # in Loop: Header=BB12_1 Depth=1
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB12_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    slli a0, a0, 56
; RV64I-NEXT:    srai a0, a0, 56
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umax_i8_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB12_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a4, (a2)
; RV64IA-NEXT:    and a6, a4, a3
; RV64IA-NEXT:    mv a5, a4
; RV64IA-NEXT:    bgeu a6, a1, .LBB12_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB12_1 Depth=1
; RV64IA-NEXT:    xor a5, a4, a1
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:  .LBB12_3: # in Loop: Header=BB12_1 Depth=1
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB12_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    slli a0, a0, 56
; RV64IA-NEXT:    srai a0, a0, 56
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umax_i8_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB12_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a4, (a2)
; RV64I-ZALRSC-NEXT:    and a6, a4, a3
; RV64I-ZALRSC-NEXT:    mv a5, a4
; RV64I-ZALRSC-NEXT:    bgeu a6, a1, .LBB12_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB12_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a5, a4, a1
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:  .LBB12_3: # in Loop: Header=BB12_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB12_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    slli a0, a0, 56
; RV64I-ZALRSC-NEXT:    srai a0, a0, 56
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw umax ptr %a, i8 %b monotonic
  ret i8 %1
}

define signext i8 @atomicrmw_umin_i8_monotonic(ptr %a, i8 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_umin_i8_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a3, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB13_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a4, (a2)
; RV64I-NEXT:    and a6, a4, a3
; RV64I-NEXT:    mv a5, a4
; RV64I-NEXT:    bgeu a1, a6, .LBB13_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB13_1 Depth=1
; RV64I-NEXT:    xor a5, a4, a1
; RV64I-NEXT:    and a5, a5, a3
; RV64I-NEXT:    xor a5, a4, a5
; RV64I-NEXT:  .LBB13_3: # in Loop: Header=BB13_1 Depth=1
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB13_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    slli a0, a0, 56
; RV64I-NEXT:    srai a0, a0, 56
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umin_i8_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a3, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB13_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a4, (a2)
; RV64IA-NEXT:    and a6, a4, a3
; RV64IA-NEXT:    mv a5, a4
; RV64IA-NEXT:    bgeu a1, a6, .LBB13_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB13_1 Depth=1
; RV64IA-NEXT:    xor a5, a4, a1
; RV64IA-NEXT:    and a5, a5, a3
; RV64IA-NEXT:    xor a5, a4, a5
; RV64IA-NEXT:  .LBB13_3: # in Loop: Header=BB13_1 Depth=1
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB13_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    slli a0, a0, 56
; RV64IA-NEXT:    srai a0, a0, 56
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umin_i8_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a3, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB13_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a4, (a2)
; RV64I-ZALRSC-NEXT:    and a6, a4, a3
; RV64I-ZALRSC-NEXT:    mv a5, a4
; RV64I-ZALRSC-NEXT:    bgeu a1, a6, .LBB13_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB13_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a5, a4, a1
; RV64I-ZALRSC-NEXT:    and a5, a5, a3
; RV64I-ZALRSC-NEXT:    xor a5, a4, a5
; RV64I-ZALRSC-NEXT:  .LBB13_3: # in Loop: Header=BB13_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB13_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    slli a0, a0, 56
; RV64I-ZALRSC-NEXT:    srai a0, a0, 56
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw umin ptr %a, i8 %b monotonic
  ret i8 %1
}

define signext i16 @atomicrmw_xchg_i16_monotonic(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xchg_i16_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB14_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a3, (a2)
; RV64I-NEXT:    mv a5, a1
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB14_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    slli a0, a0, 48
; RV64I-NEXT:    srai a0, a0, 48
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_i16_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB14_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a3, (a2)
; RV64IA-NEXT:    mv a5, a1
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB14_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    slli a0, a0, 48
; RV64IA-NEXT:    srai a0, a0, 48
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_i16_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB14_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a3, (a2)
; RV64I-ZALRSC-NEXT:    mv a5, a1
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB14_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    slli a0, a0, 48
; RV64I-ZALRSC-NEXT:    srai a0, a0, 48
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i16 %b monotonic
  ret i16 %1
}

define signext i16 @atomicrmw_add_i16_monotonic(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_add_i16_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB15_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a3, (a2)
; RV64I-NEXT:    add a5, a3, a1
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB15_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    slli a0, a0, 48
; RV64I-NEXT:    srai a0, a0, 48
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_add_i16_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB15_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a3, (a2)
; RV64IA-NEXT:    add a5, a3, a1
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB15_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    slli a0, a0, 48
; RV64IA-NEXT:    srai a0, a0, 48
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_add_i16_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB15_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a3, (a2)
; RV64I-ZALRSC-NEXT:    add a5, a3, a1
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB15_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    slli a0, a0, 48
; RV64I-ZALRSC-NEXT:    srai a0, a0, 48
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw add ptr %a, i16 %b monotonic
  ret i16 %1
}

define signext i16 @atomicrmw_sub_i16_monotonic(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_sub_i16_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB16_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a3, (a2)
; RV64I-NEXT:    sub a5, a3, a1
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB16_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    slli a0, a0, 48
; RV64I-NEXT:    srai a0, a0, 48
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_sub_i16_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB16_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a3, (a2)
; RV64IA-NEXT:    sub a5, a3, a1
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB16_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    slli a0, a0, 48
; RV64IA-NEXT:    srai a0, a0, 48
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_sub_i16_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB16_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a3, (a2)
; RV64I-ZALRSC-NEXT:    sub a5, a3, a1
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB16_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    slli a0, a0, 48
; RV64I-ZALRSC-NEXT:    srai a0, a0, 48
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw sub ptr %a, i16 %b monotonic
  ret i16 %1
}

define signext i16 @atomicrmw_and_i16_monotonic(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_and_i16_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    not a3, a4
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    or a1, a1, a3
; RV64I-NEXT:    amoand.w a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    slli a0, a0, 48
; RV64I-NEXT:    srai a0, a0, 48
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_and_i16_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    not a3, a4
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    or a1, a1, a3
; RV64IA-NEXT:    amoand.w a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    slli a0, a0, 48
; RV64IA-NEXT:    srai a0, a0, 48
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_and_i16_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    not a3, a4
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    or a1, a1, a3
; RV64I-ZALRSC-NEXT:    amoand.w a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    slli a0, a0, 48
; RV64I-ZALRSC-NEXT:    srai a0, a0, 48
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw and ptr %a, i16 %b monotonic
  ret i16 %1
}

define signext i16 @atomicrmw_nand_i16_monotonic(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_nand_i16_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB18_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a3, (a2)
; RV64I-NEXT:    and a5, a3, a1
; RV64I-NEXT:    not a5, a5
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB18_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    slli a0, a0, 48
; RV64I-NEXT:    srai a0, a0, 48
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_nand_i16_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB18_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a3, (a2)
; RV64IA-NEXT:    and a5, a3, a1
; RV64IA-NEXT:    not a5, a5
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB18_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    slli a0, a0, 48
; RV64IA-NEXT:    srai a0, a0, 48
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_nand_i16_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB18_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a3, (a2)
; RV64I-ZALRSC-NEXT:    and a5, a3, a1
; RV64I-ZALRSC-NEXT:    not a5, a5
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB18_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    slli a0, a0, 48
; RV64I-ZALRSC-NEXT:    srai a0, a0, 48
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw nand ptr %a, i16 %b monotonic
  ret i16 %1
}

define signext i16 @atomicrmw_or_i16_monotonic(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_or_i16_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    slli a1, a1, 48
; RV64I-NEXT:    srli a1, a1, 48
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    amoor.w a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    slli a0, a0, 48
; RV64I-NEXT:    srai a0, a0, 48
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_or_i16_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    slli a1, a1, 48
; RV64IA-NEXT:    srli a1, a1, 48
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    amoor.w a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    slli a0, a0, 48
; RV64IA-NEXT:    srai a0, a0, 48
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_or_i16_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    slli a1, a1, 48
; RV64I-ZALRSC-NEXT:    srli a1, a1, 48
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    amoor.w a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    slli a0, a0, 48
; RV64I-ZALRSC-NEXT:    srai a0, a0, 48
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw or ptr %a, i16 %b monotonic
  ret i16 %1
}

define signext i16 @atomicrmw_xor_i16_monotonic(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xor_i16_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    slli a1, a1, 48
; RV64I-NEXT:    srli a1, a1, 48
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    amoxor.w a1, a1, (a2)
; RV64I-NEXT:    srlw a0, a1, a0
; RV64I-NEXT:    slli a0, a0, 48
; RV64I-NEXT:    srai a0, a0, 48
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xor_i16_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    slli a1, a1, 48
; RV64IA-NEXT:    srli a1, a1, 48
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    amoxor.w a1, a1, (a2)
; RV64IA-NEXT:    srlw a0, a1, a0
; RV64IA-NEXT:    slli a0, a0, 48
; RV64IA-NEXT:    srai a0, a0, 48
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xor_i16_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    slli a1, a1, 48
; RV64I-ZALRSC-NEXT:    srli a1, a1, 48
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    amoxor.w a1, a1, (a2)
; RV64I-ZALRSC-NEXT:    srlw a0, a1, a0
; RV64I-ZALRSC-NEXT:    slli a0, a0, 48
; RV64I-ZALRSC-NEXT:    srai a0, a0, 48
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw xor ptr %a, i16 %b monotonic
  ret i16 %1
}

define signext i16 @atomicrmw_max_i16_monotonic(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_max_i16_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    slli a1, a1, 48
; RV64I-NEXT:    li a4, 48
; RV64I-NEXT:    andi a5, a0, 24
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    srai a1, a1, 48
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    sub a4, a4, a5
; RV64I-NEXT:  .LBB21_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a5, (a2)
; RV64I-NEXT:    and a7, a5, a3
; RV64I-NEXT:    mv a6, a5
; RV64I-NEXT:    sll a7, a7, a4
; RV64I-NEXT:    sra a7, a7, a4
; RV64I-NEXT:    bge a7, a1, .LBB21_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB21_1 Depth=1
; RV64I-NEXT:    xor a6, a5, a1
; RV64I-NEXT:    and a6, a6, a3
; RV64I-NEXT:    xor a6, a5, a6
; RV64I-NEXT:  .LBB21_3: # in Loop: Header=BB21_1 Depth=1
; RV64I-NEXT:    sc.w a6, a6, (a2)
; RV64I-NEXT:    bnez a6, .LBB21_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a5, a0
; RV64I-NEXT:    slli a0, a0, 48
; RV64I-NEXT:    srai a0, a0, 48
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_max_i16_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    slli a1, a1, 48
; RV64IA-NEXT:    li a4, 48
; RV64IA-NEXT:    andi a5, a0, 24
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    srai a1, a1, 48
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    sub a4, a4, a5
; RV64IA-NEXT:  .LBB21_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a5, (a2)
; RV64IA-NEXT:    and a7, a5, a3
; RV64IA-NEXT:    mv a6, a5
; RV64IA-NEXT:    sll a7, a7, a4
; RV64IA-NEXT:    sra a7, a7, a4
; RV64IA-NEXT:    bge a7, a1, .LBB21_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB21_1 Depth=1
; RV64IA-NEXT:    xor a6, a5, a1
; RV64IA-NEXT:    and a6, a6, a3
; RV64IA-NEXT:    xor a6, a5, a6
; RV64IA-NEXT:  .LBB21_3: # in Loop: Header=BB21_1 Depth=1
; RV64IA-NEXT:    sc.w a6, a6, (a2)
; RV64IA-NEXT:    bnez a6, .LBB21_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a5, a0
; RV64IA-NEXT:    slli a0, a0, 48
; RV64IA-NEXT:    srai a0, a0, 48
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_max_i16_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    slli a1, a1, 48
; RV64I-ZALRSC-NEXT:    li a4, 48
; RV64I-ZALRSC-NEXT:    andi a5, a0, 24
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    srai a1, a1, 48
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    sub a4, a4, a5
; RV64I-ZALRSC-NEXT:  .LBB21_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a5, (a2)
; RV64I-ZALRSC-NEXT:    and a7, a5, a3
; RV64I-ZALRSC-NEXT:    mv a6, a5
; RV64I-ZALRSC-NEXT:    sll a7, a7, a4
; RV64I-ZALRSC-NEXT:    sra a7, a7, a4
; RV64I-ZALRSC-NEXT:    bge a7, a1, .LBB21_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB21_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a6, a5, a1
; RV64I-ZALRSC-NEXT:    and a6, a6, a3
; RV64I-ZALRSC-NEXT:    xor a6, a5, a6
; RV64I-ZALRSC-NEXT:  .LBB21_3: # in Loop: Header=BB21_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w a6, a6, (a2)
; RV64I-ZALRSC-NEXT:    bnez a6, .LBB21_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a5, a0
; RV64I-ZALRSC-NEXT:    slli a0, a0, 48
; RV64I-ZALRSC-NEXT:    srai a0, a0, 48
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw max ptr %a, i16 %b monotonic
  ret i16 %1
}

define signext i16 @atomicrmw_min_i16_monotonic(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_min_i16_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    slli a1, a1, 48
; RV64I-NEXT:    li a4, 48
; RV64I-NEXT:    andi a5, a0, 24
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    srai a1, a1, 48
; RV64I-NEXT:    sllw a3, a3, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    sub a4, a4, a5
; RV64I-NEXT:  .LBB22_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a5, (a2)
; RV64I-NEXT:    and a7, a5, a3
; RV64I-NEXT:    mv a6, a5
; RV64I-NEXT:    sll a7, a7, a4
; RV64I-NEXT:    sra a7, a7, a4
; RV64I-NEXT:    bge a1, a7, .LBB22_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB22_1 Depth=1
; RV64I-NEXT:    xor a6, a5, a1
; RV64I-NEXT:    and a6, a6, a3
; RV64I-NEXT:    xor a6, a5, a6
; RV64I-NEXT:  .LBB22_3: # in Loop: Header=BB22_1 Depth=1
; RV64I-NEXT:    sc.w a6, a6, (a2)
; RV64I-NEXT:    bnez a6, .LBB22_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a5, a0
; RV64I-NEXT:    slli a0, a0, 48
; RV64I-NEXT:    srai a0, a0, 48
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_min_i16_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    slli a1, a1, 48
; RV64IA-NEXT:    li a4, 48
; RV64IA-NEXT:    andi a5, a0, 24
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    srai a1, a1, 48
; RV64IA-NEXT:    sllw a3, a3, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    sub a4, a4, a5
; RV64IA-NEXT:  .LBB22_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a5, (a2)
; RV64IA-NEXT:    and a7, a5, a3
; RV64IA-NEXT:    mv a6, a5
; RV64IA-NEXT:    sll a7, a7, a4
; RV64IA-NEXT:    sra a7, a7, a4
; RV64IA-NEXT:    bge a1, a7, .LBB22_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB22_1 Depth=1
; RV64IA-NEXT:    xor a6, a5, a1
; RV64IA-NEXT:    and a6, a6, a3
; RV64IA-NEXT:    xor a6, a5, a6
; RV64IA-NEXT:  .LBB22_3: # in Loop: Header=BB22_1 Depth=1
; RV64IA-NEXT:    sc.w a6, a6, (a2)
; RV64IA-NEXT:    bnez a6, .LBB22_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a5, a0
; RV64IA-NEXT:    slli a0, a0, 48
; RV64IA-NEXT:    srai a0, a0, 48
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_min_i16_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    slli a1, a1, 48
; RV64I-ZALRSC-NEXT:    li a4, 48
; RV64I-ZALRSC-NEXT:    andi a5, a0, 24
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    srai a1, a1, 48
; RV64I-ZALRSC-NEXT:    sllw a3, a3, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    sub a4, a4, a5
; RV64I-ZALRSC-NEXT:  .LBB22_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a5, (a2)
; RV64I-ZALRSC-NEXT:    and a7, a5, a3
; RV64I-ZALRSC-NEXT:    mv a6, a5
; RV64I-ZALRSC-NEXT:    sll a7, a7, a4
; RV64I-ZALRSC-NEXT:    sra a7, a7, a4
; RV64I-ZALRSC-NEXT:    bge a1, a7, .LBB22_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB22_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a6, a5, a1
; RV64I-ZALRSC-NEXT:    and a6, a6, a3
; RV64I-ZALRSC-NEXT:    xor a6, a5, a6
; RV64I-ZALRSC-NEXT:  .LBB22_3: # in Loop: Header=BB22_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w a6, a6, (a2)
; RV64I-ZALRSC-NEXT:    bnez a6, .LBB22_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a5, a0
; RV64I-ZALRSC-NEXT:    slli a0, a0, 48
; RV64I-ZALRSC-NEXT:    srai a0, a0, 48
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw min ptr %a, i16 %b monotonic
  ret i16 %1
}

define signext i16 @atomicrmw_umax_i16_monotonic(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_umax_i16_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB23_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a3, (a2)
; RV64I-NEXT:    and a6, a3, a4
; RV64I-NEXT:    mv a5, a3
; RV64I-NEXT:    bgeu a6, a1, .LBB23_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB23_1 Depth=1
; RV64I-NEXT:    xor a5, a3, a1
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:  .LBB23_3: # in Loop: Header=BB23_1 Depth=1
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB23_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    slli a0, a0, 48
; RV64I-NEXT:    srai a0, a0, 48
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umax_i16_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB23_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a3, (a2)
; RV64IA-NEXT:    and a6, a3, a4
; RV64IA-NEXT:    mv a5, a3
; RV64IA-NEXT:    bgeu a6, a1, .LBB23_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB23_1 Depth=1
; RV64IA-NEXT:    xor a5, a3, a1
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:  .LBB23_3: # in Loop: Header=BB23_1 Depth=1
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB23_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    slli a0, a0, 48
; RV64IA-NEXT:    srai a0, a0, 48
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umax_i16_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB23_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a3, (a2)
; RV64I-ZALRSC-NEXT:    and a6, a3, a4
; RV64I-ZALRSC-NEXT:    mv a5, a3
; RV64I-ZALRSC-NEXT:    bgeu a6, a1, .LBB23_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB23_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a5, a3, a1
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:  .LBB23_3: # in Loop: Header=BB23_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB23_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    slli a0, a0, 48
; RV64I-ZALRSC-NEXT:    srai a0, a0, 48
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw umax ptr %a, i16 %b monotonic
  ret i16 %1
}

define signext i16 @atomicrmw_umin_i16_monotonic(ptr %a, i16 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_umin_i16_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a3, 16
; RV64I-NEXT:    addi a3, a3, -1
; RV64I-NEXT:    sllw a4, a3, a0
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:  .LBB24_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a3, (a2)
; RV64I-NEXT:    and a6, a3, a4
; RV64I-NEXT:    mv a5, a3
; RV64I-NEXT:    bgeu a1, a6, .LBB24_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB24_1 Depth=1
; RV64I-NEXT:    xor a5, a3, a1
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a3, a5
; RV64I-NEXT:  .LBB24_3: # in Loop: Header=BB24_1 Depth=1
; RV64I-NEXT:    sc.w a5, a5, (a2)
; RV64I-NEXT:    bnez a5, .LBB24_1
; RV64I-NEXT:  # %bb.4:
; RV64I-NEXT:    srlw a0, a3, a0
; RV64I-NEXT:    slli a0, a0, 48
; RV64I-NEXT:    srai a0, a0, 48
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umin_i16_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a3, 16
; RV64IA-NEXT:    addi a3, a3, -1
; RV64IA-NEXT:    sllw a4, a3, a0
; RV64IA-NEXT:    and a1, a1, a3
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:  .LBB24_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a3, (a2)
; RV64IA-NEXT:    and a6, a3, a4
; RV64IA-NEXT:    mv a5, a3
; RV64IA-NEXT:    bgeu a1, a6, .LBB24_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB24_1 Depth=1
; RV64IA-NEXT:    xor a5, a3, a1
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a3, a5
; RV64IA-NEXT:  .LBB24_3: # in Loop: Header=BB24_1 Depth=1
; RV64IA-NEXT:    sc.w a5, a5, (a2)
; RV64IA-NEXT:    bnez a5, .LBB24_1
; RV64IA-NEXT:  # %bb.4:
; RV64IA-NEXT:    srlw a0, a3, a0
; RV64IA-NEXT:    slli a0, a0, 48
; RV64IA-NEXT:    srai a0, a0, 48
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umin_i16_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a3, 16
; RV64I-ZALRSC-NEXT:    addi a3, a3, -1
; RV64I-ZALRSC-NEXT:    sllw a4, a3, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a3
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:  .LBB24_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a3, (a2)
; RV64I-ZALRSC-NEXT:    and a6, a3, a4
; RV64I-ZALRSC-NEXT:    mv a5, a3
; RV64I-ZALRSC-NEXT:    bgeu a1, a6, .LBB24_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB24_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a5, a3, a1
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a3, a5
; RV64I-ZALRSC-NEXT:  .LBB24_3: # in Loop: Header=BB24_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a2)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB24_1
; RV64I-ZALRSC-NEXT:  # %bb.4:
; RV64I-ZALRSC-NEXT:    srlw a0, a3, a0
; RV64I-ZALRSC-NEXT:    slli a0, a0, 48
; RV64I-ZALRSC-NEXT:    srai a0, a0, 48
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw umin ptr %a, i16 %b monotonic
  ret i16 %1
}

define signext i32 @atomicrmw_xchg_i32_monotonic(ptr %a, i32 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xchg_i32_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoswap.w a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_i32_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoswap.w a0, a1, (a0)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_i32_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoswap.w a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i32 %b monotonic
  ret i32 %1
}

define signext i32 @atomicrmw_add_i32_monotonic(ptr %a, i32 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_add_i32_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoadd.w a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_add_i32_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoadd.w a0, a1, (a0)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_add_i32_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoadd.w a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw add ptr %a, i32 %b monotonic
  ret i32 %1
}

define signext i32 @atomicrmw_sub_i32_monotonic(ptr %a, i32 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_sub_i32_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    neg a1, a1
; RV64I-NEXT:    amoadd.w a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_sub_i32_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    neg a1, a1
; RV64IA-NEXT:    amoadd.w a0, a1, (a0)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_sub_i32_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    neg a1, a1
; RV64I-ZALRSC-NEXT:    amoadd.w a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw sub ptr %a, i32 %b monotonic
  ret i32 %1
}

define signext i32 @atomicrmw_and_i32_monotonic(ptr %a, i32 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_and_i32_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoand.w a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_and_i32_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoand.w a0, a1, (a0)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_and_i32_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoand.w a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw and ptr %a, i32 %b monotonic
  ret i32 %1
}

define signext i32 @atomicrmw_nand_i32_monotonic(ptr %a, i32 %b) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_nand_i32_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:  .LBB29_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a2, (a0)
; RV64I-NEXT:    and a3, a2, a1
; RV64I-NEXT:    not a3, a3
; RV64I-NEXT:    sc.w a3, a3, (a0)
; RV64I-NEXT:    bnez a3, .LBB29_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    mv a0, a2
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_nand_i32_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:  .LBB29_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a2, (a0)
; RV64IA-NEXT:    and a3, a2, a1
; RV64IA-NEXT:    not a3, a3
; RV64IA-NEXT:    sc.w a3, a3, (a0)
; RV64IA-NEXT:    bnez a3, .LBB29_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    mv a0, a2
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_nand_i32_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:  .LBB29_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a2, (a0)
; RV64I-ZALRSC-NEXT:    and a3, a2, a1
; RV64I-ZALRSC-NEXT:    not a3, a3
; RV64I-ZALRSC-NEXT:    sc.w a3, a3, (a0)
; RV64I-ZALRSC-NEXT:    bnez a3, .LBB29_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    mv a0, a2
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw nand ptr %a, i32 %b monotonic
  ret i32 %1
}

define signext i32 @atomicrmw_or_i32_monotonic(ptr %a, i32 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_or_i32_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoor.w a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_or_i32_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoor.w a0, a1, (a0)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_or_i32_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoor.w a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw or ptr %a, i32 %b monotonic
  ret i32 %1
}

define signext i32 @atomicrmw_xor_i32_monotonic(ptr %a, i32 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xor_i32_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoxor.w a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xor_i32_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoxor.w a0, a1, (a0)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xor_i32_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoxor.w a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw xor ptr %a, i32 %b monotonic
  ret i32 %1
}

define signext i32 @atomicrmw_max_i32_monotonic(ptr %a, i32 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_max_i32_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomax.w a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_max_i32_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomax.w a0, a1, (a0)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_max_i32_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomax.w a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw max ptr %a, i32 %b monotonic
  ret i32 %1
}

define signext i32 @atomicrmw_min_i32_monotonic(ptr %a, i32 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_min_i32_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomin.w a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_min_i32_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomin.w a0, a1, (a0)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_min_i32_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomin.w a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw min ptr %a, i32 %b monotonic
  ret i32 %1
}

define signext i32 @atomicrmw_umax_i32_monotonic(ptr %a, i32 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_umax_i32_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomaxu.w a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umax_i32_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomaxu.w a0, a1, (a0)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umax_i32_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomaxu.w a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw umax ptr %a, i32 %b monotonic
  ret i32 %1
}

define signext i32 @atomicrmw_umin_i32_monotonic(ptr %a, i32 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_umin_i32_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amominu.w a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umin_i32_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amominu.w a0, a1, (a0)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umin_i32_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amominu.w a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw umin ptr %a, i32 %b monotonic
  ret i32 %1
}

define signext i64 @atomicrmw_xchg_i64_monotonic(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xchg_i64_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoswap.d a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_i64_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoswap.d a0, a1, (a0)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_i64_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoswap.d a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw xchg ptr %a, i64 %b monotonic
  ret i64 %1
}

define signext i64 @atomicrmw_add_i64_monotonic(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_add_i64_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoadd.d a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_add_i64_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoadd.d a0, a1, (a0)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_add_i64_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoadd.d a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw add ptr %a, i64 %b monotonic
  ret i64 %1
}

define signext i64 @atomicrmw_sub_i64_monotonic(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_sub_i64_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    neg a1, a1
; RV64I-NEXT:    amoadd.d a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_sub_i64_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    neg a1, a1
; RV64IA-NEXT:    amoadd.d a0, a1, (a0)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_sub_i64_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    neg a1, a1
; RV64I-ZALRSC-NEXT:    amoadd.d a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw sub ptr %a, i64 %b monotonic
  ret i64 %1
}

define signext i64 @atomicrmw_and_i64_monotonic(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_and_i64_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoand.d a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_and_i64_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoand.d a0, a1, (a0)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_and_i64_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoand.d a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw and ptr %a, i64 %b monotonic
  ret i64 %1
}

define signext i64 @atomicrmw_nand_i64_monotonic(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_nand_i64_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:  .LBB40_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.d a2, (a0)
; RV64I-NEXT:    and a3, a2, a1
; RV64I-NEXT:    not a3, a3
; RV64I-NEXT:    sc.d a3, a3, (a0)
; RV64I-NEXT:    bnez a3, .LBB40_1
; RV64I-NEXT:  # %bb.2:
; RV64I-NEXT:    mv a0, a2
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_nand_i64_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:  .LBB40_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.d a2, (a0)
; RV64IA-NEXT:    and a3, a2, a1
; RV64IA-NEXT:    not a3, a3
; RV64IA-NEXT:    sc.d a3, a3, (a0)
; RV64IA-NEXT:    bnez a3, .LBB40_1
; RV64IA-NEXT:  # %bb.2:
; RV64IA-NEXT:    mv a0, a2
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_nand_i64_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:  .LBB40_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.d a2, (a0)
; RV64I-ZALRSC-NEXT:    and a3, a2, a1
; RV64I-ZALRSC-NEXT:    not a3, a3
; RV64I-ZALRSC-NEXT:    sc.d a3, a3, (a0)
; RV64I-ZALRSC-NEXT:    bnez a3, .LBB40_1
; RV64I-ZALRSC-NEXT:  # %bb.2:
; RV64I-ZALRSC-NEXT:    mv a0, a2
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw nand ptr %a, i64 %b monotonic
  ret i64 %1
}

define signext i64 @atomicrmw_or_i64_monotonic(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_or_i64_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoor.d a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_or_i64_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoor.d a0, a1, (a0)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_or_i64_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoor.d a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw or ptr %a, i64 %b monotonic
  ret i64 %1
}

define signext i64 @atomicrmw_xor_i64_monotonic(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xor_i64_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amoxor.d a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xor_i64_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amoxor.d a0, a1, (a0)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xor_i64_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amoxor.d a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw xor ptr %a, i64 %b monotonic
  ret i64 %1
}

define signext i64 @atomicrmw_max_i64_monotonic(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_max_i64_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomax.d a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_max_i64_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomax.d a0, a1, (a0)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_max_i64_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomax.d a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw max ptr %a, i64 %b monotonic
  ret i64 %1
}

define signext i64 @atomicrmw_min_i64_monotonic(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_min_i64_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomin.d a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_min_i64_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomin.d a0, a1, (a0)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_min_i64_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomin.d a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw min ptr %a, i64 %b monotonic
  ret i64 %1
}

define signext i64 @atomicrmw_umax_i64_monotonic(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_umax_i64_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amomaxu.d a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umax_i64_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amomaxu.d a0, a1, (a0)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umax_i64_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amomaxu.d a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw umax ptr %a, i64 %b monotonic
  ret i64 %1
}

define signext i64 @atomicrmw_umin_i64_monotonic(ptr %a, i64 %b) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_umin_i64_monotonic:
; RV64I:       # %bb.0:
; RV64I-NEXT:    amominu.d a0, a1, (a0)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umin_i64_monotonic:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    amominu.d a0, a1, (a0)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umin_i64_monotonic:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    amominu.d a0, a1, (a0)
; RV64I-ZALRSC-NEXT:    ret
  %1 = atomicrmw umin ptr %a, i64 %b monotonic
  ret i64 %1
}

define signext i8 @cmpxchg_i8_monotonic_monotonic_val0(ptr %ptr, i8 signext %cmp, i8 signext %val) nounwind {
;
;
;
; RV64I-LABEL: cmpxchg_i8_monotonic_monotonic_val0:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a3, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a4, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    zext.b a2, a2
; RV64I-NEXT:    sllw a4, a4, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    sllw a2, a2, a0
; RV64I-NEXT:  .LBB47_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a5, (a3)
; RV64I-NEXT:    and a6, a5, a4
; RV64I-NEXT:    bne a6, a1, .LBB47_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB47_1 Depth=1
; RV64I-NEXT:    xor a6, a5, a2
; RV64I-NEXT:    and a6, a6, a4
; RV64I-NEXT:    xor a6, a5, a6
; RV64I-NEXT:    sc.w a6, a6, (a3)
; RV64I-NEXT:    bnez a6, .LBB47_1
; RV64I-NEXT:  .LBB47_3:
; RV64I-NEXT:    srlw a0, a5, a0
; RV64I-NEXT:    slli a0, a0, 56
; RV64I-NEXT:    srai a0, a0, 56
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: cmpxchg_i8_monotonic_monotonic_val0:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a3, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a4, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    zext.b a2, a2
; RV64IA-NEXT:    sllw a4, a4, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    sllw a2, a2, a0
; RV64IA-NEXT:  .LBB47_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a5, (a3)
; RV64IA-NEXT:    and a6, a5, a4
; RV64IA-NEXT:    bne a6, a1, .LBB47_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB47_1 Depth=1
; RV64IA-NEXT:    xor a6, a5, a2
; RV64IA-NEXT:    and a6, a6, a4
; RV64IA-NEXT:    xor a6, a5, a6
; RV64IA-NEXT:    sc.w a6, a6, (a3)
; RV64IA-NEXT:    bnez a6, .LBB47_1
; RV64IA-NEXT:  .LBB47_3:
; RV64IA-NEXT:    srlw a0, a5, a0
; RV64IA-NEXT:    slli a0, a0, 56
; RV64IA-NEXT:    srai a0, a0, 56
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: cmpxchg_i8_monotonic_monotonic_val0:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a3, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a4, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    zext.b a2, a2
; RV64I-ZALRSC-NEXT:    sllw a4, a4, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    sllw a2, a2, a0
; RV64I-ZALRSC-NEXT:  .LBB47_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a5, (a3)
; RV64I-ZALRSC-NEXT:    and a6, a5, a4
; RV64I-ZALRSC-NEXT:    bne a6, a1, .LBB47_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB47_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a6, a5, a2
; RV64I-ZALRSC-NEXT:    and a6, a6, a4
; RV64I-ZALRSC-NEXT:    xor a6, a5, a6
; RV64I-ZALRSC-NEXT:    sc.w a6, a6, (a3)
; RV64I-ZALRSC-NEXT:    bnez a6, .LBB47_1
; RV64I-ZALRSC-NEXT:  .LBB47_3:
; RV64I-ZALRSC-NEXT:    srlw a0, a5, a0
; RV64I-ZALRSC-NEXT:    slli a0, a0, 56
; RV64I-ZALRSC-NEXT:    srai a0, a0, 56
; RV64I-ZALRSC-NEXT:    ret
  %1 = cmpxchg ptr %ptr, i8 %cmp, i8 %val monotonic monotonic
  %2 = extractvalue { i8, i1 } %1, 0
  ret i8 %2
}

define i1 @cmpxchg_i8_monotonic_monotonic_val1(ptr %ptr, i8 signext %cmp, i8 signext %val) nounwind {
;
;
;
; RV64I-LABEL: cmpxchg_i8_monotonic_monotonic_val1:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a3, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    li a4, 255
; RV64I-NEXT:    zext.b a1, a1
; RV64I-NEXT:    zext.b a2, a2
; RV64I-NEXT:    sllw a4, a4, a0
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    sllw a0, a2, a0
; RV64I-NEXT:  .LBB48_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a2, (a3)
; RV64I-NEXT:    and a5, a2, a4
; RV64I-NEXT:    bne a5, a1, .LBB48_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB48_1 Depth=1
; RV64I-NEXT:    xor a5, a2, a0
; RV64I-NEXT:    and a5, a5, a4
; RV64I-NEXT:    xor a5, a2, a5
; RV64I-NEXT:    sc.w a5, a5, (a3)
; RV64I-NEXT:    bnez a5, .LBB48_1
; RV64I-NEXT:  .LBB48_3:
; RV64I-NEXT:    and a0, a2, a4
; RV64I-NEXT:    sext.w a0, a0
; RV64I-NEXT:    xor a0, a1, a0
; RV64I-NEXT:    seqz a0, a0
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: cmpxchg_i8_monotonic_monotonic_val1:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a3, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    li a4, 255
; RV64IA-NEXT:    zext.b a1, a1
; RV64IA-NEXT:    zext.b a2, a2
; RV64IA-NEXT:    sllw a4, a4, a0
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    sllw a0, a2, a0
; RV64IA-NEXT:  .LBB48_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a2, (a3)
; RV64IA-NEXT:    and a5, a2, a4
; RV64IA-NEXT:    bne a5, a1, .LBB48_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB48_1 Depth=1
; RV64IA-NEXT:    xor a5, a2, a0
; RV64IA-NEXT:    and a5, a5, a4
; RV64IA-NEXT:    xor a5, a2, a5
; RV64IA-NEXT:    sc.w a5, a5, (a3)
; RV64IA-NEXT:    bnez a5, .LBB48_1
; RV64IA-NEXT:  .LBB48_3:
; RV64IA-NEXT:    and a0, a2, a4
; RV64IA-NEXT:    sext.w a0, a0
; RV64IA-NEXT:    xor a0, a1, a0
; RV64IA-NEXT:    seqz a0, a0
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: cmpxchg_i8_monotonic_monotonic_val1:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a3, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    li a4, 255
; RV64I-ZALRSC-NEXT:    zext.b a1, a1
; RV64I-ZALRSC-NEXT:    zext.b a2, a2
; RV64I-ZALRSC-NEXT:    sllw a4, a4, a0
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    sllw a0, a2, a0
; RV64I-ZALRSC-NEXT:  .LBB48_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a2, (a3)
; RV64I-ZALRSC-NEXT:    and a5, a2, a4
; RV64I-ZALRSC-NEXT:    bne a5, a1, .LBB48_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB48_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a5, a2, a0
; RV64I-ZALRSC-NEXT:    and a5, a5, a4
; RV64I-ZALRSC-NEXT:    xor a5, a2, a5
; RV64I-ZALRSC-NEXT:    sc.w a5, a5, (a3)
; RV64I-ZALRSC-NEXT:    bnez a5, .LBB48_1
; RV64I-ZALRSC-NEXT:  .LBB48_3:
; RV64I-ZALRSC-NEXT:    and a0, a2, a4
; RV64I-ZALRSC-NEXT:    sext.w a0, a0
; RV64I-ZALRSC-NEXT:    xor a0, a1, a0
; RV64I-ZALRSC-NEXT:    seqz a0, a0
; RV64I-ZALRSC-NEXT:    ret
  %1 = cmpxchg ptr %ptr, i8 %cmp, i8 %val monotonic monotonic
  %2 = extractvalue { i8, i1 } %1, 1
  ret i1 %2
}

define signext i16 @cmpxchg_i16_monotonic_monotonic_val0(ptr %ptr, i16 signext %cmp, i16 signext %val) nounwind {
;
;
;
; RV64I-LABEL: cmpxchg_i16_monotonic_monotonic_val0:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a3, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a4, 16
; RV64I-NEXT:    addi a4, a4, -1
; RV64I-NEXT:    sllw a5, a4, a0
; RV64I-NEXT:    and a1, a1, a4
; RV64I-NEXT:    and a2, a2, a4
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    sllw a2, a2, a0
; RV64I-NEXT:  .LBB49_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a4, (a3)
; RV64I-NEXT:    and a6, a4, a5
; RV64I-NEXT:    bne a6, a1, .LBB49_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB49_1 Depth=1
; RV64I-NEXT:    xor a6, a4, a2
; RV64I-NEXT:    and a6, a6, a5
; RV64I-NEXT:    xor a6, a4, a6
; RV64I-NEXT:    sc.w a6, a6, (a3)
; RV64I-NEXT:    bnez a6, .LBB49_1
; RV64I-NEXT:  .LBB49_3:
; RV64I-NEXT:    srlw a0, a4, a0
; RV64I-NEXT:    slli a0, a0, 48
; RV64I-NEXT:    srai a0, a0, 48
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: cmpxchg_i16_monotonic_monotonic_val0:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a3, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a4, 16
; RV64IA-NEXT:    addi a4, a4, -1
; RV64IA-NEXT:    sllw a5, a4, a0
; RV64IA-NEXT:    and a1, a1, a4
; RV64IA-NEXT:    and a2, a2, a4
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    sllw a2, a2, a0
; RV64IA-NEXT:  .LBB49_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a4, (a3)
; RV64IA-NEXT:    and a6, a4, a5
; RV64IA-NEXT:    bne a6, a1, .LBB49_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB49_1 Depth=1
; RV64IA-NEXT:    xor a6, a4, a2
; RV64IA-NEXT:    and a6, a6, a5
; RV64IA-NEXT:    xor a6, a4, a6
; RV64IA-NEXT:    sc.w a6, a6, (a3)
; RV64IA-NEXT:    bnez a6, .LBB49_1
; RV64IA-NEXT:  .LBB49_3:
; RV64IA-NEXT:    srlw a0, a4, a0
; RV64IA-NEXT:    slli a0, a0, 48
; RV64IA-NEXT:    srai a0, a0, 48
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: cmpxchg_i16_monotonic_monotonic_val0:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a3, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a4, 16
; RV64I-ZALRSC-NEXT:    addi a4, a4, -1
; RV64I-ZALRSC-NEXT:    sllw a5, a4, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a4
; RV64I-ZALRSC-NEXT:    and a2, a2, a4
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    sllw a2, a2, a0
; RV64I-ZALRSC-NEXT:  .LBB49_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a4, (a3)
; RV64I-ZALRSC-NEXT:    and a6, a4, a5
; RV64I-ZALRSC-NEXT:    bne a6, a1, .LBB49_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB49_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a6, a4, a2
; RV64I-ZALRSC-NEXT:    and a6, a6, a5
; RV64I-ZALRSC-NEXT:    xor a6, a4, a6
; RV64I-ZALRSC-NEXT:    sc.w a6, a6, (a3)
; RV64I-ZALRSC-NEXT:    bnez a6, .LBB49_1
; RV64I-ZALRSC-NEXT:  .LBB49_3:
; RV64I-ZALRSC-NEXT:    srlw a0, a4, a0
; RV64I-ZALRSC-NEXT:    slli a0, a0, 48
; RV64I-ZALRSC-NEXT:    srai a0, a0, 48
; RV64I-ZALRSC-NEXT:    ret
  %1 = cmpxchg ptr %ptr, i16 %cmp, i16 %val monotonic monotonic
  %2 = extractvalue { i16, i1 } %1, 0
  ret i16 %2
}

define i1 @cmpxchg_i16_monotonic_monotonic_val1(ptr %ptr, i16 signext %cmp, i16 signext %val) nounwind {
;
;
;
; RV64I-LABEL: cmpxchg_i16_monotonic_monotonic_val1:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a3, a0, -4
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    lui a4, 16
; RV64I-NEXT:    addi a4, a4, -1
; RV64I-NEXT:    sllw a5, a4, a0
; RV64I-NEXT:    and a1, a1, a4
; RV64I-NEXT:    and a2, a2, a4
; RV64I-NEXT:    sllw a1, a1, a0
; RV64I-NEXT:    sllw a0, a2, a0
; RV64I-NEXT:  .LBB50_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a2, (a3)
; RV64I-NEXT:    and a4, a2, a5
; RV64I-NEXT:    bne a4, a1, .LBB50_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB50_1 Depth=1
; RV64I-NEXT:    xor a4, a2, a0
; RV64I-NEXT:    and a4, a4, a5
; RV64I-NEXT:    xor a4, a2, a4
; RV64I-NEXT:    sc.w a4, a4, (a3)
; RV64I-NEXT:    bnez a4, .LBB50_1
; RV64I-NEXT:  .LBB50_3:
; RV64I-NEXT:    and a0, a2, a5
; RV64I-NEXT:    sext.w a0, a0
; RV64I-NEXT:    xor a0, a1, a0
; RV64I-NEXT:    seqz a0, a0
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: cmpxchg_i16_monotonic_monotonic_val1:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a3, a0, -4
; RV64IA-NEXT:    slliw a0, a0, 3
; RV64IA-NEXT:    lui a4, 16
; RV64IA-NEXT:    addi a4, a4, -1
; RV64IA-NEXT:    sllw a5, a4, a0
; RV64IA-NEXT:    and a1, a1, a4
; RV64IA-NEXT:    and a2, a2, a4
; RV64IA-NEXT:    sllw a1, a1, a0
; RV64IA-NEXT:    sllw a0, a2, a0
; RV64IA-NEXT:  .LBB50_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a2, (a3)
; RV64IA-NEXT:    and a4, a2, a5
; RV64IA-NEXT:    bne a4, a1, .LBB50_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB50_1 Depth=1
; RV64IA-NEXT:    xor a4, a2, a0
; RV64IA-NEXT:    and a4, a4, a5
; RV64IA-NEXT:    xor a4, a2, a4
; RV64IA-NEXT:    sc.w a4, a4, (a3)
; RV64IA-NEXT:    bnez a4, .LBB50_1
; RV64IA-NEXT:  .LBB50_3:
; RV64IA-NEXT:    and a0, a2, a5
; RV64IA-NEXT:    sext.w a0, a0
; RV64IA-NEXT:    xor a0, a1, a0
; RV64IA-NEXT:    seqz a0, a0
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: cmpxchg_i16_monotonic_monotonic_val1:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a3, a0, -4
; RV64I-ZALRSC-NEXT:    slliw a0, a0, 3
; RV64I-ZALRSC-NEXT:    lui a4, 16
; RV64I-ZALRSC-NEXT:    addi a4, a4, -1
; RV64I-ZALRSC-NEXT:    sllw a5, a4, a0
; RV64I-ZALRSC-NEXT:    and a1, a1, a4
; RV64I-ZALRSC-NEXT:    and a2, a2, a4
; RV64I-ZALRSC-NEXT:    sllw a1, a1, a0
; RV64I-ZALRSC-NEXT:    sllw a0, a2, a0
; RV64I-ZALRSC-NEXT:  .LBB50_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a2, (a3)
; RV64I-ZALRSC-NEXT:    and a4, a2, a5
; RV64I-ZALRSC-NEXT:    bne a4, a1, .LBB50_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB50_1 Depth=1
; RV64I-ZALRSC-NEXT:    xor a4, a2, a0
; RV64I-ZALRSC-NEXT:    and a4, a4, a5
; RV64I-ZALRSC-NEXT:    xor a4, a2, a4
; RV64I-ZALRSC-NEXT:    sc.w a4, a4, (a3)
; RV64I-ZALRSC-NEXT:    bnez a4, .LBB50_1
; RV64I-ZALRSC-NEXT:  .LBB50_3:
; RV64I-ZALRSC-NEXT:    and a0, a2, a5
; RV64I-ZALRSC-NEXT:    sext.w a0, a0
; RV64I-ZALRSC-NEXT:    xor a0, a1, a0
; RV64I-ZALRSC-NEXT:    seqz a0, a0
; RV64I-ZALRSC-NEXT:    ret
  %1 = cmpxchg ptr %ptr, i16 %cmp, i16 %val monotonic monotonic
  %2 = extractvalue { i16, i1 } %1, 1
  ret i1 %2
}

define signext i32 @cmpxchg_i32_monotonic_monotonic_val0(ptr %ptr, i32 signext %cmp, i32 signext %val) nounwind {
;
;
;
;
; RV64I-LABEL: cmpxchg_i32_monotonic_monotonic_val0:
; RV64I:       # %bb.0:
; RV64I-NEXT:  .LBB51_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a3, (a0)
; RV64I-NEXT:    bne a3, a1, .LBB51_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB51_1 Depth=1
; RV64I-NEXT:    sc.w a4, a2, (a0)
; RV64I-NEXT:    bnez a4, .LBB51_1
; RV64I-NEXT:  .LBB51_3:
; RV64I-NEXT:    mv a0, a3
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: cmpxchg_i32_monotonic_monotonic_val0:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:  .LBB51_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a3, (a0)
; RV64IA-NEXT:    bne a3, a1, .LBB51_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB51_1 Depth=1
; RV64IA-NEXT:    sc.w a4, a2, (a0)
; RV64IA-NEXT:    bnez a4, .LBB51_1
; RV64IA-NEXT:  .LBB51_3:
; RV64IA-NEXT:    mv a0, a3
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: cmpxchg_i32_monotonic_monotonic_val0:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:  .LBB51_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a3, (a0)
; RV64I-ZALRSC-NEXT:    bne a3, a1, .LBB51_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB51_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w a4, a2, (a0)
; RV64I-ZALRSC-NEXT:    bnez a4, .LBB51_1
; RV64I-ZALRSC-NEXT:  .LBB51_3:
; RV64I-ZALRSC-NEXT:    mv a0, a3
; RV64I-ZALRSC-NEXT:    ret
  %1 = cmpxchg ptr %ptr, i32 %cmp, i32 %val monotonic monotonic
  %2 = extractvalue { i32, i1 } %1, 0
  ret i32 %2
}

define i1 @cmpxchg_i32_monotonic_monotonic_val1(ptr %ptr, i32 signext %cmp, i32 signext %val) nounwind {
;
;
;
;
; RV64I-LABEL: cmpxchg_i32_monotonic_monotonic_val1:
; RV64I:       # %bb.0:
; RV64I-NEXT:  .LBB52_1: # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a3, (a0)
; RV64I-NEXT:    bne a3, a1, .LBB52_3
; RV64I-NEXT:  # %bb.2: # in Loop: Header=BB52_1 Depth=1
; RV64I-NEXT:    sc.w a4, a2, (a0)
; RV64I-NEXT:    bnez a4, .LBB52_1
; RV64I-NEXT:  .LBB52_3:
; RV64I-NEXT:    xor a0, a3, a1
; RV64I-NEXT:    seqz a0, a0
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: cmpxchg_i32_monotonic_monotonic_val1:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:  .LBB52_1: # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a3, (a0)
; RV64IA-NEXT:    bne a3, a1, .LBB52_3
; RV64IA-NEXT:  # %bb.2: # in Loop: Header=BB52_1 Depth=1
; RV64IA-NEXT:    sc.w a4, a2, (a0)
; RV64IA-NEXT:    bnez a4, .LBB52_1
; RV64IA-NEXT:  .LBB52_3:
; RV64IA-NEXT:    xor a0, a3, a1
; RV64IA-NEXT:    seqz a0, a0
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: cmpxchg_i32_monotonic_monotonic_val1:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:  .LBB52_1: # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a3, (a0)
; RV64I-ZALRSC-NEXT:    bne a3, a1, .LBB52_3
; RV64I-ZALRSC-NEXT:  # %bb.2: # in Loop: Header=BB52_1 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w a4, a2, (a0)
; RV64I-ZALRSC-NEXT:    bnez a4, .LBB52_1
; RV64I-ZALRSC-NEXT:  .LBB52_3:
; RV64I-ZALRSC-NEXT:    xor a0, a3, a1
; RV64I-ZALRSC-NEXT:    seqz a0, a0
; RV64I-ZALRSC-NEXT:    ret
  %1 = cmpxchg ptr %ptr, i32 %cmp, i32 %val monotonic monotonic
  %2 = extractvalue { i32, i1 } %1, 1
  ret i1 %2
}

define signext i32 @atomicrmw_xchg_i32_monotonic_crossbb(ptr %a, i1 %c) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xchg_i32_monotonic_crossbb:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a1, a1, 1
; RV64I-NEXT:    beqz a1, .LBB53_2
; RV64I-NEXT:  # %bb.1: # %then
; RV64I-NEXT:    li a1, 1
; RV64I-NEXT:    amoswap.w a1, a1, (a0)
; RV64I-NEXT:    sext.w a0, a1
; RV64I-NEXT:    ret
; RV64I-NEXT:  .LBB53_2: # %else
; RV64I-NEXT:    lw a1, 0(a0)
; RV64I-NEXT:    li a2, 1
; RV64I-NEXT:    sw a2, 0(a0)
; RV64I-NEXT:    sext.w a0, a1
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xchg_i32_monotonic_crossbb:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a1, a1, 1
; RV64IA-NEXT:    beqz a1, .LBB53_2
; RV64IA-NEXT:  # %bb.1: # %then
; RV64IA-NEXT:    li a1, 1
; RV64IA-NEXT:    amoswap.w a1, a1, (a0)
; RV64IA-NEXT:    sext.w a0, a1
; RV64IA-NEXT:    ret
; RV64IA-NEXT:  .LBB53_2: # %else
; RV64IA-NEXT:    lw a1, 0(a0)
; RV64IA-NEXT:    li a2, 1
; RV64IA-NEXT:    sw a2, 0(a0)
; RV64IA-NEXT:    sext.w a0, a1
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xchg_i32_monotonic_crossbb:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a1, a1, 1
; RV64I-ZALRSC-NEXT:    beqz a1, .LBB53_2
; RV64I-ZALRSC-NEXT:  # %bb.1: # %then
; RV64I-ZALRSC-NEXT:    li a1, 1
; RV64I-ZALRSC-NEXT:    amoswap.w a1, a1, (a0)
; RV64I-ZALRSC-NEXT:    sext.w a0, a1
; RV64I-ZALRSC-NEXT:    ret
; RV64I-ZALRSC-NEXT:  .LBB53_2: # %else
; RV64I-ZALRSC-NEXT:    lw a1, 0(a0)
; RV64I-ZALRSC-NEXT:    li a2, 1
; RV64I-ZALRSC-NEXT:    sw a2, 0(a0)
; RV64I-ZALRSC-NEXT:    sext.w a0, a1
; RV64I-ZALRSC-NEXT:    ret
  br i1 %c, label %then, label %else

then:
  %1 = atomicrmw xchg ptr %a, i32 1 monotonic
  br label %merge

else:
  %2 = load i32, ptr %a, align 4
  store i32 1, ptr %a
  br label %merge

merge:
  %3 = phi i32 [ %1, %then ], [ %2, %else ]
  ret i32 %3
}

define signext i32 @atomicrmw_add_i32_monotonic_crossbb(ptr %a, i1 %c) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_add_i32_monotonic_crossbb:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a1, a1, 1
; RV64I-NEXT:    beqz a1, .LBB54_2
; RV64I-NEXT:  # %bb.1: # %then
; RV64I-NEXT:    li a1, 1
; RV64I-NEXT:    amoadd.w a1, a1, (a0)
; RV64I-NEXT:    sext.w a0, a1
; RV64I-NEXT:    ret
; RV64I-NEXT:  .LBB54_2: # %else
; RV64I-NEXT:    lw a1, 0(a0)
; RV64I-NEXT:    addiw a2, a1, 1
; RV64I-NEXT:    sw a2, 0(a0)
; RV64I-NEXT:    sext.w a0, a1
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_add_i32_monotonic_crossbb:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a1, a1, 1
; RV64IA-NEXT:    beqz a1, .LBB54_2
; RV64IA-NEXT:  # %bb.1: # %then
; RV64IA-NEXT:    li a1, 1
; RV64IA-NEXT:    amoadd.w a1, a1, (a0)
; RV64IA-NEXT:    sext.w a0, a1
; RV64IA-NEXT:    ret
; RV64IA-NEXT:  .LBB54_2: # %else
; RV64IA-NEXT:    lw a1, 0(a0)
; RV64IA-NEXT:    addiw a2, a1, 1
; RV64IA-NEXT:    sw a2, 0(a0)
; RV64IA-NEXT:    sext.w a0, a1
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_add_i32_monotonic_crossbb:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a1, a1, 1
; RV64I-ZALRSC-NEXT:    beqz a1, .LBB54_2
; RV64I-ZALRSC-NEXT:  # %bb.1: # %then
; RV64I-ZALRSC-NEXT:    li a1, 1
; RV64I-ZALRSC-NEXT:    amoadd.w a1, a1, (a0)
; RV64I-ZALRSC-NEXT:    sext.w a0, a1
; RV64I-ZALRSC-NEXT:    ret
; RV64I-ZALRSC-NEXT:  .LBB54_2: # %else
; RV64I-ZALRSC-NEXT:    lw a1, 0(a0)
; RV64I-ZALRSC-NEXT:    addiw a2, a1, 1
; RV64I-ZALRSC-NEXT:    sw a2, 0(a0)
; RV64I-ZALRSC-NEXT:    sext.w a0, a1
; RV64I-ZALRSC-NEXT:    ret
  br i1 %c, label %then, label %else

then:
  %1 = atomicrmw add ptr %a, i32 1 monotonic
  br label %merge

else:
  %2 = load i32, ptr %a, align 4
  %3 = add i32 %2, 1
  store i32 %3, ptr %a
  br label %merge

merge:
  %4 = phi i32 [ %1, %then ], [ %2, %else ]
  ret i32 %4
}

define signext i32 @atomicrmw_sub_i32_monotonic_crossbb(ptr %a, i1 %c) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_sub_i32_monotonic_crossbb:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a1, a1, 1
; RV64I-NEXT:    beqz a1, .LBB55_2
; RV64I-NEXT:  # %bb.1: # %then
; RV64I-NEXT:    li a1, -1
; RV64I-NEXT:    amoadd.w a1, a1, (a0)
; RV64I-NEXT:    sext.w a0, a1
; RV64I-NEXT:    ret
; RV64I-NEXT:  .LBB55_2: # %else
; RV64I-NEXT:    lw a1, 0(a0)
; RV64I-NEXT:    addiw a2, a1, -1
; RV64I-NEXT:    sw a2, 0(a0)
; RV64I-NEXT:    sext.w a0, a1
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_sub_i32_monotonic_crossbb:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a1, a1, 1
; RV64IA-NEXT:    beqz a1, .LBB55_2
; RV64IA-NEXT:  # %bb.1: # %then
; RV64IA-NEXT:    li a1, -1
; RV64IA-NEXT:    amoadd.w a1, a1, (a0)
; RV64IA-NEXT:    sext.w a0, a1
; RV64IA-NEXT:    ret
; RV64IA-NEXT:  .LBB55_2: # %else
; RV64IA-NEXT:    lw a1, 0(a0)
; RV64IA-NEXT:    addiw a2, a1, -1
; RV64IA-NEXT:    sw a2, 0(a0)
; RV64IA-NEXT:    sext.w a0, a1
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_sub_i32_monotonic_crossbb:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a1, a1, 1
; RV64I-ZALRSC-NEXT:    beqz a1, .LBB55_2
; RV64I-ZALRSC-NEXT:  # %bb.1: # %then
; RV64I-ZALRSC-NEXT:    li a1, -1
; RV64I-ZALRSC-NEXT:    amoadd.w a1, a1, (a0)
; RV64I-ZALRSC-NEXT:    sext.w a0, a1
; RV64I-ZALRSC-NEXT:    ret
; RV64I-ZALRSC-NEXT:  .LBB55_2: # %else
; RV64I-ZALRSC-NEXT:    lw a1, 0(a0)
; RV64I-ZALRSC-NEXT:    addiw a2, a1, -1
; RV64I-ZALRSC-NEXT:    sw a2, 0(a0)
; RV64I-ZALRSC-NEXT:    sext.w a0, a1
; RV64I-ZALRSC-NEXT:    ret
  br i1 %c, label %then, label %else

then:
  %1 = atomicrmw sub ptr %a, i32 1 monotonic
  br label %merge

else:
  %2 = load i32, ptr %a, align 4
  %3 = sub i32 %2, 1
  store i32 %3, ptr %a
  br label %merge

merge:
  %4 = phi i32 [ %1, %then ], [ %2, %else ]
  ret i32 %4
}

define signext i32 @atomicrmw_and_i32_monotonic_crossbb(ptr %a, i1 %c) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_and_i32_monotonic_crossbb:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a1, a1, 1
; RV64I-NEXT:    beqz a1, .LBB56_2
; RV64I-NEXT:  # %bb.1: # %then
; RV64I-NEXT:    li a1, 1
; RV64I-NEXT:    amoand.w a1, a1, (a0)
; RV64I-NEXT:    sext.w a0, a1
; RV64I-NEXT:    ret
; RV64I-NEXT:  .LBB56_2: # %else
; RV64I-NEXT:    lwu a1, 0(a0)
; RV64I-NEXT:    andi a2, a1, 1
; RV64I-NEXT:    sw a2, 0(a0)
; RV64I-NEXT:    sext.w a0, a1
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_and_i32_monotonic_crossbb:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a1, a1, 1
; RV64IA-NEXT:    beqz a1, .LBB56_2
; RV64IA-NEXT:  # %bb.1: # %then
; RV64IA-NEXT:    li a1, 1
; RV64IA-NEXT:    amoand.w a1, a1, (a0)
; RV64IA-NEXT:    sext.w a0, a1
; RV64IA-NEXT:    ret
; RV64IA-NEXT:  .LBB56_2: # %else
; RV64IA-NEXT:    lwu a1, 0(a0)
; RV64IA-NEXT:    andi a2, a1, 1
; RV64IA-NEXT:    sw a2, 0(a0)
; RV64IA-NEXT:    sext.w a0, a1
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_and_i32_monotonic_crossbb:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a1, a1, 1
; RV64I-ZALRSC-NEXT:    beqz a1, .LBB56_2
; RV64I-ZALRSC-NEXT:  # %bb.1: # %then
; RV64I-ZALRSC-NEXT:    li a1, 1
; RV64I-ZALRSC-NEXT:    amoand.w a1, a1, (a0)
; RV64I-ZALRSC-NEXT:    sext.w a0, a1
; RV64I-ZALRSC-NEXT:    ret
; RV64I-ZALRSC-NEXT:  .LBB56_2: # %else
; RV64I-ZALRSC-NEXT:    lwu a1, 0(a0)
; RV64I-ZALRSC-NEXT:    andi a2, a1, 1
; RV64I-ZALRSC-NEXT:    sw a2, 0(a0)
; RV64I-ZALRSC-NEXT:    sext.w a0, a1
; RV64I-ZALRSC-NEXT:    ret
  br i1 %c, label %then, label %else

then:
  %1 = atomicrmw and ptr %a, i32 1 monotonic
  br label %merge

else:
  %2 = load i32, ptr %a, align 4
  %3 = and i32 %2, 1
  store i32 %3, ptr %a
  br label %merge

merge:
  %4 = phi i32 [ %1, %then ], [ %2, %else ]
  ret i32 %4
}

define signext i32 @atomicrmw_nand_i32_monotonic_crossbb(ptr %a, i1 %c) nounwind {
;
;
;
;
; RV64I-LABEL: atomicrmw_nand_i32_monotonic_crossbb:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a1, a1, 1
; RV64I-NEXT:    beqz a1, .LBB57_2
; RV64I-NEXT:  # %bb.1: # %then
; RV64I-NEXT:    li a2, 1
; RV64I-NEXT:  .LBB57_3: # %then
; RV64I-NEXT:    # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w a1, (a0)
; RV64I-NEXT:    and a3, a1, a2
; RV64I-NEXT:    not a3, a3
; RV64I-NEXT:    sc.w a3, a3, (a0)
; RV64I-NEXT:    bnez a3, .LBB57_3
; RV64I-NEXT:  # %bb.4: # %then
; RV64I-NEXT:    sext.w a0, a1
; RV64I-NEXT:    ret
; RV64I-NEXT:  .LBB57_2: # %else
; RV64I-NEXT:    lwu a1, 0(a0)
; RV64I-NEXT:    andi a2, a1, 1
; RV64I-NEXT:    sw a2, 0(a0)
; RV64I-NEXT:    sext.w a0, a1
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_nand_i32_monotonic_crossbb:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a1, a1, 1
; RV64IA-NEXT:    beqz a1, .LBB57_2
; RV64IA-NEXT:  # %bb.1: # %then
; RV64IA-NEXT:    li a2, 1
; RV64IA-NEXT:  .LBB57_3: # %then
; RV64IA-NEXT:    # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w a1, (a0)
; RV64IA-NEXT:    and a3, a1, a2
; RV64IA-NEXT:    not a3, a3
; RV64IA-NEXT:    sc.w a3, a3, (a0)
; RV64IA-NEXT:    bnez a3, .LBB57_3
; RV64IA-NEXT:  # %bb.4: # %then
; RV64IA-NEXT:    sext.w a0, a1
; RV64IA-NEXT:    ret
; RV64IA-NEXT:  .LBB57_2: # %else
; RV64IA-NEXT:    lwu a1, 0(a0)
; RV64IA-NEXT:    andi a2, a1, 1
; RV64IA-NEXT:    sw a2, 0(a0)
; RV64IA-NEXT:    sext.w a0, a1
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_nand_i32_monotonic_crossbb:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a1, a1, 1
; RV64I-ZALRSC-NEXT:    beqz a1, .LBB57_2
; RV64I-ZALRSC-NEXT:  # %bb.1: # %then
; RV64I-ZALRSC-NEXT:    li a2, 1
; RV64I-ZALRSC-NEXT:  .LBB57_3: # %then
; RV64I-ZALRSC-NEXT:    # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w a1, (a0)
; RV64I-ZALRSC-NEXT:    and a3, a1, a2
; RV64I-ZALRSC-NEXT:    not a3, a3
; RV64I-ZALRSC-NEXT:    sc.w a3, a3, (a0)
; RV64I-ZALRSC-NEXT:    bnez a3, .LBB57_3
; RV64I-ZALRSC-NEXT:  # %bb.4: # %then
; RV64I-ZALRSC-NEXT:    sext.w a0, a1
; RV64I-ZALRSC-NEXT:    ret
; RV64I-ZALRSC-NEXT:  .LBB57_2: # %else
; RV64I-ZALRSC-NEXT:    lwu a1, 0(a0)
; RV64I-ZALRSC-NEXT:    andi a2, a1, 1
; RV64I-ZALRSC-NEXT:    sw a2, 0(a0)
; RV64I-ZALRSC-NEXT:    sext.w a0, a1
; RV64I-ZALRSC-NEXT:    ret
  br i1 %c, label %then, label %else

then:
  %1 = atomicrmw nand ptr %a, i32 1 monotonic
  br label %merge

else:
  %2 = load i32, ptr %a, align 4
  %3 = and i32 %2, 1
  store i32 %3, ptr %a
  br label %merge

merge:
  %4 = phi i32 [ %1, %then ], [ %2, %else ]
  ret i32 %4
}

define signext i32 @atomicrmw_or_i32_monotonic_crossbb(ptr %a, i1 %c) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_or_i32_monotonic_crossbb:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a1, a1, 1
; RV64I-NEXT:    beqz a1, .LBB58_2
; RV64I-NEXT:  # %bb.1: # %then
; RV64I-NEXT:    li a1, 1
; RV64I-NEXT:    amoor.w a1, a1, (a0)
; RV64I-NEXT:    sext.w a0, a1
; RV64I-NEXT:    ret
; RV64I-NEXT:  .LBB58_2: # %else
; RV64I-NEXT:    lw a1, 0(a0)
; RV64I-NEXT:    ori a2, a1, 1
; RV64I-NEXT:    sw a2, 0(a0)
; RV64I-NEXT:    sext.w a0, a1
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_or_i32_monotonic_crossbb:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a1, a1, 1
; RV64IA-NEXT:    beqz a1, .LBB58_2
; RV64IA-NEXT:  # %bb.1: # %then
; RV64IA-NEXT:    li a1, 1
; RV64IA-NEXT:    amoor.w a1, a1, (a0)
; RV64IA-NEXT:    sext.w a0, a1
; RV64IA-NEXT:    ret
; RV64IA-NEXT:  .LBB58_2: # %else
; RV64IA-NEXT:    lw a1, 0(a0)
; RV64IA-NEXT:    ori a2, a1, 1
; RV64IA-NEXT:    sw a2, 0(a0)
; RV64IA-NEXT:    sext.w a0, a1
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_or_i32_monotonic_crossbb:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a1, a1, 1
; RV64I-ZALRSC-NEXT:    beqz a1, .LBB58_2
; RV64I-ZALRSC-NEXT:  # %bb.1: # %then
; RV64I-ZALRSC-NEXT:    li a1, 1
; RV64I-ZALRSC-NEXT:    amoor.w a1, a1, (a0)
; RV64I-ZALRSC-NEXT:    sext.w a0, a1
; RV64I-ZALRSC-NEXT:    ret
; RV64I-ZALRSC-NEXT:  .LBB58_2: # %else
; RV64I-ZALRSC-NEXT:    lw a1, 0(a0)
; RV64I-ZALRSC-NEXT:    ori a2, a1, 1
; RV64I-ZALRSC-NEXT:    sw a2, 0(a0)
; RV64I-ZALRSC-NEXT:    sext.w a0, a1
; RV64I-ZALRSC-NEXT:    ret
  br i1 %c, label %then, label %else

then:
  %1 = atomicrmw or ptr %a, i32 1 monotonic
  br label %merge

else:
  %2 = load i32, ptr %a, align 4
  %3 = or i32 %2, 1
  store i32 %3, ptr %a
  br label %merge

merge:
  %4 = phi i32 [ %1, %then ], [ %2, %else ]
  ret i32 %4
}

define signext i32 @atomicrmw_xor_i32_monotonic_crossbb(ptr %a, i1 %c) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_xor_i32_monotonic_crossbb:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a1, a1, 1
; RV64I-NEXT:    beqz a1, .LBB59_2
; RV64I-NEXT:  # %bb.1: # %then
; RV64I-NEXT:    li a1, 1
; RV64I-NEXT:    amoxor.w a1, a1, (a0)
; RV64I-NEXT:    sext.w a0, a1
; RV64I-NEXT:    ret
; RV64I-NEXT:  .LBB59_2: # %else
; RV64I-NEXT:    lw a1, 0(a0)
; RV64I-NEXT:    xori a2, a1, 1
; RV64I-NEXT:    sw a2, 0(a0)
; RV64I-NEXT:    sext.w a0, a1
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_xor_i32_monotonic_crossbb:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a1, a1, 1
; RV64IA-NEXT:    beqz a1, .LBB59_2
; RV64IA-NEXT:  # %bb.1: # %then
; RV64IA-NEXT:    li a1, 1
; RV64IA-NEXT:    amoxor.w a1, a1, (a0)
; RV64IA-NEXT:    sext.w a0, a1
; RV64IA-NEXT:    ret
; RV64IA-NEXT:  .LBB59_2: # %else
; RV64IA-NEXT:    lw a1, 0(a0)
; RV64IA-NEXT:    xori a2, a1, 1
; RV64IA-NEXT:    sw a2, 0(a0)
; RV64IA-NEXT:    sext.w a0, a1
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_xor_i32_monotonic_crossbb:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a1, a1, 1
; RV64I-ZALRSC-NEXT:    beqz a1, .LBB59_2
; RV64I-ZALRSC-NEXT:  # %bb.1: # %then
; RV64I-ZALRSC-NEXT:    li a1, 1
; RV64I-ZALRSC-NEXT:    amoxor.w a1, a1, (a0)
; RV64I-ZALRSC-NEXT:    sext.w a0, a1
; RV64I-ZALRSC-NEXT:    ret
; RV64I-ZALRSC-NEXT:  .LBB59_2: # %else
; RV64I-ZALRSC-NEXT:    lw a1, 0(a0)
; RV64I-ZALRSC-NEXT:    xori a2, a1, 1
; RV64I-ZALRSC-NEXT:    sw a2, 0(a0)
; RV64I-ZALRSC-NEXT:    sext.w a0, a1
; RV64I-ZALRSC-NEXT:    ret
  br i1 %c, label %then, label %else

then:
  %1 = atomicrmw xor ptr %a, i32 1 monotonic
  br label %merge

else:
  %2 = load i32, ptr %a, align 4
  %3 = xor i32 %2, 1
  store i32 %3, ptr %a
  br label %merge

merge:
  %4 = phi i32 [ %1, %then ], [ %2, %else ]
  ret i32 %4
}

define signext i32 @atomicrmw_max_i32_monotonic_crossbb(ptr %a, i1 %c) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_max_i32_monotonic_crossbb:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a1, 1
; RV64I-NEXT:    mv a1, a0
; RV64I-NEXT:    beqz a2, .LBB60_2
; RV64I-NEXT:  # %bb.1: # %then
; RV64I-NEXT:    li a0, 1
; RV64I-NEXT:    amomax.w a0, a0, (a1)
; RV64I-NEXT:    ret
; RV64I-NEXT:  .LBB60_2: # %else
; RV64I-NEXT:    lw a0, 0(a1)
; RV64I-NEXT:    li a3, 1
; RV64I-NEXT:    mv a2, a0
; RV64I-NEXT:    blt a3, a0, .LBB60_4
; RV64I-NEXT:  # %bb.3: # %else
; RV64I-NEXT:    li a2, 1
; RV64I-NEXT:  .LBB60_4: # %else
; RV64I-NEXT:    sw a2, 0(a1)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_max_i32_monotonic_crossbb:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a1, 1
; RV64IA-NEXT:    mv a1, a0
; RV64IA-NEXT:    beqz a2, .LBB60_2
; RV64IA-NEXT:  # %bb.1: # %then
; RV64IA-NEXT:    li a0, 1
; RV64IA-NEXT:    amomax.w a0, a0, (a1)
; RV64IA-NEXT:    ret
; RV64IA-NEXT:  .LBB60_2: # %else
; RV64IA-NEXT:    lw a0, 0(a1)
; RV64IA-NEXT:    li a3, 1
; RV64IA-NEXT:    mv a2, a0
; RV64IA-NEXT:    blt a3, a0, .LBB60_4
; RV64IA-NEXT:  # %bb.3: # %else
; RV64IA-NEXT:    li a2, 1
; RV64IA-NEXT:  .LBB60_4: # %else
; RV64IA-NEXT:    sw a2, 0(a1)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_max_i32_monotonic_crossbb:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a1, 1
; RV64I-ZALRSC-NEXT:    mv a1, a0
; RV64I-ZALRSC-NEXT:    beqz a2, .LBB60_2
; RV64I-ZALRSC-NEXT:  # %bb.1: # %then
; RV64I-ZALRSC-NEXT:    li a0, 1
; RV64I-ZALRSC-NEXT:    amomax.w a0, a0, (a1)
; RV64I-ZALRSC-NEXT:    ret
; RV64I-ZALRSC-NEXT:  .LBB60_2: # %else
; RV64I-ZALRSC-NEXT:    lw a0, 0(a1)
; RV64I-ZALRSC-NEXT:    li a3, 1
; RV64I-ZALRSC-NEXT:    mv a2, a0
; RV64I-ZALRSC-NEXT:    blt a3, a0, .LBB60_4
; RV64I-ZALRSC-NEXT:  # %bb.3: # %else
; RV64I-ZALRSC-NEXT:    li a2, 1
; RV64I-ZALRSC-NEXT:  .LBB60_4: # %else
; RV64I-ZALRSC-NEXT:    sw a2, 0(a1)
; RV64I-ZALRSC-NEXT:    ret
  br i1 %c, label %then, label %else

then:
  %1 = atomicrmw max ptr %a, i32 1 monotonic
  br label %merge

else:
  %2 = load i32, ptr %a, align 4
  %3 = call i32 @llvm.smax.i32(i32 %2, i32 1)
  store i32 %3, ptr %a
  br label %merge

merge:
  %4 = phi i32 [ %1, %then ], [ %2, %else ]
  ret i32 %4
}

define signext i32 @atomicrmw_min_i32_monotonic_crossbb(ptr %a, i1 %c) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_min_i32_monotonic_crossbb:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a1, 1
; RV64I-NEXT:    mv a1, a0
; RV64I-NEXT:    beqz a2, .LBB61_2
; RV64I-NEXT:  # %bb.1: # %then
; RV64I-NEXT:    li a0, 1
; RV64I-NEXT:    amomin.w a0, a0, (a1)
; RV64I-NEXT:    ret
; RV64I-NEXT:  .LBB61_2: # %else
; RV64I-NEXT:    lw a0, 0(a1)
; RV64I-NEXT:    mv a2, a0
; RV64I-NEXT:    blez a0, .LBB61_4
; RV64I-NEXT:  # %bb.3: # %else
; RV64I-NEXT:    li a2, 1
; RV64I-NEXT:  .LBB61_4: # %else
; RV64I-NEXT:    sw a2, 0(a1)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_min_i32_monotonic_crossbb:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a1, 1
; RV64IA-NEXT:    mv a1, a0
; RV64IA-NEXT:    beqz a2, .LBB61_2
; RV64IA-NEXT:  # %bb.1: # %then
; RV64IA-NEXT:    li a0, 1
; RV64IA-NEXT:    amomin.w a0, a0, (a1)
; RV64IA-NEXT:    ret
; RV64IA-NEXT:  .LBB61_2: # %else
; RV64IA-NEXT:    lw a0, 0(a1)
; RV64IA-NEXT:    mv a2, a0
; RV64IA-NEXT:    blez a0, .LBB61_4
; RV64IA-NEXT:  # %bb.3: # %else
; RV64IA-NEXT:    li a2, 1
; RV64IA-NEXT:  .LBB61_4: # %else
; RV64IA-NEXT:    sw a2, 0(a1)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_min_i32_monotonic_crossbb:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a1, 1
; RV64I-ZALRSC-NEXT:    mv a1, a0
; RV64I-ZALRSC-NEXT:    beqz a2, .LBB61_2
; RV64I-ZALRSC-NEXT:  # %bb.1: # %then
; RV64I-ZALRSC-NEXT:    li a0, 1
; RV64I-ZALRSC-NEXT:    amomin.w a0, a0, (a1)
; RV64I-ZALRSC-NEXT:    ret
; RV64I-ZALRSC-NEXT:  .LBB61_2: # %else
; RV64I-ZALRSC-NEXT:    lw a0, 0(a1)
; RV64I-ZALRSC-NEXT:    mv a2, a0
; RV64I-ZALRSC-NEXT:    blez a0, .LBB61_4
; RV64I-ZALRSC-NEXT:  # %bb.3: # %else
; RV64I-ZALRSC-NEXT:    li a2, 1
; RV64I-ZALRSC-NEXT:  .LBB61_4: # %else
; RV64I-ZALRSC-NEXT:    sw a2, 0(a1)
; RV64I-ZALRSC-NEXT:    ret
  br i1 %c, label %then, label %else

then:
  %1 = atomicrmw min ptr %a, i32 1 monotonic
  br label %merge

else:
  %2 = load i32, ptr %a, align 4
  %3 = call i32 @llvm.smin.i32(i32 %2, i32 1)
  store i32 %3, ptr %a
  br label %merge

merge:
  %4 = phi i32 [ %1, %then ], [ %2, %else ]
  ret i32 %4
}

define signext i32 @atomicrmw_umax_i32_monotonic_crossbb(ptr %a, i1 %c) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_umax_i32_monotonic_crossbb:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a1, 1
; RV64I-NEXT:    mv a1, a0
; RV64I-NEXT:    beqz a2, .LBB62_2
; RV64I-NEXT:  # %bb.1: # %then
; RV64I-NEXT:    li a0, 1
; RV64I-NEXT:    amomaxu.w a0, a0, (a1)
; RV64I-NEXT:    ret
; RV64I-NEXT:  .LBB62_2: # %else
; RV64I-NEXT:    lw a0, 0(a1)
; RV64I-NEXT:    li a3, 1
; RV64I-NEXT:    mv a2, a0
; RV64I-NEXT:    bltu a3, a0, .LBB62_4
; RV64I-NEXT:  # %bb.3: # %else
; RV64I-NEXT:    li a2, 1
; RV64I-NEXT:  .LBB62_4: # %else
; RV64I-NEXT:    sw a2, 0(a1)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umax_i32_monotonic_crossbb:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a1, 1
; RV64IA-NEXT:    mv a1, a0
; RV64IA-NEXT:    beqz a2, .LBB62_2
; RV64IA-NEXT:  # %bb.1: # %then
; RV64IA-NEXT:    li a0, 1
; RV64IA-NEXT:    amomaxu.w a0, a0, (a1)
; RV64IA-NEXT:    ret
; RV64IA-NEXT:  .LBB62_2: # %else
; RV64IA-NEXT:    lw a0, 0(a1)
; RV64IA-NEXT:    li a3, 1
; RV64IA-NEXT:    mv a2, a0
; RV64IA-NEXT:    bltu a3, a0, .LBB62_4
; RV64IA-NEXT:  # %bb.3: # %else
; RV64IA-NEXT:    li a2, 1
; RV64IA-NEXT:  .LBB62_4: # %else
; RV64IA-NEXT:    sw a2, 0(a1)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umax_i32_monotonic_crossbb:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a1, 1
; RV64I-ZALRSC-NEXT:    mv a1, a0
; RV64I-ZALRSC-NEXT:    beqz a2, .LBB62_2
; RV64I-ZALRSC-NEXT:  # %bb.1: # %then
; RV64I-ZALRSC-NEXT:    li a0, 1
; RV64I-ZALRSC-NEXT:    amomaxu.w a0, a0, (a1)
; RV64I-ZALRSC-NEXT:    ret
; RV64I-ZALRSC-NEXT:  .LBB62_2: # %else
; RV64I-ZALRSC-NEXT:    lw a0, 0(a1)
; RV64I-ZALRSC-NEXT:    li a3, 1
; RV64I-ZALRSC-NEXT:    mv a2, a0
; RV64I-ZALRSC-NEXT:    bltu a3, a0, .LBB62_4
; RV64I-ZALRSC-NEXT:  # %bb.3: # %else
; RV64I-ZALRSC-NEXT:    li a2, 1
; RV64I-ZALRSC-NEXT:  .LBB62_4: # %else
; RV64I-ZALRSC-NEXT:    sw a2, 0(a1)
; RV64I-ZALRSC-NEXT:    ret
  br i1 %c, label %then, label %else

then:
  %1 = atomicrmw umax ptr %a, i32 1 monotonic
  br label %merge

else:
  %2 = load i32, ptr %a, align 4
  %3 = call i32 @llvm.umax.i32(i32 %2, i32 1)
  store i32 %3, ptr %a
  br label %merge

merge:
  %4 = phi i32 [ %1, %then ], [ %2, %else ]
  ret i32 %4
}

define signext i32 @atomicrmw_umin_i32_monotonic_crossbb(ptr %a, i1 %c) nounwind {
;
;
;
; RV64I-LABEL: atomicrmw_umin_i32_monotonic_crossbb:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a1, 1
; RV64I-NEXT:    mv a1, a0
; RV64I-NEXT:    beqz a2, .LBB63_2
; RV64I-NEXT:  # %bb.1: # %then
; RV64I-NEXT:    li a0, 1
; RV64I-NEXT:    amominu.w a0, a0, (a1)
; RV64I-NEXT:    ret
; RV64I-NEXT:  .LBB63_2: # %else
; RV64I-NEXT:    lw a0, 0(a1)
; RV64I-NEXT:    li a3, 1
; RV64I-NEXT:    mv a2, a0
; RV64I-NEXT:    bltu a0, a3, .LBB63_4
; RV64I-NEXT:  # %bb.3: # %else
; RV64I-NEXT:    li a2, 1
; RV64I-NEXT:  .LBB63_4: # %else
; RV64I-NEXT:    sw a2, 0(a1)
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: atomicrmw_umin_i32_monotonic_crossbb:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    andi a2, a1, 1
; RV64IA-NEXT:    mv a1, a0
; RV64IA-NEXT:    beqz a2, .LBB63_2
; RV64IA-NEXT:  # %bb.1: # %then
; RV64IA-NEXT:    li a0, 1
; RV64IA-NEXT:    amominu.w a0, a0, (a1)
; RV64IA-NEXT:    ret
; RV64IA-NEXT:  .LBB63_2: # %else
; RV64IA-NEXT:    lw a0, 0(a1)
; RV64IA-NEXT:    li a3, 1
; RV64IA-NEXT:    mv a2, a0
; RV64IA-NEXT:    bltu a0, a3, .LBB63_4
; RV64IA-NEXT:  # %bb.3: # %else
; RV64IA-NEXT:    li a2, 1
; RV64IA-NEXT:  .LBB63_4: # %else
; RV64IA-NEXT:    sw a2, 0(a1)
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: atomicrmw_umin_i32_monotonic_crossbb:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    andi a2, a1, 1
; RV64I-ZALRSC-NEXT:    mv a1, a0
; RV64I-ZALRSC-NEXT:    beqz a2, .LBB63_2
; RV64I-ZALRSC-NEXT:  # %bb.1: # %then
; RV64I-ZALRSC-NEXT:    li a0, 1
; RV64I-ZALRSC-NEXT:    amominu.w a0, a0, (a1)
; RV64I-ZALRSC-NEXT:    ret
; RV64I-ZALRSC-NEXT:  .LBB63_2: # %else
; RV64I-ZALRSC-NEXT:    lw a0, 0(a1)
; RV64I-ZALRSC-NEXT:    li a3, 1
; RV64I-ZALRSC-NEXT:    mv a2, a0
; RV64I-ZALRSC-NEXT:    bltu a0, a3, .LBB63_4
; RV64I-ZALRSC-NEXT:  # %bb.3: # %else
; RV64I-ZALRSC-NEXT:    li a2, 1
; RV64I-ZALRSC-NEXT:  .LBB63_4: # %else
; RV64I-ZALRSC-NEXT:    sw a2, 0(a1)
; RV64I-ZALRSC-NEXT:    ret
  br i1 %c, label %then, label %else

then:
  %1 = atomicrmw umin ptr %a, i32 1 monotonic
  br label %merge

else:
  %2 = load i32, ptr %a, align 4
  %3 = call i32 @llvm.umin.i32(i32 %2, i32 1)
  store i32 %3, ptr %a
  br label %merge

merge:
  %4 = phi i32 [ %1, %then ], [ %2, %else ]
  ret i32 %4
}

define signext i32 @cmpxchg_i32_monotonic_crossbb(ptr %ptr, i32 signext %cmp, i32 signext %val, i1 zeroext %c) nounwind {
;
;
;
;
; RV64I-LABEL: cmpxchg_i32_monotonic_crossbb:
; RV64I:       # %bb.0:
; RV64I-NEXT:    beqz a3, .LBB64_2
; RV64I-NEXT:  # %bb.1: # %then
; RV64I-NEXT:  .LBB64_3: # %then
; RV64I-NEXT:    # =>This Inner Loop Header: Depth=1
; RV64I-NEXT:    lr.w.aqrl a3, (a0)
; RV64I-NEXT:    bne a3, a1, .LBB64_5
; RV64I-NEXT:  # %bb.4: # %then
; RV64I-NEXT:    # in Loop: Header=BB64_3 Depth=1
; RV64I-NEXT:    sc.w.rl a4, a2, (a0)
; RV64I-NEXT:    bnez a4, .LBB64_3
; RV64I-NEXT:  .LBB64_5: # %then
; RV64I-NEXT:    sext.w a0, a3
; RV64I-NEXT:    ret
; RV64I-NEXT:  .LBB64_2: # %else
; RV64I-NEXT:    lw a3, 0(a0)
; RV64I-NEXT:    sext.w a0, a3
; RV64I-NEXT:    ret
;
; RV64IA-LABEL: cmpxchg_i32_monotonic_crossbb:
; RV64IA:       # %bb.0:
; RV64IA-NEXT:    beqz a3, .LBB64_2
; RV64IA-NEXT:  # %bb.1: # %then
; RV64IA-NEXT:  .LBB64_3: # %then
; RV64IA-NEXT:    # =>This Inner Loop Header: Depth=1
; RV64IA-NEXT:    lr.w.aqrl a3, (a0)
; RV64IA-NEXT:    bne a3, a1, .LBB64_5
; RV64IA-NEXT:  # %bb.4: # %then
; RV64IA-NEXT:    # in Loop: Header=BB64_3 Depth=1
; RV64IA-NEXT:    sc.w.rl a4, a2, (a0)
; RV64IA-NEXT:    bnez a4, .LBB64_3
; RV64IA-NEXT:  .LBB64_5: # %then
; RV64IA-NEXT:    sext.w a0, a3
; RV64IA-NEXT:    ret
; RV64IA-NEXT:  .LBB64_2: # %else
; RV64IA-NEXT:    lw a3, 0(a0)
; RV64IA-NEXT:    sext.w a0, a3
; RV64IA-NEXT:    ret
;
; RV64I-ZALRSC-LABEL: cmpxchg_i32_monotonic_crossbb:
; RV64I-ZALRSC:       # %bb.0:
; RV64I-ZALRSC-NEXT:    beqz a3, .LBB64_2
; RV64I-ZALRSC-NEXT:  # %bb.1: # %then
; RV64I-ZALRSC-NEXT:  .LBB64_3: # %then
; RV64I-ZALRSC-NEXT:    # =>This Inner Loop Header: Depth=1
; RV64I-ZALRSC-NEXT:    lr.w.aqrl a3, (a0)
; RV64I-ZALRSC-NEXT:    bne a3, a1, .LBB64_5
; RV64I-ZALRSC-NEXT:  # %bb.4: # %then
; RV64I-ZALRSC-NEXT:    # in Loop: Header=BB64_3 Depth=1
; RV64I-ZALRSC-NEXT:    sc.w.rl a4, a2, (a0)
; RV64I-ZALRSC-NEXT:    bnez a4, .LBB64_3
; RV64I-ZALRSC-NEXT:  .LBB64_5: # %then
; RV64I-ZALRSC-NEXT:    sext.w a0, a3
; RV64I-ZALRSC-NEXT:    ret
; RV64I-ZALRSC-NEXT:  .LBB64_2: # %else
; RV64I-ZALRSC-NEXT:    lw a3, 0(a0)
; RV64I-ZALRSC-NEXT:    sext.w a0, a3
; RV64I-ZALRSC-NEXT:    ret
  br i1 %c, label %then, label %else

then:
  %1 = cmpxchg ptr %ptr, i32 %cmp, i32 %val seq_cst seq_cst
  %2 = extractvalue { i32, i1 } %1, 0
  br label %merge

else:
  %3 = load i32, ptr %ptr, align 4
  br label %merge

merge:
  %4 = phi i32 [ %2, %then ], [ %3, %else ]
  ret i32 %4
}
