; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=ysx64 %s -o - | FileCheck %s

define i64 @add(i64 %a, i64 %b) {
; CHECK-LABEL: add:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    add a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %c = add i64 %a, %b
  ret i64 %c
}

define i64 @mul(i64 %a, i64 %b) {
; CHECK-LABEL: mul:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mul a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %c = mul i64 %a, %b
  ret i64 %c
}
