; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ysx64 < %s | FileCheck %s -check-prefix=RV64I

; Check the PreserveMost calling convention works.

declare void @standard_cc_func()
declare preserve_mostcc void @preserve_mostcc_func()

define preserve_mostcc void @preserve_mostcc1() nounwind {
;
; RV64I-LABEL: preserve_mostcc1:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    addi sp, sp, -112
; RV64I-NEXT:    sd ra, 104(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd t0, 96(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd a0, 88(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd a1, 80(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd a2, 72(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd a3, 64(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd a4, 56(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd a5, 48(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd a6, 40(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd a7, 32(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd t4, 24(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd t5, 16(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd t6, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    call standard_cc_func
; RV64I-NEXT:    ld ra, 104(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld t0, 96(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld a0, 88(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld a1, 80(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld a2, 72(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld a3, 64(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld a4, 56(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld a5, 48(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld a6, 40(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld a7, 32(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld t4, 24(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld t5, 16(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld t6, 8(sp) # 8-byte Folded Reload
; RV64I-NEXT:    addi sp, sp, 112
; RV64I-NEXT:    ret
entry:
  call void @standard_cc_func()
  ret void
}

define preserve_mostcc void @preserve_mostcc2() nounwind {
;
; RV64I-LABEL: preserve_mostcc2:
; RV64I:       # %bb.0:
; RV64I-NEXT:    addi sp, sp, -16
; RV64I-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    call preserve_mostcc_func
; RV64I-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64I-NEXT:    addi sp, sp, 16
; RV64I-NEXT:    ret
  call preserve_mostcc void @preserve_mostcc_func()
  ret void
}

; X6, X7 and X28 will be saved to registers.
define void @preserve_mostcc3() nounwind {
;
; RV64I-LABEL: preserve_mostcc3:
; RV64I:       # %bb.0:
; RV64I-NEXT:    addi sp, sp, -32
; RV64I-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s1, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    #APP
; RV64I-NEXT:    #NO_APP
; RV64I-NEXT:    mv a0, t1
; RV64I-NEXT:    #APP
; RV64I-NEXT:    #NO_APP
; RV64I-NEXT:    mv a1, t2
; RV64I-NEXT:    #APP
; RV64I-NEXT:    #NO_APP
; RV64I-NEXT:    #APP
; RV64I-NEXT:    #NO_APP
; RV64I-NEXT:    #APP
; RV64I-NEXT:    #NO_APP
; RV64I-NEXT:    mv a2, t3
; RV64I-NEXT:    call preserve_mostcc_func
; RV64I-NEXT:    mv t1, a0
; RV64I-NEXT:    mv t2, a1
; RV64I-NEXT:    mv t3, a2
; RV64I-NEXT:    #APP
; RV64I-NEXT:    #NO_APP
; RV64I-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s1, 8(sp) # 8-byte Folded Reload
; RV64I-NEXT:    addi sp, sp, 32
; RV64I-NEXT:    ret
  %1 = call i32 asm sideeffect "", "={x6}"() nounwind
  %2 = call i32 asm sideeffect "", "={x7}"() nounwind
  %3 = call i32 asm sideeffect "", "={x8}"() nounwind
  %4 = call i32 asm sideeffect "", "={x9}"() nounwind
  %5 = call i32 asm sideeffect "", "={x28}"() nounwind
  call preserve_mostcc void @preserve_mostcc_func()
  call void asm sideeffect "", "{x6},{x7},{x8},{x9},{x28}"(i32 %1, i32 %2, i32 %3, i32 %4, i32 %5)
  ret void
}

; X6, X7 and X28 will be saved to the stack.
define void @preserve_mostcc4() nounwind {
;
; RV64I-LABEL: preserve_mostcc4:
; RV64I:       # %bb.0:
; RV64I-NEXT:    addi sp, sp, -48
; RV64I-NEXT:    sd ra, 40(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s0, 32(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s1, 24(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s2, 16(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s3, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s4, 0(sp) # 8-byte Folded Spill
; RV64I-NEXT:    #APP
; RV64I-NEXT:    #NO_APP
; RV64I-NEXT:    mv s2, t1
; RV64I-NEXT:    #APP
; RV64I-NEXT:    #NO_APP
; RV64I-NEXT:    mv s3, t2
; RV64I-NEXT:    #APP
; RV64I-NEXT:    #NO_APP
; RV64I-NEXT:    #APP
; RV64I-NEXT:    #NO_APP
; RV64I-NEXT:    #APP
; RV64I-NEXT:    #NO_APP
; RV64I-NEXT:    mv s4, t3
; RV64I-NEXT:    call standard_cc_func
; RV64I-NEXT:    mv t1, s2
; RV64I-NEXT:    mv t2, s3
; RV64I-NEXT:    mv t3, s4
; RV64I-NEXT:    #APP
; RV64I-NEXT:    #NO_APP
; RV64I-NEXT:    ld ra, 40(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s0, 32(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s1, 24(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s2, 16(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s3, 8(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s4, 0(sp) # 8-byte Folded Reload
; RV64I-NEXT:    addi sp, sp, 48
; RV64I-NEXT:    ret
  %1 = call i32 asm sideeffect "", "={x6}"() nounwind
  %2 = call i32 asm sideeffect "", "={x7}"() nounwind
  %3 = call i32 asm sideeffect "", "={x8}"() nounwind
  %4 = call i32 asm sideeffect "", "={x9}"() nounwind
  %5 = call i32 asm sideeffect "", "={x28}"() nounwind
  call void @standard_cc_func()
  call void asm sideeffect "", "{x6},{x7},{x8},{x9},{x28}"(i32 %1, i32 %2, i32 %3, i32 %4, i32 %5)
  ret void
}
