; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ysx64 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV64I
; RUN: llc -mtriple=ysx64 -verify-machineinstrs -frame-pointer=all < %s \
; RUN:   | FileCheck %s -check-prefix=RV64I-WITH-FP

@var = global [32 x i32] zeroinitializer

; This function tests that YSXRegisterInfo::getCalleeSavedRegs returns
; something appropriate.

define void @callee() {
;
;
;
;
;
; RV64I-LABEL: callee:
; RV64I:       # %bb.0:
; RV64I-NEXT:    addi sp, sp, -144
; RV64I-NEXT:    .cfi_def_cfa_offset 144
; RV64I-NEXT:    sd ra, 136(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s0, 128(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s1, 120(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s2, 112(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s3, 104(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s4, 96(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s5, 88(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s6, 80(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s7, 72(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s8, 64(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s9, 56(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s10, 48(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s11, 40(sp) # 8-byte Folded Spill
; RV64I-NEXT:    .cfi_offset ra, -8
; RV64I-NEXT:    .cfi_offset s0, -16
; RV64I-NEXT:    .cfi_offset s1, -24
; RV64I-NEXT:    .cfi_offset s2, -32
; RV64I-NEXT:    .cfi_offset s3, -40
; RV64I-NEXT:    .cfi_offset s4, -48
; RV64I-NEXT:    .cfi_offset s5, -56
; RV64I-NEXT:    .cfi_offset s6, -64
; RV64I-NEXT:    .cfi_offset s7, -72
; RV64I-NEXT:    .cfi_offset s8, -80
; RV64I-NEXT:    .cfi_offset s9, -88
; RV64I-NEXT:    .cfi_offset s10, -96
; RV64I-NEXT:    .cfi_offset s11, -104
; RV64I-NEXT:    lui a0, %hi(var)
; RV64I-NEXT:    addi a0, a0, %lo(var)
; RV64I-NEXT:    lw a1, 0(a0)
; RV64I-NEXT:    sd a1, 32(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lw a1, 4(a0)
; RV64I-NEXT:    sd a1, 24(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lw a1, 8(a0)
; RV64I-NEXT:    sd a1, 16(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lw a1, 12(a0)
; RV64I-NEXT:    sd a1, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lw a1, 16(a0)
; RV64I-NEXT:    sd a1, 0(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lw a6, 20(a0)
; RV64I-NEXT:    lw a7, 24(a0)
; RV64I-NEXT:    lw t0, 28(a0)
; RV64I-NEXT:    lw t1, 32(a0)
; RV64I-NEXT:    lw t2, 36(a0)
; RV64I-NEXT:    lw t3, 40(a0)
; RV64I-NEXT:    lw t4, 44(a0)
; RV64I-NEXT:    lw t5, 48(a0)
; RV64I-NEXT:    lw t6, 52(a0)
; RV64I-NEXT:    lw s0, 56(a0)
; RV64I-NEXT:    lw s1, 60(a0)
; RV64I-NEXT:    lw s2, 64(a0)
; RV64I-NEXT:    lw s3, 68(a0)
; RV64I-NEXT:    lw s4, 72(a0)
; RV64I-NEXT:    lw s5, 76(a0)
; RV64I-NEXT:    lw s6, 80(a0)
; RV64I-NEXT:    lw s7, 84(a0)
; RV64I-NEXT:    lw s8, 88(a0)
; RV64I-NEXT:    lw s9, 92(a0)
; RV64I-NEXT:    lw s10, 112(a0)
; RV64I-NEXT:    lw s11, 116(a0)
; RV64I-NEXT:    lw ra, 120(a0)
; RV64I-NEXT:    lw a1, 124(a0)
; RV64I-NEXT:    lw a5, 96(a0)
; RV64I-NEXT:    lw a4, 100(a0)
; RV64I-NEXT:    lw a3, 104(a0)
; RV64I-NEXT:    lw a2, 108(a0)
; RV64I-NEXT:    sw a1, 124(a0)
; RV64I-NEXT:    sw ra, 120(a0)
; RV64I-NEXT:    sw s11, 116(a0)
; RV64I-NEXT:    sw s10, 112(a0)
; RV64I-NEXT:    sw a2, 108(a0)
; RV64I-NEXT:    sw a3, 104(a0)
; RV64I-NEXT:    sw a4, 100(a0)
; RV64I-NEXT:    sw a5, 96(a0)
; RV64I-NEXT:    sw s9, 92(a0)
; RV64I-NEXT:    sw s8, 88(a0)
; RV64I-NEXT:    sw s7, 84(a0)
; RV64I-NEXT:    sw s6, 80(a0)
; RV64I-NEXT:    sw s5, 76(a0)
; RV64I-NEXT:    sw s4, 72(a0)
; RV64I-NEXT:    sw s3, 68(a0)
; RV64I-NEXT:    sw s2, 64(a0)
; RV64I-NEXT:    sw s1, 60(a0)
; RV64I-NEXT:    sw s0, 56(a0)
; RV64I-NEXT:    sw t6, 52(a0)
; RV64I-NEXT:    sw t5, 48(a0)
; RV64I-NEXT:    sw t4, 44(a0)
; RV64I-NEXT:    sw t3, 40(a0)
; RV64I-NEXT:    sw t2, 36(a0)
; RV64I-NEXT:    sw t1, 32(a0)
; RV64I-NEXT:    sw t0, 28(a0)
; RV64I-NEXT:    sw a7, 24(a0)
; RV64I-NEXT:    sw a6, 20(a0)
; RV64I-NEXT:    ld a1, 0(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sw a1, 16(a0)
; RV64I-NEXT:    ld a1, 8(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sw a1, 12(a0)
; RV64I-NEXT:    ld a1, 16(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sw a1, 8(a0)
; RV64I-NEXT:    ld a1, 24(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sw a1, 4(a0)
; RV64I-NEXT:    ld a1, 32(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sw a1, 0(a0)
; RV64I-NEXT:    ld ra, 136(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s0, 128(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s1, 120(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s2, 112(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s3, 104(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s4, 96(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s5, 88(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s6, 80(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s7, 72(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s8, 64(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s9, 56(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s10, 48(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s11, 40(sp) # 8-byte Folded Reload
; RV64I-NEXT:    .cfi_restore ra
; RV64I-NEXT:    .cfi_restore s0
; RV64I-NEXT:    .cfi_restore s1
; RV64I-NEXT:    .cfi_restore s2
; RV64I-NEXT:    .cfi_restore s3
; RV64I-NEXT:    .cfi_restore s4
; RV64I-NEXT:    .cfi_restore s5
; RV64I-NEXT:    .cfi_restore s6
; RV64I-NEXT:    .cfi_restore s7
; RV64I-NEXT:    .cfi_restore s8
; RV64I-NEXT:    .cfi_restore s9
; RV64I-NEXT:    .cfi_restore s10
; RV64I-NEXT:    .cfi_restore s11
; RV64I-NEXT:    addi sp, sp, 144
; RV64I-NEXT:    .cfi_def_cfa_offset 0
; RV64I-NEXT:    ret
;
; RV64I-WITH-FP-LABEL: callee:
; RV64I-WITH-FP:       # %bb.0:
; RV64I-WITH-FP-NEXT:    addi sp, sp, -160
; RV64I-WITH-FP-NEXT:    .cfi_def_cfa_offset 160
; RV64I-WITH-FP-NEXT:    sd ra, 152(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    sd s0, 144(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    sd s1, 136(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    sd s2, 128(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    sd s3, 120(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    sd s4, 112(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    sd s5, 104(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    sd s6, 96(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    sd s7, 88(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    sd s8, 80(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    sd s9, 72(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    sd s10, 64(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    sd s11, 56(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    .cfi_offset ra, -8
; RV64I-WITH-FP-NEXT:    .cfi_offset s0, -16
; RV64I-WITH-FP-NEXT:    .cfi_offset s1, -24
; RV64I-WITH-FP-NEXT:    .cfi_offset s2, -32
; RV64I-WITH-FP-NEXT:    .cfi_offset s3, -40
; RV64I-WITH-FP-NEXT:    .cfi_offset s4, -48
; RV64I-WITH-FP-NEXT:    .cfi_offset s5, -56
; RV64I-WITH-FP-NEXT:    .cfi_offset s6, -64
; RV64I-WITH-FP-NEXT:    .cfi_offset s7, -72
; RV64I-WITH-FP-NEXT:    .cfi_offset s8, -80
; RV64I-WITH-FP-NEXT:    .cfi_offset s9, -88
; RV64I-WITH-FP-NEXT:    .cfi_offset s10, -96
; RV64I-WITH-FP-NEXT:    .cfi_offset s11, -104
; RV64I-WITH-FP-NEXT:    addi s0, sp, 160
; RV64I-WITH-FP-NEXT:    .cfi_def_cfa s0, 0
; RV64I-WITH-FP-NEXT:    lui a0, %hi(var)
; RV64I-WITH-FP-NEXT:    addi a0, a0, %lo(var)
; RV64I-WITH-FP-NEXT:    lw a1, 0(a0)
; RV64I-WITH-FP-NEXT:    sd a1, -112(s0) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    lw a1, 4(a0)
; RV64I-WITH-FP-NEXT:    sd a1, -120(s0) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    lw a1, 8(a0)
; RV64I-WITH-FP-NEXT:    sd a1, -128(s0) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    lw a1, 12(a0)
; RV64I-WITH-FP-NEXT:    sd a1, -136(s0) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    lw a1, 16(a0)
; RV64I-WITH-FP-NEXT:    sd a1, -144(s0) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    lw a1, 20(a0)
; RV64I-WITH-FP-NEXT:    sd a1, -152(s0) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    lw a7, 24(a0)
; RV64I-WITH-FP-NEXT:    lw t0, 28(a0)
; RV64I-WITH-FP-NEXT:    lw t1, 32(a0)
; RV64I-WITH-FP-NEXT:    lw t2, 36(a0)
; RV64I-WITH-FP-NEXT:    lw t3, 40(a0)
; RV64I-WITH-FP-NEXT:    lw t4, 44(a0)
; RV64I-WITH-FP-NEXT:    lw t5, 48(a0)
; RV64I-WITH-FP-NEXT:    lw t6, 52(a0)
; RV64I-WITH-FP-NEXT:    lw s1, 56(a0)
; RV64I-WITH-FP-NEXT:    lw s2, 60(a0)
; RV64I-WITH-FP-NEXT:    lw s3, 64(a0)
; RV64I-WITH-FP-NEXT:    lw s4, 68(a0)
; RV64I-WITH-FP-NEXT:    lw s5, 72(a0)
; RV64I-WITH-FP-NEXT:    lw s6, 76(a0)
; RV64I-WITH-FP-NEXT:    lw s7, 80(a0)
; RV64I-WITH-FP-NEXT:    lw s8, 84(a0)
; RV64I-WITH-FP-NEXT:    lw s9, 88(a0)
; RV64I-WITH-FP-NEXT:    lw s10, 92(a0)
; RV64I-WITH-FP-NEXT:    lw s11, 112(a0)
; RV64I-WITH-FP-NEXT:    lw ra, 116(a0)
; RV64I-WITH-FP-NEXT:    lw a4, 120(a0)
; RV64I-WITH-FP-NEXT:    lw a1, 124(a0)
; RV64I-WITH-FP-NEXT:    lw a6, 96(a0)
; RV64I-WITH-FP-NEXT:    lw a5, 100(a0)
; RV64I-WITH-FP-NEXT:    lw a3, 104(a0)
; RV64I-WITH-FP-NEXT:    lw a2, 108(a0)
; RV64I-WITH-FP-NEXT:    sw a1, 124(a0)
; RV64I-WITH-FP-NEXT:    sw a4, 120(a0)
; RV64I-WITH-FP-NEXT:    sw ra, 116(a0)
; RV64I-WITH-FP-NEXT:    sw s11, 112(a0)
; RV64I-WITH-FP-NEXT:    sw a2, 108(a0)
; RV64I-WITH-FP-NEXT:    sw a3, 104(a0)
; RV64I-WITH-FP-NEXT:    sw a5, 100(a0)
; RV64I-WITH-FP-NEXT:    sw a6, 96(a0)
; RV64I-WITH-FP-NEXT:    sw s10, 92(a0)
; RV64I-WITH-FP-NEXT:    sw s9, 88(a0)
; RV64I-WITH-FP-NEXT:    sw s8, 84(a0)
; RV64I-WITH-FP-NEXT:    sw s7, 80(a0)
; RV64I-WITH-FP-NEXT:    sw s6, 76(a0)
; RV64I-WITH-FP-NEXT:    sw s5, 72(a0)
; RV64I-WITH-FP-NEXT:    sw s4, 68(a0)
; RV64I-WITH-FP-NEXT:    sw s3, 64(a0)
; RV64I-WITH-FP-NEXT:    sw s2, 60(a0)
; RV64I-WITH-FP-NEXT:    sw s1, 56(a0)
; RV64I-WITH-FP-NEXT:    sw t6, 52(a0)
; RV64I-WITH-FP-NEXT:    sw t5, 48(a0)
; RV64I-WITH-FP-NEXT:    sw t4, 44(a0)
; RV64I-WITH-FP-NEXT:    sw t3, 40(a0)
; RV64I-WITH-FP-NEXT:    sw t2, 36(a0)
; RV64I-WITH-FP-NEXT:    sw t1, 32(a0)
; RV64I-WITH-FP-NEXT:    sw t0, 28(a0)
; RV64I-WITH-FP-NEXT:    sw a7, 24(a0)
; RV64I-WITH-FP-NEXT:    ld a1, -152(s0) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    sw a1, 20(a0)
; RV64I-WITH-FP-NEXT:    ld a1, -144(s0) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    sw a1, 16(a0)
; RV64I-WITH-FP-NEXT:    ld a1, -136(s0) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    sw a1, 12(a0)
; RV64I-WITH-FP-NEXT:    ld a1, -128(s0) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    sw a1, 8(a0)
; RV64I-WITH-FP-NEXT:    ld a1, -120(s0) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    sw a1, 4(a0)
; RV64I-WITH-FP-NEXT:    ld a1, -112(s0) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    sw a1, 0(a0)
; RV64I-WITH-FP-NEXT:    .cfi_def_cfa sp, 160
; RV64I-WITH-FP-NEXT:    ld ra, 152(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    ld s0, 144(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    ld s1, 136(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    ld s2, 128(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    ld s3, 120(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    ld s4, 112(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    ld s5, 104(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    ld s6, 96(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    ld s7, 88(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    ld s8, 80(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    ld s9, 72(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    ld s10, 64(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    ld s11, 56(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    .cfi_restore ra
; RV64I-WITH-FP-NEXT:    .cfi_restore s0
; RV64I-WITH-FP-NEXT:    .cfi_restore s1
; RV64I-WITH-FP-NEXT:    .cfi_restore s2
; RV64I-WITH-FP-NEXT:    .cfi_restore s3
; RV64I-WITH-FP-NEXT:    .cfi_restore s4
; RV64I-WITH-FP-NEXT:    .cfi_restore s5
; RV64I-WITH-FP-NEXT:    .cfi_restore s6
; RV64I-WITH-FP-NEXT:    .cfi_restore s7
; RV64I-WITH-FP-NEXT:    .cfi_restore s8
; RV64I-WITH-FP-NEXT:    .cfi_restore s9
; RV64I-WITH-FP-NEXT:    .cfi_restore s10
; RV64I-WITH-FP-NEXT:    .cfi_restore s11
; RV64I-WITH-FP-NEXT:    addi sp, sp, 160
; RV64I-WITH-FP-NEXT:    .cfi_def_cfa_offset 0
; RV64I-WITH-FP-NEXT:    ret
  %val = load [32 x i32], ptr @var
  store volatile [32 x i32] %val, ptr @var
  ret void
}

; This function tests that YSXRegisterInfo::getCallPreservedMask returns
; something appropriate.

define void @caller() {
;
;
;
;
;
; RV64I-LABEL: caller:
; RV64I:       # %bb.0:
; RV64I-NEXT:    addi sp, sp, -272
; RV64I-NEXT:    .cfi_def_cfa_offset 272
; RV64I-NEXT:    sd ra, 264(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s0, 256(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s1, 248(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s2, 240(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s3, 232(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s4, 224(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s5, 216(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s6, 208(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s7, 200(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s8, 192(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s9, 184(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s10, 176(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s11, 168(sp) # 8-byte Folded Spill
; RV64I-NEXT:    .cfi_offset ra, -8
; RV64I-NEXT:    .cfi_offset s0, -16
; RV64I-NEXT:    .cfi_offset s1, -24
; RV64I-NEXT:    .cfi_offset s2, -32
; RV64I-NEXT:    .cfi_offset s3, -40
; RV64I-NEXT:    .cfi_offset s4, -48
; RV64I-NEXT:    .cfi_offset s5, -56
; RV64I-NEXT:    .cfi_offset s6, -64
; RV64I-NEXT:    .cfi_offset s7, -72
; RV64I-NEXT:    .cfi_offset s8, -80
; RV64I-NEXT:    .cfi_offset s9, -88
; RV64I-NEXT:    .cfi_offset s10, -96
; RV64I-NEXT:    .cfi_offset s11, -104
; RV64I-NEXT:    lui s0, %hi(var)
; RV64I-NEXT:    addi s0, s0, %lo(var)
; RV64I-NEXT:    lw a0, 0(s0)
; RV64I-NEXT:    sd a0, 160(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lw a0, 4(s0)
; RV64I-NEXT:    sd a0, 152(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lw a0, 8(s0)
; RV64I-NEXT:    sd a0, 144(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lw a0, 12(s0)
; RV64I-NEXT:    sd a0, 136(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lw a0, 16(s0)
; RV64I-NEXT:    sd a0, 128(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lw a0, 20(s0)
; RV64I-NEXT:    sd a0, 120(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lw a0, 24(s0)
; RV64I-NEXT:    sd a0, 112(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lw a0, 28(s0)
; RV64I-NEXT:    sd a0, 104(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lw a0, 32(s0)
; RV64I-NEXT:    sd a0, 96(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lw a0, 36(s0)
; RV64I-NEXT:    sd a0, 88(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lw a0, 40(s0)
; RV64I-NEXT:    sd a0, 80(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lw a0, 44(s0)
; RV64I-NEXT:    sd a0, 72(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lw a0, 48(s0)
; RV64I-NEXT:    sd a0, 64(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lw a0, 52(s0)
; RV64I-NEXT:    sd a0, 56(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lw a0, 56(s0)
; RV64I-NEXT:    sd a0, 48(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lw a0, 60(s0)
; RV64I-NEXT:    sd a0, 40(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lw a0, 64(s0)
; RV64I-NEXT:    sd a0, 32(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lw a0, 68(s0)
; RV64I-NEXT:    sd a0, 24(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lw a0, 72(s0)
; RV64I-NEXT:    sd a0, 16(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lw a0, 76(s0)
; RV64I-NEXT:    sd a0, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lw a0, 80(s0)
; RV64I-NEXT:    sd a0, 0(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lw s11, 84(s0)
; RV64I-NEXT:    lw s1, 88(s0)
; RV64I-NEXT:    lw s2, 92(s0)
; RV64I-NEXT:    lw s3, 96(s0)
; RV64I-NEXT:    lw s4, 100(s0)
; RV64I-NEXT:    lw s5, 104(s0)
; RV64I-NEXT:    lw s6, 108(s0)
; RV64I-NEXT:    lw s7, 112(s0)
; RV64I-NEXT:    lw s8, 116(s0)
; RV64I-NEXT:    lw s9, 120(s0)
; RV64I-NEXT:    lw s10, 124(s0)
; RV64I-NEXT:    call callee
; RV64I-NEXT:    sw s10, 124(s0)
; RV64I-NEXT:    sw s9, 120(s0)
; RV64I-NEXT:    sw s8, 116(s0)
; RV64I-NEXT:    sw s7, 112(s0)
; RV64I-NEXT:    sw s6, 108(s0)
; RV64I-NEXT:    sw s5, 104(s0)
; RV64I-NEXT:    sw s4, 100(s0)
; RV64I-NEXT:    sw s3, 96(s0)
; RV64I-NEXT:    sw s2, 92(s0)
; RV64I-NEXT:    sw s1, 88(s0)
; RV64I-NEXT:    sw s11, 84(s0)
; RV64I-NEXT:    ld a0, 0(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sw a0, 80(s0)
; RV64I-NEXT:    ld a0, 8(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sw a0, 76(s0)
; RV64I-NEXT:    ld a0, 16(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sw a0, 72(s0)
; RV64I-NEXT:    ld a0, 24(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sw a0, 68(s0)
; RV64I-NEXT:    ld a0, 32(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sw a0, 64(s0)
; RV64I-NEXT:    ld a0, 40(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sw a0, 60(s0)
; RV64I-NEXT:    ld a0, 48(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sw a0, 56(s0)
; RV64I-NEXT:    ld a0, 56(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sw a0, 52(s0)
; RV64I-NEXT:    ld a0, 64(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sw a0, 48(s0)
; RV64I-NEXT:    ld a0, 72(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sw a0, 44(s0)
; RV64I-NEXT:    ld a0, 80(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sw a0, 40(s0)
; RV64I-NEXT:    ld a0, 88(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sw a0, 36(s0)
; RV64I-NEXT:    ld a0, 96(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sw a0, 32(s0)
; RV64I-NEXT:    ld a0, 104(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sw a0, 28(s0)
; RV64I-NEXT:    ld a0, 112(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sw a0, 24(s0)
; RV64I-NEXT:    ld a0, 120(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sw a0, 20(s0)
; RV64I-NEXT:    ld a0, 128(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sw a0, 16(s0)
; RV64I-NEXT:    ld a0, 136(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sw a0, 12(s0)
; RV64I-NEXT:    ld a0, 144(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sw a0, 8(s0)
; RV64I-NEXT:    ld a0, 152(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sw a0, 4(s0)
; RV64I-NEXT:    ld a0, 160(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sw a0, 0(s0)
; RV64I-NEXT:    ld ra, 264(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s0, 256(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s1, 248(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s2, 240(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s3, 232(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s4, 224(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s5, 216(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s6, 208(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s7, 200(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s8, 192(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s9, 184(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s10, 176(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s11, 168(sp) # 8-byte Folded Reload
; RV64I-NEXT:    .cfi_restore ra
; RV64I-NEXT:    .cfi_restore s0
; RV64I-NEXT:    .cfi_restore s1
; RV64I-NEXT:    .cfi_restore s2
; RV64I-NEXT:    .cfi_restore s3
; RV64I-NEXT:    .cfi_restore s4
; RV64I-NEXT:    .cfi_restore s5
; RV64I-NEXT:    .cfi_restore s6
; RV64I-NEXT:    .cfi_restore s7
; RV64I-NEXT:    .cfi_restore s8
; RV64I-NEXT:    .cfi_restore s9
; RV64I-NEXT:    .cfi_restore s10
; RV64I-NEXT:    .cfi_restore s11
; RV64I-NEXT:    addi sp, sp, 272
; RV64I-NEXT:    .cfi_def_cfa_offset 0
; RV64I-NEXT:    ret
;
; RV64I-WITH-FP-LABEL: caller:
; RV64I-WITH-FP:       # %bb.0:
; RV64I-WITH-FP-NEXT:    addi sp, sp, -288
; RV64I-WITH-FP-NEXT:    .cfi_def_cfa_offset 288
; RV64I-WITH-FP-NEXT:    sd ra, 280(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    sd s0, 272(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    sd s1, 264(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    sd s2, 256(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    sd s3, 248(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    sd s4, 240(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    sd s5, 232(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    sd s6, 224(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    sd s7, 216(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    sd s8, 208(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    sd s9, 200(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    sd s10, 192(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    sd s11, 184(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    .cfi_offset ra, -8
; RV64I-WITH-FP-NEXT:    .cfi_offset s0, -16
; RV64I-WITH-FP-NEXT:    .cfi_offset s1, -24
; RV64I-WITH-FP-NEXT:    .cfi_offset s2, -32
; RV64I-WITH-FP-NEXT:    .cfi_offset s3, -40
; RV64I-WITH-FP-NEXT:    .cfi_offset s4, -48
; RV64I-WITH-FP-NEXT:    .cfi_offset s5, -56
; RV64I-WITH-FP-NEXT:    .cfi_offset s6, -64
; RV64I-WITH-FP-NEXT:    .cfi_offset s7, -72
; RV64I-WITH-FP-NEXT:    .cfi_offset s8, -80
; RV64I-WITH-FP-NEXT:    .cfi_offset s9, -88
; RV64I-WITH-FP-NEXT:    .cfi_offset s10, -96
; RV64I-WITH-FP-NEXT:    .cfi_offset s11, -104
; RV64I-WITH-FP-NEXT:    addi s0, sp, 288
; RV64I-WITH-FP-NEXT:    .cfi_def_cfa s0, 0
; RV64I-WITH-FP-NEXT:    lui s1, %hi(var)
; RV64I-WITH-FP-NEXT:    addi s1, s1, %lo(var)
; RV64I-WITH-FP-NEXT:    lw a0, 0(s1)
; RV64I-WITH-FP-NEXT:    sd a0, -112(s0) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    lw a0, 4(s1)
; RV64I-WITH-FP-NEXT:    sd a0, -120(s0) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    lw a0, 8(s1)
; RV64I-WITH-FP-NEXT:    sd a0, -128(s0) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    lw a0, 12(s1)
; RV64I-WITH-FP-NEXT:    sd a0, -136(s0) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    lw a0, 16(s1)
; RV64I-WITH-FP-NEXT:    sd a0, -144(s0) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    lw a0, 20(s1)
; RV64I-WITH-FP-NEXT:    sd a0, -152(s0) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    lw a0, 24(s1)
; RV64I-WITH-FP-NEXT:    sd a0, -160(s0) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    lw a0, 28(s1)
; RV64I-WITH-FP-NEXT:    sd a0, -168(s0) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    lw a0, 32(s1)
; RV64I-WITH-FP-NEXT:    sd a0, -176(s0) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    lw a0, 36(s1)
; RV64I-WITH-FP-NEXT:    sd a0, -184(s0) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    lw a0, 40(s1)
; RV64I-WITH-FP-NEXT:    sd a0, -192(s0) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    lw a0, 44(s1)
; RV64I-WITH-FP-NEXT:    sd a0, -200(s0) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    lw a0, 48(s1)
; RV64I-WITH-FP-NEXT:    sd a0, -208(s0) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    lw a0, 52(s1)
; RV64I-WITH-FP-NEXT:    sd a0, -216(s0) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    lw a0, 56(s1)
; RV64I-WITH-FP-NEXT:    sd a0, -224(s0) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    lw a0, 60(s1)
; RV64I-WITH-FP-NEXT:    sd a0, -232(s0) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    lw a0, 64(s1)
; RV64I-WITH-FP-NEXT:    sd a0, -240(s0) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    lw a0, 68(s1)
; RV64I-WITH-FP-NEXT:    sd a0, -248(s0) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    lw a0, 72(s1)
; RV64I-WITH-FP-NEXT:    sd a0, -256(s0) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    lw a0, 76(s1)
; RV64I-WITH-FP-NEXT:    sd a0, -264(s0) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    lw a0, 80(s1)
; RV64I-WITH-FP-NEXT:    sd a0, -272(s0) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    lw a0, 84(s1)
; RV64I-WITH-FP-NEXT:    sd a0, -280(s0) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    lw s4, 88(s1)
; RV64I-WITH-FP-NEXT:    lw s5, 92(s1)
; RV64I-WITH-FP-NEXT:    lw s6, 96(s1)
; RV64I-WITH-FP-NEXT:    lw s7, 100(s1)
; RV64I-WITH-FP-NEXT:    lw s8, 104(s1)
; RV64I-WITH-FP-NEXT:    lw s9, 108(s1)
; RV64I-WITH-FP-NEXT:    lw s10, 112(s1)
; RV64I-WITH-FP-NEXT:    lw s11, 116(s1)
; RV64I-WITH-FP-NEXT:    lw s2, 120(s1)
; RV64I-WITH-FP-NEXT:    lw s3, 124(s1)
; RV64I-WITH-FP-NEXT:    call callee
; RV64I-WITH-FP-NEXT:    sw s3, 124(s1)
; RV64I-WITH-FP-NEXT:    sw s2, 120(s1)
; RV64I-WITH-FP-NEXT:    sw s11, 116(s1)
; RV64I-WITH-FP-NEXT:    sw s10, 112(s1)
; RV64I-WITH-FP-NEXT:    sw s9, 108(s1)
; RV64I-WITH-FP-NEXT:    sw s8, 104(s1)
; RV64I-WITH-FP-NEXT:    sw s7, 100(s1)
; RV64I-WITH-FP-NEXT:    sw s6, 96(s1)
; RV64I-WITH-FP-NEXT:    sw s5, 92(s1)
; RV64I-WITH-FP-NEXT:    sw s4, 88(s1)
; RV64I-WITH-FP-NEXT:    ld a0, -280(s0) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    sw a0, 84(s1)
; RV64I-WITH-FP-NEXT:    ld a0, -272(s0) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    sw a0, 80(s1)
; RV64I-WITH-FP-NEXT:    ld a0, -264(s0) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    sw a0, 76(s1)
; RV64I-WITH-FP-NEXT:    ld a0, -256(s0) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    sw a0, 72(s1)
; RV64I-WITH-FP-NEXT:    ld a0, -248(s0) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    sw a0, 68(s1)
; RV64I-WITH-FP-NEXT:    ld a0, -240(s0) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    sw a0, 64(s1)
; RV64I-WITH-FP-NEXT:    ld a0, -232(s0) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    sw a0, 60(s1)
; RV64I-WITH-FP-NEXT:    ld a0, -224(s0) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    sw a0, 56(s1)
; RV64I-WITH-FP-NEXT:    ld a0, -216(s0) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    sw a0, 52(s1)
; RV64I-WITH-FP-NEXT:    ld a0, -208(s0) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    sw a0, 48(s1)
; RV64I-WITH-FP-NEXT:    ld a0, -200(s0) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    sw a0, 44(s1)
; RV64I-WITH-FP-NEXT:    ld a0, -192(s0) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    sw a0, 40(s1)
; RV64I-WITH-FP-NEXT:    ld a0, -184(s0) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    sw a0, 36(s1)
; RV64I-WITH-FP-NEXT:    ld a0, -176(s0) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    sw a0, 32(s1)
; RV64I-WITH-FP-NEXT:    ld a0, -168(s0) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    sw a0, 28(s1)
; RV64I-WITH-FP-NEXT:    ld a0, -160(s0) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    sw a0, 24(s1)
; RV64I-WITH-FP-NEXT:    ld a0, -152(s0) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    sw a0, 20(s1)
; RV64I-WITH-FP-NEXT:    ld a0, -144(s0) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    sw a0, 16(s1)
; RV64I-WITH-FP-NEXT:    ld a0, -136(s0) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    sw a0, 12(s1)
; RV64I-WITH-FP-NEXT:    ld a0, -128(s0) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    sw a0, 8(s1)
; RV64I-WITH-FP-NEXT:    ld a0, -120(s0) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    sw a0, 4(s1)
; RV64I-WITH-FP-NEXT:    ld a0, -112(s0) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    sw a0, 0(s1)
; RV64I-WITH-FP-NEXT:    .cfi_def_cfa sp, 288
; RV64I-WITH-FP-NEXT:    ld ra, 280(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    ld s0, 272(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    ld s1, 264(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    ld s2, 256(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    ld s3, 248(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    ld s4, 240(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    ld s5, 232(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    ld s6, 224(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    ld s7, 216(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    ld s8, 208(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    ld s9, 200(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    ld s10, 192(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    ld s11, 184(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    .cfi_restore ra
; RV64I-WITH-FP-NEXT:    .cfi_restore s0
; RV64I-WITH-FP-NEXT:    .cfi_restore s1
; RV64I-WITH-FP-NEXT:    .cfi_restore s2
; RV64I-WITH-FP-NEXT:    .cfi_restore s3
; RV64I-WITH-FP-NEXT:    .cfi_restore s4
; RV64I-WITH-FP-NEXT:    .cfi_restore s5
; RV64I-WITH-FP-NEXT:    .cfi_restore s6
; RV64I-WITH-FP-NEXT:    .cfi_restore s7
; RV64I-WITH-FP-NEXT:    .cfi_restore s8
; RV64I-WITH-FP-NEXT:    .cfi_restore s9
; RV64I-WITH-FP-NEXT:    .cfi_restore s10
; RV64I-WITH-FP-NEXT:    .cfi_restore s11
; RV64I-WITH-FP-NEXT:    addi sp, sp, 288
; RV64I-WITH-FP-NEXT:    .cfi_def_cfa_offset 0
; RV64I-WITH-FP-NEXT:    ret
  %val = load [32 x i32], ptr @var
  call void @callee()
  store volatile [32 x i32] %val, ptr @var
  ret void
}

; This function tests if the stack size is correctly calculated when
; callee-saved registers are not a sequential list from $ra
define void @foo() {
;
;
;
;
;
; RV64I-LABEL: foo:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    addi sp, sp, -16
; RV64I-NEXT:    .cfi_def_cfa_offset 16
; RV64I-NEXT:    sd s4, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    .cfi_offset s4, -8
; RV64I-NEXT:    #APP
; RV64I-NEXT:    li s4, 0
; RV64I-NEXT:    #NO_APP
; RV64I-NEXT:    ld s4, 8(sp) # 8-byte Folded Reload
; RV64I-NEXT:    .cfi_restore s4
; RV64I-NEXT:    addi sp, sp, 16
; RV64I-NEXT:    .cfi_def_cfa_offset 0
; RV64I-NEXT:    ret
;
; RV64I-WITH-FP-LABEL: foo:
; RV64I-WITH-FP:       # %bb.0: # %entry
; RV64I-WITH-FP-NEXT:    addi sp, sp, -32
; RV64I-WITH-FP-NEXT:    .cfi_def_cfa_offset 32
; RV64I-WITH-FP-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    sd s4, 8(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    .cfi_offset ra, -8
; RV64I-WITH-FP-NEXT:    .cfi_offset s0, -16
; RV64I-WITH-FP-NEXT:    .cfi_offset s4, -24
; RV64I-WITH-FP-NEXT:    addi s0, sp, 32
; RV64I-WITH-FP-NEXT:    .cfi_def_cfa s0, 0
; RV64I-WITH-FP-NEXT:    #APP
; RV64I-WITH-FP-NEXT:    li s4, 0
; RV64I-WITH-FP-NEXT:    #NO_APP
; RV64I-WITH-FP-NEXT:    .cfi_def_cfa sp, 32
; RV64I-WITH-FP-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    ld s4, 8(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    .cfi_restore ra
; RV64I-WITH-FP-NEXT:    .cfi_restore s0
; RV64I-WITH-FP-NEXT:    .cfi_restore s4
; RV64I-WITH-FP-NEXT:    addi sp, sp, 32
; RV64I-WITH-FP-NEXT:    .cfi_def_cfa_offset 0
; RV64I-WITH-FP-NEXT:    ret
entry:
  tail call void asm sideeffect "li s4, 0", "~{s4}"()
  ret void
}

; Check .cfi_offset of s11 is correct.
define void @bar() {
;
;
;
;
;
; RV64I-LABEL: bar:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    addi sp, sp, -16
; RV64I-NEXT:    .cfi_def_cfa_offset 16
; RV64I-NEXT:    sd s11, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    .cfi_offset s11, -8
; RV64I-NEXT:    #APP
; RV64I-NEXT:    li s11, 0
; RV64I-NEXT:    #NO_APP
; RV64I-NEXT:    ld s11, 8(sp) # 8-byte Folded Reload
; RV64I-NEXT:    .cfi_restore s11
; RV64I-NEXT:    addi sp, sp, 16
; RV64I-NEXT:    .cfi_def_cfa_offset 0
; RV64I-NEXT:    ret
;
; RV64I-WITH-FP-LABEL: bar:
; RV64I-WITH-FP:       # %bb.0: # %entry
; RV64I-WITH-FP-NEXT:    addi sp, sp, -32
; RV64I-WITH-FP-NEXT:    .cfi_def_cfa_offset 32
; RV64I-WITH-FP-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    sd s11, 8(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    .cfi_offset ra, -8
; RV64I-WITH-FP-NEXT:    .cfi_offset s0, -16
; RV64I-WITH-FP-NEXT:    .cfi_offset s11, -24
; RV64I-WITH-FP-NEXT:    addi s0, sp, 32
; RV64I-WITH-FP-NEXT:    .cfi_def_cfa s0, 0
; RV64I-WITH-FP-NEXT:    #APP
; RV64I-WITH-FP-NEXT:    li s11, 0
; RV64I-WITH-FP-NEXT:    #NO_APP
; RV64I-WITH-FP-NEXT:    .cfi_def_cfa sp, 32
; RV64I-WITH-FP-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    ld s11, 8(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    .cfi_restore ra
; RV64I-WITH-FP-NEXT:    .cfi_restore s0
; RV64I-WITH-FP-NEXT:    .cfi_restore s11
; RV64I-WITH-FP-NEXT:    addi sp, sp, 32
; RV64I-WITH-FP-NEXT:    .cfi_def_cfa_offset 0
; RV64I-WITH-FP-NEXT:    ret
entry:
  tail call void asm sideeffect "li s11, 0", "~{s11}"()
  ret void
}

define void @varargs(...) {
;
;
;
;
;
; RV64I-LABEL: varargs:
; RV64I:       # %bb.0:
; RV64I-NEXT:    addi sp, sp, -80
; RV64I-NEXT:    .cfi_def_cfa_offset 80
; RV64I-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    .cfi_offset ra, -72
; RV64I-NEXT:    sd a4, 48(sp)
; RV64I-NEXT:    sd a5, 56(sp)
; RV64I-NEXT:    sd a6, 64(sp)
; RV64I-NEXT:    sd a7, 72(sp)
; RV64I-NEXT:    sd a0, 16(sp)
; RV64I-NEXT:    sd a1, 24(sp)
; RV64I-NEXT:    sd a2, 32(sp)
; RV64I-NEXT:    sd a3, 40(sp)
; RV64I-NEXT:    call callee
; RV64I-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64I-NEXT:    .cfi_restore ra
; RV64I-NEXT:    addi sp, sp, 80
; RV64I-NEXT:    .cfi_def_cfa_offset 0
; RV64I-NEXT:    ret
;
; RV64I-WITH-FP-LABEL: varargs:
; RV64I-WITH-FP:       # %bb.0:
; RV64I-WITH-FP-NEXT:    addi sp, sp, -80
; RV64I-WITH-FP-NEXT:    .cfi_def_cfa_offset 80
; RV64I-WITH-FP-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    sd s0, 0(sp) # 8-byte Folded Spill
; RV64I-WITH-FP-NEXT:    .cfi_offset ra, -72
; RV64I-WITH-FP-NEXT:    .cfi_offset s0, -80
; RV64I-WITH-FP-NEXT:    addi s0, sp, 16
; RV64I-WITH-FP-NEXT:    .cfi_def_cfa s0, 64
; RV64I-WITH-FP-NEXT:    sd a4, 32(s0)
; RV64I-WITH-FP-NEXT:    sd a5, 40(s0)
; RV64I-WITH-FP-NEXT:    sd a6, 48(s0)
; RV64I-WITH-FP-NEXT:    sd a7, 56(s0)
; RV64I-WITH-FP-NEXT:    sd a0, 0(s0)
; RV64I-WITH-FP-NEXT:    sd a1, 8(s0)
; RV64I-WITH-FP-NEXT:    sd a2, 16(s0)
; RV64I-WITH-FP-NEXT:    sd a3, 24(s0)
; RV64I-WITH-FP-NEXT:    call callee
; RV64I-WITH-FP-NEXT:    .cfi_def_cfa sp, 80
; RV64I-WITH-FP-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    ld s0, 0(sp) # 8-byte Folded Reload
; RV64I-WITH-FP-NEXT:    .cfi_restore ra
; RV64I-WITH-FP-NEXT:    .cfi_restore s0
; RV64I-WITH-FP-NEXT:    addi sp, sp, 80
; RV64I-WITH-FP-NEXT:    .cfi_def_cfa_offset 0
; RV64I-WITH-FP-NEXT:    ret
  call void @callee()
  ret void
}
