; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ysx64 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefixes=RV64I
; RUN: llc -mtriple=ysx64 -mattr=+m -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefixes=RV64M

define i8 @test_cttz_i8(i8 %a) nounwind {
;
; RV64I-LABEL: test_cttz_i8:
; RV64I:       # %bb.0:
; RV64I-NEXT:    zext.b a1, a0
; RV64I-NEXT:    beqz a1, .LBB0_2
; RV64I-NEXT:  # %bb.1: # %cond.false
; RV64I-NEXT:    addiw a1, a0, -1
; RV64I-NEXT:    not a0, a0
; RV64I-NEXT:    and a0, a0, a1
; RV64I-NEXT:    srli a1, a0, 1
; RV64I-NEXT:    andi a1, a1, 85
; RV64I-NEXT:    subw a0, a0, a1
; RV64I-NEXT:    andi a1, a0, 51
; RV64I-NEXT:    srli a0, a0, 2
; RV64I-NEXT:    andi a0, a0, 51
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    srli a1, a0, 4
; RV64I-NEXT:    addw a0, a0, a1
; RV64I-NEXT:    andi a0, a0, 15
; RV64I-NEXT:    ret
; RV64I-NEXT:  .LBB0_2:
; RV64I-NEXT:    li a0, 8
; RV64I-NEXT:    ret
;
; RV64M-LABEL: test_cttz_i8:
; RV64M:       # %bb.0:
; RV64M-NEXT:    zext.b a1, a0
; RV64M-NEXT:    beqz a1, .LBB0_2
; RV64M-NEXT:  # %bb.1: # %cond.false
; RV64M-NEXT:    addiw a1, a0, -1
; RV64M-NEXT:    not a0, a0
; RV64M-NEXT:    and a0, a0, a1
; RV64M-NEXT:    srli a1, a0, 1
; RV64M-NEXT:    andi a1, a1, 85
; RV64M-NEXT:    subw a0, a0, a1
; RV64M-NEXT:    andi a1, a0, 51
; RV64M-NEXT:    srli a0, a0, 2
; RV64M-NEXT:    andi a0, a0, 51
; RV64M-NEXT:    add a0, a1, a0
; RV64M-NEXT:    srli a1, a0, 4
; RV64M-NEXT:    addw a0, a0, a1
; RV64M-NEXT:    andi a0, a0, 15
; RV64M-NEXT:    ret
; RV64M-NEXT:  .LBB0_2:
; RV64M-NEXT:    li a0, 8
; RV64M-NEXT:    ret
  %tmp = call i8 @llvm.cttz.i8(i8 %a, i1 false)
  ret i8 %tmp
}

define i16 @test_cttz_i16(i16 %a) nounwind {
;
; RV64I-LABEL: test_cttz_i16:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a1, a0, 48
; RV64I-NEXT:    beqz a1, .LBB1_2
; RV64I-NEXT:  # %bb.1: # %cond.false
; RV64I-NEXT:    addi a1, a0, -1
; RV64I-NEXT:    not a0, a0
; RV64I-NEXT:    lui a2, 5
; RV64I-NEXT:    and a0, a0, a1
; RV64I-NEXT:    addi a1, a2, 1365
; RV64I-NEXT:    srli a2, a0, 1
; RV64I-NEXT:    and a1, a2, a1
; RV64I-NEXT:    lui a2, 3
; RV64I-NEXT:    addi a2, a2, 819
; RV64I-NEXT:    sub a0, a0, a1
; RV64I-NEXT:    and a1, a0, a2
; RV64I-NEXT:    srli a0, a0, 2
; RV64I-NEXT:    and a0, a0, a2
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    srli a1, a0, 4
; RV64I-NEXT:    addw a0, a0, a1
; RV64I-NEXT:    andi a1, a0, 15
; RV64I-NEXT:    slli a0, a0, 52
; RV64I-NEXT:    srli a0, a0, 60
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    ret
; RV64I-NEXT:  .LBB1_2:
; RV64I-NEXT:    li a0, 16
; RV64I-NEXT:    ret
;
; RV64M-LABEL: test_cttz_i16:
; RV64M:       # %bb.0:
; RV64M-NEXT:    slli a1, a0, 48
; RV64M-NEXT:    beqz a1, .LBB1_2
; RV64M-NEXT:  # %bb.1: # %cond.false
; RV64M-NEXT:    addi a1, a0, -1
; RV64M-NEXT:    not a0, a0
; RV64M-NEXT:    lui a2, 5
; RV64M-NEXT:    and a0, a0, a1
; RV64M-NEXT:    addi a1, a2, 1365
; RV64M-NEXT:    srli a2, a0, 1
; RV64M-NEXT:    and a1, a2, a1
; RV64M-NEXT:    lui a2, 3
; RV64M-NEXT:    addi a2, a2, 819
; RV64M-NEXT:    sub a0, a0, a1
; RV64M-NEXT:    and a1, a0, a2
; RV64M-NEXT:    srli a0, a0, 2
; RV64M-NEXT:    and a0, a0, a2
; RV64M-NEXT:    add a0, a1, a0
; RV64M-NEXT:    srli a1, a0, 4
; RV64M-NEXT:    addw a0, a0, a1
; RV64M-NEXT:    andi a1, a0, 15
; RV64M-NEXT:    slli a0, a0, 52
; RV64M-NEXT:    srli a0, a0, 60
; RV64M-NEXT:    add a0, a1, a0
; RV64M-NEXT:    ret
; RV64M-NEXT:  .LBB1_2:
; RV64M-NEXT:    li a0, 16
; RV64M-NEXT:    ret
  %tmp = call i16 @llvm.cttz.i16(i16 %a, i1 false)
  ret i16 %tmp
}

define i32 @test_cttz_i32(i32 %a) nounwind {
;
; RV64I-LABEL: test_cttz_i32:
; RV64I:       # %bb.0:
; RV64I-NEXT:    sext.w a1, a0
; RV64I-NEXT:    beqz a1, .LBB2_2
; RV64I-NEXT:  # %bb.1: # %cond.false
; RV64I-NEXT:    negw a1, a0
; RV64I-NEXT:    and a0, a0, a1
; RV64I-NEXT:    lui a1, 30667
; RV64I-NEXT:    addi a1, a1, 1329
; RV64I-NEXT:    mulw a0, a0, a1
; RV64I-NEXT:    srliw a0, a0, 27
; RV64I-NEXT:    lui a1, %hi(.LCPI2_0)
; RV64I-NEXT:    addi a1, a1, %lo(.LCPI2_0)
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    lbu a0, 0(a0)
; RV64I-NEXT:    ret
; RV64I-NEXT:  .LBB2_2:
; RV64I-NEXT:    li a0, 32
; RV64I-NEXT:    ret
;
; RV64M-LABEL: test_cttz_i32:
; RV64M:       # %bb.0:
; RV64M-NEXT:    sext.w a1, a0
; RV64M-NEXT:    beqz a1, .LBB2_2
; RV64M-NEXT:  # %bb.1: # %cond.false
; RV64M-NEXT:    negw a1, a0
; RV64M-NEXT:    and a0, a0, a1
; RV64M-NEXT:    lui a1, 30667
; RV64M-NEXT:    addi a1, a1, 1329
; RV64M-NEXT:    mulw a0, a0, a1
; RV64M-NEXT:    srliw a0, a0, 27
; RV64M-NEXT:    lui a1, %hi(.LCPI2_0)
; RV64M-NEXT:    addi a1, a1, %lo(.LCPI2_0)
; RV64M-NEXT:    add a0, a1, a0
; RV64M-NEXT:    lbu a0, 0(a0)
; RV64M-NEXT:    ret
; RV64M-NEXT:  .LBB2_2:
; RV64M-NEXT:    li a0, 32
; RV64M-NEXT:    ret
  %tmp = call i32 @llvm.cttz.i32(i32 %a, i1 false)
  ret i32 %tmp
}

define i64 @test_cttz_i64(i64 %a) nounwind {
;
; RV64I-LABEL: test_cttz_i64:
; RV64I:       # %bb.0:
; RV64I-NEXT:    beqz a0, .LBB3_2
; RV64I-NEXT:  # %bb.1: # %cond.false
; RV64I-NEXT:    lui a1, %hi(.LCPI3_0)
; RV64I-NEXT:    ld a1, %lo(.LCPI3_0)(a1)
; RV64I-NEXT:    neg a2, a0
; RV64I-NEXT:    and a0, a0, a2
; RV64I-NEXT:    mul a0, a0, a1
; RV64I-NEXT:    srli a0, a0, 58
; RV64I-NEXT:    lui a1, %hi(.LCPI3_1)
; RV64I-NEXT:    addi a1, a1, %lo(.LCPI3_1)
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    lbu a0, 0(a0)
; RV64I-NEXT:    ret
; RV64I-NEXT:  .LBB3_2:
; RV64I-NEXT:    li a0, 64
; RV64I-NEXT:    ret
;
; RV64M-LABEL: test_cttz_i64:
; RV64M:       # %bb.0:
; RV64M-NEXT:    beqz a0, .LBB3_2
; RV64M-NEXT:  # %bb.1: # %cond.false
; RV64M-NEXT:    lui a1, %hi(.LCPI3_0)
; RV64M-NEXT:    ld a1, %lo(.LCPI3_0)(a1)
; RV64M-NEXT:    neg a2, a0
; RV64M-NEXT:    and a0, a0, a2
; RV64M-NEXT:    mul a0, a0, a1
; RV64M-NEXT:    srli a0, a0, 58
; RV64M-NEXT:    lui a1, %hi(.LCPI3_1)
; RV64M-NEXT:    addi a1, a1, %lo(.LCPI3_1)
; RV64M-NEXT:    add a0, a1, a0
; RV64M-NEXT:    lbu a0, 0(a0)
; RV64M-NEXT:    ret
; RV64M-NEXT:  .LBB3_2:
; RV64M-NEXT:    li a0, 64
; RV64M-NEXT:    ret
  %tmp = call i64 @llvm.cttz.i64(i64 %a, i1 false)
  ret i64 %tmp
}

define i8 @test_cttz_i8_zero_undef(i8 %a) nounwind {
;
; RV64I-LABEL: test_cttz_i8_zero_undef:
; RV64I:       # %bb.0:
; RV64I-NEXT:    addiw a1, a0, -1
; RV64I-NEXT:    not a0, a0
; RV64I-NEXT:    and a0, a0, a1
; RV64I-NEXT:    srli a1, a0, 1
; RV64I-NEXT:    andi a1, a1, 85
; RV64I-NEXT:    subw a0, a0, a1
; RV64I-NEXT:    andi a1, a0, 51
; RV64I-NEXT:    srli a0, a0, 2
; RV64I-NEXT:    andi a0, a0, 51
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    srli a1, a0, 4
; RV64I-NEXT:    addw a0, a0, a1
; RV64I-NEXT:    andi a0, a0, 15
; RV64I-NEXT:    ret
;
; RV64M-LABEL: test_cttz_i8_zero_undef:
; RV64M:       # %bb.0:
; RV64M-NEXT:    addiw a1, a0, -1
; RV64M-NEXT:    not a0, a0
; RV64M-NEXT:    and a0, a0, a1
; RV64M-NEXT:    srli a1, a0, 1
; RV64M-NEXT:    andi a1, a1, 85
; RV64M-NEXT:    subw a0, a0, a1
; RV64M-NEXT:    andi a1, a0, 51
; RV64M-NEXT:    srli a0, a0, 2
; RV64M-NEXT:    andi a0, a0, 51
; RV64M-NEXT:    add a0, a1, a0
; RV64M-NEXT:    srli a1, a0, 4
; RV64M-NEXT:    addw a0, a0, a1
; RV64M-NEXT:    andi a0, a0, 15
; RV64M-NEXT:    ret
  %tmp = call i8 @llvm.cttz.i8(i8 %a, i1 true)
  ret i8 %tmp
}

define i16 @test_cttz_i16_zero_undef(i16 %a) nounwind {
;
; RV64I-LABEL: test_cttz_i16_zero_undef:
; RV64I:       # %bb.0:
; RV64I-NEXT:    addi a1, a0, -1
; RV64I-NEXT:    not a0, a0
; RV64I-NEXT:    lui a2, 5
; RV64I-NEXT:    and a0, a0, a1
; RV64I-NEXT:    addi a1, a2, 1365
; RV64I-NEXT:    srli a2, a0, 1
; RV64I-NEXT:    and a1, a2, a1
; RV64I-NEXT:    lui a2, 3
; RV64I-NEXT:    addi a2, a2, 819
; RV64I-NEXT:    sub a0, a0, a1
; RV64I-NEXT:    and a1, a0, a2
; RV64I-NEXT:    srli a0, a0, 2
; RV64I-NEXT:    and a0, a0, a2
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    srli a1, a0, 4
; RV64I-NEXT:    addw a0, a0, a1
; RV64I-NEXT:    andi a1, a0, 15
; RV64I-NEXT:    slli a0, a0, 52
; RV64I-NEXT:    srli a0, a0, 60
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64M-LABEL: test_cttz_i16_zero_undef:
; RV64M:       # %bb.0:
; RV64M-NEXT:    addi a1, a0, -1
; RV64M-NEXT:    not a0, a0
; RV64M-NEXT:    lui a2, 5
; RV64M-NEXT:    and a0, a0, a1
; RV64M-NEXT:    addi a1, a2, 1365
; RV64M-NEXT:    srli a2, a0, 1
; RV64M-NEXT:    and a1, a2, a1
; RV64M-NEXT:    lui a2, 3
; RV64M-NEXT:    addi a2, a2, 819
; RV64M-NEXT:    sub a0, a0, a1
; RV64M-NEXT:    and a1, a0, a2
; RV64M-NEXT:    srli a0, a0, 2
; RV64M-NEXT:    and a0, a0, a2
; RV64M-NEXT:    add a0, a1, a0
; RV64M-NEXT:    srli a1, a0, 4
; RV64M-NEXT:    addw a0, a0, a1
; RV64M-NEXT:    andi a1, a0, 15
; RV64M-NEXT:    slli a0, a0, 52
; RV64M-NEXT:    srli a0, a0, 60
; RV64M-NEXT:    add a0, a1, a0
; RV64M-NEXT:    ret
  %tmp = call i16 @llvm.cttz.i16(i16 %a, i1 true)
  ret i16 %tmp
}

define i32 @test_cttz_i32_zero_undef(i32 %a) nounwind {
;
; RV64I-LABEL: test_cttz_i32_zero_undef:
; RV64I:       # %bb.0:
; RV64I-NEXT:    negw a1, a0
; RV64I-NEXT:    and a0, a0, a1
; RV64I-NEXT:    lui a1, 30667
; RV64I-NEXT:    addi a1, a1, 1329
; RV64I-NEXT:    mulw a0, a0, a1
; RV64I-NEXT:    srliw a0, a0, 27
; RV64I-NEXT:    lui a1, %hi(.LCPI6_0)
; RV64I-NEXT:    addi a1, a1, %lo(.LCPI6_0)
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    lbu a0, 0(a0)
; RV64I-NEXT:    ret
;
; RV64M-LABEL: test_cttz_i32_zero_undef:
; RV64M:       # %bb.0:
; RV64M-NEXT:    negw a1, a0
; RV64M-NEXT:    and a0, a0, a1
; RV64M-NEXT:    lui a1, 30667
; RV64M-NEXT:    addi a1, a1, 1329
; RV64M-NEXT:    mulw a0, a0, a1
; RV64M-NEXT:    srliw a0, a0, 27
; RV64M-NEXT:    lui a1, %hi(.LCPI6_0)
; RV64M-NEXT:    addi a1, a1, %lo(.LCPI6_0)
; RV64M-NEXT:    add a0, a1, a0
; RV64M-NEXT:    lbu a0, 0(a0)
; RV64M-NEXT:    ret
  %tmp = call i32 @llvm.cttz.i32(i32 %a, i1 true)
  ret i32 %tmp
}

define i64 @test_cttz_i64_zero_undef(i64 %a) nounwind {
;
; RV64I-LABEL: test_cttz_i64_zero_undef:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lui a1, %hi(.LCPI7_0)
; RV64I-NEXT:    ld a1, %lo(.LCPI7_0)(a1)
; RV64I-NEXT:    neg a2, a0
; RV64I-NEXT:    and a0, a0, a2
; RV64I-NEXT:    mul a0, a0, a1
; RV64I-NEXT:    srli a0, a0, 58
; RV64I-NEXT:    lui a1, %hi(.LCPI7_1)
; RV64I-NEXT:    addi a1, a1, %lo(.LCPI7_1)
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    lbu a0, 0(a0)
; RV64I-NEXT:    ret
;
; RV64M-LABEL: test_cttz_i64_zero_undef:
; RV64M:       # %bb.0:
; RV64M-NEXT:    lui a1, %hi(.LCPI7_0)
; RV64M-NEXT:    ld a1, %lo(.LCPI7_0)(a1)
; RV64M-NEXT:    neg a2, a0
; RV64M-NEXT:    and a0, a0, a2
; RV64M-NEXT:    mul a0, a0, a1
; RV64M-NEXT:    srli a0, a0, 58
; RV64M-NEXT:    lui a1, %hi(.LCPI7_1)
; RV64M-NEXT:    addi a1, a1, %lo(.LCPI7_1)
; RV64M-NEXT:    add a0, a1, a0
; RV64M-NEXT:    lbu a0, 0(a0)
; RV64M-NEXT:    ret
  %tmp = call i64 @llvm.cttz.i64(i64 %a, i1 true)
  ret i64 %tmp
}

define i8 @test_ctlz_i8(i8 %a) nounwind {
;
; RV64I-LABEL: test_ctlz_i8:
; RV64I:       # %bb.0:
; RV64I-NEXT:    zext.b a1, a0
; RV64I-NEXT:    beqz a1, .LBB8_2
; RV64I-NEXT:  # %bb.1: # %cond.false
; RV64I-NEXT:    slli a1, a0, 56
; RV64I-NEXT:    srli a1, a1, 57
; RV64I-NEXT:    or a0, a0, a1
; RV64I-NEXT:    slli a1, a0, 56
; RV64I-NEXT:    srli a1, a1, 58
; RV64I-NEXT:    or a0, a0, a1
; RV64I-NEXT:    slli a1, a0, 56
; RV64I-NEXT:    srli a1, a1, 60
; RV64I-NEXT:    or a0, a0, a1
; RV64I-NEXT:    not a0, a0
; RV64I-NEXT:    srli a1, a0, 1
; RV64I-NEXT:    andi a1, a1, 85
; RV64I-NEXT:    subw a0, a0, a1
; RV64I-NEXT:    andi a1, a0, 51
; RV64I-NEXT:    srli a0, a0, 2
; RV64I-NEXT:    andi a0, a0, 51
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    srli a1, a0, 4
; RV64I-NEXT:    addw a0, a0, a1
; RV64I-NEXT:    andi a0, a0, 15
; RV64I-NEXT:    ret
; RV64I-NEXT:  .LBB8_2:
; RV64I-NEXT:    li a0, 8
; RV64I-NEXT:    ret
;
; RV64M-LABEL: test_ctlz_i8:
; RV64M:       # %bb.0:
; RV64M-NEXT:    zext.b a1, a0
; RV64M-NEXT:    beqz a1, .LBB8_2
; RV64M-NEXT:  # %bb.1: # %cond.false
; RV64M-NEXT:    slli a1, a0, 56
; RV64M-NEXT:    srli a1, a1, 57
; RV64M-NEXT:    or a0, a0, a1
; RV64M-NEXT:    slli a1, a0, 56
; RV64M-NEXT:    srli a1, a1, 58
; RV64M-NEXT:    or a0, a0, a1
; RV64M-NEXT:    slli a1, a0, 56
; RV64M-NEXT:    srli a1, a1, 60
; RV64M-NEXT:    or a0, a0, a1
; RV64M-NEXT:    not a0, a0
; RV64M-NEXT:    srli a1, a0, 1
; RV64M-NEXT:    andi a1, a1, 85
; RV64M-NEXT:    subw a0, a0, a1
; RV64M-NEXT:    andi a1, a0, 51
; RV64M-NEXT:    srli a0, a0, 2
; RV64M-NEXT:    andi a0, a0, 51
; RV64M-NEXT:    add a0, a1, a0
; RV64M-NEXT:    srli a1, a0, 4
; RV64M-NEXT:    addw a0, a0, a1
; RV64M-NEXT:    andi a0, a0, 15
; RV64M-NEXT:    ret
; RV64M-NEXT:  .LBB8_2:
; RV64M-NEXT:    li a0, 8
; RV64M-NEXT:    ret
  %tmp = call i8 @llvm.ctlz.i8(i8 %a, i1 false)
  ret i8 %tmp
}

define i16 @test_ctlz_i16(i16 %a) nounwind {
;
; RV64I-LABEL: test_ctlz_i16:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a1, a0, 48
; RV64I-NEXT:    beqz a1, .LBB9_2
; RV64I-NEXT:  # %bb.1: # %cond.false
; RV64I-NEXT:    srli a1, a1, 49
; RV64I-NEXT:    lui a2, 5
; RV64I-NEXT:    or a0, a0, a1
; RV64I-NEXT:    addi a1, a2, 1365
; RV64I-NEXT:    slli a2, a0, 48
; RV64I-NEXT:    srli a2, a2, 50
; RV64I-NEXT:    or a0, a0, a2
; RV64I-NEXT:    slli a2, a0, 48
; RV64I-NEXT:    srli a2, a2, 52
; RV64I-NEXT:    or a0, a0, a2
; RV64I-NEXT:    slli a2, a0, 48
; RV64I-NEXT:    srli a2, a2, 56
; RV64I-NEXT:    or a0, a0, a2
; RV64I-NEXT:    not a0, a0
; RV64I-NEXT:    srli a2, a0, 1
; RV64I-NEXT:    and a1, a2, a1
; RV64I-NEXT:    lui a2, 3
; RV64I-NEXT:    addi a2, a2, 819
; RV64I-NEXT:    sub a0, a0, a1
; RV64I-NEXT:    and a1, a0, a2
; RV64I-NEXT:    srli a0, a0, 2
; RV64I-NEXT:    and a0, a0, a2
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    srli a1, a0, 4
; RV64I-NEXT:    addw a0, a0, a1
; RV64I-NEXT:    andi a1, a0, 15
; RV64I-NEXT:    slli a0, a0, 52
; RV64I-NEXT:    srli a0, a0, 60
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    ret
; RV64I-NEXT:  .LBB9_2:
; RV64I-NEXT:    li a0, 16
; RV64I-NEXT:    ret
;
; RV64M-LABEL: test_ctlz_i16:
; RV64M:       # %bb.0:
; RV64M-NEXT:    slli a1, a0, 48
; RV64M-NEXT:    beqz a1, .LBB9_2
; RV64M-NEXT:  # %bb.1: # %cond.false
; RV64M-NEXT:    srli a1, a1, 49
; RV64M-NEXT:    lui a2, 5
; RV64M-NEXT:    or a0, a0, a1
; RV64M-NEXT:    addi a1, a2, 1365
; RV64M-NEXT:    slli a2, a0, 48
; RV64M-NEXT:    srli a2, a2, 50
; RV64M-NEXT:    or a0, a0, a2
; RV64M-NEXT:    slli a2, a0, 48
; RV64M-NEXT:    srli a2, a2, 52
; RV64M-NEXT:    or a0, a0, a2
; RV64M-NEXT:    slli a2, a0, 48
; RV64M-NEXT:    srli a2, a2, 56
; RV64M-NEXT:    or a0, a0, a2
; RV64M-NEXT:    not a0, a0
; RV64M-NEXT:    srli a2, a0, 1
; RV64M-NEXT:    and a1, a2, a1
; RV64M-NEXT:    lui a2, 3
; RV64M-NEXT:    addi a2, a2, 819
; RV64M-NEXT:    sub a0, a0, a1
; RV64M-NEXT:    and a1, a0, a2
; RV64M-NEXT:    srli a0, a0, 2
; RV64M-NEXT:    and a0, a0, a2
; RV64M-NEXT:    add a0, a1, a0
; RV64M-NEXT:    srli a1, a0, 4
; RV64M-NEXT:    addw a0, a0, a1
; RV64M-NEXT:    andi a1, a0, 15
; RV64M-NEXT:    slli a0, a0, 52
; RV64M-NEXT:    srli a0, a0, 60
; RV64M-NEXT:    add a0, a1, a0
; RV64M-NEXT:    ret
; RV64M-NEXT:  .LBB9_2:
; RV64M-NEXT:    li a0, 16
; RV64M-NEXT:    ret
  %tmp = call i16 @llvm.ctlz.i16(i16 %a, i1 false)
  ret i16 %tmp
}

define i32 @test_ctlz_i32(i32 %a) nounwind {
;
; RV64I-LABEL: test_ctlz_i32:
; RV64I:       # %bb.0:
; RV64I-NEXT:    sext.w a1, a0
; RV64I-NEXT:    beqz a1, .LBB10_2
; RV64I-NEXT:  # %bb.1: # %cond.false
; RV64I-NEXT:    srliw a1, a0, 1
; RV64I-NEXT:    lui a2, 349525
; RV64I-NEXT:    or a0, a0, a1
; RV64I-NEXT:    addi a1, a2, 1365
; RV64I-NEXT:    srliw a2, a0, 2
; RV64I-NEXT:    or a0, a0, a2
; RV64I-NEXT:    srliw a2, a0, 4
; RV64I-NEXT:    or a0, a0, a2
; RV64I-NEXT:    srliw a2, a0, 8
; RV64I-NEXT:    or a0, a0, a2
; RV64I-NEXT:    srliw a2, a0, 16
; RV64I-NEXT:    or a0, a0, a2
; RV64I-NEXT:    not a0, a0
; RV64I-NEXT:    srli a2, a0, 1
; RV64I-NEXT:    and a1, a2, a1
; RV64I-NEXT:    lui a2, 209715
; RV64I-NEXT:    addi a2, a2, 819
; RV64I-NEXT:    sub a0, a0, a1
; RV64I-NEXT:    and a1, a0, a2
; RV64I-NEXT:    srli a0, a0, 2
; RV64I-NEXT:    and a0, a0, a2
; RV64I-NEXT:    lui a2, 61681
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    srli a1, a0, 4
; RV64I-NEXT:    addw a0, a0, a1
; RV64I-NEXT:    lui a1, 4112
; RV64I-NEXT:    addi a2, a2, -241
; RV64I-NEXT:    and a0, a0, a2
; RV64I-NEXT:    addi a1, a1, 257
; RV64I-NEXT:    mulw a0, a0, a1
; RV64I-NEXT:    srliw a0, a0, 24
; RV64I-NEXT:    ret
; RV64I-NEXT:  .LBB10_2:
; RV64I-NEXT:    li a0, 32
; RV64I-NEXT:    ret
;
; RV64M-LABEL: test_ctlz_i32:
; RV64M:       # %bb.0:
; RV64M-NEXT:    sext.w a1, a0
; RV64M-NEXT:    beqz a1, .LBB10_2
; RV64M-NEXT:  # %bb.1: # %cond.false
; RV64M-NEXT:    srliw a1, a0, 1
; RV64M-NEXT:    lui a2, 349525
; RV64M-NEXT:    or a0, a0, a1
; RV64M-NEXT:    addi a1, a2, 1365
; RV64M-NEXT:    srliw a2, a0, 2
; RV64M-NEXT:    or a0, a0, a2
; RV64M-NEXT:    srliw a2, a0, 4
; RV64M-NEXT:    or a0, a0, a2
; RV64M-NEXT:    srliw a2, a0, 8
; RV64M-NEXT:    or a0, a0, a2
; RV64M-NEXT:    srliw a2, a0, 16
; RV64M-NEXT:    or a0, a0, a2
; RV64M-NEXT:    not a0, a0
; RV64M-NEXT:    srli a2, a0, 1
; RV64M-NEXT:    and a1, a2, a1
; RV64M-NEXT:    lui a2, 209715
; RV64M-NEXT:    addi a2, a2, 819
; RV64M-NEXT:    sub a0, a0, a1
; RV64M-NEXT:    and a1, a0, a2
; RV64M-NEXT:    srli a0, a0, 2
; RV64M-NEXT:    and a0, a0, a2
; RV64M-NEXT:    lui a2, 61681
; RV64M-NEXT:    add a0, a1, a0
; RV64M-NEXT:    srli a1, a0, 4
; RV64M-NEXT:    addw a0, a0, a1
; RV64M-NEXT:    lui a1, 4112
; RV64M-NEXT:    addi a2, a2, -241
; RV64M-NEXT:    and a0, a0, a2
; RV64M-NEXT:    addi a1, a1, 257
; RV64M-NEXT:    mulw a0, a0, a1
; RV64M-NEXT:    srliw a0, a0, 24
; RV64M-NEXT:    ret
; RV64M-NEXT:  .LBB10_2:
; RV64M-NEXT:    li a0, 32
; RV64M-NEXT:    ret
  %tmp = call i32 @llvm.ctlz.i32(i32 %a, i1 false)
  ret i32 %tmp
}

define i64 @test_ctlz_i64(i64 %a) nounwind {
;
; RV64I-LABEL: test_ctlz_i64:
; RV64I:       # %bb.0:
; RV64I-NEXT:    beqz a0, .LBB11_2
; RV64I-NEXT:  # %bb.1: # %cond.false
; RV64I-NEXT:    srli a1, a0, 1
; RV64I-NEXT:    lui a2, 349525
; RV64I-NEXT:    lui a3, 209715
; RV64I-NEXT:    lui a4, 61681
; RV64I-NEXT:    or a0, a0, a1
; RV64I-NEXT:    addi a1, a2, 1365
; RV64I-NEXT:    addi a2, a3, 819
; RV64I-NEXT:    addi a3, a4, -241
; RV64I-NEXT:    srli a4, a0, 2
; RV64I-NEXT:    or a0, a0, a4
; RV64I-NEXT:    slli a4, a1, 32
; RV64I-NEXT:    add a1, a1, a4
; RV64I-NEXT:    slli a4, a2, 32
; RV64I-NEXT:    add a2, a2, a4
; RV64I-NEXT:    slli a4, a3, 32
; RV64I-NEXT:    add a3, a3, a4
; RV64I-NEXT:    srli a4, a0, 4
; RV64I-NEXT:    or a0, a0, a4
; RV64I-NEXT:    srli a4, a0, 8
; RV64I-NEXT:    or a0, a0, a4
; RV64I-NEXT:    srli a4, a0, 16
; RV64I-NEXT:    or a0, a0, a4
; RV64I-NEXT:    srli a4, a0, 32
; RV64I-NEXT:    or a0, a0, a4
; RV64I-NEXT:    not a0, a0
; RV64I-NEXT:    srli a4, a0, 1
; RV64I-NEXT:    and a1, a4, a1
; RV64I-NEXT:    sub a0, a0, a1
; RV64I-NEXT:    and a1, a0, a2
; RV64I-NEXT:    srli a0, a0, 2
; RV64I-NEXT:    and a0, a0, a2
; RV64I-NEXT:    lui a2, 4112
; RV64I-NEXT:    addi a2, a2, 257
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    srli a1, a0, 4
; RV64I-NEXT:    add a0, a0, a1
; RV64I-NEXT:    slli a1, a2, 32
; RV64I-NEXT:    and a0, a0, a3
; RV64I-NEXT:    add a1, a2, a1
; RV64I-NEXT:    mul a0, a0, a1
; RV64I-NEXT:    srli a0, a0, 56
; RV64I-NEXT:    ret
; RV64I-NEXT:  .LBB11_2:
; RV64I-NEXT:    li a0, 64
; RV64I-NEXT:    ret
;
; RV64M-LABEL: test_ctlz_i64:
; RV64M:       # %bb.0:
; RV64M-NEXT:    beqz a0, .LBB11_2
; RV64M-NEXT:  # %bb.1: # %cond.false
; RV64M-NEXT:    srli a1, a0, 1
; RV64M-NEXT:    lui a2, 349525
; RV64M-NEXT:    lui a3, 209715
; RV64M-NEXT:    lui a4, 61681
; RV64M-NEXT:    or a0, a0, a1
; RV64M-NEXT:    addi a1, a2, 1365
; RV64M-NEXT:    addi a2, a3, 819
; RV64M-NEXT:    addi a3, a4, -241
; RV64M-NEXT:    srli a4, a0, 2
; RV64M-NEXT:    or a0, a0, a4
; RV64M-NEXT:    slli a4, a1, 32
; RV64M-NEXT:    add a1, a1, a4
; RV64M-NEXT:    slli a4, a2, 32
; RV64M-NEXT:    add a2, a2, a4
; RV64M-NEXT:    slli a4, a3, 32
; RV64M-NEXT:    add a3, a3, a4
; RV64M-NEXT:    srli a4, a0, 4
; RV64M-NEXT:    or a0, a0, a4
; RV64M-NEXT:    srli a4, a0, 8
; RV64M-NEXT:    or a0, a0, a4
; RV64M-NEXT:    srli a4, a0, 16
; RV64M-NEXT:    or a0, a0, a4
; RV64M-NEXT:    srli a4, a0, 32
; RV64M-NEXT:    or a0, a0, a4
; RV64M-NEXT:    not a0, a0
; RV64M-NEXT:    srli a4, a0, 1
; RV64M-NEXT:    and a1, a4, a1
; RV64M-NEXT:    sub a0, a0, a1
; RV64M-NEXT:    and a1, a0, a2
; RV64M-NEXT:    srli a0, a0, 2
; RV64M-NEXT:    and a0, a0, a2
; RV64M-NEXT:    lui a2, 4112
; RV64M-NEXT:    addi a2, a2, 257
; RV64M-NEXT:    add a0, a1, a0
; RV64M-NEXT:    srli a1, a0, 4
; RV64M-NEXT:    add a0, a0, a1
; RV64M-NEXT:    slli a1, a2, 32
; RV64M-NEXT:    and a0, a0, a3
; RV64M-NEXT:    add a1, a2, a1
; RV64M-NEXT:    mul a0, a0, a1
; RV64M-NEXT:    srli a0, a0, 56
; RV64M-NEXT:    ret
; RV64M-NEXT:  .LBB11_2:
; RV64M-NEXT:    li a0, 64
; RV64M-NEXT:    ret
  %tmp = call i64 @llvm.ctlz.i64(i64 %a, i1 false)
  ret i64 %tmp
}

define i8 @test_ctlz_i8_zero_undef(i8 %a) nounwind {
;
; RV64I-LABEL: test_ctlz_i8_zero_undef:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a1, a0, 56
; RV64I-NEXT:    srli a1, a1, 57
; RV64I-NEXT:    or a0, a0, a1
; RV64I-NEXT:    slli a1, a0, 56
; RV64I-NEXT:    srli a1, a1, 58
; RV64I-NEXT:    or a0, a0, a1
; RV64I-NEXT:    slli a1, a0, 56
; RV64I-NEXT:    srli a1, a1, 60
; RV64I-NEXT:    or a0, a0, a1
; RV64I-NEXT:    not a0, a0
; RV64I-NEXT:    srli a1, a0, 1
; RV64I-NEXT:    andi a1, a1, 85
; RV64I-NEXT:    subw a0, a0, a1
; RV64I-NEXT:    andi a1, a0, 51
; RV64I-NEXT:    srli a0, a0, 2
; RV64I-NEXT:    andi a0, a0, 51
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    srli a1, a0, 4
; RV64I-NEXT:    addw a0, a0, a1
; RV64I-NEXT:    andi a0, a0, 15
; RV64I-NEXT:    ret
;
; RV64M-LABEL: test_ctlz_i8_zero_undef:
; RV64M:       # %bb.0:
; RV64M-NEXT:    slli a1, a0, 56
; RV64M-NEXT:    srli a1, a1, 57
; RV64M-NEXT:    or a0, a0, a1
; RV64M-NEXT:    slli a1, a0, 56
; RV64M-NEXT:    srli a1, a1, 58
; RV64M-NEXT:    or a0, a0, a1
; RV64M-NEXT:    slli a1, a0, 56
; RV64M-NEXT:    srli a1, a1, 60
; RV64M-NEXT:    or a0, a0, a1
; RV64M-NEXT:    not a0, a0
; RV64M-NEXT:    srli a1, a0, 1
; RV64M-NEXT:    andi a1, a1, 85
; RV64M-NEXT:    subw a0, a0, a1
; RV64M-NEXT:    andi a1, a0, 51
; RV64M-NEXT:    srli a0, a0, 2
; RV64M-NEXT:    andi a0, a0, 51
; RV64M-NEXT:    add a0, a1, a0
; RV64M-NEXT:    srli a1, a0, 4
; RV64M-NEXT:    addw a0, a0, a1
; RV64M-NEXT:    andi a0, a0, 15
; RV64M-NEXT:    ret
  %tmp = call i8 @llvm.ctlz.i8(i8 %a, i1 true)
  ret i8 %tmp
}

define i16 @test_ctlz_i16_zero_undef(i16 %a) nounwind {
;
; RV64I-LABEL: test_ctlz_i16_zero_undef:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a1, a0, 48
; RV64I-NEXT:    lui a2, 5
; RV64I-NEXT:    srli a1, a1, 49
; RV64I-NEXT:    addi a2, a2, 1365
; RV64I-NEXT:    or a0, a0, a1
; RV64I-NEXT:    slli a1, a0, 48
; RV64I-NEXT:    srli a1, a1, 50
; RV64I-NEXT:    or a0, a0, a1
; RV64I-NEXT:    slli a1, a0, 48
; RV64I-NEXT:    srli a1, a1, 52
; RV64I-NEXT:    or a0, a0, a1
; RV64I-NEXT:    slli a1, a0, 48
; RV64I-NEXT:    srli a1, a1, 56
; RV64I-NEXT:    or a0, a0, a1
; RV64I-NEXT:    not a0, a0
; RV64I-NEXT:    srli a1, a0, 1
; RV64I-NEXT:    and a1, a1, a2
; RV64I-NEXT:    lui a2, 3
; RV64I-NEXT:    addi a2, a2, 819
; RV64I-NEXT:    sub a0, a0, a1
; RV64I-NEXT:    and a1, a0, a2
; RV64I-NEXT:    srli a0, a0, 2
; RV64I-NEXT:    and a0, a0, a2
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    srli a1, a0, 4
; RV64I-NEXT:    addw a0, a0, a1
; RV64I-NEXT:    andi a1, a0, 15
; RV64I-NEXT:    slli a0, a0, 52
; RV64I-NEXT:    srli a0, a0, 60
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64M-LABEL: test_ctlz_i16_zero_undef:
; RV64M:       # %bb.0:
; RV64M-NEXT:    slli a1, a0, 48
; RV64M-NEXT:    lui a2, 5
; RV64M-NEXT:    srli a1, a1, 49
; RV64M-NEXT:    addi a2, a2, 1365
; RV64M-NEXT:    or a0, a0, a1
; RV64M-NEXT:    slli a1, a0, 48
; RV64M-NEXT:    srli a1, a1, 50
; RV64M-NEXT:    or a0, a0, a1
; RV64M-NEXT:    slli a1, a0, 48
; RV64M-NEXT:    srli a1, a1, 52
; RV64M-NEXT:    or a0, a0, a1
; RV64M-NEXT:    slli a1, a0, 48
; RV64M-NEXT:    srli a1, a1, 56
; RV64M-NEXT:    or a0, a0, a1
; RV64M-NEXT:    not a0, a0
; RV64M-NEXT:    srli a1, a0, 1
; RV64M-NEXT:    and a1, a1, a2
; RV64M-NEXT:    lui a2, 3
; RV64M-NEXT:    addi a2, a2, 819
; RV64M-NEXT:    sub a0, a0, a1
; RV64M-NEXT:    and a1, a0, a2
; RV64M-NEXT:    srli a0, a0, 2
; RV64M-NEXT:    and a0, a0, a2
; RV64M-NEXT:    add a0, a1, a0
; RV64M-NEXT:    srli a1, a0, 4
; RV64M-NEXT:    addw a0, a0, a1
; RV64M-NEXT:    andi a1, a0, 15
; RV64M-NEXT:    slli a0, a0, 52
; RV64M-NEXT:    srli a0, a0, 60
; RV64M-NEXT:    add a0, a1, a0
; RV64M-NEXT:    ret
  %tmp = call i16 @llvm.ctlz.i16(i16 %a, i1 true)
  ret i16 %tmp
}

define i32 @test_ctlz_i32_zero_undef(i32 %a) nounwind {
;
; RV64I-LABEL: test_ctlz_i32_zero_undef:
; RV64I:       # %bb.0:
; RV64I-NEXT:    srliw a1, a0, 1
; RV64I-NEXT:    lui a2, 349525
; RV64I-NEXT:    or a0, a0, a1
; RV64I-NEXT:    addi a1, a2, 1365
; RV64I-NEXT:    srliw a2, a0, 2
; RV64I-NEXT:    or a0, a0, a2
; RV64I-NEXT:    srliw a2, a0, 4
; RV64I-NEXT:    or a0, a0, a2
; RV64I-NEXT:    srliw a2, a0, 8
; RV64I-NEXT:    or a0, a0, a2
; RV64I-NEXT:    srliw a2, a0, 16
; RV64I-NEXT:    or a0, a0, a2
; RV64I-NEXT:    not a0, a0
; RV64I-NEXT:    srli a2, a0, 1
; RV64I-NEXT:    and a1, a2, a1
; RV64I-NEXT:    lui a2, 209715
; RV64I-NEXT:    addi a2, a2, 819
; RV64I-NEXT:    sub a0, a0, a1
; RV64I-NEXT:    and a1, a0, a2
; RV64I-NEXT:    srli a0, a0, 2
; RV64I-NEXT:    and a0, a0, a2
; RV64I-NEXT:    lui a2, 61681
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    srli a1, a0, 4
; RV64I-NEXT:    addw a0, a0, a1
; RV64I-NEXT:    lui a1, 4112
; RV64I-NEXT:    addi a2, a2, -241
; RV64I-NEXT:    and a0, a0, a2
; RV64I-NEXT:    addi a1, a1, 257
; RV64I-NEXT:    mulw a0, a0, a1
; RV64I-NEXT:    srliw a0, a0, 24
; RV64I-NEXT:    ret
;
; RV64M-LABEL: test_ctlz_i32_zero_undef:
; RV64M:       # %bb.0:
; RV64M-NEXT:    srliw a1, a0, 1
; RV64M-NEXT:    lui a2, 349525
; RV64M-NEXT:    or a0, a0, a1
; RV64M-NEXT:    addi a1, a2, 1365
; RV64M-NEXT:    srliw a2, a0, 2
; RV64M-NEXT:    or a0, a0, a2
; RV64M-NEXT:    srliw a2, a0, 4
; RV64M-NEXT:    or a0, a0, a2
; RV64M-NEXT:    srliw a2, a0, 8
; RV64M-NEXT:    or a0, a0, a2
; RV64M-NEXT:    srliw a2, a0, 16
; RV64M-NEXT:    or a0, a0, a2
; RV64M-NEXT:    not a0, a0
; RV64M-NEXT:    srli a2, a0, 1
; RV64M-NEXT:    and a1, a2, a1
; RV64M-NEXT:    lui a2, 209715
; RV64M-NEXT:    addi a2, a2, 819
; RV64M-NEXT:    sub a0, a0, a1
; RV64M-NEXT:    and a1, a0, a2
; RV64M-NEXT:    srli a0, a0, 2
; RV64M-NEXT:    and a0, a0, a2
; RV64M-NEXT:    lui a2, 61681
; RV64M-NEXT:    add a0, a1, a0
; RV64M-NEXT:    srli a1, a0, 4
; RV64M-NEXT:    addw a0, a0, a1
; RV64M-NEXT:    lui a1, 4112
; RV64M-NEXT:    addi a2, a2, -241
; RV64M-NEXT:    and a0, a0, a2
; RV64M-NEXT:    addi a1, a1, 257
; RV64M-NEXT:    mulw a0, a0, a1
; RV64M-NEXT:    srliw a0, a0, 24
; RV64M-NEXT:    ret
  %tmp = call i32 @llvm.ctlz.i32(i32 %a, i1 true)
  ret i32 %tmp
}

define i64 @test_ctlz_i64_zero_undef(i64 %a) nounwind {
;
; RV64I-LABEL: test_ctlz_i64_zero_undef:
; RV64I:       # %bb.0:
; RV64I-NEXT:    srli a1, a0, 1
; RV64I-NEXT:    lui a2, 349525
; RV64I-NEXT:    lui a3, 209715
; RV64I-NEXT:    lui a4, 61681
; RV64I-NEXT:    or a0, a0, a1
; RV64I-NEXT:    addi a1, a2, 1365
; RV64I-NEXT:    addi a2, a3, 819
; RV64I-NEXT:    addi a3, a4, -241
; RV64I-NEXT:    srli a4, a0, 2
; RV64I-NEXT:    or a0, a0, a4
; RV64I-NEXT:    slli a4, a1, 32
; RV64I-NEXT:    add a1, a1, a4
; RV64I-NEXT:    slli a4, a2, 32
; RV64I-NEXT:    add a2, a2, a4
; RV64I-NEXT:    slli a4, a3, 32
; RV64I-NEXT:    add a3, a3, a4
; RV64I-NEXT:    srli a4, a0, 4
; RV64I-NEXT:    or a0, a0, a4
; RV64I-NEXT:    srli a4, a0, 8
; RV64I-NEXT:    or a0, a0, a4
; RV64I-NEXT:    srli a4, a0, 16
; RV64I-NEXT:    or a0, a0, a4
; RV64I-NEXT:    srli a4, a0, 32
; RV64I-NEXT:    or a0, a0, a4
; RV64I-NEXT:    not a0, a0
; RV64I-NEXT:    srli a4, a0, 1
; RV64I-NEXT:    and a1, a4, a1
; RV64I-NEXT:    sub a0, a0, a1
; RV64I-NEXT:    and a1, a0, a2
; RV64I-NEXT:    srli a0, a0, 2
; RV64I-NEXT:    and a0, a0, a2
; RV64I-NEXT:    lui a2, 4112
; RV64I-NEXT:    addi a2, a2, 257
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    srli a1, a0, 4
; RV64I-NEXT:    add a0, a0, a1
; RV64I-NEXT:    slli a1, a2, 32
; RV64I-NEXT:    and a0, a0, a3
; RV64I-NEXT:    add a1, a2, a1
; RV64I-NEXT:    mul a0, a0, a1
; RV64I-NEXT:    srli a0, a0, 56
; RV64I-NEXT:    ret
;
; RV64M-LABEL: test_ctlz_i64_zero_undef:
; RV64M:       # %bb.0:
; RV64M-NEXT:    srli a1, a0, 1
; RV64M-NEXT:    lui a2, 349525
; RV64M-NEXT:    lui a3, 209715
; RV64M-NEXT:    lui a4, 61681
; RV64M-NEXT:    or a0, a0, a1
; RV64M-NEXT:    addi a1, a2, 1365
; RV64M-NEXT:    addi a2, a3, 819
; RV64M-NEXT:    addi a3, a4, -241
; RV64M-NEXT:    srli a4, a0, 2
; RV64M-NEXT:    or a0, a0, a4
; RV64M-NEXT:    slli a4, a1, 32
; RV64M-NEXT:    add a1, a1, a4
; RV64M-NEXT:    slli a4, a2, 32
; RV64M-NEXT:    add a2, a2, a4
; RV64M-NEXT:    slli a4, a3, 32
; RV64M-NEXT:    add a3, a3, a4
; RV64M-NEXT:    srli a4, a0, 4
; RV64M-NEXT:    or a0, a0, a4
; RV64M-NEXT:    srli a4, a0, 8
; RV64M-NEXT:    or a0, a0, a4
; RV64M-NEXT:    srli a4, a0, 16
; RV64M-NEXT:    or a0, a0, a4
; RV64M-NEXT:    srli a4, a0, 32
; RV64M-NEXT:    or a0, a0, a4
; RV64M-NEXT:    not a0, a0
; RV64M-NEXT:    srli a4, a0, 1
; RV64M-NEXT:    and a1, a4, a1
; RV64M-NEXT:    sub a0, a0, a1
; RV64M-NEXT:    and a1, a0, a2
; RV64M-NEXT:    srli a0, a0, 2
; RV64M-NEXT:    and a0, a0, a2
; RV64M-NEXT:    lui a2, 4112
; RV64M-NEXT:    addi a2, a2, 257
; RV64M-NEXT:    add a0, a1, a0
; RV64M-NEXT:    srli a1, a0, 4
; RV64M-NEXT:    add a0, a0, a1
; RV64M-NEXT:    slli a1, a2, 32
; RV64M-NEXT:    and a0, a0, a3
; RV64M-NEXT:    add a1, a2, a1
; RV64M-NEXT:    mul a0, a0, a1
; RV64M-NEXT:    srli a0, a0, 56
; RV64M-NEXT:    ret
  %tmp = call i64 @llvm.ctlz.i64(i64 %a, i1 true)
  ret i64 %tmp
}

define i8 @test_ctpop_i8(i8 %a) nounwind {
;
; RV64I-LABEL: test_ctpop_i8:
; RV64I:       # %bb.0:
; RV64I-NEXT:    srli a1, a0, 1
; RV64I-NEXT:    andi a1, a1, 85
; RV64I-NEXT:    subw a0, a0, a1
; RV64I-NEXT:    andi a1, a0, 51
; RV64I-NEXT:    srli a0, a0, 2
; RV64I-NEXT:    andi a0, a0, 51
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    srli a1, a0, 4
; RV64I-NEXT:    addw a0, a0, a1
; RV64I-NEXT:    andi a0, a0, 15
; RV64I-NEXT:    ret
;
; RV64M-LABEL: test_ctpop_i8:
; RV64M:       # %bb.0:
; RV64M-NEXT:    srli a1, a0, 1
; RV64M-NEXT:    andi a1, a1, 85
; RV64M-NEXT:    subw a0, a0, a1
; RV64M-NEXT:    andi a1, a0, 51
; RV64M-NEXT:    srli a0, a0, 2
; RV64M-NEXT:    andi a0, a0, 51
; RV64M-NEXT:    add a0, a1, a0
; RV64M-NEXT:    srli a1, a0, 4
; RV64M-NEXT:    addw a0, a0, a1
; RV64M-NEXT:    andi a0, a0, 15
; RV64M-NEXT:    ret
  %1 = call i8 @llvm.ctpop.i8(i8 %a)
  ret i8 %1
}

define i16 @test_ctpop_i16(i16 %a) nounwind {
;
; RV64I-LABEL: test_ctpop_i16:
; RV64I:       # %bb.0:
; RV64I-NEXT:    srli a1, a0, 1
; RV64I-NEXT:    lui a2, 5
; RV64I-NEXT:    addi a2, a2, 1365
; RV64I-NEXT:    and a1, a1, a2
; RV64I-NEXT:    lui a2, 3
; RV64I-NEXT:    addi a2, a2, 819
; RV64I-NEXT:    sub a0, a0, a1
; RV64I-NEXT:    and a1, a0, a2
; RV64I-NEXT:    srli a0, a0, 2
; RV64I-NEXT:    and a0, a0, a2
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    srli a1, a0, 4
; RV64I-NEXT:    addw a0, a0, a1
; RV64I-NEXT:    andi a1, a0, 15
; RV64I-NEXT:    slli a0, a0, 52
; RV64I-NEXT:    srli a0, a0, 60
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64M-LABEL: test_ctpop_i16:
; RV64M:       # %bb.0:
; RV64M-NEXT:    srli a1, a0, 1
; RV64M-NEXT:    lui a2, 5
; RV64M-NEXT:    addi a2, a2, 1365
; RV64M-NEXT:    and a1, a1, a2
; RV64M-NEXT:    lui a2, 3
; RV64M-NEXT:    addi a2, a2, 819
; RV64M-NEXT:    sub a0, a0, a1
; RV64M-NEXT:    and a1, a0, a2
; RV64M-NEXT:    srli a0, a0, 2
; RV64M-NEXT:    and a0, a0, a2
; RV64M-NEXT:    add a0, a1, a0
; RV64M-NEXT:    srli a1, a0, 4
; RV64M-NEXT:    addw a0, a0, a1
; RV64M-NEXT:    andi a1, a0, 15
; RV64M-NEXT:    slli a0, a0, 52
; RV64M-NEXT:    srli a0, a0, 60
; RV64M-NEXT:    add a0, a1, a0
; RV64M-NEXT:    ret
  %1 = call i16 @llvm.ctpop.i16(i16 %a)
  ret i16 %1
}

define i32 @test_ctpop_i32(i32 %a) nounwind {
;
; RV64I-LABEL: test_ctpop_i32:
; RV64I:       # %bb.0:
; RV64I-NEXT:    srli a1, a0, 1
; RV64I-NEXT:    lui a2, 349525
; RV64I-NEXT:    addi a2, a2, 1365
; RV64I-NEXT:    and a1, a1, a2
; RV64I-NEXT:    lui a2, 209715
; RV64I-NEXT:    addi a2, a2, 819
; RV64I-NEXT:    sub a0, a0, a1
; RV64I-NEXT:    and a1, a0, a2
; RV64I-NEXT:    srli a0, a0, 2
; RV64I-NEXT:    and a0, a0, a2
; RV64I-NEXT:    lui a2, 61681
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    srli a1, a0, 4
; RV64I-NEXT:    addw a0, a0, a1
; RV64I-NEXT:    lui a1, 4112
; RV64I-NEXT:    addi a2, a2, -241
; RV64I-NEXT:    and a0, a0, a2
; RV64I-NEXT:    addi a1, a1, 257
; RV64I-NEXT:    mulw a0, a0, a1
; RV64I-NEXT:    srliw a0, a0, 24
; RV64I-NEXT:    ret
;
; RV64M-LABEL: test_ctpop_i32:
; RV64M:       # %bb.0:
; RV64M-NEXT:    srli a1, a0, 1
; RV64M-NEXT:    lui a2, 349525
; RV64M-NEXT:    addi a2, a2, 1365
; RV64M-NEXT:    and a1, a1, a2
; RV64M-NEXT:    lui a2, 209715
; RV64M-NEXT:    addi a2, a2, 819
; RV64M-NEXT:    sub a0, a0, a1
; RV64M-NEXT:    and a1, a0, a2
; RV64M-NEXT:    srli a0, a0, 2
; RV64M-NEXT:    and a0, a0, a2
; RV64M-NEXT:    lui a2, 61681
; RV64M-NEXT:    add a0, a1, a0
; RV64M-NEXT:    srli a1, a0, 4
; RV64M-NEXT:    addw a0, a0, a1
; RV64M-NEXT:    lui a1, 4112
; RV64M-NEXT:    addi a2, a2, -241
; RV64M-NEXT:    and a0, a0, a2
; RV64M-NEXT:    addi a1, a1, 257
; RV64M-NEXT:    mulw a0, a0, a1
; RV64M-NEXT:    srliw a0, a0, 24
; RV64M-NEXT:    ret
  %1 = call i32 @llvm.ctpop.i32(i32 %a)
  ret i32 %1
}

define i64 @test_ctpop_i64(i64 %a) nounwind {
;
; RV64I-LABEL: test_ctpop_i64:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lui a1, 349525
; RV64I-NEXT:    lui a2, 209715
; RV64I-NEXT:    lui a3, 61681
; RV64I-NEXT:    addi a1, a1, 1365
; RV64I-NEXT:    addi a2, a2, 819
; RV64I-NEXT:    addi a3, a3, -241
; RV64I-NEXT:    slli a4, a1, 32
; RV64I-NEXT:    add a1, a1, a4
; RV64I-NEXT:    slli a4, a2, 32
; RV64I-NEXT:    add a2, a2, a4
; RV64I-NEXT:    slli a4, a3, 32
; RV64I-NEXT:    add a3, a3, a4
; RV64I-NEXT:    srli a4, a0, 1
; RV64I-NEXT:    and a1, a4, a1
; RV64I-NEXT:    sub a0, a0, a1
; RV64I-NEXT:    and a1, a0, a2
; RV64I-NEXT:    srli a0, a0, 2
; RV64I-NEXT:    and a0, a0, a2
; RV64I-NEXT:    lui a2, 4112
; RV64I-NEXT:    addi a2, a2, 257
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    srli a1, a0, 4
; RV64I-NEXT:    add a0, a0, a1
; RV64I-NEXT:    slli a1, a2, 32
; RV64I-NEXT:    and a0, a0, a3
; RV64I-NEXT:    add a1, a2, a1
; RV64I-NEXT:    mul a0, a0, a1
; RV64I-NEXT:    srli a0, a0, 56
; RV64I-NEXT:    ret
;
; RV64M-LABEL: test_ctpop_i64:
; RV64M:       # %bb.0:
; RV64M-NEXT:    lui a1, 349525
; RV64M-NEXT:    lui a2, 209715
; RV64M-NEXT:    lui a3, 61681
; RV64M-NEXT:    addi a1, a1, 1365
; RV64M-NEXT:    addi a2, a2, 819
; RV64M-NEXT:    addi a3, a3, -241
; RV64M-NEXT:    slli a4, a1, 32
; RV64M-NEXT:    add a1, a1, a4
; RV64M-NEXT:    slli a4, a2, 32
; RV64M-NEXT:    add a2, a2, a4
; RV64M-NEXT:    slli a4, a3, 32
; RV64M-NEXT:    add a3, a3, a4
; RV64M-NEXT:    srli a4, a0, 1
; RV64M-NEXT:    and a1, a4, a1
; RV64M-NEXT:    sub a0, a0, a1
; RV64M-NEXT:    and a1, a0, a2
; RV64M-NEXT:    srli a0, a0, 2
; RV64M-NEXT:    and a0, a0, a2
; RV64M-NEXT:    lui a2, 4112
; RV64M-NEXT:    addi a2, a2, 257
; RV64M-NEXT:    add a0, a1, a0
; RV64M-NEXT:    srli a1, a0, 4
; RV64M-NEXT:    add a0, a0, a1
; RV64M-NEXT:    slli a1, a2, 32
; RV64M-NEXT:    and a0, a0, a3
; RV64M-NEXT:    add a1, a2, a1
; RV64M-NEXT:    mul a0, a0, a1
; RV64M-NEXT:    srli a0, a0, 56
; RV64M-NEXT:    ret
  %1 = call i64 @llvm.ctpop.i64(i64 %a)
  ret i64 %1
}

define i8 @test_parity_i8(i8 %a) {
;
; RV64I-LABEL: test_parity_i8:
; RV64I:       # %bb.0:
; RV64I-NEXT:    zext.b a0, a0
; RV64I-NEXT:    srli a1, a0, 4
; RV64I-NEXT:    xor a0, a0, a1
; RV64I-NEXT:    srli a1, a0, 2
; RV64I-NEXT:    xor a0, a0, a1
; RV64I-NEXT:    srli a1, a0, 1
; RV64I-NEXT:    xor a0, a0, a1
; RV64I-NEXT:    andi a0, a0, 1
; RV64I-NEXT:    ret
;
; RV64M-LABEL: test_parity_i8:
; RV64M:       # %bb.0:
; RV64M-NEXT:    zext.b a0, a0
; RV64M-NEXT:    srli a1, a0, 4
; RV64M-NEXT:    xor a0, a0, a1
; RV64M-NEXT:    srli a1, a0, 2
; RV64M-NEXT:    xor a0, a0, a1
; RV64M-NEXT:    srli a1, a0, 1
; RV64M-NEXT:    xor a0, a0, a1
; RV64M-NEXT:    andi a0, a0, 1
; RV64M-NEXT:    ret
  %1 = call i8 @llvm.ctpop.i8(i8 %a)
  %2 = and i8 %1, 1
  ret i8 %2
}

define i16 @test_parity_i16(i16 %a) {
;
; RV64I-LABEL: test_parity_i16:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 48
; RV64I-NEXT:    srli a0, a0, 48
; RV64I-NEXT:    srli a1, a0, 8
; RV64I-NEXT:    xor a0, a0, a1
; RV64I-NEXT:    srli a1, a0, 4
; RV64I-NEXT:    xor a0, a0, a1
; RV64I-NEXT:    srli a1, a0, 2
; RV64I-NEXT:    xor a0, a0, a1
; RV64I-NEXT:    srli a1, a0, 1
; RV64I-NEXT:    xor a0, a0, a1
; RV64I-NEXT:    andi a0, a0, 1
; RV64I-NEXT:    ret
;
; RV64M-LABEL: test_parity_i16:
; RV64M:       # %bb.0:
; RV64M-NEXT:    slli a0, a0, 48
; RV64M-NEXT:    srli a0, a0, 48
; RV64M-NEXT:    srli a1, a0, 8
; RV64M-NEXT:    xor a0, a0, a1
; RV64M-NEXT:    srli a1, a0, 4
; RV64M-NEXT:    xor a0, a0, a1
; RV64M-NEXT:    srli a1, a0, 2
; RV64M-NEXT:    xor a0, a0, a1
; RV64M-NEXT:    srli a1, a0, 1
; RV64M-NEXT:    xor a0, a0, a1
; RV64M-NEXT:    andi a0, a0, 1
; RV64M-NEXT:    ret
  %1 = call i16 @llvm.ctpop.i16(i16 %a)
  %2 = and i16 %1, 1
  ret i16 %2
}

define i32 @test_parity_i32(i32 %a) {
;
; RV64I-LABEL: test_parity_i32:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a1, a0, 32
; RV64I-NEXT:    srli a1, a1, 32
; RV64I-NEXT:    srliw a0, a0, 16
; RV64I-NEXT:    xor a0, a1, a0
; RV64I-NEXT:    srli a1, a0, 8
; RV64I-NEXT:    xor a0, a0, a1
; RV64I-NEXT:    srli a1, a0, 4
; RV64I-NEXT:    xor a0, a0, a1
; RV64I-NEXT:    srli a1, a0, 2
; RV64I-NEXT:    xor a0, a0, a1
; RV64I-NEXT:    srli a1, a0, 1
; RV64I-NEXT:    xor a0, a0, a1
; RV64I-NEXT:    andi a0, a0, 1
; RV64I-NEXT:    ret
;
; RV64M-LABEL: test_parity_i32:
; RV64M:       # %bb.0:
; RV64M-NEXT:    slli a1, a0, 32
; RV64M-NEXT:    srli a1, a1, 32
; RV64M-NEXT:    srliw a0, a0, 16
; RV64M-NEXT:    xor a0, a1, a0
; RV64M-NEXT:    srli a1, a0, 8
; RV64M-NEXT:    xor a0, a0, a1
; RV64M-NEXT:    srli a1, a0, 4
; RV64M-NEXT:    xor a0, a0, a1
; RV64M-NEXT:    srli a1, a0, 2
; RV64M-NEXT:    xor a0, a0, a1
; RV64M-NEXT:    srli a1, a0, 1
; RV64M-NEXT:    xor a0, a0, a1
; RV64M-NEXT:    andi a0, a0, 1
; RV64M-NEXT:    ret
  %1 = call i32 @llvm.ctpop.i32(i32 %a)
  %2 = and i32 %1, 1
  ret i32 %2
}

define i64 @test_parity_i64(i64 %a) {
;
; RV64I-LABEL: test_parity_i64:
; RV64I:       # %bb.0:
; RV64I-NEXT:    srli a1, a0, 32
; RV64I-NEXT:    xor a0, a0, a1
; RV64I-NEXT:    srli a1, a0, 16
; RV64I-NEXT:    xor a0, a0, a1
; RV64I-NEXT:    srli a1, a0, 8
; RV64I-NEXT:    xor a0, a0, a1
; RV64I-NEXT:    srli a1, a0, 4
; RV64I-NEXT:    xor a0, a0, a1
; RV64I-NEXT:    srli a1, a0, 2
; RV64I-NEXT:    xor a0, a0, a1
; RV64I-NEXT:    srli a1, a0, 1
; RV64I-NEXT:    xor a0, a0, a1
; RV64I-NEXT:    andi a0, a0, 1
; RV64I-NEXT:    ret
;
; RV64M-LABEL: test_parity_i64:
; RV64M:       # %bb.0:
; RV64M-NEXT:    srli a1, a0, 32
; RV64M-NEXT:    xor a0, a0, a1
; RV64M-NEXT:    srli a1, a0, 16
; RV64M-NEXT:    xor a0, a0, a1
; RV64M-NEXT:    srli a1, a0, 8
; RV64M-NEXT:    xor a0, a0, a1
; RV64M-NEXT:    srli a1, a0, 4
; RV64M-NEXT:    xor a0, a0, a1
; RV64M-NEXT:    srli a1, a0, 2
; RV64M-NEXT:    xor a0, a0, a1
; RV64M-NEXT:    srli a1, a0, 1
; RV64M-NEXT:    xor a0, a0, a1
; RV64M-NEXT:    andi a0, a0, 1
; RV64M-NEXT:    ret
  %1 = call i64 @llvm.ctpop.i64(i64 %a)
  %2 = and i64 %1, 1
  ret i64 %2
}
