; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ysx64 -mattr=+m -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefixes=RV64IM %s

define i32 @testsize1(i32 %x) minsize nounwind {
;
; RV64IM-LABEL: testsize1:
; RV64IM:       # %bb.0: # %entry
; RV64IM-NEXT:    li a1, 32
; RV64IM-NEXT:    divw a0, a0, a1
; RV64IM-NEXT:    ret
entry:
  %div = sdiv i32 %x, 32
  ret i32 %div
}

define i32 @testsize2(i32 %x) minsize nounwind {
;
; RV64IM-LABEL: testsize2:
; RV64IM:       # %bb.0: # %entry
; RV64IM-NEXT:    li a1, 33
; RV64IM-NEXT:    divw a0, a0, a1
; RV64IM-NEXT:    ret
entry:
  %div = sdiv i32 %x, 33
  ret i32 %div
}

define i32 @testsize3(i32 %x) minsize nounwind {
;
; RV64IM-LABEL: testsize3:
; RV64IM:       # %bb.0: # %entry
; RV64IM-NEXT:    srliw a0, a0, 5
; RV64IM-NEXT:    ret
entry:
  %div = udiv i32 %x, 32
  ret i32 %div
}

define i32 @testsize4(i32 %x) minsize nounwind {
;
; RV64IM-LABEL: testsize4:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    li a1, 33
; RV64IM-NEXT:    divuw a0, a0, a1
; RV64IM-NEXT:    ret
  %div = udiv i32 %x, 33
  ret i32 %div
}

define i128 @i128_sdiv(i128 %arg0) minsize nounwind {
;
; RV64IM-LABEL: i128_sdiv:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    addi sp, sp, -16
; RV64IM-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64IM-NEXT:    li a2, 4
; RV64IM-NEXT:    li a3, 0
; RV64IM-NEXT:    call __divti3
; RV64IM-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64IM-NEXT:    addi sp, sp, 16
; RV64IM-NEXT:    ret
  %div = sdiv i128 %arg0, 4
  ret i128 %div
}

define i256 @i256_sdiv(i256 %arg0) minsize nounwind {
;
; RV64IM-LABEL: i256_sdiv:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    srai a4, a3, 63
; RV64IM-NEXT:    srli a4, a4, 62
; RV64IM-NEXT:    add a4, a0, a4
; RV64IM-NEXT:    sltu a0, a4, a0
; RV64IM-NEXT:    srli a4, a4, 2
; RV64IM-NEXT:    add a5, a1, a0
; RV64IM-NEXT:    sltu a1, a5, a1
; RV64IM-NEXT:    and a1, a0, a1
; RV64IM-NEXT:    slli a0, a5, 62
; RV64IM-NEXT:    srli a5, a5, 2
; RV64IM-NEXT:    or a0, a4, a0
; RV64IM-NEXT:    add a1, a2, a1
; RV64IM-NEXT:    srli a4, a1, 2
; RV64IM-NEXT:    sltu a2, a1, a2
; RV64IM-NEXT:    slli a1, a1, 62
; RV64IM-NEXT:    add a3, a3, a2
; RV64IM-NEXT:    or a1, a5, a1
; RV64IM-NEXT:    slli a2, a3, 62
; RV64IM-NEXT:    or a2, a4, a2
; RV64IM-NEXT:    srai a3, a3, 2
; RV64IM-NEXT:    ret
  %div = sdiv i256 %arg0, 4
  ret i256 %div
}
