; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ysx64 -mattr=+m -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefixes=RV64IM %s

define i32 @testsize1(i32 %x) minsize nounwind {
;
; RV64IM-LABEL: testsize1:
; RV64IM:       # %bb.0: # %entry
; RV64IM-NEXT:    li a1, 32
; RV64IM-NEXT:    divw a0, a0, a1
; RV64IM-NEXT:    ret
entry:
  %div = sdiv i32 %x, 32
  ret i32 %div
}

define i32 @testsize2(i32 %x) minsize nounwind {
;
; RV64IM-LABEL: testsize2:
; RV64IM:       # %bb.0: # %entry
; RV64IM-NEXT:    li a1, 33
; RV64IM-NEXT:    divw a0, a0, a1
; RV64IM-NEXT:    ret
entry:
  %div = sdiv i32 %x, 33
  ret i32 %div
}

define i32 @testsize3(i32 %x) minsize nounwind {
;
; RV64IM-LABEL: testsize3:
; RV64IM:       # %bb.0: # %entry
; RV64IM-NEXT:    srliw a0, a0, 5
; RV64IM-NEXT:    ret
entry:
  %div = udiv i32 %x, 32
  ret i32 %div
}

define i32 @testsize4(i32 %x) minsize nounwind {
;
; RV64IM-LABEL: testsize4:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    li a1, 33
; RV64IM-NEXT:    divuw a0, a0, a1
; RV64IM-NEXT:    ret
  %div = udiv i32 %x, 33
  ret i32 %div
}

define i128 @i128_sdiv(i128 %arg0) minsize nounwind {
;
; RV64IM-LABEL: i128_sdiv:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    addi sp, sp, -16
; RV64IM-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64IM-NEXT:    li a2, 4
; RV64IM-NEXT:    li a3, 0
; RV64IM-NEXT:    call __divti3
; RV64IM-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64IM-NEXT:    addi sp, sp, 16
; RV64IM-NEXT:    ret
  %div = sdiv i128 %arg0, 4
  ret i128 %div
}

define i256 @i256_sdiv(i256 %arg0) minsize nounwind {
;
; RV64IM-LABEL: i256_sdiv:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    ld a2, 24(a1)
; RV64IM-NEXT:    ld a3, 16(a1)
; RV64IM-NEXT:    ld a4, 0(a1)
; RV64IM-NEXT:    ld a1, 8(a1)
; RV64IM-NEXT:    srai a5, a2, 63
; RV64IM-NEXT:    srli a5, a5, 62
; RV64IM-NEXT:    add a5, a4, a5
; RV64IM-NEXT:    sltu a4, a5, a4
; RV64IM-NEXT:    srli a5, a5, 2
; RV64IM-NEXT:    add a6, a1, a4
; RV64IM-NEXT:    sltu a1, a6, a1
; RV64IM-NEXT:    and a1, a4, a1
; RV64IM-NEXT:    srli a4, a6, 2
; RV64IM-NEXT:    slli a6, a6, 62
; RV64IM-NEXT:    or a5, a5, a6
; RV64IM-NEXT:    add a1, a3, a1
; RV64IM-NEXT:    srli a6, a1, 2
; RV64IM-NEXT:    sltu a3, a1, a3
; RV64IM-NEXT:    slli a1, a1, 62
; RV64IM-NEXT:    add a2, a2, a3
; RV64IM-NEXT:    or a1, a4, a1
; RV64IM-NEXT:    slli a3, a2, 62
; RV64IM-NEXT:    srai a2, a2, 2
; RV64IM-NEXT:    or a3, a6, a3
; RV64IM-NEXT:    sd a5, 0(a0)
; RV64IM-NEXT:    sd a1, 8(a0)
; RV64IM-NEXT:    sd a3, 16(a0)
; RV64IM-NEXT:    sd a2, 24(a0)
; RV64IM-NEXT:    ret
  %div = sdiv i256 %arg0, 4
  ret i256 %div
}
