; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ysx64 < %s \
; RUN:   | FileCheck -check-prefix=RV64 %s
; RUN: llc -mtriple=ysx64 -frame-pointer=all -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV64-WITHFP %s

; RUN: llc -mtriple=ysx64 --enable-shrink-wrap=false < %s \
; RUN:   | FileCheck -check-prefix=RV64-DISABLESW %s
; RUN: llc -mtriple=ysx64 -frame-pointer=all --enable-shrink-wrap=false -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV64-WITHFP-DISABLESW %s

define void @trivial() {
;
; RV64-LABEL: trivial:
; RV64:       # %bb.0:
; RV64-NEXT:    ret
;
; RV64-WITHFP-LABEL: trivial:
; RV64-WITHFP:       # %bb.0:
; RV64-WITHFP-NEXT:    addi sp, sp, -16
; RV64-WITHFP-NEXT:    .cfi_def_cfa_offset 16
; RV64-WITHFP-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64-WITHFP-NEXT:    sd s0, 0(sp) # 8-byte Folded Spill
; RV64-WITHFP-NEXT:    .cfi_offset ra, -8
; RV64-WITHFP-NEXT:    .cfi_offset s0, -16
; RV64-WITHFP-NEXT:    addi s0, sp, 16
; RV64-WITHFP-NEXT:    .cfi_def_cfa s0, 0
; RV64-WITHFP-NEXT:    .cfi_def_cfa sp, 16
; RV64-WITHFP-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64-WITHFP-NEXT:    ld s0, 0(sp) # 8-byte Folded Reload
; RV64-WITHFP-NEXT:    .cfi_restore ra
; RV64-WITHFP-NEXT:    .cfi_restore s0
; RV64-WITHFP-NEXT:    addi sp, sp, 16
; RV64-WITHFP-NEXT:    .cfi_def_cfa_offset 0
; RV64-WITHFP-NEXT:    ret
;
; RV64-DISABLESW-LABEL: trivial:
; RV64-DISABLESW:       # %bb.0:
; RV64-DISABLESW-NEXT:    ret
;
; RV64-WITHFP-DISABLESW-LABEL: trivial:
; RV64-WITHFP-DISABLESW:       # %bb.0:
; RV64-WITHFP-DISABLESW-NEXT:    addi sp, sp, -16
; RV64-WITHFP-DISABLESW-NEXT:    .cfi_def_cfa_offset 16
; RV64-WITHFP-DISABLESW-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64-WITHFP-DISABLESW-NEXT:    sd s0, 0(sp) # 8-byte Folded Spill
; RV64-WITHFP-DISABLESW-NEXT:    .cfi_offset ra, -8
; RV64-WITHFP-DISABLESW-NEXT:    .cfi_offset s0, -16
; RV64-WITHFP-DISABLESW-NEXT:    addi s0, sp, 16
; RV64-WITHFP-DISABLESW-NEXT:    .cfi_def_cfa s0, 0
; RV64-WITHFP-DISABLESW-NEXT:    .cfi_def_cfa sp, 16
; RV64-WITHFP-DISABLESW-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64-WITHFP-DISABLESW-NEXT:    ld s0, 0(sp) # 8-byte Folded Reload
; RV64-WITHFP-DISABLESW-NEXT:    .cfi_restore ra
; RV64-WITHFP-DISABLESW-NEXT:    .cfi_restore s0
; RV64-WITHFP-DISABLESW-NEXT:    addi sp, sp, 16
; RV64-WITHFP-DISABLESW-NEXT:    .cfi_def_cfa_offset 0
; RV64-WITHFP-DISABLESW-NEXT:    ret
  ret void
}

define void @stack_alloc(i32 signext %size) {
;
; RV64-LABEL: stack_alloc:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    addi sp, sp, -16
; RV64-NEXT:    .cfi_def_cfa_offset 16
; RV64-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s0, 0(sp) # 8-byte Folded Spill
; RV64-NEXT:    .cfi_offset ra, -8
; RV64-NEXT:    .cfi_offset s0, -16
; RV64-NEXT:    addi s0, sp, 16
; RV64-NEXT:    .cfi_def_cfa s0, 0
; RV64-NEXT:    slli a0, a0, 32
; RV64-NEXT:    srli a0, a0, 32
; RV64-NEXT:    addi a0, a0, 15
; RV64-NEXT:    andi a0, a0, -16
; RV64-NEXT:    sub a0, sp, a0
; RV64-NEXT:    mv sp, a0
; RV64-NEXT:    call callee_with_args
; RV64-NEXT:    addi sp, s0, -16
; RV64-NEXT:    .cfi_def_cfa sp, 16
; RV64-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64-NEXT:    ld s0, 0(sp) # 8-byte Folded Reload
; RV64-NEXT:    .cfi_restore ra
; RV64-NEXT:    .cfi_restore s0
; RV64-NEXT:    addi sp, sp, 16
; RV64-NEXT:    .cfi_def_cfa_offset 0
; RV64-NEXT:    ret
;
; RV64-WITHFP-LABEL: stack_alloc:
; RV64-WITHFP:       # %bb.0: # %entry
; RV64-WITHFP-NEXT:    addi sp, sp, -16
; RV64-WITHFP-NEXT:    .cfi_def_cfa_offset 16
; RV64-WITHFP-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64-WITHFP-NEXT:    sd s0, 0(sp) # 8-byte Folded Spill
; RV64-WITHFP-NEXT:    .cfi_offset ra, -8
; RV64-WITHFP-NEXT:    .cfi_offset s0, -16
; RV64-WITHFP-NEXT:    addi s0, sp, 16
; RV64-WITHFP-NEXT:    .cfi_def_cfa s0, 0
; RV64-WITHFP-NEXT:    slli a0, a0, 32
; RV64-WITHFP-NEXT:    srli a0, a0, 32
; RV64-WITHFP-NEXT:    addi a0, a0, 15
; RV64-WITHFP-NEXT:    andi a0, a0, -16
; RV64-WITHFP-NEXT:    sub a0, sp, a0
; RV64-WITHFP-NEXT:    mv sp, a0
; RV64-WITHFP-NEXT:    call callee_with_args
; RV64-WITHFP-NEXT:    addi sp, s0, -16
; RV64-WITHFP-NEXT:    .cfi_def_cfa sp, 16
; RV64-WITHFP-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64-WITHFP-NEXT:    ld s0, 0(sp) # 8-byte Folded Reload
; RV64-WITHFP-NEXT:    .cfi_restore ra
; RV64-WITHFP-NEXT:    .cfi_restore s0
; RV64-WITHFP-NEXT:    addi sp, sp, 16
; RV64-WITHFP-NEXT:    .cfi_def_cfa_offset 0
; RV64-WITHFP-NEXT:    ret
;
; RV64-DISABLESW-LABEL: stack_alloc:
; RV64-DISABLESW:       # %bb.0: # %entry
; RV64-DISABLESW-NEXT:    addi sp, sp, -16
; RV64-DISABLESW-NEXT:    .cfi_def_cfa_offset 16
; RV64-DISABLESW-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64-DISABLESW-NEXT:    sd s0, 0(sp) # 8-byte Folded Spill
; RV64-DISABLESW-NEXT:    .cfi_offset ra, -8
; RV64-DISABLESW-NEXT:    .cfi_offset s0, -16
; RV64-DISABLESW-NEXT:    addi s0, sp, 16
; RV64-DISABLESW-NEXT:    .cfi_def_cfa s0, 0
; RV64-DISABLESW-NEXT:    slli a0, a0, 32
; RV64-DISABLESW-NEXT:    srli a0, a0, 32
; RV64-DISABLESW-NEXT:    addi a0, a0, 15
; RV64-DISABLESW-NEXT:    andi a0, a0, -16
; RV64-DISABLESW-NEXT:    sub a0, sp, a0
; RV64-DISABLESW-NEXT:    mv sp, a0
; RV64-DISABLESW-NEXT:    call callee_with_args
; RV64-DISABLESW-NEXT:    addi sp, s0, -16
; RV64-DISABLESW-NEXT:    .cfi_def_cfa sp, 16
; RV64-DISABLESW-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64-DISABLESW-NEXT:    ld s0, 0(sp) # 8-byte Folded Reload
; RV64-DISABLESW-NEXT:    .cfi_restore ra
; RV64-DISABLESW-NEXT:    .cfi_restore s0
; RV64-DISABLESW-NEXT:    addi sp, sp, 16
; RV64-DISABLESW-NEXT:    .cfi_def_cfa_offset 0
; RV64-DISABLESW-NEXT:    ret
;
; RV64-WITHFP-DISABLESW-LABEL: stack_alloc:
; RV64-WITHFP-DISABLESW:       # %bb.0: # %entry
; RV64-WITHFP-DISABLESW-NEXT:    addi sp, sp, -16
; RV64-WITHFP-DISABLESW-NEXT:    .cfi_def_cfa_offset 16
; RV64-WITHFP-DISABLESW-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64-WITHFP-DISABLESW-NEXT:    sd s0, 0(sp) # 8-byte Folded Spill
; RV64-WITHFP-DISABLESW-NEXT:    .cfi_offset ra, -8
; RV64-WITHFP-DISABLESW-NEXT:    .cfi_offset s0, -16
; RV64-WITHFP-DISABLESW-NEXT:    addi s0, sp, 16
; RV64-WITHFP-DISABLESW-NEXT:    .cfi_def_cfa s0, 0
; RV64-WITHFP-DISABLESW-NEXT:    slli a0, a0, 32
; RV64-WITHFP-DISABLESW-NEXT:    srli a0, a0, 32
; RV64-WITHFP-DISABLESW-NEXT:    addi a0, a0, 15
; RV64-WITHFP-DISABLESW-NEXT:    andi a0, a0, -16
; RV64-WITHFP-DISABLESW-NEXT:    sub a0, sp, a0
; RV64-WITHFP-DISABLESW-NEXT:    mv sp, a0
; RV64-WITHFP-DISABLESW-NEXT:    call callee_with_args
; RV64-WITHFP-DISABLESW-NEXT:    addi sp, s0, -16
; RV64-WITHFP-DISABLESW-NEXT:    .cfi_def_cfa sp, 16
; RV64-WITHFP-DISABLESW-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64-WITHFP-DISABLESW-NEXT:    ld s0, 0(sp) # 8-byte Folded Reload
; RV64-WITHFP-DISABLESW-NEXT:    .cfi_restore ra
; RV64-WITHFP-DISABLESW-NEXT:    .cfi_restore s0
; RV64-WITHFP-DISABLESW-NEXT:    addi sp, sp, 16
; RV64-WITHFP-DISABLESW-NEXT:    .cfi_def_cfa_offset 0
; RV64-WITHFP-DISABLESW-NEXT:    ret
entry:
  %0 = alloca i8, i32 %size, align 16
  call void @callee_with_args(ptr nonnull %0)
  ret void
}

define void @branch_and_tail_call(i1 %a) {
;
; RV64-LABEL: branch_and_tail_call:
; RV64:       # %bb.0:
; RV64-NEXT:    andi a0, a0, 1
; RV64-NEXT:    beqz a0, .LBB2_2
; RV64-NEXT:  # %bb.1: # %blue_pill
; RV64-NEXT:    tail callee1
; RV64-NEXT:  .LBB2_2: # %red_pill
; RV64-NEXT:    addi sp, sp, -16
; RV64-NEXT:    .cfi_def_cfa_offset 16
; RV64-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64-NEXT:    .cfi_offset ra, -8
; RV64-NEXT:    call callee2
; RV64-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64-NEXT:    .cfi_restore ra
; RV64-NEXT:    addi sp, sp, 16
; RV64-NEXT:    .cfi_def_cfa_offset 0
; RV64-NEXT:    ret
;
; RV64-WITHFP-LABEL: branch_and_tail_call:
; RV64-WITHFP:       # %bb.0:
; RV64-WITHFP-NEXT:    andi a0, a0, 1
; RV64-WITHFP-NEXT:    beqz a0, .LBB2_2
; RV64-WITHFP-NEXT:  # %bb.1: # %blue_pill
; RV64-WITHFP-NEXT:    tail callee1
; RV64-WITHFP-NEXT:  .LBB2_2: # %red_pill
; RV64-WITHFP-NEXT:    addi sp, sp, -16
; RV64-WITHFP-NEXT:    .cfi_def_cfa_offset 16
; RV64-WITHFP-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64-WITHFP-NEXT:    sd s0, 0(sp) # 8-byte Folded Spill
; RV64-WITHFP-NEXT:    .cfi_offset ra, -8
; RV64-WITHFP-NEXT:    .cfi_offset s0, -16
; RV64-WITHFP-NEXT:    addi s0, sp, 16
; RV64-WITHFP-NEXT:    .cfi_def_cfa s0, 0
; RV64-WITHFP-NEXT:    call callee2
; RV64-WITHFP-NEXT:    .cfi_def_cfa sp, 16
; RV64-WITHFP-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64-WITHFP-NEXT:    ld s0, 0(sp) # 8-byte Folded Reload
; RV64-WITHFP-NEXT:    .cfi_restore ra
; RV64-WITHFP-NEXT:    .cfi_restore s0
; RV64-WITHFP-NEXT:    addi sp, sp, 16
; RV64-WITHFP-NEXT:    .cfi_def_cfa_offset 0
; RV64-WITHFP-NEXT:    ret
;
; RV64-DISABLESW-LABEL: branch_and_tail_call:
; RV64-DISABLESW:       # %bb.0:
; RV64-DISABLESW-NEXT:    addi sp, sp, -16
; RV64-DISABLESW-NEXT:    .cfi_def_cfa_offset 16
; RV64-DISABLESW-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64-DISABLESW-NEXT:    .cfi_offset ra, -8
; RV64-DISABLESW-NEXT:    .cfi_remember_state
; RV64-DISABLESW-NEXT:    andi a0, a0, 1
; RV64-DISABLESW-NEXT:    beqz a0, .LBB2_2
; RV64-DISABLESW-NEXT:  # %bb.1: # %blue_pill
; RV64-DISABLESW-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64-DISABLESW-NEXT:    .cfi_restore ra
; RV64-DISABLESW-NEXT:    addi sp, sp, 16
; RV64-DISABLESW-NEXT:    .cfi_def_cfa_offset 0
; RV64-DISABLESW-NEXT:    tail callee1
; RV64-DISABLESW-NEXT:  .LBB2_2: # %red_pill
; RV64-DISABLESW-NEXT:    .cfi_restore_state
; RV64-DISABLESW-NEXT:    call callee2
; RV64-DISABLESW-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64-DISABLESW-NEXT:    .cfi_restore ra
; RV64-DISABLESW-NEXT:    addi sp, sp, 16
; RV64-DISABLESW-NEXT:    .cfi_def_cfa_offset 0
; RV64-DISABLESW-NEXT:    ret
;
; RV64-WITHFP-DISABLESW-LABEL: branch_and_tail_call:
; RV64-WITHFP-DISABLESW:       # %bb.0:
; RV64-WITHFP-DISABLESW-NEXT:    addi sp, sp, -16
; RV64-WITHFP-DISABLESW-NEXT:    .cfi_def_cfa_offset 16
; RV64-WITHFP-DISABLESW-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64-WITHFP-DISABLESW-NEXT:    sd s0, 0(sp) # 8-byte Folded Spill
; RV64-WITHFP-DISABLESW-NEXT:    .cfi_offset ra, -8
; RV64-WITHFP-DISABLESW-NEXT:    .cfi_offset s0, -16
; RV64-WITHFP-DISABLESW-NEXT:    addi s0, sp, 16
; RV64-WITHFP-DISABLESW-NEXT:    .cfi_def_cfa s0, 0
; RV64-WITHFP-DISABLESW-NEXT:    .cfi_remember_state
; RV64-WITHFP-DISABLESW-NEXT:    andi a0, a0, 1
; RV64-WITHFP-DISABLESW-NEXT:    beqz a0, .LBB2_2
; RV64-WITHFP-DISABLESW-NEXT:  # %bb.1: # %blue_pill
; RV64-WITHFP-DISABLESW-NEXT:    .cfi_def_cfa sp, 16
; RV64-WITHFP-DISABLESW-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64-WITHFP-DISABLESW-NEXT:    ld s0, 0(sp) # 8-byte Folded Reload
; RV64-WITHFP-DISABLESW-NEXT:    .cfi_restore ra
; RV64-WITHFP-DISABLESW-NEXT:    .cfi_restore s0
; RV64-WITHFP-DISABLESW-NEXT:    addi sp, sp, 16
; RV64-WITHFP-DISABLESW-NEXT:    .cfi_def_cfa_offset 0
; RV64-WITHFP-DISABLESW-NEXT:    tail callee1
; RV64-WITHFP-DISABLESW-NEXT:  .LBB2_2: # %red_pill
; RV64-WITHFP-DISABLESW-NEXT:    .cfi_restore_state
; RV64-WITHFP-DISABLESW-NEXT:    call callee2
; RV64-WITHFP-DISABLESW-NEXT:    .cfi_def_cfa sp, 16
; RV64-WITHFP-DISABLESW-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64-WITHFP-DISABLESW-NEXT:    ld s0, 0(sp) # 8-byte Folded Reload
; RV64-WITHFP-DISABLESW-NEXT:    .cfi_restore ra
; RV64-WITHFP-DISABLESW-NEXT:    .cfi_restore s0
; RV64-WITHFP-DISABLESW-NEXT:    addi sp, sp, 16
; RV64-WITHFP-DISABLESW-NEXT:    .cfi_def_cfa_offset 0
; RV64-WITHFP-DISABLESW-NEXT:    ret
  br i1 %a, label %blue_pill, label %red_pill
blue_pill:
  tail call void @callee1()
  ret void
red_pill:
  call void @callee2()
  ret void
}

declare void @callee1()
declare void @callee2()
declare void @callee_with_args(ptr)
