; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=ysx64-unknown-linux-gnu < %s | FileCheck %s

; Make sure that boolean immediates are properly (zero) extended.
target triple = "ysx64-unknown-linux-gnu"

define i32 @foo() #0 {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    #TEST 42 + 1 - .
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    li a0, 1
; CHECK-NEXT:    ret
entry:
  tail call void asm sideeffect "#TEST 42 + ${0:c} - .\0A\09", "i,~{dirflag},~{fpsr},~{flags}"(i1 true) #0
  ret i32 1
}

attributes #0 = { nounwind }
