; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=ysx64 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV64I

; For each of these examples, it is fewer instructions to narrow the load and
; then shift (which is an opportunity that can be exposed by doing the mask
; before the shift).

define ptr @narrow_to_lbu(ptr %a, ptr %b) {
;
; RV64I-LABEL: narrow_to_lbu:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lh a0, 0(a0)
; RV64I-NEXT:    slli a0, a0, 56
; RV64I-NEXT:    srli a0, a0, 52
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    ret
  %1 = load i16, ptr %a, align 2
  %2 = shl i16 %1, 1
  %3 = and i16 %2, 510
  %4 = zext nneg i16 %3 to i64
  %5 = getelementptr inbounds double, ptr %b, i64 %4
  ret ptr %5
}

define ptr @narrow_to_lhu(ptr %a, ptr %b) {
;
; RV64I-LABEL: narrow_to_lhu:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lw a0, 0(a0)
; RV64I-NEXT:    slli a0, a0, 48
; RV64I-NEXT:    srli a0, a0, 44
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    ret
  %1 = load i32, ptr %a, align 4
  %2 = shl i32 %1, 1
  %3 = and i32 %2, 131070
  %4 = zext nneg i32 %3 to i64
  %5 = getelementptr inbounds double, ptr %b, i64 %4
  ret ptr %5
}

define ptr @narrow_to_lwu(ptr %a, ptr %b) {
;
; RV64I-LABEL: narrow_to_lwu:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ld a0, 0(a0)
; RV64I-NEXT:    slli a0, a0, 32
; RV64I-NEXT:    srli a0, a0, 28
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    ret
  %1 = load i64, ptr %a, align 8
  %2 = shl i64 %1, 1
  %3 = and i64 %2, 8589934590
  %4 = getelementptr inbounds double, ptr %b, i64 %3
  ret ptr %4
}
