; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ysx64 -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV64I %s
; RUN: llc -mtriple=ysx64 -mattr=+m -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV64IM %s

define signext i32 @square(i32 %a) nounwind {
;
;
; RV64I-LABEL: square:
; RV64I:       # %bb.0:
; RV64I-NEXT:    mulw a0, a0, a0
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: square:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    mulw a0, a0, a0
; RV64IM-NEXT:    ret
  %1 = mul i32 %a, %a
  ret i32 %1
}

define signext i32 @mul(i32 %a, i32 %b) nounwind {
;
;
; RV64I-LABEL: mul:
; RV64I:       # %bb.0:
; RV64I-NEXT:    mulw a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: mul:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    mulw a0, a0, a1
; RV64IM-NEXT:    ret
  %1 = mul i32 %a, %b
  ret i32 %1
}

define signext i32 @mul_constant(i32 %a) nounwind {
;
;
; RV64I-LABEL: mul_constant:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slliw a1, a0, 2
; RV64I-NEXT:    addw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: mul_constant:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    slliw a1, a0, 2
; RV64IM-NEXT:    addw a0, a1, a0
; RV64IM-NEXT:    ret
  %1 = mul i32 %a, 5
  ret i32 %1
}

define i32 @mul_pow2(i32 %a) nounwind {
;
;
; RV64I-LABEL: mul_pow2:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slliw a0, a0, 3
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: mul_pow2:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    slliw a0, a0, 3
; RV64IM-NEXT:    ret
  %1 = mul i32 %a, 8
  ret i32 %1
}

define i64 @mul64(i64 %a, i64 %b) nounwind {
;
;
; RV64I-LABEL: mul64:
; RV64I:       # %bb.0:
; RV64I-NEXT:    mul a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: mul64:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    mul a0, a0, a1
; RV64IM-NEXT:    ret
  %1 = mul i64 %a, %b
  ret i64 %1
}

define i64 @mul64_constant(i64 %a) nounwind {
;
;
; RV64I-LABEL: mul64_constant:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a1, a0, 2
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: mul64_constant:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    slli a1, a0, 2
; RV64IM-NEXT:    add a0, a1, a0
; RV64IM-NEXT:    ret
  %1 = mul i64 %a, 5
  ret i64 %1
}

define i32 @mulhs(i32 %a, i32 %b) nounwind {
;
;
; RV64I-LABEL: mulhs:
; RV64I:       # %bb.0:
; RV64I-NEXT:    sext.w a0, a0
; RV64I-NEXT:    sext.w a1, a1
; RV64I-NEXT:    mul a0, a0, a1
; RV64I-NEXT:    srli a0, a0, 32
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: mulhs:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    sext.w a0, a0
; RV64IM-NEXT:    sext.w a1, a1
; RV64IM-NEXT:    mul a0, a0, a1
; RV64IM-NEXT:    srli a0, a0, 32
; RV64IM-NEXT:    ret
  %1 = sext i32 %a to i64
  %2 = sext i32 %b to i64
  %3 = mul i64 %1, %2
  %4 = lshr i64 %3, 32
  %5 = trunc i64 %4 to i32
  ret i32 %5
}

define i32 @mulhs_positive_constant(i32 %a) nounwind {
;
;
; RV64I-LABEL: mulhs_positive_constant:
; RV64I:       # %bb.0:
; RV64I-NEXT:    sext.w a0, a0
; RV64I-NEXT:    slli a1, a0, 2
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    srli a0, a0, 32
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: mulhs_positive_constant:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    sext.w a0, a0
; RV64IM-NEXT:    slli a1, a0, 2
; RV64IM-NEXT:    add a0, a1, a0
; RV64IM-NEXT:    srli a0, a0, 32
; RV64IM-NEXT:    ret
  %1 = sext i32 %a to i64
  %2 = mul i64 %1, 5
  %3 = lshr i64 %2, 32
  %4 = trunc i64 %3 to i32
  ret i32 %4
}

define i32 @mulhs_negative_constant(i32 %a) nounwind {
;
;
; RV64I-LABEL: mulhs_negative_constant:
; RV64I:       # %bb.0:
; RV64I-NEXT:    sext.w a0, a0
; RV64I-NEXT:    slli a1, a0, 2
; RV64I-NEXT:    neg a0, a0
; RV64I-NEXT:    sub a0, a0, a1
; RV64I-NEXT:    srli a0, a0, 32
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: mulhs_negative_constant:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    sext.w a0, a0
; RV64IM-NEXT:    slli a1, a0, 2
; RV64IM-NEXT:    neg a0, a0
; RV64IM-NEXT:    sub a0, a0, a1
; RV64IM-NEXT:    srli a0, a0, 32
; RV64IM-NEXT:    ret
  %1 = sext i32 %a to i64
  %2 = mul i64 %1, -5
  %3 = lshr i64 %2, 32
  %4 = trunc i64 %3 to i32
  ret i32 %4
}

define zeroext i32 @mulhu(i32 zeroext %a, i32 zeroext %b) nounwind {
;
;
; RV64I-LABEL: mulhu:
; RV64I:       # %bb.0:
; RV64I-NEXT:    mul a0, a0, a1
; RV64I-NEXT:    srli a0, a0, 32
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: mulhu:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    mul a0, a0, a1
; RV64IM-NEXT:    srli a0, a0, 32
; RV64IM-NEXT:    ret
  %1 = zext i32 %a to i64
  %2 = zext i32 %b to i64
  %3 = mul i64 %1, %2
  %4 = lshr i64 %3, 32
  %5 = trunc i64 %4 to i32
  ret i32 %5
}

define i32 @mulhsu(i32 %a, i32 %b) nounwind {
;
;
; RV64I-LABEL: mulhsu:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 32
; RV64I-NEXT:    srli a0, a0, 32
; RV64I-NEXT:    sext.w a1, a1
; RV64I-NEXT:    mul a0, a0, a1
; RV64I-NEXT:    srli a0, a0, 32
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: mulhsu:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    slli a0, a0, 32
; RV64IM-NEXT:    srli a0, a0, 32
; RV64IM-NEXT:    sext.w a1, a1
; RV64IM-NEXT:    mul a0, a0, a1
; RV64IM-NEXT:    srli a0, a0, 32
; RV64IM-NEXT:    ret
  %1 = zext i32 %a to i64
  %2 = sext i32 %b to i64
  %3 = mul i64 %1, %2
  %4 = lshr i64 %3, 32
  %5 = trunc i64 %4 to i32
  ret i32 %5
}

define i32 @mulhu_constant(i32 %a) nounwind {
;
;
; RV64I-LABEL: mulhu_constant:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 32
; RV64I-NEXT:    srli a1, a0, 32
; RV64I-NEXT:    srli a0, a0, 30
; RV64I-NEXT:    add a0, a0, a1
; RV64I-NEXT:    srli a0, a0, 32
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: mulhu_constant:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    slli a0, a0, 32
; RV64IM-NEXT:    srli a1, a0, 32
; RV64IM-NEXT:    srli a0, a0, 30
; RV64IM-NEXT:    add a0, a0, a1
; RV64IM-NEXT:    srli a0, a0, 32
; RV64IM-NEXT:    ret
  %1 = zext i32 %a to i64
  %2 = mul i64 %1, 5
  %3 = lshr i64 %2, 32
  %4 = trunc i64 %3 to i32
  ret i32 %4
}

define i32 @muli32_p10(i32 %a) nounwind {
;
;
; RV64I-LABEL: muli32_p10:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a1, 10
; RV64I-NEXT:    mulw a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli32_p10:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    li a1, 10
; RV64IM-NEXT:    mulw a0, a0, a1
; RV64IM-NEXT:    ret
  %1 = mul i32 %a, 10
  ret i32 %1
}

define i32 @muli32_p14(i32 %a) nounwind {
;
;
; RV64I-LABEL: muli32_p14:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a1, 14
; RV64I-NEXT:    mulw a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli32_p14:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    li a1, 14
; RV64IM-NEXT:    mulw a0, a0, a1
; RV64IM-NEXT:    ret
  %1 = mul i32 %a, 14
  ret i32 %1
}

define i32 @muli32_p18(i32 %a) nounwind {
;
;
; RV64I-LABEL: muli32_p18:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a1, 18
; RV64I-NEXT:    mulw a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli32_p18:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    li a1, 18
; RV64IM-NEXT:    mulw a0, a0, a1
; RV64IM-NEXT:    ret
  %1 = mul i32 %a, 18
  ret i32 %1
}

define i32 @muli32_p28(i32 %a) nounwind {
;
;
; RV64I-LABEL: muli32_p28:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a1, 28
; RV64I-NEXT:    mulw a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli32_p28:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    li a1, 28
; RV64IM-NEXT:    mulw a0, a0, a1
; RV64IM-NEXT:    ret
  %1 = mul i32 %a, 28
  ret i32 %1
}

define i32 @muli32_p30(i32 %a) nounwind {
;
;
; RV64I-LABEL: muli32_p30:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a1, 30
; RV64I-NEXT:    mulw a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli32_p30:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    li a1, 30
; RV64IM-NEXT:    mulw a0, a0, a1
; RV64IM-NEXT:    ret
  %1 = mul i32 %a, 30
  ret i32 %1
}

define i32 @muli32_p34(i32 %a) nounwind {
;
;
; RV64I-LABEL: muli32_p34:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a1, 34
; RV64I-NEXT:    mulw a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli32_p34:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    li a1, 34
; RV64IM-NEXT:    mulw a0, a0, a1
; RV64IM-NEXT:    ret
  %1 = mul i32 %a, 34
  ret i32 %1
}

define i32 @muli32_p36(i32 %a) nounwind {
;
;
; RV64I-LABEL: muli32_p36:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a1, 36
; RV64I-NEXT:    mulw a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli32_p36:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    li a1, 36
; RV64IM-NEXT:    mulw a0, a0, a1
; RV64IM-NEXT:    ret
  %1 = mul i32 %a, 36
  ret i32 %1
}

define i32 @muli32_p56(i32 %a) nounwind {
;
;
; RV64I-LABEL: muli32_p56:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a1, 56
; RV64I-NEXT:    mulw a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli32_p56:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    li a1, 56
; RV64IM-NEXT:    mulw a0, a0, a1
; RV64IM-NEXT:    ret
  %1 = mul i32 %a, 56
  ret i32 %1
}

define i32 @muli32_p60(i32 %a) nounwind {
;
;
; RV64I-LABEL: muli32_p60:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a1, 60
; RV64I-NEXT:    mulw a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli32_p60:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    li a1, 60
; RV64IM-NEXT:    mulw a0, a0, a1
; RV64IM-NEXT:    ret
  %1 = mul i32 %a, 60
  ret i32 %1
}

define i32 @muli32_p62(i32 %a) nounwind {
;
;
; RV64I-LABEL: muli32_p62:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a1, 62
; RV64I-NEXT:    mulw a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli32_p62:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    li a1, 62
; RV64IM-NEXT:    mulw a0, a0, a1
; RV64IM-NEXT:    ret
  %1 = mul i32 %a, 62
  ret i32 %1
}

define i32 @muli32_p65(i32 %a) nounwind {
;
;
; RV64I-LABEL: muli32_p65:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slliw a1, a0, 6
; RV64I-NEXT:    addw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli32_p65:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    slliw a1, a0, 6
; RV64IM-NEXT:    addw a0, a1, a0
; RV64IM-NEXT:    ret
  %1 = mul i32 %a, 65
  ret i32 %1
}

define i32 @muli32_p66(i32 %a) nounwind {
;
;
; RV64I-LABEL: muli32_p66:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a1, 66
; RV64I-NEXT:    mulw a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli32_p66:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    li a1, 66
; RV64IM-NEXT:    mulw a0, a0, a1
; RV64IM-NEXT:    ret
  %1 = mul i32 %a, 66
  ret i32 %1
}

define i32 @muli32_p63(i32 %a) nounwind {
;
;
; RV64I-LABEL: muli32_p63:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slliw a1, a0, 6
; RV64I-NEXT:    subw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli32_p63:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    slliw a1, a0, 6
; RV64IM-NEXT:    subw a0, a1, a0
; RV64IM-NEXT:    ret
  %1 = mul i32 %a, 63
  ret i32 %1
}

define i64 @muli64_p65(i64 %a) nounwind {
;
;
; RV64I-LABEL: muli64_p65:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a1, a0, 6
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli64_p65:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    slli a1, a0, 6
; RV64IM-NEXT:    add a0, a1, a0
; RV64IM-NEXT:    ret
  %1 = mul i64 %a, 65
  ret i64 %1
}

define i64 @muli64_p63(i64 %a) nounwind {
;
;
; RV64I-LABEL: muli64_p63:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a1, a0, 6
; RV64I-NEXT:    sub a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli64_p63:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    slli a1, a0, 6
; RV64IM-NEXT:    sub a0, a1, a0
; RV64IM-NEXT:    ret
  %1 = mul i64 %a, 63
  ret i64 %1
}

define i64 @muli64_p72(i64 %a) nounwind {
;
;
; RV64I-LABEL: muli64_p72:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a1, 72
; RV64I-NEXT:    mul a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli64_p72:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    li a1, 72
; RV64IM-NEXT:    mul a0, a0, a1
; RV64IM-NEXT:    ret
  %1 = mul i64 %a, 72
  ret i64 %1
}

define i64 @muli64_p68(i64 %a) nounwind {
;
;
; RV64I-LABEL: muli64_p68:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a1, 68
; RV64I-NEXT:    mul a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli64_p68:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    li a1, 68
; RV64IM-NEXT:    mul a0, a0, a1
; RV64IM-NEXT:    ret
  %1 = mul i64 %a, 68
  ret i64 %1
}

define i32 @muli32_m63(i32 %a) nounwind {
;
;
; RV64I-LABEL: muli32_m63:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slliw a1, a0, 6
; RV64I-NEXT:    subw a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli32_m63:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    slliw a1, a0, 6
; RV64IM-NEXT:    subw a0, a0, a1
; RV64IM-NEXT:    ret
  %1 = mul i32 %a, -63
  ret i32 %1
}

define i32 @muli32_m65(i32 %a) nounwind {
;
;
; RV64I-LABEL: muli32_m65:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slliw a1, a0, 6
; RV64I-NEXT:    negw a0, a0
; RV64I-NEXT:    subw a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli32_m65:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    slliw a1, a0, 6
; RV64IM-NEXT:    negw a0, a0
; RV64IM-NEXT:    subw a0, a0, a1
; RV64IM-NEXT:    ret
  %1 = mul i32 %a, -65
  ret i32 %1
}

define i64 @muli64_m63(i64 %a) nounwind {
;
;
; RV64I-LABEL: muli64_m63:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a1, a0, 6
; RV64I-NEXT:    sub a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli64_m63:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    slli a1, a0, 6
; RV64IM-NEXT:    sub a0, a0, a1
; RV64IM-NEXT:    ret
  %1 = mul i64 %a, -63
  ret i64 %1
}

define i64 @muli64_m65(i64 %a) nounwind {
;
;
; RV64I-LABEL: muli64_m65:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a1, a0, 6
; RV64I-NEXT:    neg a0, a0
; RV64I-NEXT:    sub a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli64_m65:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    slli a1, a0, 6
; RV64IM-NEXT:    neg a0, a0
; RV64IM-NEXT:    sub a0, a0, a1
; RV64IM-NEXT:    ret
  %1 = mul i64 %a, -65
  ret i64 %1
}

define i32 @muli32_p384(i32 %a) nounwind {
;
;
; RV64I-LABEL: muli32_p384:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a1, 384
; RV64I-NEXT:    mulw a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli32_p384:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    li a1, 384
; RV64IM-NEXT:    mulw a0, a0, a1
; RV64IM-NEXT:    ret
  %1 = mul i32 %a, 384
  ret i32 %1
}

define i32 @muli32_p12288(i32 %a) nounwind {
;
;
; RV64I-LABEL: muli32_p12288:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lui a1, 3
; RV64I-NEXT:    mulw a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli32_p12288:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    lui a1, 3
; RV64IM-NEXT:    mulw a0, a0, a1
; RV64IM-NEXT:    ret
  %1 = mul i32 %a, 12288
  ret i32 %1
}

define i32 @muli32_p4352(i32 %a) nounwind {
;
;
; RV64I-LABEL: muli32_p4352:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slliw a1, a0, 8
; RV64I-NEXT:    slliw a0, a0, 12
; RV64I-NEXT:    addw a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli32_p4352:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    slliw a1, a0, 8
; RV64IM-NEXT:    slliw a0, a0, 12
; RV64IM-NEXT:    addw a0, a0, a1
; RV64IM-NEXT:    ret
  %1 = mul i32 %a, 4352
  ret i32 %1
}

define i32 @muli32_p3840(i32 %a) nounwind {
;
;
; RV64I-LABEL: muli32_p3840:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slliw a1, a0, 8
; RV64I-NEXT:    slliw a0, a0, 12
; RV64I-NEXT:    subw a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli32_p3840:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    slliw a1, a0, 8
; RV64IM-NEXT:    slliw a0, a0, 12
; RV64IM-NEXT:    subw a0, a0, a1
; RV64IM-NEXT:    ret
  %1 = mul i32 %a, 3840
  ret i32 %1
}

define i32 @muli32_m3840(i32 %a) nounwind {
;
;
; RV64I-LABEL: muli32_m3840:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slliw a1, a0, 12
; RV64I-NEXT:    slliw a0, a0, 8
; RV64I-NEXT:    subw a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli32_m3840:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    slliw a1, a0, 12
; RV64IM-NEXT:    slliw a0, a0, 8
; RV64IM-NEXT:    subw a0, a0, a1
; RV64IM-NEXT:    ret
  %1 = mul i32 %a, -3840
  ret i32 %1
}

define i32 @muli32_m4352(i32 %a) nounwind {
;
;
; RV64I-LABEL: muli32_m4352:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a1, -17
; RV64I-NEXT:    slli a1, a1, 8
; RV64I-NEXT:    mulw a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli32_m4352:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    li a1, -17
; RV64IM-NEXT:    slli a1, a1, 8
; RV64IM-NEXT:    mulw a0, a0, a1
; RV64IM-NEXT:    ret
  %1 = mul i32 %a, -4352
  ret i32 %1
}

define i64 @muli64_p4352(i64 %a) nounwind {
;
;
; RV64I-LABEL: muli64_p4352:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a1, a0, 8
; RV64I-NEXT:    slli a0, a0, 12
; RV64I-NEXT:    add a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli64_p4352:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    slli a1, a0, 8
; RV64IM-NEXT:    slli a0, a0, 12
; RV64IM-NEXT:    add a0, a0, a1
; RV64IM-NEXT:    ret
  %1 = mul i64 %a, 4352
  ret i64 %1
}

define i64 @muli64_p3840(i64 %a) nounwind {
;
;
; RV64I-LABEL: muli64_p3840:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a1, a0, 8
; RV64I-NEXT:    slli a0, a0, 12
; RV64I-NEXT:    sub a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli64_p3840:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    slli a1, a0, 8
; RV64IM-NEXT:    slli a0, a0, 12
; RV64IM-NEXT:    sub a0, a0, a1
; RV64IM-NEXT:    ret
  %1 = mul i64 %a, 3840
  ret i64 %1
}

define i64 @muli64_m4352(i64 %a) nounwind {
;
;
; RV64I-LABEL: muli64_m4352:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a1, -17
; RV64I-NEXT:    slli a1, a1, 8
; RV64I-NEXT:    mul a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli64_m4352:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    li a1, -17
; RV64IM-NEXT:    slli a1, a1, 8
; RV64IM-NEXT:    mul a0, a0, a1
; RV64IM-NEXT:    ret
  %1 = mul i64 %a, -4352
  ret i64 %1
}

define i64 @muli64_m3840(i64 %a) nounwind {
;
;
; RV64I-LABEL: muli64_m3840:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a1, a0, 12
; RV64I-NEXT:    slli a0, a0, 8
; RV64I-NEXT:    sub a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli64_m3840:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    slli a1, a0, 12
; RV64IM-NEXT:    slli a0, a0, 8
; RV64IM-NEXT:    sub a0, a0, a1
; RV64IM-NEXT:    ret
  %1 = mul i64 %a, -3840
  ret i64 %1
}

define i128 @muli128_m3840(i128 %a) nounwind {
;
;
; RV64I-LABEL: muli128_m3840:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a2, -15
; RV64I-NEXT:    slli a2, a2, 8
; RV64I-NEXT:    mul a1, a1, a2
; RV64I-NEXT:    mulhu a3, a0, a2
; RV64I-NEXT:    sub a3, a3, a0
; RV64I-NEXT:    add a1, a3, a1
; RV64I-NEXT:    mul a0, a0, a2
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli128_m3840:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    li a2, -15
; RV64IM-NEXT:    slli a2, a2, 8
; RV64IM-NEXT:    mul a1, a1, a2
; RV64IM-NEXT:    mulhu a3, a0, a2
; RV64IM-NEXT:    sub a3, a3, a0
; RV64IM-NEXT:    add a1, a3, a1
; RV64IM-NEXT:    mul a0, a0, a2
; RV64IM-NEXT:    ret
  %1 = mul i128 %a, -3840
  ret i128 %1
}

define i128 @muli128_m63(i128 %a) nounwind {
;
;
; RV64I-LABEL: muli128_m63:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a2, a1, 6
; RV64I-NEXT:    sub a1, a1, a2
; RV64I-NEXT:    li a2, -63
; RV64I-NEXT:    mulhu a2, a0, a2
; RV64I-NEXT:    sub a2, a2, a0
; RV64I-NEXT:    add a1, a2, a1
; RV64I-NEXT:    slli a2, a0, 6
; RV64I-NEXT:    sub a0, a0, a2
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muli128_m63:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    slli a2, a1, 6
; RV64IM-NEXT:    sub a1, a1, a2
; RV64IM-NEXT:    li a2, -63
; RV64IM-NEXT:    mulhu a2, a0, a2
; RV64IM-NEXT:    sub a2, a2, a0
; RV64IM-NEXT:    add a1, a2, a1
; RV64IM-NEXT:    slli a2, a0, 6
; RV64IM-NEXT:    sub a0, a0, a2
; RV64IM-NEXT:    ret
  %1 = mul i128 %a, -63
  ret i128 %1
}

define i64 @mulhsu_i64(i64 %a, i64 %b) nounwind {
;
;
; RV64I-LABEL: mulhsu_i64:
; RV64I:       # %bb.0:
; RV64I-NEXT:    mulhsu a0, a1, a0
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: mulhsu_i64:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    mulhsu a0, a1, a0
; RV64IM-NEXT:    ret
  %1 = zext i64 %a to i128
  %2 = sext i64 %b to i128
  %3 = mul i128 %1, %2
  %4 = lshr i128 %3, 64
  %5 = trunc i128 %4 to i64
  ret i64 %5
}

define i8 @muladd_demand(i8 %x, i8 %y) nounwind {
;
;
; RV64I-LABEL: muladd_demand:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slliw a0, a0, 1
; RV64I-NEXT:    subw a0, a1, a0
; RV64I-NEXT:    andi a0, a0, 15
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muladd_demand:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    slliw a0, a0, 1
; RV64IM-NEXT:    subw a0, a1, a0
; RV64IM-NEXT:    andi a0, a0, 15
; RV64IM-NEXT:    ret
  %m = mul i8 %x, 14
  %a = add i8 %y, %m
  %r = and i8 %a, 15
  ret i8 %r
}

define i8 @mulsub_demand(i8 %x, i8 %y) nounwind {
;
;
; RV64I-LABEL: mulsub_demand:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slliw a0, a0, 1
; RV64I-NEXT:    addw a0, a1, a0
; RV64I-NEXT:    andi a0, a0, 15
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: mulsub_demand:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    slliw a0, a0, 1
; RV64IM-NEXT:    addw a0, a1, a0
; RV64IM-NEXT:    andi a0, a0, 15
; RV64IM-NEXT:    ret
  %m = mul i8 %x, 14
  %a = sub i8 %y, %m
  %r = and i8 %a, 15
  ret i8 %r
}

define i8 @muladd_demand_2(i8 %x, i8 %y) nounwind {
;
;
; RV64I-LABEL: muladd_demand_2:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slliw a0, a0, 1
; RV64I-NEXT:    subw a0, a1, a0
; RV64I-NEXT:    ori a0, a0, -16
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muladd_demand_2:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    slliw a0, a0, 1
; RV64IM-NEXT:    subw a0, a1, a0
; RV64IM-NEXT:    ori a0, a0, -16
; RV64IM-NEXT:    ret
  %m = mul i8 %x, 14
  %a = add i8 %y, %m
  %r = or i8 %a, 240
  ret i8 %r
}

define i8 @mulsub_demand_2(i8 %x, i8 %y) nounwind {
;
;
; RV64I-LABEL: mulsub_demand_2:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slliw a0, a0, 1
; RV64I-NEXT:    addw a0, a1, a0
; RV64I-NEXT:    ori a0, a0, -16
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: mulsub_demand_2:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    slliw a0, a0, 1
; RV64IM-NEXT:    addw a0, a1, a0
; RV64IM-NEXT:    ori a0, a0, -16
; RV64IM-NEXT:    ret
  %m = mul i8 %x, 14
  %a = sub i8 %y, %m
  %r = or i8 %a, 240
  ret i8 %r
}

define i64 @muland_demand(i64 %x) nounwind {
;
;
; RV64I-LABEL: muland_demand:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a0, a0, -8
; RV64I-NEXT:    li a1, 12
; RV64I-NEXT:    mul a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: muland_demand:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    andi a0, a0, -8
; RV64IM-NEXT:    li a1, 12
; RV64IM-NEXT:    mul a0, a0, a1
; RV64IM-NEXT:    ret
  %and = and i64 %x, 4611686018427387896
  %mul = mul i64 %and, 12
  ret i64 %mul
}

define i64 @mulzext_demand(i32 signext %x) nounwind {
;
;
; RV64I-LABEL: mulzext_demand:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a1, 3
; RV64I-NEXT:    slli a1, a1, 32
; RV64I-NEXT:    mul a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: mulzext_demand:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    li a1, 3
; RV64IM-NEXT:    slli a1, a1, 32
; RV64IM-NEXT:    mul a0, a0, a1
; RV64IM-NEXT:    ret
  %ext = zext i32 %x to i64
  %mul = mul i64 %ext, 12884901888
  ret i64 %mul
}

define i32 @mulfshl_demand(i32 signext %x) nounwind {
;
;
; RV64I-LABEL: mulfshl_demand:
; RV64I:       # %bb.0:
; RV64I-NEXT:    srliw a0, a0, 11
; RV64I-NEXT:    lui a1, 92808
; RV64I-NEXT:    mulw a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: mulfshl_demand:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    srliw a0, a0, 11
; RV64IM-NEXT:    lui a1, 92808
; RV64IM-NEXT:    mulw a0, a0, a1
; RV64IM-NEXT:    ret
  %fshl = tail call i32 @llvm.fshl.i32(i32 %x, i32 %x, i32 21)
  %mul = mul i32 %fshl, 380141568
  ret i32 %mul
}

define i32 @mulor_demand(i32 signext %x, i32 signext %y) nounwind {
;
;
; RV64I-LABEL: mulor_demand:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lui a1, 92808
; RV64I-NEXT:    mulw a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: mulor_demand:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    lui a1, 92808
; RV64IM-NEXT:    mulw a0, a0, a1
; RV64IM-NEXT:    ret
  %mul1 = mul i32 %y, 10485760
  %or = or disjoint i32 %mul1, %x
  %mul2 = mul i32 %or, 380141568
  ret i32 %mul2
}

define i64 @mul_add_bitcast(i64 %x) {
;
;
; RV64I-LABEL: mul_add_bitcast:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a0, 0
; RV64I-NEXT:    ret
;
; RV64IM-LABEL: mul_add_bitcast:
; RV64IM:       # %bb.0:
; RV64IM-NEXT:    li a0, 0
; RV64IM-NEXT:    ret
  %add = add i64 %x, 1
  %bitcast = bitcast <2 x i32> zeroinitializer to i64
  %mul = mul i64 %add, %bitcast
  ret i64 %mul
}
