; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=ysx64 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefixes=RV64

define signext i32 @select_i32_trunc(i32 signext %cond, i32 signext %x, i32 signext %y) nounwind {
;
;
;
;
;
; RV64-LABEL: select_i32_trunc:
; RV64:       # %bb.0:
; RV64-NEXT:    andi a3, a0, 1
; RV64-NEXT:    mv a0, a1
; RV64-NEXT:    bnez a3, .LBB0_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:  .LBB0_2:
; RV64-NEXT:    ret
  %cond_trunc = trunc i32 %cond to i1
  %res = select i1 %cond_trunc, i32 %x, i32 %y
  ret i32 %res
}

define signext i32 @select_i32_param(i1 signext %cond, i32 signext %x, i32 signext %y) nounwind {
;
;
;
;
;
; RV64-LABEL: select_i32_param:
; RV64:       # %bb.0:
; RV64-NEXT:    andi a3, a0, 1
; RV64-NEXT:    mv a0, a1
; RV64-NEXT:    bnez a3, .LBB1_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:  .LBB1_2:
; RV64-NEXT:    ret
  %res = select i1 %cond, i32 %x, i32 %y
  ret i32 %res
}

define signext i32 @select_i32_eq(i32 signext %a, i32 signext %b, i32 signext %x, i32 signext %y) nounwind {
;
;
;
;
;
; RV64-LABEL: select_i32_eq:
; RV64:       # %bb.0:
; RV64-NEXT:    beq a0, a1, .LBB2_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a2, a3
; RV64-NEXT:  .LBB2_2:
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:    ret
  %cond = icmp eq i32 %a, %b
  %res = select i1 %cond, i32 %x, i32 %y
  ret i32 %res
}

define signext i32 @select_i32_ne(i32 signext %a, i32 signext %b, i32 signext %x, i32 signext %y) nounwind {
;
;
;
;
;
; RV64-LABEL: select_i32_ne:
; RV64:       # %bb.0:
; RV64-NEXT:    bne a0, a1, .LBB3_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a2, a3
; RV64-NEXT:  .LBB3_2:
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:    ret
  %cond = icmp ne i32 %a, %b
  %res = select i1 %cond, i32 %x, i32 %y
  ret i32 %res
}

define signext i32 @select_i32_ugt(i32 signext %a, i32 signext %b, i32 signext %x, i32 signext %y) nounwind {
;
;
;
;
;
; RV64-LABEL: select_i32_ugt:
; RV64:       # %bb.0:
; RV64-NEXT:    bltu a1, a0, .LBB4_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a2, a3
; RV64-NEXT:  .LBB4_2:
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:    ret
  %cond = icmp ugt i32 %a, %b
  %res = select i1 %cond, i32 %x, i32 %y
  ret i32 %res
}

define signext i32 @select_i32_uge(i32 signext %a, i32 signext %b, i32 signext %x, i32 signext %y) nounwind {
;
;
;
;
;
; RV64-LABEL: select_i32_uge:
; RV64:       # %bb.0:
; RV64-NEXT:    bgeu a0, a1, .LBB5_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a2, a3
; RV64-NEXT:  .LBB5_2:
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:    ret
  %cond = icmp uge i32 %a, %b
  %res = select i1 %cond, i32 %x, i32 %y
  ret i32 %res
}

define signext i32 @select_i32_ult(i32 signext %a, i32 signext %b, i32 signext %x, i32 signext %y) nounwind {
;
;
;
;
;
; RV64-LABEL: select_i32_ult:
; RV64:       # %bb.0:
; RV64-NEXT:    bltu a0, a1, .LBB6_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a2, a3
; RV64-NEXT:  .LBB6_2:
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:    ret
  %cond = icmp ult i32 %a, %b
  %res = select i1 %cond, i32 %x, i32 %y
  ret i32 %res
}

define signext i32 @select_i32_ule(i32 signext %a, i32 signext %b, i32 signext %x, i32 signext %y) nounwind {
;
;
;
;
;
; RV64-LABEL: select_i32_ule:
; RV64:       # %bb.0:
; RV64-NEXT:    bgeu a1, a0, .LBB7_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a2, a3
; RV64-NEXT:  .LBB7_2:
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:    ret
  %cond = icmp ule i32 %a, %b
  %res = select i1 %cond, i32 %x, i32 %y
  ret i32 %res
}

define signext i32 @select_i32_sgt(i32 signext %a, i32 signext %b, i32 signext %x, i32 signext %y) nounwind {
;
;
;
;
;
; RV64-LABEL: select_i32_sgt:
; RV64:       # %bb.0:
; RV64-NEXT:    blt a1, a0, .LBB8_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a2, a3
; RV64-NEXT:  .LBB8_2:
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:    ret
  %cond = icmp sgt i32 %a, %b
  %res = select i1 %cond, i32 %x, i32 %y
  ret i32 %res
}

define signext i32 @select_i32_sge(i32 signext %a, i32 signext %b, i32 signext %x, i32 signext %y) nounwind {
;
;
;
;
;
; RV64-LABEL: select_i32_sge:
; RV64:       # %bb.0:
; RV64-NEXT:    bge a0, a1, .LBB9_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a2, a3
; RV64-NEXT:  .LBB9_2:
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:    ret
  %cond = icmp sge i32 %a, %b
  %res = select i1 %cond, i32 %x, i32 %y
  ret i32 %res
}

define signext i32 @select_i32_slt(i32 signext %a, i32 signext %b, i32 signext %x, i32 signext %y) nounwind {
;
;
;
;
;
; RV64-LABEL: select_i32_slt:
; RV64:       # %bb.0:
; RV64-NEXT:    blt a0, a1, .LBB10_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a2, a3
; RV64-NEXT:  .LBB10_2:
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:    ret
  %cond = icmp slt i32 %a, %b
  %res = select i1 %cond, i32 %x, i32 %y
  ret i32 %res
}

define signext i32 @select_i32_sle(i32 signext %a, i32 signext %b, i32 signext %x, i32 signext %y) nounwind {
;
;
;
;
;
; RV64-LABEL: select_i32_sle:
; RV64:       # %bb.0:
; RV64-NEXT:    bge a1, a0, .LBB11_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a2, a3
; RV64-NEXT:  .LBB11_2:
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:    ret
  %cond = icmp sle i32 %a, %b
  %res = select i1 %cond, i32 %x, i32 %y
  ret i32 %res
}

define i64 @select_i64_trunc(i64 %cond, i64 %x, i64 %y) nounwind {
;
;
;
;
;
; RV64-LABEL: select_i64_trunc:
; RV64:       # %bb.0:
; RV64-NEXT:    andi a3, a0, 1
; RV64-NEXT:    mv a0, a1
; RV64-NEXT:    bnez a3, .LBB12_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:  .LBB12_2:
; RV64-NEXT:    ret
  %cond_trunc = trunc i64 %cond to i1
  %res = select i1 %cond_trunc, i64 %x, i64 %y
  ret i64 %res
}

define i64 @select_i64_param(i1 %cond, i64 %x, i64 %y) nounwind {
;
;
;
;
;
; RV64-LABEL: select_i64_param:
; RV64:       # %bb.0:
; RV64-NEXT:    andi a3, a0, 1
; RV64-NEXT:    mv a0, a1
; RV64-NEXT:    bnez a3, .LBB13_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:  .LBB13_2:
; RV64-NEXT:    ret
  %res = select i1 %cond, i64 %x, i64 %y
  ret i64 %res
}

define i64 @select_i64_eq(i64 %a, i64 %b, i64 %x, i64 %y) nounwind {
;
;
;
;
;
; RV64-LABEL: select_i64_eq:
; RV64:       # %bb.0:
; RV64-NEXT:    beq a0, a1, .LBB14_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a2, a3
; RV64-NEXT:  .LBB14_2:
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:    ret
  %cond = icmp eq i64 %a, %b
  %res = select i1 %cond, i64 %x, i64 %y
  ret i64 %res
}

define i64 @select_i64_ne(i64 %a, i64 %b, i64 %x, i64 %y) nounwind {
;
;
;
;
;
; RV64-LABEL: select_i64_ne:
; RV64:       # %bb.0:
; RV64-NEXT:    bne a0, a1, .LBB15_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a2, a3
; RV64-NEXT:  .LBB15_2:
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:    ret
  %cond = icmp ne i64 %a, %b
  %res = select i1 %cond, i64 %x, i64 %y
  ret i64 %res
}

define i64 @select_i64_ugt(i64 %a, i64 %b, i64 %x, i64 %y) nounwind {
;
;
;
;
;
; RV64-LABEL: select_i64_ugt:
; RV64:       # %bb.0:
; RV64-NEXT:    bltu a1, a0, .LBB16_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a2, a3
; RV64-NEXT:  .LBB16_2:
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:    ret
  %cond = icmp ugt i64 %a, %b
  %res = select i1 %cond, i64 %x, i64 %y
  ret i64 %res
}

define i64 @select_i64_uge(i64 %a, i64 %b, i64 %x, i64 %y) nounwind {
;
;
;
;
;
; RV64-LABEL: select_i64_uge:
; RV64:       # %bb.0:
; RV64-NEXT:    bgeu a0, a1, .LBB17_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a2, a3
; RV64-NEXT:  .LBB17_2:
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:    ret
  %cond = icmp uge i64 %a, %b
  %res = select i1 %cond, i64 %x, i64 %y
  ret i64 %res
}

define i64 @select_i64_ult(i64 %a, i64 %b, i64 %x, i64 %y) nounwind {
;
;
;
;
;
; RV64-LABEL: select_i64_ult:
; RV64:       # %bb.0:
; RV64-NEXT:    bltu a0, a1, .LBB18_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a2, a3
; RV64-NEXT:  .LBB18_2:
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:    ret
  %cond = icmp ult i64 %a, %b
  %res = select i1 %cond, i64 %x, i64 %y
  ret i64 %res
}

define i64 @select_i64_ule(i64 %a, i64 %b, i64 %x, i64 %y) nounwind {
;
;
;
;
;
; RV64-LABEL: select_i64_ule:
; RV64:       # %bb.0:
; RV64-NEXT:    bgeu a1, a0, .LBB19_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a2, a3
; RV64-NEXT:  .LBB19_2:
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:    ret
  %cond = icmp ule i64 %a, %b
  %res = select i1 %cond, i64 %x, i64 %y
  ret i64 %res
}

define i64 @select_i64_sgt(i64 %a, i64 %b, i64 %x, i64 %y) nounwind {
;
;
;
;
;
; RV64-LABEL: select_i64_sgt:
; RV64:       # %bb.0:
; RV64-NEXT:    blt a1, a0, .LBB20_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a2, a3
; RV64-NEXT:  .LBB20_2:
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:    ret
  %cond = icmp sgt i64 %a, %b
  %res = select i1 %cond, i64 %x, i64 %y
  ret i64 %res
}

define i64 @select_i64_sge(i64 %a, i64 %b, i64 %x, i64 %y) nounwind {
;
;
;
;
;
; RV64-LABEL: select_i64_sge:
; RV64:       # %bb.0:
; RV64-NEXT:    bge a0, a1, .LBB21_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a2, a3
; RV64-NEXT:  .LBB21_2:
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:    ret
  %cond = icmp sge i64 %a, %b
  %res = select i1 %cond, i64 %x, i64 %y
  ret i64 %res
}

define i64 @select_i64_slt(i64 %a, i64 %b, i64 %x, i64 %y) nounwind {
;
;
;
;
;
; RV64-LABEL: select_i64_slt:
; RV64:       # %bb.0:
; RV64-NEXT:    blt a0, a1, .LBB22_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a2, a3
; RV64-NEXT:  .LBB22_2:
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:    ret
  %cond = icmp slt i64 %a, %b
  %res = select i1 %cond, i64 %x, i64 %y
  ret i64 %res
}

define i64 @select_i64_sle(i64 %a, i64 %b, i64 %x, i64 %y) nounwind {
;
;
;
;
;
; RV64-LABEL: select_i64_sle:
; RV64:       # %bb.0:
; RV64-NEXT:    bge a1, a0, .LBB23_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a2, a3
; RV64-NEXT:  .LBB23_2:
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:    ret
  %cond = icmp sle i64 %a, %b
  %res = select i1 %cond, i64 %x, i64 %y
  ret i64 %res
}

