; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=ysx64 \
; RUN:   | FileCheck %s --check-prefixes=CHECK

; Compare if negative and select of constants where one constant is zero.
define i32 @neg_sel_constants(i32 signext %a) {
;
; CHECK-LABEL: neg_sel_constants:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srai a0, a0, 63
; CHECK-NEXT:    andi a0, a0, 5
; CHECK-NEXT:    ret
  %tmp.1 = icmp slt i32 %a, 0
  %retval = select i1 %tmp.1, i32 5, i32 0
  ret i32 %retval
}

; Compare if negative and select of constants where one constant is zero and the
; other is a single bit.
define i32 @neg_sel_special_constant(i32 signext %a) {
;
; CHECK-LABEL: neg_sel_special_constant:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srliw a0, a0, 31
; CHECK-NEXT:    slli a0, a0, 9
; CHECK-NEXT:    ret
  %tmp.1 = icmp slt i32 %a, 0
  %retval = select i1 %tmp.1, i32 512, i32 0
  ret i32 %retval
}

; Compare if negative and select variable or zero.
define i32 @neg_sel_variable_and_zero(i32 signext %a, i32 signext %b) {
; CHECK-LABEL: neg_sel_variable_and_zero:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srai a0, a0, 31
; CHECK-NEXT:    and a0, a0, a1
; CHECK-NEXT:    ret
  %tmp.1 = icmp slt i32 %a, 0
  %retval = select i1 %tmp.1, i32 %b, i32 0
  ret i32 %retval
}

; Compare if not positive and select the same variable as being compared:
; smin(a, 0).
define i32 @not_pos_sel_same_variable(i32 signext %a) {
; CHECK-LABEL: not_pos_sel_same_variable:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srai a1, a0, 31
; CHECK-NEXT:    and a0, a1, a0
; CHECK-NEXT:    ret
  %tmp = icmp slt i32 %a, 1
  %min = select i1 %tmp, i32 %a, i32 0
  ret i32 %min
}

; Flipping the comparison condition can be handled by getting the bitwise not of
; the sign mask.
; TODO: We aren't doing a good job of this.

; Compare if positive and select of constants where one constant is zero.
define i32 @pos_sel_constants(i32 signext %a) {
;
; CHECK-LABEL: pos_sel_constants:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srli a0, a0, 63
; CHECK-NEXT:    xori a0, a0, 1
; CHECK-NEXT:    negw a0, a0
; CHECK-NEXT:    andi a0, a0, 5
; CHECK-NEXT:    ret
  %tmp.1 = icmp sgt i32 %a, -1
  %retval = select i1 %tmp.1, i32 5, i32 0
  ret i32 %retval
}

; Compare if positive and select of constants where one constant is zero and the
; other is a single bit.
; The addi is not part of the dependency chain of %a, so this form may be
; faster despite using one more register.
define i32 @pos_sel_special_constant(i32 signext %a) {
;
; CHECK-LABEL: pos_sel_special_constant:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srli a0, a0, 63
; CHECK-NEXT:    xori a0, a0, 1
; CHECK-NEXT:    slli a0, a0, 9
; CHECK-NEXT:    ret
  %tmp.1 = icmp sgt i32 %a, -1
  %retval = select i1 %tmp.1, i32 512, i32 0
  ret i32 %retval
}

; Compare if positive and select variable or zero.
define i32 @pos_sel_variable_and_zero(i32 signext %a, i32 signext %b) {
;
; CHECK-LABEL: pos_sel_variable_and_zero:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srli a0, a0, 63
; CHECK-NEXT:    xori a0, a0, 1
; CHECK-NEXT:    neg a0, a0
; CHECK-NEXT:    and a0, a0, a1
; CHECK-NEXT:    ret
  %tmp.1 = icmp sgt i32 %a, -1
  %retval = select i1 %tmp.1, i32 %b, i32 0
  ret i32 %retval
}

; Compare if not negative or zero and select the same variable as being
; compared: smax(a, 0).
define i32 @not_neg_sel_same_variable(i32 signext %a) {
;
; CHECK-LABEL: not_neg_sel_same_variable:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sgtz a1, a0
; CHECK-NEXT:    neg a1, a1
; CHECK-NEXT:    and a0, a1, a0
; CHECK-NEXT:    ret
  %tmp = icmp sgt i32 %a, 0
  %min = select i1 %tmp, i32 %a, i32 0
  ret i32 %min
}

; ret = (x-y) > 0 ? x-y : 0
define i32 @sub_clamp_zero(i32 signext %x, i32 signext %y) {
;
; CHECK-LABEL: sub_clamp_zero:
; CHECK:       # %bb.0:
; CHECK-NEXT:    subw a0, a0, a1
; CHECK-NEXT:    sgtz a1, a0
; CHECK-NEXT:    neg a1, a1
; CHECK-NEXT:    and a0, a1, a0
; CHECK-NEXT:    ret
  %sub = sub nsw i32 %x, %y
  %cmp = icmp sgt i32 %sub, 0
  %sel = select i1 %cmp, i32 %sub, i32 0
  ret i32 %sel
}

define i8 @sel_shift_bool_i8(i1 %t) {
;
; CHECK-LABEL: sel_shift_bool_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli a0, a0, 63
; CHECK-NEXT:    srai a0, a0, 63
; CHECK-NEXT:    andi a0, a0, -128
; CHECK-NEXT:    ret
  %shl = select i1 %t, i8 128, i8 0
  ret i8 %shl
}

define i16 @sel_shift_bool_i16(i1 %t) {
; CHECK-LABEL: sel_shift_bool_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    andi a0, a0, 1
; CHECK-NEXT:    slli a0, a0, 7
; CHECK-NEXT:    ret
  %shl = select i1 %t, i16 128, i16 0
  ret i16 %shl
}

define i32 @sel_shift_bool_i32(i1 %t) {
; CHECK-LABEL: sel_shift_bool_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    andi a0, a0, 1
; CHECK-NEXT:    slli a0, a0, 6
; CHECK-NEXT:    ret
  %shl = select i1 %t, i32 64, i32 0
  ret i32 %shl
}

define i64 @sel_shift_bool_i64(i1 %t) {
;
; CHECK-LABEL: sel_shift_bool_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    andi a0, a0, 1
; CHECK-NEXT:    slli a0, a0, 16
; CHECK-NEXT:    ret
  %shl = select i1 %t, i64 65536, i64 0
  ret i64 %shl
}

define i64 @sraiw_andi(i32 signext %0, i32 signext %1) nounwind {
;
; CHECK-LABEL: sraiw_andi:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addw a0, a0, a1
; CHECK-NEXT:    srliw a0, a0, 31
; CHECK-NEXT:    xori a0, a0, 1
; CHECK-NEXT:    addiw a0, a0, -1
; CHECK-NEXT:    andi a0, a0, 7
; CHECK-NEXT:    ret
entry:
  %3 = add i32 %0, %1
  %4 = icmp sgt i32 %3, -1
  %5 = select i1 %4, i64 0, i64 7
  ret i64 %5
}
