; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ysx64 -mattr=+m -verify-machineinstrs < %s | FileCheck --check-prefixes=CHECK %s

define i16 @select_xor_1(i16 %A, i8 %cond) {
;
; CHECK-LABEL: select_xor_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a1, a1, 1
; CHECK-NEXT:    beqz a1, .LBB0_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    xori a0, a0, 43
; CHECK-NEXT:  .LBB0_2: # %entry
; CHECK-NEXT:    ret
entry:
 %and = and i8 %cond, 1
 %cmp10 = icmp eq i8 %and, 0
 %0 = xor i16 %A, 43
 %1 = select i1 %cmp10, i16 %A, i16 %0
 ret i16 %1
}

; Equivalent to above, but with icmp ne (and %cond, 1), 1 instead of
; icmp eq (and %cond, 1), 0
define i16 @select_xor_1b(i16 %A, i8 %cond) {
;
; CHECK-LABEL: select_xor_1b:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a1, a1, 1
; CHECK-NEXT:    beqz a1, .LBB1_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    xori a0, a0, 43
; CHECK-NEXT:  .LBB1_2: # %entry
; CHECK-NEXT:    ret
entry:
 %and = and i8 %cond, 1
 %cmp10 = icmp ne i8 %and, 1
 %0 = xor i16 %A, 43
 %1 = select i1 %cmp10, i16 %A, i16 %0
 ret i16 %1
}

define i32 @select_xor_2(i32 %A, i32 %B, i8 %cond) {
;
; CHECK-LABEL: select_xor_2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a2, a2, 1
; CHECK-NEXT:    beqz a2, .LBB2_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    xor a0, a1, a0
; CHECK-NEXT:  .LBB2_2: # %entry
; CHECK-NEXT:    ret
entry:
 %and = and i8 %cond, 1
 %cmp10 = icmp eq i8 %and, 0
 %0 = xor i32 %B, %A
 %1 = select i1 %cmp10, i32 %A, i32 %0
 ret i32 %1
}

; Equivalent to above, but with icmp ne (and %cond, 1), 1 instead of
; icmp eq (and %cond, 1), 0
define i32 @select_xor_2b(i32 %A, i32 %B, i8 %cond) {
;
; CHECK-LABEL: select_xor_2b:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a2, a2, 1
; CHECK-NEXT:    beqz a2, .LBB3_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    xor a0, a1, a0
; CHECK-NEXT:  .LBB3_2: # %entry
; CHECK-NEXT:    ret
entry:
 %and = and i8 %cond, 1
 %cmp10 = icmp ne i8 %and, 1
 %0 = xor i32 %B, %A
 %1 = select i1 %cmp10, i32 %A, i32 %0
 ret i32 %1
}

define i16 @select_xor_3(i16 %A, i8 %cond) {
; CHECK-LABEL: select_xor_3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a1, a1, 1
; CHECK-NEXT:    bnez a1, .LBB4_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    xori a0, a0, 43
; CHECK-NEXT:  .LBB4_2: # %entry
; CHECK-NEXT:    ret
entry:
 %and = and i8 %cond, 1
 %cmp10 = icmp eq i8 %and, 0
 %0 = xor i16 %A, 43
 %1 = select i1 %cmp10, i16 %0, i16 %A
 ret i16 %1
}

; Equivalent to above, but with icmp ne (and %cond, 1), 1 instead of
; icmp eq (and %cond, 1), 0
define i16 @select_xor_3b(i16 %A, i8 %cond) {
; CHECK-LABEL: select_xor_3b:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a1, a1, 1
; CHECK-NEXT:    bnez a1, .LBB5_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    xori a0, a0, 43
; CHECK-NEXT:  .LBB5_2: # %entry
; CHECK-NEXT:    ret
entry:
 %and = and i8 %cond, 1
 %cmp10 = icmp ne i8 %and, 1
 %0 = xor i16 %A, 43
 %1 = select i1 %cmp10, i16 %0, i16 %A
 ret i16 %1
}

define i32 @select_xor_4(i32 %A, i32 %B, i8 %cond) {
;
; CHECK-LABEL: select_xor_4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a2, a2, 1
; CHECK-NEXT:    bnez a2, .LBB6_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    xor a0, a1, a0
; CHECK-NEXT:  .LBB6_2: # %entry
; CHECK-NEXT:    ret
entry:
 %and = and i8 %cond, 1
 %cmp10 = icmp eq i8 %and, 0
 %0 = xor i32 %B, %A
 %1 = select i1 %cmp10, i32 %0, i32 %A
 ret i32 %1
}

; Equivalent to above, but with icmp ne (and %cond, 1), 1 instead of
; icmp eq (and %cond, 1), 0
define i32 @select_xor_4b(i32 %A, i32 %B, i8 %cond) {
;
; CHECK-LABEL: select_xor_4b:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a2, a2, 1
; CHECK-NEXT:    bnez a2, .LBB7_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    xor a0, a1, a0
; CHECK-NEXT:  .LBB7_2: # %entry
; CHECK-NEXT:    ret
entry:
 %and = and i8 %cond, 1
 %cmp10 = icmp ne i8 %and, 1
 %0 = xor i32 %B, %A
 %1 = select i1 %cmp10, i32 %0, i32 %A
 ret i32 %1
}

define i32 @select_xor_5(i1 zeroext %cond, i32 %x) {
;
; CHECK-LABEL: select_xor_5:
; CHECK:       # %bb.0:
; CHECK-NEXT:    bnez a0, .LBB8_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    xori a0, a1, 128
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB8_2:
; CHECK-NEXT:    li a0, 128
; CHECK-NEXT:    ret
  %add = xor i32 %x, 128
  %sel = select i1 %cond, i32 128, i32 %add
  ret i32 %sel
}

define i32 @select_or(i32 %A, i32 %B, i8 %cond) {
;
; CHECK-LABEL: select_or:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a2, a2, 1
; CHECK-NEXT:    beqz a2, .LBB9_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    or a0, a1, a0
; CHECK-NEXT:  .LBB9_2: # %entry
; CHECK-NEXT:    ret
entry:
 %and = and i8 %cond, 1
 %cmp10 = icmp eq i8 %and, 0
 %0 = or i32 %B, %A
 %1 = select i1 %cmp10, i32 %A, i32 %0
 ret i32 %1
}

; Equivalent to above, but with icmp ne (and %cond, 1), 1 instead of
; icmp eq (and %cond, 1), 0
define i32 @select_or_b(i32 %A, i32 %B, i8 %cond) {
;
; CHECK-LABEL: select_or_b:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a2, a2, 1
; CHECK-NEXT:    beqz a2, .LBB10_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    or a0, a1, a0
; CHECK-NEXT:  .LBB10_2: # %entry
; CHECK-NEXT:    ret
entry:
 %and = and i8 %cond, 1
 %cmp10 = icmp ne i8 %and, 1
 %0 = or i32 %B, %A
 %1 = select i1 %cmp10, i32 %A, i32 %0
 ret i32 %1
}

define i32 @select_or_1(i32 %A, i32 %B, i32 %cond) {
;
; CHECK-LABEL: select_or_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a2, a2, 1
; CHECK-NEXT:    beqz a2, .LBB11_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    or a0, a1, a0
; CHECK-NEXT:  .LBB11_2: # %entry
; CHECK-NEXT:    ret
entry:
 %and = and i32 %cond, 1
 %cmp10 = icmp eq i32 %and, 0
 %0 = or i32 %B, %A
 %1 = select i1 %cmp10, i32 %A, i32 %0
 ret i32 %1
}

; Equivalent to above, but with icmp ne (and %cond, 1), 1 instead of
; icmp eq (and %cond, 1), 0
define i32 @select_or_1b(i32 %A, i32 %B, i32 %cond) {
;
; CHECK-LABEL: select_or_1b:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a2, a2, 1
; CHECK-NEXT:    beqz a2, .LBB12_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    or a0, a1, a0
; CHECK-NEXT:  .LBB12_2: # %entry
; CHECK-NEXT:    ret
entry:
 %and = and i32 %cond, 1
 %cmp10 = icmp ne i32 %and, 1
 %0 = or i32 %B, %A
 %1 = select i1 %cmp10, i32 %A, i32 %0
 ret i32 %1
}

define i32 @select_or_2(i32 %A, i32 %B, i8 %cond) {
;
; CHECK-LABEL: select_or_2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a2, a2, 1
; CHECK-NEXT:    bnez a2, .LBB13_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    or a0, a1, a0
; CHECK-NEXT:  .LBB13_2: # %entry
; CHECK-NEXT:    ret
entry:
 %and = and i8 %cond, 1
 %cmp10 = icmp eq i8 %and, 0
 %0 = or i32 %B, %A
 %1 = select i1 %cmp10, i32 %0, i32 %A
 ret i32 %1
}

; Equivalent to above, but with icmp ne (and %cond, 1), 1 instead of
; icmp eq (and %cond, 1), 0
define i32 @select_or_2b(i32 %A, i32 %B, i8 %cond) {
;
; CHECK-LABEL: select_or_2b:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a2, a2, 1
; CHECK-NEXT:    bnez a2, .LBB14_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    or a0, a1, a0
; CHECK-NEXT:  .LBB14_2: # %entry
; CHECK-NEXT:    ret
entry:
 %and = and i8 %cond, 1
 %cmp10 = icmp ne i8 %and, 1
 %0 = or i32 %B, %A
 %1 = select i1 %cmp10, i32 %0, i32 %A
 ret i32 %1
}

define i32 @select_or_3(i32 %A, i32 %B, i32 %cond) {
;
; CHECK-LABEL: select_or_3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a2, a2, 1
; CHECK-NEXT:    bnez a2, .LBB15_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    or a0, a1, a0
; CHECK-NEXT:  .LBB15_2: # %entry
; CHECK-NEXT:    ret
entry:
 %and = and i32 %cond, 1
 %cmp10 = icmp eq i32 %and, 0
 %0 = or i32 %B, %A
 %1 = select i1 %cmp10, i32 %0, i32 %A
 ret i32 %1
}

; Equivalent to above, but with icmp ne (and %cond, 1), 1 instead of
; icmp eq (and %cond, 1), 0
define i32 @select_or_3b(i32 %A, i32 %B, i32 %cond) {
;
; CHECK-LABEL: select_or_3b:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a2, a2, 1
; CHECK-NEXT:    bnez a2, .LBB16_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    or a0, a1, a0
; CHECK-NEXT:  .LBB16_2: # %entry
; CHECK-NEXT:    ret
entry:
 %and = and i32 %cond, 1
 %cmp10 = icmp ne i32 %and, 1
 %0 = or i32 %B, %A
 %1 = select i1 %cmp10, i32 %0, i32 %A
 ret i32 %1
}

define i32 @select_or_4(i1 zeroext %cond, i32 %x) {
;
; CHECK-LABEL: select_or_4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    bnez a0, .LBB17_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    ori a0, a1, 128
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB17_2:
; CHECK-NEXT:    li a0, 128
; CHECK-NEXT:    ret
  %add = or i32 %x, 128
  %sel = select i1 %cond, i32 128, i32 %add
  ret i32 %sel
}

define i32 @select_add_1(i1 zeroext %cond, i32 %a, i32 %b) {
;
; CHECK-LABEL: select_add_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    beqz a0, .LBB18_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    addw a2, a1, a2
; CHECK-NEXT:  .LBB18_2: # %entry
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:    ret
entry:
  %c = add i32 %a, %b
  %res = select i1 %cond, i32 %c, i32 %b
  ret i32 %res
}

define i32 @select_add_2(i1 zeroext %cond, i32 %a, i32 %b) {
;
; CHECK-LABEL: select_add_2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    bnez a0, .LBB19_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    addw a1, a1, a2
; CHECK-NEXT:  .LBB19_2: # %entry
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    ret
entry:
  %c = add i32 %a, %b
  %res = select i1 %cond, i32 %a, i32 %c
  ret i32 %res
}

define i32 @select_add_3(i1 zeroext %cond, i32 %a) {
;
; CHECK-LABEL: select_add_3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    bnez a0, .LBB20_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    addiw a1, a1, 42
; CHECK-NEXT:  .LBB20_2: # %entry
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    ret
entry:
  %c = add i32 %a, 42
  %res = select i1 %cond, i32 %a, i32 %c
  ret i32 %res
}

define i32 @select_add_4(i1 zeroext %cond, i32 %x) {
;
; CHECK-LABEL: select_add_4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    bnez a0, .LBB21_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    addiw a0, a1, 128
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB21_2:
; CHECK-NEXT:    li a0, 128
; CHECK-NEXT:    ret
  %add = add i32 %x, 128
  %sel = select i1 %cond, i32 128, i32 %add
  ret i32 %sel
}

define i64 @select_add_5(i1 zeroext %cond, i64 %x) {
;
; CHECK-LABEL: select_add_5:
; CHECK:       # %bb.0:
; CHECK-NEXT:    bnez a0, .LBB22_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    addi a0, a1, 128
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB22_2:
; CHECK-NEXT:    li a0, 128
; CHECK-NEXT:    ret
  %add = add i64 %x, 128
  %sel = select i1 %cond, i64 128, i64 %add
  ret i64 %sel
}

define i64 @select_add_6(i1 zeroext %cond, i64 %x) {
;
; CHECK-LABEL: select_add_6:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mv a2, a0
; CHECK-NEXT:    lui a0, 14
; CHECK-NEXT:    addi a0, a0, 1005
; CHECK-NEXT:    bnez a2, .LBB23_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    add a0, a1, a0
; CHECK-NEXT:  .LBB23_2:
; CHECK-NEXT:    ret
  %add = add i64 %x, 58349
  %sel = select i1 %cond, i64 58349, i64 %add
  ret i64 %sel
}

define i32 @select_sub_1(i1 zeroext %cond, i32 %a, i32 %b) {
;
; CHECK-LABEL: select_sub_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    beqz a0, .LBB24_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    subw a2, a1, a2
; CHECK-NEXT:  .LBB24_2: # %entry
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:    ret
entry:
  %c = sub i32 %a, %b
  %res = select i1 %cond, i32 %c, i32 %b
  ret i32 %res
}

define i32 @select_sub_2(i1 zeroext %cond, i32 %a, i32 %b) {
;
; CHECK-LABEL: select_sub_2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    bnez a0, .LBB25_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    subw a1, a1, a2
; CHECK-NEXT:  .LBB25_2: # %entry
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    ret
entry:
  %c = sub i32 %a, %b
  %res = select i1 %cond, i32 %a, i32 %c
  ret i32 %res
}

define i32 @select_sub_3(i1 zeroext %cond, i32 %a) {
;
; CHECK-LABEL: select_sub_3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    bnez a0, .LBB26_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    addiw a1, a1, -42
; CHECK-NEXT:  .LBB26_2: # %entry
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    ret
entry:
  %c = sub i32 %a, 42
  %res = select i1 %cond, i32 %a, i32 %c
  ret i32 %res
}

define i32 @select_sub_4(i1 zeroext %cond, i32 %x) {
;
; CHECK-LABEL: select_sub_4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    bnez a0, .LBB27_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    addiw a0, a1, -128
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB27_2:
; CHECK-NEXT:    li a0, 128
; CHECK-NEXT:    ret
  %add = sub i32 %x, 128
  %sel = select i1 %cond, i32 128, i32 %add
  ret i32 %sel
}


define i32 @select_and_1(i1 zeroext %cond, i32 %a, i32 %b) {
;
; CHECK-LABEL: select_and_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    beqz a0, .LBB28_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    and a2, a1, a2
; CHECK-NEXT:  .LBB28_2: # %entry
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:    ret
entry:
  %c = and i32 %a, %b
  %res = select i1 %cond, i32 %c, i32 %b
  ret i32 %res
}

define i32 @select_and_2(i1 zeroext %cond, i32 %a, i32 %b) {
;
; CHECK-LABEL: select_and_2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    bnez a0, .LBB29_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    and a1, a1, a2
; CHECK-NEXT:  .LBB29_2: # %entry
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    ret
entry:
  %c = and i32 %a, %b
  %res = select i1 %cond, i32 %a, i32 %c
  ret i32 %res
}

define i32 @select_and_3(i1 zeroext %cond, i32 %a) {
;
; CHECK-LABEL: select_and_3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    bnez a0, .LBB30_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    andi a1, a1, 42
; CHECK-NEXT:  .LBB30_2: # %entry
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    ret
entry:
  %c = and i32 %a, 42
  %res = select i1 %cond, i32 %a, i32 %c
  ret i32 %res
}

define i32 @select_udiv_1(i1 zeroext %cond, i32 %a, i32 %b) {
;
; CHECK-LABEL: select_udiv_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    beqz a0, .LBB31_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    divuw a2, a1, a2
; CHECK-NEXT:  .LBB31_2: # %entry
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:    ret
entry:
  %c = udiv i32 %a, %b
  %res = select i1 %cond, i32 %c, i32 %b
  ret i32 %res
}

define i32 @select_udiv_2(i1 zeroext %cond, i32 %a, i32 %b) {
;
; CHECK-LABEL: select_udiv_2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    bnez a0, .LBB32_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    divuw a1, a1, a2
; CHECK-NEXT:  .LBB32_2: # %entry
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    ret
entry:
  %c = udiv i32 %a, %b
  %res = select i1 %cond, i32 %a, i32 %c
  ret i32 %res
}

define i32 @select_udiv_3(i1 zeroext %cond, i32 %a) {
;
; CHECK-LABEL: select_udiv_3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    bnez a0, .LBB33_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    srliw a0, a1, 1
; CHECK-NEXT:    lui a1, 199729
; CHECK-NEXT:    addi a1, a1, -975
; CHECK-NEXT:    mul a0, a0, a1
; CHECK-NEXT:    srli a1, a0, 34
; CHECK-NEXT:  .LBB33_2: # %entry
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    ret
entry:
  %c = udiv i32 %a, 42
  %res = select i1 %cond, i32 %a, i32 %c
  ret i32 %res
}

define i32 @select_shl_1(i1 zeroext %cond, i32 %a, i32 %b) {
;
; CHECK-LABEL: select_shl_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    beqz a0, .LBB34_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    sllw a2, a1, a2
; CHECK-NEXT:  .LBB34_2: # %entry
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:    ret
entry:
  %c = shl i32 %a, %b
  %res = select i1 %cond, i32 %c, i32 %b
  ret i32 %res
}

define i32 @select_shl_2(i1 zeroext %cond, i32 %a, i32 %b) {
;
; CHECK-LABEL: select_shl_2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    bnez a0, .LBB35_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    sllw a1, a1, a2
; CHECK-NEXT:  .LBB35_2: # %entry
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    ret
entry:
  %c = shl i32 %a, %b
  %res = select i1 %cond, i32 %a, i32 %c
  ret i32 %res
}

define i32 @select_shl_3(i1 zeroext %cond, i32 %a) {
; CHECK-LABEL: select_shl_3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    ret
entry:
  %c = shl i32 %a, 42
  %res = select i1 %cond, i32 %a, i32 %c
  ret i32 %res
}

define i32 @select_ashr_1(i1 zeroext %cond, i32 %a, i32 %b) {
;
; CHECK-LABEL: select_ashr_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    beqz a0, .LBB37_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    sraw a2, a1, a2
; CHECK-NEXT:  .LBB37_2: # %entry
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:    ret
entry:
  %c = ashr i32 %a, %b
  %res = select i1 %cond, i32 %c, i32 %b
  ret i32 %res
}

define i32 @select_ashr_2(i1 zeroext %cond, i32 %a, i32 %b) {
;
; CHECK-LABEL: select_ashr_2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    bnez a0, .LBB38_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    sraw a1, a1, a2
; CHECK-NEXT:  .LBB38_2: # %entry
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    ret
entry:
  %c = ashr i32 %a, %b
  %res = select i1 %cond, i32 %a, i32 %c
  ret i32 %res
}

define i32 @select_ashr_3(i1 zeroext %cond, i32 %a) {
; CHECK-LABEL: select_ashr_3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    ret
entry:
  %c = ashr i32 %a, 42
  %res = select i1 %cond, i32 %a, i32 %c
  ret i32 %res
}

define i32 @select_lshr_1(i1 zeroext %cond, i32 %a, i32 %b) {
;
; CHECK-LABEL: select_lshr_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    beqz a0, .LBB40_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    srlw a2, a1, a2
; CHECK-NEXT:  .LBB40_2: # %entry
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:    ret
entry:
  %c = lshr i32 %a, %b
  %res = select i1 %cond, i32 %c, i32 %b
  ret i32 %res
}

define i32 @select_lshr_2(i1 zeroext %cond, i32 %a, i32 %b) {
;
; CHECK-LABEL: select_lshr_2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    bnez a0, .LBB41_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    srlw a1, a1, a2
; CHECK-NEXT:  .LBB41_2: # %entry
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    ret
entry:
  %c = lshr i32 %a, %b
  %res = select i1 %cond, i32 %a, i32 %c
  ret i32 %res
}

define i32 @select_lshr_3(i1 zeroext %cond, i32 %a) {
; CHECK-LABEL: select_lshr_3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    ret
entry:
  %c = lshr i32 %a, 42
  %res = select i1 %cond, i32 %a, i32 %c
  ret i32 %res
}

define i32 @select_cst_not1(i32 signext %a, i32 signext %b) {
; CHECK-LABEL: select_cst_not1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slt a0, a0, a1
; CHECK-NEXT:    neg a0, a0
; CHECK-NEXT:    xori a0, a0, -6
; CHECK-NEXT:    ret
  %cond = icmp slt i32 %a, %b
  %ret = select i1 %cond, i32 5, i32 -6
  ret i32 %ret
}

define i32 @select_cst_not2(i32 signext %a) {
; CHECK-LABEL: select_cst_not2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srai a0, a0, 31
; CHECK-NEXT:    xori a0, a0, -6
; CHECK-NEXT:    ret
  %cond = icmp slt i32 %a, 0
  %ret = select i1 %cond, i32 5, i32 -6
  ret i32 %ret
}

define i32 @select_cst_not3(i32 signext %a) {
; CHECK-LABEL: select_cst_not3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srai a0, a0, 31
; CHECK-NEXT:    xori a0, a0, 5
; CHECK-NEXT:    ret
  %cond = icmp sgt i32 %a, -1
  %ret = select i1 %cond, i32 5, i32 -6
  ret i32 %ret
}

define i32 @select_cst_not4(i32 signext %a, i32 signext %b) {
;
; CHECK-LABEL: select_cst_not4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slt a0, a0, a1
; CHECK-NEXT:    lui a1, 524288
; CHECK-NEXT:    neg a0, a0
; CHECK-NEXT:    addiw a1, a1, -1
; CHECK-NEXT:    xor a0, a0, a1
; CHECK-NEXT:    ret
  %cond = icmp slt i32 %a, %b
  %ret = select i1 %cond, i32 -2147483648, i32 2147483647
  ret i32 %ret
}

define i32 @select_cst_not5(i32 signext %a, i32 signext %b) {
; CHECK-LABEL: select_cst_not5:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slt a0, a0, a1
; CHECK-NEXT:    lui a1, 16
; CHECK-NEXT:    neg a0, a0
; CHECK-NEXT:    addi a1, a1, -5
; CHECK-NEXT:    xor a0, a0, a1
; CHECK-NEXT:    ret
  %cond = icmp slt i32 %a, %b
  %ret = select i1 %cond, i32 -65532, i32 65531
  ret i32 %ret
}

define i32 @select_cst_unknown(i32 signext %a, i32 signext %b) {
;
; CHECK-LABEL: select_cst_unknown:
; CHECK:       # %bb.0:
; CHECK-NEXT:    blt a0, a1, .LBB48_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    li a0, -7
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB48_2:
; CHECK-NEXT:    li a0, 5
; CHECK-NEXT:    ret
  %cond = icmp slt i32 %a, %b
  %ret = select i1 %cond, i32 5, i32 -7
  ret i32 %ret
}

define i32 @select_cst1(i1 zeroext %cond) {
;
; CHECK-LABEL: select_cst1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    bnez a0, .LBB49_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    li a0, 20
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB49_2:
; CHECK-NEXT:    li a0, 10
; CHECK-NEXT:    ret
  %ret = select i1 %cond, i32 10, i32 20
  ret i32 %ret
}

define i32 @select_cst2(i1 zeroext %cond) {
;
; CHECK-LABEL: select_cst2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    bnez a0, .LBB50_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    lui a0, 5
; CHECK-NEXT:    addi a0, a0, -480
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB50_2:
; CHECK-NEXT:    li a0, 10
; CHECK-NEXT:    ret
  %ret = select i1 %cond, i32 10, i32 20000
  ret i32 %ret
}

define i32 @select_cst3(i1 zeroext %cond) {
;
; CHECK-LABEL: select_cst3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    bnez a0, .LBB51_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    lui a0, 5
; CHECK-NEXT:    addi a0, a0, -480
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB51_2:
; CHECK-NEXT:    lui a0, 7
; CHECK-NEXT:    addi a0, a0, 1328
; CHECK-NEXT:    ret
  %ret = select i1 %cond, i32 30000, i32 20000
  ret i32 %ret
}

define i32 @select_cst4(i1 zeroext %cond) {
; CHECK-LABEL: select_cst4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    neg a0, a0
; CHECK-NEXT:    xori a0, a0, 2047
; CHECK-NEXT:    ret
  %ret = select i1 %cond, i32 -2048, i32 2047
  ret i32 %ret
}

define i32 @select_cst5(i1 zeroext %cond) {
;
; CHECK-LABEL: select_cst5:
; CHECK:       # %bb.0:
; CHECK-NEXT:    bnez a0, .LBB53_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    lui a0, 1
; CHECK-NEXT:    addi a0, a0, -2047
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB53_2:
; CHECK-NEXT:    li a0, 2047
; CHECK-NEXT:    ret
  %ret = select i1 %cond, i32 2047, i32 2049
  ret i32 %ret
}

define i32 @select_cst5_invert(i1 zeroext %cond) {
;
; CHECK-LABEL: select_cst5_invert:
; CHECK:       # %bb.0:
; CHECK-NEXT:    bnez a0, .LBB54_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    li a0, 2047
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB54_2:
; CHECK-NEXT:    lui a0, 1
; CHECK-NEXT:    addi a0, a0, -2047
; CHECK-NEXT:    ret
  %ret = select i1 %cond, i32 2049, i32 2047
  ret i32 %ret
}

define i32 @select_cst_diff2(i1 zeroext %cond) {
;
; CHECK-LABEL: select_cst_diff2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    bnez a0, .LBB55_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    li a0, 122
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB55_2:
; CHECK-NEXT:    li a0, 120
; CHECK-NEXT:    ret
  %ret = select i1 %cond, i32 120, i32 122
  ret i32 %ret
}

define i32 @select_cst_diff2_invert(i1 zeroext %cond) {
;
; CHECK-LABEL: select_cst_diff2_invert:
; CHECK:       # %bb.0:
; CHECK-NEXT:    bnez a0, .LBB56_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    li a0, 120
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB56_2:
; CHECK-NEXT:    li a0, 122
; CHECK-NEXT:    ret
  %ret = select i1 %cond, i32 122, i32 120
  ret i32 %ret
}

define i32 @select_cst_diff4(i1 zeroext %cond) {
;
; CHECK-LABEL: select_cst_diff4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    bnez a0, .LBB57_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    li a0, 6
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB57_2:
; CHECK-NEXT:    li a0, 10
; CHECK-NEXT:    ret
  %ret = select i1 %cond, i32 10, i32 6
  ret i32 %ret
}

define i32 @select_cst_diff4_invert(i1 zeroext %cond) {
;
; CHECK-LABEL: select_cst_diff4_invert:
; CHECK:       # %bb.0:
; CHECK-NEXT:    bnez a0, .LBB58_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    li a0, 10
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB58_2:
; CHECK-NEXT:    li a0, 6
; CHECK-NEXT:    ret
  %ret = select i1 %cond, i32 6, i32 10
  ret i32 %ret
}

define i32 @select_cst_diff8(i1 zeroext %cond) {
;
; CHECK-LABEL: select_cst_diff8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    bnez a0, .LBB59_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    li a0, 6
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB59_2:
; CHECK-NEXT:    li a0, 14
; CHECK-NEXT:    ret
  %ret = select i1 %cond, i32 14, i32 6
  ret i32 %ret
}

define i32 @select_cst_diff8_invert(i1 zeroext %cond) {
;
; CHECK-LABEL: select_cst_diff8_invert:
; CHECK:       # %bb.0:
; CHECK-NEXT:    bnez a0, .LBB60_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    li a0, 14
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB60_2:
; CHECK-NEXT:    li a0, 6
; CHECK-NEXT:    ret
  %ret = select i1 %cond, i32 6, i32 14
  ret i32 %ret
}


define i32 @select_cst_diff1024(i1 zeroext %cond) {
;
; CHECK-LABEL: select_cst_diff1024:
; CHECK:       # %bb.0:
; CHECK-NEXT:    bnez a0, .LBB61_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    li a0, 6
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB61_2:
; CHECK-NEXT:    li a0, 1030
; CHECK-NEXT:    ret
  %ret = select i1 %cond, i32 1030, i32 6
  ret i32 %ret
}

define i32 @select_cst_diff1024_invert(i1 zeroext %cond) {
;
; CHECK-LABEL: select_cst_diff1024_invert:
; CHECK:       # %bb.0:
; CHECK-NEXT:    bnez a0, .LBB62_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    li a0, 1030
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB62_2:
; CHECK-NEXT:    li a0, 6
; CHECK-NEXT:    ret
  %ret = select i1 %cond, i32 6, i32 1030
  ret i32 %ret
}


@select_redundant_czero_eqz_data = global i32 0, align 4

define void @select_redundant_czero_eqz1(ptr %0, ptr %1) {
;
; CHECK-LABEL: select_redundant_czero_eqz1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    bnez a0, .LBB63_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    lui a0, %hi(select_redundant_czero_eqz_data)
; CHECK-NEXT:    addi a0, a0, %lo(select_redundant_czero_eqz_data)
; CHECK-NEXT:  .LBB63_2: # %entry
; CHECK-NEXT:    sd a0, 0(a1)
; CHECK-NEXT:    ret
entry:
  %3 = icmp eq ptr %0, null
  %4 = select i1 %3, ptr @select_redundant_czero_eqz_data, ptr %0
  store ptr %4, ptr %1, align 8
  ret void
}

define void @select_redundant_czero_eqz2(ptr %0, ptr %1) {
;
; CHECK-LABEL: select_redundant_czero_eqz2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    bnez a0, .LBB64_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    lui a0, %hi(select_redundant_czero_eqz_data)
; CHECK-NEXT:    addi a0, a0, %lo(select_redundant_czero_eqz_data)
; CHECK-NEXT:  .LBB64_2: # %entry
; CHECK-NEXT:    sd a0, 0(a1)
; CHECK-NEXT:    ret
entry:
  %3 = icmp ne ptr %0, null
  %4 = select i1 %3, ptr %0, ptr @select_redundant_czero_eqz_data
  store ptr %4, ptr %1, align 8
  ret void
}
