; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ysx64 -target-abi=lp64 -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefixes=RV64 %s

;; This tests how good we are at materialising constants using `select`. The aim
;; is that we do so without a branch if possible (at the moment our lowering of
;; select always introduces a branch).
;;
;; Currently the hook `convertSelectOfConstantsToMath` only is useful when the
;; constants are either 1 away from each other, or one is a power of two and
;; the other is zero.

define signext i32 @select_const_int_easy(i1 zeroext %a) nounwind {
;
;
; RV64-LABEL: select_const_int_easy:
; RV64:       # %bb.0:
; RV64-NEXT:    ret
  %1 = select i1 %a, i32 1, i32 0
  ret i32 %1
}

define signext i32 @select_const_int_one_away(i1 zeroext %a) nounwind {
;
;
; RV64-LABEL: select_const_int_one_away:
; RV64:       # %bb.0:
; RV64-NEXT:    li a1, 4
; RV64-NEXT:    sub a0, a1, a0
; RV64-NEXT:    ret
  %1 = select i1 %a, i32 3, i32 4
  ret i32 %1
}

define signext i32 @select_const_int_pow2_zero(i1 zeroext %a) nounwind {
;
;
; RV64-LABEL: select_const_int_pow2_zero:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a0, a0, 2
; RV64-NEXT:    ret
  %1 = select i1 %a, i32 4, i32 0
  ret i32 %1
}

define signext i32 @select_const_int_harder(i1 zeroext %a) nounwind {
;
;
;
;
; RV64-LABEL: select_const_int_harder:
; RV64:       # %bb.0:
; RV64-NEXT:    bnez a0, .LBB3_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    li a0, 38
; RV64-NEXT:    ret
; RV64-NEXT:  .LBB3_2:
; RV64-NEXT:    li a0, 6
; RV64-NEXT:    ret
  %1 = select i1 %a, i32 6, i32 38
  ret i32 %1
}

define float @select_const_fp(i1 zeroext %a) nounwind {
;
;
;
;
; RV64-LABEL: select_const_fp:
; RV64:       # %bb.0:
; RV64-NEXT:    mv a1, a0
; RV64-NEXT:    lui a0, 263168
; RV64-NEXT:    bnez a1, .LBB4_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    lui a0, 264192
; RV64-NEXT:  .LBB4_2:
; RV64-NEXT:    ret
  %1 = select i1 %a, float 3.0, float 4.0
  ret float %1
}

define signext i32 @select_eq_zero_negone(i32 signext %a, i32 signext %b) nounwind {
;
;
; RV64-LABEL: select_eq_zero_negone:
; RV64:       # %bb.0:
; RV64-NEXT:    xor a0, a0, a1
; RV64-NEXT:    seqz a0, a0
; RV64-NEXT:    neg a0, a0
; RV64-NEXT:    ret
  %1 = icmp eq i32 %a, %b
  %2 = select i1 %1, i32 -1, i32 0
  ret i32 %2
}

define signext i32 @select_ne_zero_negone(i32 signext %a, i32 signext %b) nounwind {
;
;
; RV64-LABEL: select_ne_zero_negone:
; RV64:       # %bb.0:
; RV64-NEXT:    xor a0, a0, a1
; RV64-NEXT:    snez a0, a0
; RV64-NEXT:    neg a0, a0
; RV64-NEXT:    ret
  %1 = icmp ne i32 %a, %b
  %2 = select i1 %1, i32 -1, i32 0
  ret i32 %2
}

define signext i32 @select_sgt_zero_negone(i32 signext %a, i32 signext %b) nounwind {
;
;
; RV64-LABEL: select_sgt_zero_negone:
; RV64:       # %bb.0:
; RV64-NEXT:    slt a0, a1, a0
; RV64-NEXT:    neg a0, a0
; RV64-NEXT:    ret
  %1 = icmp sgt i32 %a, %b
  %2 = select i1 %1, i32 -1, i32 0
  ret i32 %2
}

define signext i32 @select_slt_zero_negone(i32 signext %a, i32 signext %b) nounwind {
;
;
; RV64-LABEL: select_slt_zero_negone:
; RV64:       # %bb.0:
; RV64-NEXT:    slt a0, a0, a1
; RV64-NEXT:    neg a0, a0
; RV64-NEXT:    ret
  %1 = icmp slt i32 %a, %b
  %2 = select i1 %1, i32 -1, i32 0
  ret i32 %2
}

define signext i32 @select_sge_zero_negone(i32 signext %a, i32 signext %b) nounwind {
;
;
; RV64-LABEL: select_sge_zero_negone:
; RV64:       # %bb.0:
; RV64-NEXT:    slt a0, a0, a1
; RV64-NEXT:    xori a0, a0, 1
; RV64-NEXT:    neg a0, a0
; RV64-NEXT:    ret
  %1 = icmp sge i32 %a, %b
  %2 = select i1 %1, i32 -1, i32 0
  ret i32 %2
}

define signext i32 @select_sle_zero_negone(i32 signext %a, i32 signext %b) nounwind {
;
;
; RV64-LABEL: select_sle_zero_negone:
; RV64:       # %bb.0:
; RV64-NEXT:    slt a0, a1, a0
; RV64-NEXT:    xori a0, a0, 1
; RV64-NEXT:    neg a0, a0
; RV64-NEXT:    ret
  %1 = icmp sle i32 %a, %b
  %2 = select i1 %1, i32 -1, i32 0
  ret i32 %2
}

define signext i32 @select_ugt_zero_negone(i32 signext %a, i32 signext %b) nounwind {
;
;
; RV64-LABEL: select_ugt_zero_negone:
; RV64:       # %bb.0:
; RV64-NEXT:    sltu a0, a1, a0
; RV64-NEXT:    neg a0, a0
; RV64-NEXT:    ret
  %1 = icmp ugt i32 %a, %b
  %2 = select i1 %1, i32 -1, i32 0
  ret i32 %2
}

define signext i32 @select_ult_zero_negone(i32 signext %a, i32 signext %b) nounwind {
;
;
; RV64-LABEL: select_ult_zero_negone:
; RV64:       # %bb.0:
; RV64-NEXT:    sltu a0, a0, a1
; RV64-NEXT:    neg a0, a0
; RV64-NEXT:    ret
  %1 = icmp ult i32 %a, %b
  %2 = select i1 %1, i32 -1, i32 0
  ret i32 %2
}

define signext i32 @select_uge_zero_negone(i32 signext %a, i32 signext %b) nounwind {
;
;
; RV64-LABEL: select_uge_zero_negone:
; RV64:       # %bb.0:
; RV64-NEXT:    sltu a0, a0, a1
; RV64-NEXT:    xori a0, a0, 1
; RV64-NEXT:    neg a0, a0
; RV64-NEXT:    ret
  %1 = icmp uge i32 %a, %b
  %2 = select i1 %1, i32 -1, i32 0
  ret i32 %2
}

define signext i32 @select_ule_zero_negone(i32 signext %a, i32 signext %b) nounwind {
;
;
; RV64-LABEL: select_ule_zero_negone:
; RV64:       # %bb.0:
; RV64-NEXT:    sltu a0, a1, a0
; RV64-NEXT:    xori a0, a0, 1
; RV64-NEXT:    neg a0, a0
; RV64-NEXT:    ret
  %1 = icmp ule i32 %a, %b
  %2 = select i1 %1, i32 -1, i32 0
  ret i32 %2
}

define i32 @select_eq_1_2(i32 signext %a, i32 signext %b) {
;
;
; RV64-LABEL: select_eq_1_2:
; RV64:       # %bb.0:
; RV64-NEXT:    xor a0, a0, a1
; RV64-NEXT:    seqz a0, a0
; RV64-NEXT:    li a1, 2
; RV64-NEXT:    sub a0, a1, a0
; RV64-NEXT:    ret
  %1 = icmp eq i32 %a, %b
  %2 = select i1 %1, i32 1, i32 2
  ret i32 %2
}

define i32 @select_ne_1_2(i32 signext %a, i32 signext %b) {
;
;
; RV64-LABEL: select_ne_1_2:
; RV64:       # %bb.0:
; RV64-NEXT:    xor a0, a0, a1
; RV64-NEXT:    snez a0, a0
; RV64-NEXT:    li a1, 2
; RV64-NEXT:    sub a0, a1, a0
; RV64-NEXT:    ret
  %1 = icmp ne i32 %a, %b
  %2 = select i1 %1, i32 1, i32 2
  ret i32 %2
}

define i32 @select_eq_10000_10001(i32 signext %a, i32 signext %b) {
;
;
; RV64-LABEL: select_eq_10000_10001:
; RV64:       # %bb.0:
; RV64-NEXT:    xor a0, a0, a1
; RV64-NEXT:    lui a1, 2
; RV64-NEXT:    seqz a0, a0
; RV64-NEXT:    addi a1, a1, 1810
; RV64-NEXT:    sub a0, a1, a0
; RV64-NEXT:    ret
  %1 = icmp eq i32 %a, %b
  %2 = select i1 %1, i32 10001, i32 10002
  ret i32 %2
}

define i32 @select_ne_10001_10002(i32 signext %a, i32 signext %b) {
;
;
; RV64-LABEL: select_ne_10001_10002:
; RV64:       # %bb.0:
; RV64-NEXT:    xor a0, a0, a1
; RV64-NEXT:    lui a1, 2
; RV64-NEXT:    snez a0, a0
; RV64-NEXT:    addi a1, a1, 1810
; RV64-NEXT:    sub a0, a1, a0
; RV64-NEXT:    ret
  %1 = icmp ne i32 %a, %b
  %2 = select i1 %1, i32 10001, i32 10002
  ret i32 %2
}

define i32 @select_slt_zero_constant1_constant2(i32 signext %x) {
;
;
; RV64-LABEL: select_slt_zero_constant1_constant2:
; RV64:       # %bb.0:
; RV64-NEXT:    bltz a0, .LBB19_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    li a0, -3
; RV64-NEXT:    ret
; RV64-NEXT:  .LBB19_2:
; RV64-NEXT:    li a0, 7
; RV64-NEXT:    ret
  %cmp = icmp slt i32 %x, 0
  %cond = select i1 %cmp, i32 7, i32 -3
  ret i32 %cond
}

define i32 @select_sgt_negative_one_constant1_constant2(i32 signext %x) {
;
;
; RV64-LABEL: select_sgt_negative_one_constant1_constant2:
; RV64:       # %bb.0:
; RV64-NEXT:    bgez a0, .LBB20_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    li a0, -3
; RV64-NEXT:    ret
; RV64-NEXT:  .LBB20_2:
; RV64-NEXT:    li a0, 7
; RV64-NEXT:    ret
  %cmp = icmp sgt i32 %x, -1
  %cond = select i1 %cmp, i32 7, i32 -3
  ret i32 %cond
}

define i32 @select_nonnegative_lui_addi(i32 signext %x) {
;
;
;
;
; RV64-LABEL: select_nonnegative_lui_addi:
; RV64:       # %bb.0:
; RV64-NEXT:    mv a1, a0
; RV64-NEXT:    lui a0, 4
; RV64-NEXT:    bgez a1, .LBB21_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    li a0, 25
; RV64-NEXT:  .LBB21_2:
; RV64-NEXT:    ret
  %cmp = icmp sgt i32 %x, -1
  %cond = select i1 %cmp, i32 16384, i32 25
  ret i32 %cond
}

define i32 @select_nonnegative_lui_addi_swapped(i32 signext %x) {
;
;
;
;
; RV64-LABEL: select_nonnegative_lui_addi_swapped:
; RV64:       # %bb.0:
; RV64-NEXT:    bgez a0, .LBB22_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    lui a0, 4
; RV64-NEXT:    ret
; RV64-NEXT:  .LBB22_2:
; RV64-NEXT:    li a0, 25
; RV64-NEXT:    ret
  %cmp = icmp sgt i32 %x, -1
  %cond = select i1 %cmp, i32 25, i32 16384
  ret i32 %cond
}



define i32 @diff_shl_addi(i32 signext %x) {
;
;
;
;
; RV64-LABEL: diff_shl_addi:
; RV64:       # %bb.0:
; RV64-NEXT:    bgez a0, .LBB23_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    lui a0, 4
; RV64-NEXT:    addi a0, a0, 25
; RV64-NEXT:    ret
; RV64-NEXT:  .LBB23_2:
; RV64-NEXT:    li a0, 25
; RV64-NEXT:    ret
  %cmp = icmp sgt i32 %x, -1
  %cond = select i1 %cmp, i32 25, i32 16409
  ret i32 %cond
}

define i32 @diff_shl_addi2(i32 signext %x) {
;
;
;
;
; RV64-LABEL: diff_shl_addi2:
; RV64:       # %bb.0:
; RV64-NEXT:    bgez a0, .LBB24_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    li a0, 25
; RV64-NEXT:    ret
; RV64-NEXT:  .LBB24_2:
; RV64-NEXT:    lui a0, 4
; RV64-NEXT:    addi a0, a0, 25
; RV64-NEXT:    ret
  %cmp = icmp sgt i32 %x, -1
  %cond = select i1 %cmp, i32 16409, i32 25
  ret i32 %cond
}

define i32 @diff_pow2_24_16(i32 signext %x) {
;
;
; RV64-LABEL: diff_pow2_24_16:
; RV64:       # %bb.0:
; RV64-NEXT:    bgez a0, .LBB25_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    li a0, 16
; RV64-NEXT:    ret
; RV64-NEXT:  .LBB25_2:
; RV64-NEXT:    li a0, 24
; RV64-NEXT:    ret
  %cmp = icmp sgt i32 %x, -1
  %cond = select i1 %cmp, i32 24, i32 16
  ret i32 %cond
}

define i32 @diff_pow2_16_24(i32 signext %x) {
;
;
; RV64-LABEL: diff_pow2_16_24:
; RV64:       # %bb.0:
; RV64-NEXT:    bgez a0, .LBB26_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    li a0, 24
; RV64-NEXT:    ret
; RV64-NEXT:  .LBB26_2:
; RV64-NEXT:    li a0, 16
; RV64-NEXT:    ret
  %cmp = icmp sgt i32 %x, -1
  %cond = select i1 %cmp, i32 16, i32 24
  ret i32 %cond
}

define i32 @zext_or_constant(i32 signext %x) {
;
;
;
;
; RV64-LABEL: zext_or_constant:
; RV64:       # %bb.0:
; RV64-NEXT:    bgez a0, .LBB27_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    lui a0, 140
; RV64-NEXT:    addi a0, a0, 417
; RV64-NEXT:    ret
; RV64-NEXT:  .LBB27_2:
; RV64-NEXT:    srli a0, a0, 63
; RV64-NEXT:    xori a0, a0, 1
; RV64-NEXT:    ret
  %cmp = icmp sgt i32 %x, -1
  %ext = zext i1 %cmp to i32
  %cond = select i1 %cmp, i32 %ext, i32 573857
  ret i32 %cond
}

define i32 @zext_or_constant2(i32 signext %x) {
;
;
;
;
; RV64-LABEL: zext_or_constant2:
; RV64:       # %bb.0:
; RV64-NEXT:    bgez a0, .LBB28_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    srli a0, a0, 63
; RV64-NEXT:    xori a0, a0, 1
; RV64-NEXT:    ret
; RV64-NEXT:  .LBB28_2:
; RV64-NEXT:    lui a0, 140
; RV64-NEXT:    addi a0, a0, 417
; RV64-NEXT:    ret
  %cmp = icmp sgt i32 %x, -1
  %ext = zext i1 %cmp to i32
  %cond = select i1 %cmp, i32 573857, i32 %ext
  ret i32 %cond
}

define i32 @sext_or_constant(i32 signext %x) {
;
;
;
;
; RV64-LABEL: sext_or_constant:
; RV64:       # %bb.0:
; RV64-NEXT:    bgez a0, .LBB29_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    lui a0, 140
; RV64-NEXT:    addi a0, a0, 417
; RV64-NEXT:    ret
; RV64-NEXT:  .LBB29_2:
; RV64-NEXT:    srli a0, a0, 63
; RV64-NEXT:    xori a0, a0, 1
; RV64-NEXT:    neg a0, a0
; RV64-NEXT:    ret
  %cmp = icmp sgt i32 %x, -1
  %ext = sext i1 %cmp to i32
  %cond = select i1 %cmp, i32 %ext, i32 573857
  ret i32 %cond
}

define i32 @sext_or_constant2(i32 signext %x) {
;
;
;
;
; RV64-LABEL: sext_or_constant2:
; RV64:       # %bb.0:
; RV64-NEXT:    bgez a0, .LBB30_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    srli a0, a0, 63
; RV64-NEXT:    xori a0, a0, 1
; RV64-NEXT:    neg a0, a0
; RV64-NEXT:    ret
; RV64-NEXT:  .LBB30_2:
; RV64-NEXT:    lui a0, 140
; RV64-NEXT:    addi a0, a0, 417
; RV64-NEXT:    ret
  %cmp = icmp sgt i32 %x, -1
  %ext = sext i1 %cmp to i32
  %cond = select i1 %cmp, i32 573857, i32 %ext
  ret i32 %cond
}


define i32 @select_0_6(i32 signext %x) {
;
;
; RV64-LABEL: select_0_6:
; RV64:       # %bb.0:
; RV64-NEXT:    srli a0, a0, 63
; RV64-NEXT:    xori a0, a0, 1
; RV64-NEXT:    addiw a0, a0, -1
; RV64-NEXT:    andi a0, a0, 6
; RV64-NEXT:    ret
  %cmp = icmp sgt i32 %x, -1
  %cond = select i1 %cmp, i32 0, i32 6
  ret i32 %cond
}

define i32 @select_6_0(i32 signext %x) {
;
;
; RV64-LABEL: select_6_0:
; RV64:       # %bb.0:
; RV64-NEXT:    srli a0, a0, 63
; RV64-NEXT:    xori a0, a0, 1
; RV64-NEXT:    negw a0, a0
; RV64-NEXT:    andi a0, a0, 6
; RV64-NEXT:    ret
  %cmp = icmp sgt i32 %x, -1
  %cond = select i1 %cmp, i32 6, i32 0
  ret i32 %cond
}

define i32 @select_0_394(i32 signext %x) {
;
;
; RV64-LABEL: select_0_394:
; RV64:       # %bb.0:
; RV64-NEXT:    srli a0, a0, 63
; RV64-NEXT:    xori a0, a0, 1
; RV64-NEXT:    addiw a0, a0, -1
; RV64-NEXT:    andi a0, a0, 394
; RV64-NEXT:    ret
  %cmp = icmp sgt i32 %x, -1
  %cond = select i1 %cmp, i32 0, i32 394
  ret i32 %cond
}

define i32 @select_394_0(i32 signext %x) {
;
;
; RV64-LABEL: select_394_0:
; RV64:       # %bb.0:
; RV64-NEXT:    srli a0, a0, 63
; RV64-NEXT:    xori a0, a0, 1
; RV64-NEXT:    negw a0, a0
; RV64-NEXT:    andi a0, a0, 394
; RV64-NEXT:    ret
  %cmp = icmp sgt i32 %x, -1
  %cond = select i1 %cmp, i32 394, i32 0
  ret i32 %cond
}
