; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -mtriple=ysx64 -mattr=+m < %s \
; RUN:   | FileCheck %s -check-prefixes=RV64I

define i8 @shl_cttz_i8(i8 %x, i8 %y) {
;
;
; RV64I-LABEL: shl_cttz_i8:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    addiw a2, a1, -1
; RV64I-NEXT:    not a1, a1
; RV64I-NEXT:    and a1, a1, a2
; RV64I-NEXT:    srli a2, a1, 1
; RV64I-NEXT:    andi a2, a2, 85
; RV64I-NEXT:    subw a1, a1, a2
; RV64I-NEXT:    andi a2, a1, 51
; RV64I-NEXT:    srli a1, a1, 2
; RV64I-NEXT:    andi a1, a1, 51
; RV64I-NEXT:    add a1, a2, a1
; RV64I-NEXT:    srli a2, a1, 4
; RV64I-NEXT:    addw a1, a1, a2
; RV64I-NEXT:    andi a1, a1, 15
; RV64I-NEXT:    sll a0, a0, a1
; RV64I-NEXT:    ret
entry:
  %cttz = call i8 @llvm.cttz.i8(i8 %y, i1 true)
  %res = shl i8 %x, %cttz
  ret i8 %res
}

define i8 @shl_cttz_constant_i8(i8 %y) {
;
;
; RV64I-LABEL: shl_cttz_constant_i8:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    addiw a1, a0, -1
; RV64I-NEXT:    not a0, a0
; RV64I-NEXT:    and a0, a0, a1
; RV64I-NEXT:    srli a1, a0, 1
; RV64I-NEXT:    andi a1, a1, 85
; RV64I-NEXT:    subw a0, a0, a1
; RV64I-NEXT:    andi a1, a0, 51
; RV64I-NEXT:    srli a0, a0, 2
; RV64I-NEXT:    andi a0, a0, 51
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    srli a1, a0, 4
; RV64I-NEXT:    addw a0, a0, a1
; RV64I-NEXT:    andi a0, a0, 15
; RV64I-NEXT:    li a1, 4
; RV64I-NEXT:    sll a0, a1, a0
; RV64I-NEXT:    ret
entry:
  %cttz = call i8 @llvm.cttz.i8(i8 %y, i1 true)
  %res = shl i8 4, %cttz
  ret i8 %res
}

define i16 @shl_cttz_i16(i16 %x, i16 %y) {
;
;
; RV64I-LABEL: shl_cttz_i16:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    addi a2, a1, -1
; RV64I-NEXT:    not a1, a1
; RV64I-NEXT:    lui a3, 5
; RV64I-NEXT:    and a1, a1, a2
; RV64I-NEXT:    addi a2, a3, 1365
; RV64I-NEXT:    srli a3, a1, 1
; RV64I-NEXT:    and a2, a3, a2
; RV64I-NEXT:    lui a3, 3
; RV64I-NEXT:    addi a3, a3, 819
; RV64I-NEXT:    sub a1, a1, a2
; RV64I-NEXT:    and a2, a1, a3
; RV64I-NEXT:    srli a1, a1, 2
; RV64I-NEXT:    and a1, a1, a3
; RV64I-NEXT:    add a1, a2, a1
; RV64I-NEXT:    srli a2, a1, 4
; RV64I-NEXT:    addw a1, a1, a2
; RV64I-NEXT:    andi a2, a1, 15
; RV64I-NEXT:    slli a1, a1, 52
; RV64I-NEXT:    srli a1, a1, 60
; RV64I-NEXT:    addw a1, a2, a1
; RV64I-NEXT:    sll a0, a0, a1
; RV64I-NEXT:    ret
entry:
  %cttz = call i16 @llvm.cttz.i16(i16 %y, i1 true)
  %res = shl i16 %x, %cttz
  ret i16 %res
}

define i16 @shl_cttz_constant_i16(i16 %y) {
;
;
; RV64I-LABEL: shl_cttz_constant_i16:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    addi a1, a0, -1
; RV64I-NEXT:    not a0, a0
; RV64I-NEXT:    lui a2, 5
; RV64I-NEXT:    and a0, a0, a1
; RV64I-NEXT:    addi a1, a2, 1365
; RV64I-NEXT:    srli a2, a0, 1
; RV64I-NEXT:    and a1, a2, a1
; RV64I-NEXT:    lui a2, 3
; RV64I-NEXT:    addi a2, a2, 819
; RV64I-NEXT:    sub a0, a0, a1
; RV64I-NEXT:    and a1, a0, a2
; RV64I-NEXT:    srli a0, a0, 2
; RV64I-NEXT:    and a0, a0, a2
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    srli a1, a0, 4
; RV64I-NEXT:    addw a0, a0, a1
; RV64I-NEXT:    andi a1, a0, 15
; RV64I-NEXT:    slli a0, a0, 52
; RV64I-NEXT:    srli a0, a0, 60
; RV64I-NEXT:    addw a0, a1, a0
; RV64I-NEXT:    li a1, 4
; RV64I-NEXT:    sll a0, a1, a0
; RV64I-NEXT:    ret
entry:
  %cttz = call i16 @llvm.cttz.i16(i16 %y, i1 true)
  %res = shl i16 4, %cttz
  ret i16 %res
}

define i32 @shl_cttz_i32(i32 %x, i32 %y) {
;
;
; RV64I-LABEL: shl_cttz_i32:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    negw a2, a1
; RV64I-NEXT:    and a1, a1, a2
; RV64I-NEXT:    lui a2, 30667
; RV64I-NEXT:    addi a2, a2, 1329
; RV64I-NEXT:    mulw a1, a1, a2
; RV64I-NEXT:    srliw a1, a1, 27
; RV64I-NEXT:    lui a2, %hi(.LCPI4_0)
; RV64I-NEXT:    addi a2, a2, %lo(.LCPI4_0)
; RV64I-NEXT:    add a1, a2, a1
; RV64I-NEXT:    lbu a1, 0(a1)
; RV64I-NEXT:    sllw a0, a0, a1
; RV64I-NEXT:    ret
entry:
  %cttz = call i32 @llvm.cttz.i32(i32 %y, i1 true)
  %res = shl i32 %x, %cttz
  ret i32 %res
}

define i32 @shl_cttz_i32_zero_is_defined(i32 %x, i32 %y) {
;
;
; RV64I-LABEL: shl_cttz_i32_zero_is_defined:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    sext.w a2, a1
; RV64I-NEXT:    beqz a2, .LBB5_2
; RV64I-NEXT:  # %bb.1: # %cond.false
; RV64I-NEXT:    negw a2, a1
; RV64I-NEXT:    and a1, a1, a2
; RV64I-NEXT:    lui a2, 30667
; RV64I-NEXT:    addi a2, a2, 1329
; RV64I-NEXT:    mulw a1, a1, a2
; RV64I-NEXT:    srliw a1, a1, 27
; RV64I-NEXT:    lui a2, %hi(.LCPI5_0)
; RV64I-NEXT:    addi a2, a2, %lo(.LCPI5_0)
; RV64I-NEXT:    add a1, a2, a1
; RV64I-NEXT:    lbu a1, 0(a1)
; RV64I-NEXT:    sllw a0, a0, a1
; RV64I-NEXT:    ret
; RV64I-NEXT:  .LBB5_2:
; RV64I-NEXT:    li a1, 32
; RV64I-NEXT:    sllw a0, a0, a1
; RV64I-NEXT:    ret
entry:
  %cttz = call i32 @llvm.cttz.i32(i32 %y, i1 false)
  %res = shl i32 %x, %cttz
  ret i32 %res
}

define i32 @shl_cttz_constant_i32(i32 %y) {
;
;
; RV64I-LABEL: shl_cttz_constant_i32:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    negw a1, a0
; RV64I-NEXT:    and a0, a0, a1
; RV64I-NEXT:    lui a1, 30667
; RV64I-NEXT:    addi a1, a1, 1329
; RV64I-NEXT:    mulw a0, a0, a1
; RV64I-NEXT:    srliw a0, a0, 27
; RV64I-NEXT:    lui a1, %hi(.LCPI6_0)
; RV64I-NEXT:    addi a1, a1, %lo(.LCPI6_0)
; RV64I-NEXT:    add a0, a1, a0
; RV64I-NEXT:    lbu a0, 0(a0)
; RV64I-NEXT:    li a1, 4
; RV64I-NEXT:    sllw a0, a1, a0
; RV64I-NEXT:    ret
entry:
  %cttz = call i32 @llvm.cttz.i32(i32 %y, i1 true)
  %res = shl i32 4, %cttz
  ret i32 %res
}

define i32 @shl_cttz_multiuse_i32(i32 %x, i32 %y) {
;
;
; RV64I-LABEL: shl_cttz_multiuse_i32:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    addi sp, sp, -32
; RV64I-NEXT:    .cfi_def_cfa_offset 32
; RV64I-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s1, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    .cfi_offset ra, -8
; RV64I-NEXT:    .cfi_offset s0, -16
; RV64I-NEXT:    .cfi_offset s1, -24
; RV64I-NEXT:    negw a2, a1
; RV64I-NEXT:    and a1, a1, a2
; RV64I-NEXT:    lui a2, 30667
; RV64I-NEXT:    addi a2, a2, 1329
; RV64I-NEXT:    mulw a1, a1, a2
; RV64I-NEXT:    srliw a1, a1, 27
; RV64I-NEXT:    lui a2, %hi(.LCPI7_0)
; RV64I-NEXT:    addi a2, a2, %lo(.LCPI7_0)
; RV64I-NEXT:    add a1, a2, a1
; RV64I-NEXT:    lbu s0, 0(a1)
; RV64I-NEXT:    mv s1, a0
; RV64I-NEXT:    mv a0, s0
; RV64I-NEXT:    call use32
; RV64I-NEXT:    sllw a0, s1, s0
; RV64I-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s1, 8(sp) # 8-byte Folded Reload
; RV64I-NEXT:    .cfi_restore ra
; RV64I-NEXT:    .cfi_restore s0
; RV64I-NEXT:    .cfi_restore s1
; RV64I-NEXT:    addi sp, sp, 32
; RV64I-NEXT:    .cfi_def_cfa_offset 0
; RV64I-NEXT:    ret
entry:
  %cttz = call i32 @llvm.cttz.i32(i32 %y, i1 true)
  call void @use32(i32 %cttz)
  %res = shl i32 %x, %cttz
  ret i32 %res
}

define i64 @shl_cttz_i64(i64 %x, i64 %y) {
;
;
; RV64I-LABEL: shl_cttz_i64:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    neg a2, a1
; RV64I-NEXT:    and a1, a1, a2
; RV64I-NEXT:    mul a0, a1, a0
; RV64I-NEXT:    ret
entry:
  %cttz = call i64 @llvm.cttz.i64(i64 %y, i1 true)
  %res = shl i64 %x, %cttz
  ret i64 %res
}

define i64 @shl_cttz_constant_i64(i64 %y) {
;
;
; RV64I-LABEL: shl_cttz_constant_i64:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    neg a1, a0
; RV64I-NEXT:    and a0, a0, a1
; RV64I-NEXT:    slli a0, a0, 2
; RV64I-NEXT:    ret
entry:
  %cttz = call i64 @llvm.cttz.i64(i64 %y, i1 true)
  %res = shl i64 4, %cttz
  ret i64 %res
}

declare void @use32(i32 signext)
