; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

;; Test target-specific stack cookie location.
;
; RUN: llc -mtriple=ysx64-linux < %s | FileCheck --check-prefix=LINUX-YSX64 %s
; RUN: llc -mtriple=ysx64-fuchsia < %s | FileCheck --check-prefix=FUCHSIA-YSX64 %s
; RUN: llc -mtriple=ysx64-android < %s | FileCheck --check-prefix=ANDROID-YSX64 %s
; RUN: llc -mtriple=ysx64-openbsd < %s | FileCheck --check-prefix=OPENBSD-YSX64 %s

define void @func() sspreq nounwind {
; LINUX-YSX64-LABEL: func:
; LINUX-YSX64:       # %bb.0:
; LINUX-YSX64-NEXT:    addi sp, sp, -32
; LINUX-YSX64-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; LINUX-YSX64-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; LINUX-YSX64-NEXT:    lui s0, %hi(__stack_chk_guard)
; LINUX-YSX64-NEXT:    ld a0, %lo(__stack_chk_guard)(s0)
; LINUX-YSX64-NEXT:    sd a0, 8(sp)
; LINUX-YSX64-NEXT:    addi a0, sp, 4
; LINUX-YSX64-NEXT:    call capture
; LINUX-YSX64-NEXT:    ld a0, %lo(__stack_chk_guard)(s0)
; LINUX-YSX64-NEXT:    ld a1, 8(sp)
; LINUX-YSX64-NEXT:    bne a0, a1, .LBB0_2
; LINUX-YSX64-NEXT:  # %bb.1:
; LINUX-YSX64-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; LINUX-YSX64-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; LINUX-YSX64-NEXT:    addi sp, sp, 32
; LINUX-YSX64-NEXT:    ret
; LINUX-YSX64-NEXT:  .LBB0_2:
; LINUX-YSX64-NEXT:    call __stack_chk_fail
;
; FUCHSIA-YSX64-LABEL: func:
; FUCHSIA-YSX64:       # %bb.0:
; FUCHSIA-YSX64-NEXT:    addi sp, sp, -32
; FUCHSIA-YSX64-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; FUCHSIA-YSX64-NEXT:    ld a0, -16(tp)
; FUCHSIA-YSX64-NEXT:    sd a0, 16(sp)
; FUCHSIA-YSX64-NEXT:    addi a0, sp, 12
; FUCHSIA-YSX64-NEXT:    call capture
; FUCHSIA-YSX64-NEXT:    ld a0, -16(tp)
; FUCHSIA-YSX64-NEXT:    ld a1, 16(sp)
; FUCHSIA-YSX64-NEXT:    bne a0, a1, .LBB0_2
; FUCHSIA-YSX64-NEXT:  # %bb.1: # %SP_return
; FUCHSIA-YSX64-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; FUCHSIA-YSX64-NEXT:    addi sp, sp, 32
; FUCHSIA-YSX64-NEXT:    ret
; FUCHSIA-YSX64-NEXT:  .LBB0_2: # %CallStackCheckFailBlk
; FUCHSIA-YSX64-NEXT:    call __stack_chk_fail
;
; ANDROID-YSX64-LABEL: func:
; ANDROID-YSX64:       # %bb.0:
; ANDROID-YSX64-NEXT:    addi sp, sp, -32
; ANDROID-YSX64-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; ANDROID-YSX64-NEXT:    ld a0, -24(tp)
; ANDROID-YSX64-NEXT:    sd a0, 16(sp)
; ANDROID-YSX64-NEXT:    addi a0, sp, 12
; ANDROID-YSX64-NEXT:    call capture
; ANDROID-YSX64-NEXT:    ld a0, -24(tp)
; ANDROID-YSX64-NEXT:    ld a1, 16(sp)
; ANDROID-YSX64-NEXT:    bne a0, a1, .LBB0_2
; ANDROID-YSX64-NEXT:  # %bb.1: # %SP_return
; ANDROID-YSX64-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; ANDROID-YSX64-NEXT:    addi sp, sp, 32
; ANDROID-YSX64-NEXT:    ret
; ANDROID-YSX64-NEXT:  .LBB0_2: # %CallStackCheckFailBlk
; ANDROID-YSX64-NEXT:    call __stack_chk_fail
;
; OPENBSD-YSX64-LABEL: func:
; OPENBSD-YSX64:       # %bb.0:
; OPENBSD-YSX64-NEXT:    addi sp, sp, -32
; OPENBSD-YSX64-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; OPENBSD-YSX64-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; OPENBSD-YSX64-NEXT:    lui s0, %hi(__guard_local)
; OPENBSD-YSX64-NEXT:    ld a0, %lo(__guard_local)(s0)
; OPENBSD-YSX64-NEXT:    sd a0, 8(sp)
; OPENBSD-YSX64-NEXT:    addi a0, sp, 4
; OPENBSD-YSX64-NEXT:    call capture
; OPENBSD-YSX64-NEXT:    ld a0, %lo(__guard_local)(s0)
; OPENBSD-YSX64-NEXT:    ld a1, 8(sp)
; OPENBSD-YSX64-NEXT:    bne a0, a1, .LBB0_2
; OPENBSD-YSX64-NEXT:  # %bb.1: # %SP_return
; OPENBSD-YSX64-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; OPENBSD-YSX64-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; OPENBSD-YSX64-NEXT:    addi sp, sp, 32
; OPENBSD-YSX64-NEXT:    ret
; OPENBSD-YSX64-NEXT:  .LBB0_2: # %CallStackCheckFailBlk
; OPENBSD-YSX64-NEXT:    lui a0, %hi(.LSSH)
; OPENBSD-YSX64-NEXT:    addi a0, a0, %lo(.LSSH)
; OPENBSD-YSX64-NEXT:    call __stack_smash_handler
  %1 = alloca i32, align 4
  call void @capture(ptr %1)
  ret void
}

declare void @capture(ptr)
