; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv64 -mattr=+v,+zvl1024b -riscv-v-vector-bits-min=1024 -verify-machineinstrs < %s | FileCheck %s --check-prefix=DEFAULT
; RUN: llc -mtriple=riscv64 -mattr=+v,+experimental-yushuxin-vfexp,+zvl1024b -riscv-v-vector-bits-min=1024 -verify-machineinstrs < %s | FileCheck %s --check-prefix=YUSHUXIN
; RUN: llc -mtriple=riscv64 -mattr=+v,+experimental-yushuxin-vfexp,+zvl1024b -riscv-v-vector-bits-min=1024 -riscv-v-reg-pressure-report < %s 2>&1 >/dev/null | FileCheck %s --check-prefix=REPORT
; RUN: llc -mtriple=riscv64 -mattr=+v,+experimental-yushuxin-vfexp,+zvl1024b -riscv-v-vector-bits-min=1024 < %s 2>&1 >/dev/null | FileCheck %s --allow-empty --check-prefix=NOREPORT

declare <128 x float> @llvm.exp.v128f32(<128 x float>)

define void @exp_v128f32(ptr noalias %in, ptr noalias %out) {
; DEFAULT-LABEL: exp_v128f32:
; DEFAULT-NOT: yushuxin.vfexp
; DEFAULT:       ret
;
; YUSHUXIN-LABEL: exp_v128f32:
; YUSHUXIN:       vle32.v
; YUSHUXIN:       yushuxin.vfexp
; YUSHUXIN:       vse32.v
; YUSHUXIN:       ret
; REPORT:         riscv-v-reg-pressure-report: function=exp_v128f32
; REPORT-SAME:    rvv-scalable-stack-bytes=
; REPORT-SAME:    rvv-spill-slots=
; REPORT-SAME:    fixed-stack-estimate=
; NOREPORT-NOT:   riscv-v-reg-pressure-report
  %v = load <128 x float>, ptr %in, align 4
  %e = call <128 x float> @llvm.exp.v128f32(<128 x float> %v)
  store <128 x float> %e, ptr %out, align 4
  ret void
}
