; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv64 -mattr=+v,+zvl1024b -riscv-v-vector-bits-min=1024 -verify-machineinstrs < %s | FileCheck %s --check-prefix=DEFAULT
; RUN: llc -mtriple=riscv64 -mattr=+v,+experimental-yushuxin-vfexp,+zvl1024b -riscv-v-vector-bits-min=1024 -verify-machineinstrs < %s | FileCheck %s --check-prefix=YUSHUXIN
; RUN: llc -mtriple=riscv64 -mattr=+v,+experimental-yushuxin-vfexp,+zvl1024b -riscv-v-vector-bits-min=1024 -riscv-v-reg-pressure-report < %s 2>&1 >/dev/null | FileCheck %s --check-prefix=REPORT
; RUN: llc -mtriple=riscv64 -mattr=+v,+experimental-yushuxin-vfexp,+zvl1024b -riscv-v-vector-bits-min=1024 < %s 2>&1 >/dev/null | FileCheck %s --allow-empty --check-prefix=NOREPORT

declare <128 x float> @llvm.exp.v128f32(<128 x float>)
declare <128 x float> @llvm.exp2.v128f32(<128 x float>)
declare <128 x float> @llvm.experimental.constrained.exp.v128f32(<128 x float>, metadata, metadata)
declare <128 x half> @llvm.experimental.constrained.exp.v128f16(<128 x half>, metadata, metadata)
declare <128 x bfloat> @llvm.experimental.constrained.exp.v128bf16(<128 x bfloat>, metadata, metadata)

define void @exp_v128f32(ptr noalias %in, ptr noalias %out) {
; DEFAULT-LABEL: exp_v128f32:
; DEFAULT-NOT: yushuxin.vfexp
; DEFAULT:       ret
;
; YUSHUXIN-LABEL: exp_v128f32:
; YUSHUXIN:       vle32.v
; YUSHUXIN:       yushuxin.vfexp
; YUSHUXIN:       vse32.v
; YUSHUXIN:       ret
; REPORT:         riscv-v-reg-pressure-report: function=exp_v128f32
; REPORT-SAME:    scalar-spill-bytes=0
; REPORT-SAME:    scalar-spill-slots=0
; REPORT-SAME:    vector-spill-bytes=0
; REPORT-SAME:    vector-spill-slots=0
; REPORT-SAME:    fixed-stack-estimate=
; NOREPORT-NOT:   riscv-v-reg-pressure-report
  %v = load <128 x float>, ptr %in, align 4
  %e = call <128 x float> @llvm.exp.v128f32(<128 x float> %v)
  store <128 x float> %e, ptr %out, align 4
  ret void
}

define void @strict_exp_v128f32(ptr noalias %in, ptr noalias %out) strictfp {
; DEFAULT-LABEL: strict_exp_v128f32:
; DEFAULT-NOT: yushuxin.vfexp
; DEFAULT:       ret
;
; YUSHUXIN-LABEL: strict_exp_v128f32:
; YUSHUXIN-NOT:   yushuxin.vfexp
; YUSHUXIN:       ret
  %v = load <128 x float>, ptr %in, align 4
  %e = call <128 x float> @llvm.experimental.constrained.exp.v128f32(
      <128 x float> %v,
      metadata !"round.dynamic",
      metadata !"fpexcept.strict") strictfp
  store <128 x float> %e, ptr %out, align 4
  ret void
}

define void @strict_exp_v128f16(ptr noalias %in, ptr noalias %out) strictfp {
; DEFAULT-LABEL: strict_exp_v128f16:
; DEFAULT-NOT: yushuxin.vfexp
; DEFAULT:       ret
;
; YUSHUXIN-LABEL: strict_exp_v128f16:
; YUSHUXIN-NOT:   yushuxin.vfexp
; YUSHUXIN:       ret
  %v = load <128 x half>, ptr %in, align 2
  %e = call <128 x half> @llvm.experimental.constrained.exp.v128f16(
      <128 x half> %v,
      metadata !"round.dynamic",
      metadata !"fpexcept.strict") strictfp
  store <128 x half> %e, ptr %out, align 2
  ret void
}

define void @strict_exp_v128bf16(ptr noalias %in, ptr noalias %out) strictfp {
; DEFAULT-LABEL: strict_exp_v128bf16:
; DEFAULT-NOT: yushuxin.vfexp
; DEFAULT:       ret
;
; YUSHUXIN-LABEL: strict_exp_v128bf16:
; YUSHUXIN-NOT:   yushuxin.vfexp
; YUSHUXIN:       ret
  %v = load <128 x bfloat>, ptr %in, align 2
  %e = call <128 x bfloat> @llvm.experimental.constrained.exp.v128bf16(
      <128 x bfloat> %v,
      metadata !"round.dynamic",
      metadata !"fpexcept.strict") strictfp
  store <128 x bfloat> %e, ptr %out, align 2
  ret void
}

define void @fast_exp2_log2e_v128f32(ptr noalias %in, ptr noalias %out) {
; DEFAULT-LABEL: fast_exp2_log2e_v128f32:
; DEFAULT-NOT: yushuxin.vfexp
; DEFAULT:       ret
;
; YUSHUXIN-LABEL: fast_exp2_log2e_v128f32:
; YUSHUXIN:       vle32.v
; YUSHUXIN:       yushuxin.vfexp
; YUSHUXIN:       vse32.v
; YUSHUXIN:       ret
  %v = load <128 x float>, ptr %in, align 4
  %c0 = insertelement <128 x float> poison, float 0x3FF7154760000000, i64 0
  %log2e = shufflevector <128 x float> %c0, <128 x float> poison,
      <128 x i32> zeroinitializer
  %scaled = fmul fast <128 x float> %v, %log2e
  %e = call fast <128 x float> @llvm.exp2.v128f32(<128 x float> %scaled)
  store <128 x float> %e, ptr %out, align 4
  ret void
}

define void @afn_exp2_log2e_v128f32(ptr noalias %in, ptr noalias %out) {
; DEFAULT-LABEL: afn_exp2_log2e_v128f32:
; DEFAULT-NOT: yushuxin.vfexp
; DEFAULT:       ret
;
; YUSHUXIN-LABEL: afn_exp2_log2e_v128f32:
; YUSHUXIN-NOT:   yushuxin.vfexp
; YUSHUXIN:       ret
  %v = load <128 x float>, ptr %in, align 4
  %c0 = insertelement <128 x float> poison, float 0x3FF7154760000000, i64 0
  %log2e = shufflevector <128 x float> %c0, <128 x float> poison,
      <128 x i32> zeroinitializer
  %scaled = fmul afn <128 x float> %v, %log2e
  %e = call afn <128 x float> @llvm.exp2.v128f32(<128 x float> %scaled)
  store <128 x float> %e, ptr %out, align 4
  ret void
}

define void @exp2_log2e_v128f32(ptr noalias %in, ptr noalias %out) {
; DEFAULT-LABEL: exp2_log2e_v128f32:
; DEFAULT-NOT: yushuxin.vfexp
; DEFAULT:       ret
;
; YUSHUXIN-LABEL: exp2_log2e_v128f32:
; YUSHUXIN-NOT:   yushuxin.vfexp
; YUSHUXIN:       ret
  %v = load <128 x float>, ptr %in, align 4
  %c0 = insertelement <128 x float> poison, float 0x3FF7154760000000, i64 0
  %log2e = shufflevector <128 x float> %c0, <128 x float> poison,
      <128 x i32> zeroinitializer
  %scaled = fmul <128 x float> %v, %log2e
  %e = call <128 x float> @llvm.exp2.v128f32(<128 x float> %scaled)
  store <128 x float> %e, ptr %out, align 4
  ret void
}

define void @fast_exp2_strict_mul_log2e_v128f32(ptr noalias %in,
                                                ptr noalias %out) {
; DEFAULT-LABEL: fast_exp2_strict_mul_log2e_v128f32:
; DEFAULT-NOT: yushuxin.vfexp
; DEFAULT:       ret
;
; YUSHUXIN-LABEL: fast_exp2_strict_mul_log2e_v128f32:
; YUSHUXIN-NOT:   yushuxin.vfexp
; YUSHUXIN:       ret
  %v = load <128 x float>, ptr %in, align 4
  %c0 = insertelement <128 x float> poison, float 0x3FF7154760000000, i64 0
  %log2e = shufflevector <128 x float> %c0, <128 x float> poison,
      <128 x i32> zeroinitializer
  %scaled = fmul <128 x float> %v, %log2e
  %e = call fast <128 x float> @llvm.exp2.v128f32(<128 x float> %scaled)
  store <128 x float> %e, ptr %out, align 4
  ret void
}

define void @rvv_alloca() {
; REPORT:         riscv-v-reg-pressure-report: function=rvv_alloca
; REPORT-SAME:    scalar-spill-bytes=0
; REPORT-SAME:    scalar-spill-slots=0
; REPORT-SAME:    vector-spill-bytes=0
; REPORT-SAME:    vector-spill-slots=0
; REPORT-SAME:    fixed-stack-estimate=
  %x = alloca <vscale x 4 x i32>, align 16
  ret void
}
